### ISSUE TITLE
NSSortDescriptors

### ISSUE THREAD

**Issue by pmodernme** [firebase/FirebaseUI-iOS#10]
I've been working on an improvement to the Firebase Array that optionally uses Sort Descriptors to sort the results after being received by the query.
I would like to share my work when its done, but I read that I should write up an issue, and sign the contributor document first.
Please let me know if this is of interest and I can share specifics.

**Comment by mcdonamp** [comment]
@pmodernme Definitely, we're interested in seeing this! The CLA is easy to deal with, and feel free to submit a PR and we can take a look.

**Comment by mcdonamp** [comment]
I'm going to close this since it's in #12
