### ISSUE TITLE
File not found. - warnings in Xcode 13.0

### ISSUE THREAD

**Issue by mamilov** [firebase/FirebaseUI-iOS#1002]
* Objective C or Swift: Swift
  * iOS version: iOS 15
  * Firebase SDK version: 8.7.0
  * FirebaseUI version: 12.0.2
  * CocoaPods Version: None -> SPM
  
### Describe the problem:

After upgrading to Xcode, I'm receiving the following Warnings from Xcode:
![image](https://user-images.githubusercontent.com/62982104/134476745-7b5c65fc-998c-47f7-81eb-ba786d25bf13.png)

#### Steps to reproduce:

  1. Install Xcode 13
  2. Add this library via spm to the project
  3. Build the target
  
#### Observed Results:

  * Received Warnings for files that could not be found
  
#### Expected Results:

  * NO warnings

**Comment by SchwartzLizer** [comment]
same problem
