### ISSUE TITLE
Google Sign-In crashes app when using SwiftUI & SPM

### ISSUE THREAD

**Issue by thecodeguyexamples** [firebase/FirebaseUI-iOS#1003]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If your issue concerns the CocoaPods error, "...transitive dependencies that include static binaries", please take a look at any of the following issues and see if your problem is solved: #48, #47, #46, #34, #23.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

Yes.

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 15.0
  * Firebase SDK version: 8.7.0
  * FirebaseUI version: 8.4.0
  * CocoaPods Version: N/A (Using SPM)
  
### Step 3: Describe the problem:

The app crashes when attempting to log in with Google, however, it does not crash when using email.

#### Steps to reproduce:

  1. Launch App
  2. Click "Sign in with Google"
  
#### Observed Results:

The app crashes with the following error message:

`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'OAuth client ID not found. Please make sure Google Sign-In is enabled in the Firebase console. You may have to download a new GoogleService-Info.plist file after enabling Google Sign-In.'
terminating with uncaught exception of type NSException`

However, the OAuth ID for my app is located within the GoogleService-Info.plist file, and the reversed ID has also been added as a URL type.
  
#### Expected Results:

The Google sign in page should have opened.
  
#### Relevant Code:

Here is some of the code that I use to create the sign in view.

  ```
  struct CustomLoginViewController : UIViewControllerRepresentable {
    var delegate: FUIAuthDelegate?
    
    var dismiss : (_ error : Error? ) -> Void
    
    func makeCoordinator() -> CustomLoginViewController.Coordinator {
        Coordinator(self)
    }
    
    func makeUIViewController(context: Context) -> UIViewController
    {
        let authUI = FUIAuth.defaultAuthUI()
        
        let providers : [FUIAuthProvider] = [
            FUIEmailAuth(),
            FUIGoogleAuth()
        ]

        authUI?.providers = providers
        authUI?.privacyPolicyURL = URL.init(string: "https://www.appworks.mrcodeguy.com/privacy/elibrarian/")?.absoluteURL
        authUI?.delegate = self.delegate
        authUI?.shouldHideCancelButton = true
        
        let authViewController = authUI?.authViewController()

        return authViewController!
    }
    
    func updateUIViewController(_ uiViewController: UIViewController, context: UIViewControllerRepresentableContext<CustomLoginViewController>)
    {
        
    }
    
    //coordinator
    class Coordinator: NSObject {
        var parent: CustomLoginViewController
        
        init(_ customLoginViewController : CustomLoginViewController) {
            self.parent = customLoginViewController
        }
    
    }
}
  ```

and

```
class AuthViewModel: NSObject, ObservableObject, FUIAuthDelegate {

    func authUI(_ authUI: FUIAuth, didSignInWith authDataResult: AuthDataResult?, url: URL?, error: Error?) {
        print("Signed in as \(Auth.auth().currentUser?.email ?? "not signed in")")
        
        UserDefaults.standard.set(true, forKey: "isUserSignedIn")
    }
}
```

**Comment by morganchen12** [comment]
Have you followed the instructions in the exception message?

> Please make sure Google Sign-In is enabled in the Firebase console. You may have to download a new GoogleService-Info.plist file after enabling Google Sign-In.

**Comment by thecodeguyexamples** [comment]
Yes, I have followed the instructions in the message, I have downloaded the GoogleService-Info.plist file several times, and have checked to make sure that my app is listed as a target, and I have tried placing the file in several different locations in my app. As you can see in the screenshots below, Google sign in is enabled in the Firebase console and in the GoogleService-Info.plist file.

<img width="432" alt="Screen Shot 2021-09-25 at 10 27 54 AM" src="https://user-images.githubusercontent.com/51267453/134774992-9b1dad6b-1700-4f66-ba8e-67a6c1657418.png">
<img width="602" alt="Screen Shot 2021-09-25 at 10 28 38 AM" src="https://user-images.githubusercontent.com/51267453/134774993-259a3103-c29e-42e2-a5e3-10a23bc003ba.png">

**Comment by thecodeguyexamples** [comment]
I also found it interesting to note that the crash occurred in my AppName_App.swift file on the "@main" line, not in one of the files concerning setting up and initializing FirebaseUI.

**Comment by pkarolis** [comment]
I am experiencing the same issue. Xcode 13. Min supported ios version 12. this error only started appeared once I upgraded to Xcode 13 and the latest firebase pods.

**Comment by morganchen12** [comment]
Can you share a sample project that repros this crash?

**Comment by pkarolis** [comment]
What resolved the error for me was the following:

previously when instantiating google Provider i just did
```
let authUI = FUIAuth.defaultAuthUI()
let googleProvider = FUIGoogleAuth(authUI: authUI!)
authUI?.providers = [googleProvider, .... etc]
```
now i changed how I instantiate the googleProvider
`        let googleProvider = FUIGoogleAuth(authUI: authUI!)
`
and it resolved the error

**Comment by thecodeguyexamples** [comment]
> What resolved the error for me was the following:
> 
> previously when instantiating google Provider i just did
> 
> ```
> let authUI = FUIAuth.defaultAuthUI()
> let googleProvider = FUIGoogleAuth()
> authUI?.providers = [googleProvider, .... etc]
> ```
> 
> now i changed how I instantiate the googleProvider
> ` let googleProvider = FUIGoogleAuth(authUI: authUI!)`
> and it resolved the error

This works for me, thanks @pkarolis, I did not even know this initializer existed.
