### ISSUE TITLE
Missing .xib files when installing through SPM

### ISSUE THREAD

**Issue by jhoanarango** [firebase/FirebaseUI-iOS#1015]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If your issue concerns the CocoaPods error, "...transitive dependencies that include static binaries", please take a look at any of the following issues and see if your problem is solved: #48, #47, #46, #34, #23.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Objective C or Swift: __Swift__
  * iOS version: __15.0 & Above___
  * Firebase SDK version: __8.10.0___
  * FirebaseUI version: _12.1.0___
  * CocoaPods Version: ____
  
### Step 3: Describe the problem:

I am removing all Cocoa Pods from my project and trasnfering them to SPM. I am trying to install the latest version of FirebaseUI-iOS and I get 10 warnings that I have not been able to get rid of no matter what I do. I have uninstall and re-install the packages, also Xcode, De-integrate Pods and re-installed other pods.

Please see image for "Warnings".

#### Steps to reproduce:

  1. _____ Installed FirebaseUI-iOS through SPM
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.
  * Same Warnings 
  
#### Expected Results:

  * What did you expect to happen?
  * To install without any issues
  
#### Relevant Code:

<img width="613" alt="Screen Shot 2021-12-19 at 7 46 54 PM" src="https://user-images.githubusercontent.com/14069813/146697665-0f53982c-6890-4d68-bd0c-cd512e0fcc51.png">

**Comment by jhoanarango** [comment]
<img width="613" alt="Screen Shot 2021-12-19 at 7 46 54 PM" src="https://user-images.githubusercontent.com/14069813/146697646-ff4692fe-3e9d-4edb-97e4-5dffe5a6f663.png">

**Comment by morganchen12** [comment]
This should be fixed in 12.1.1.
