### ISSUE TITLE
SPM error: Package.swift has no Package.swift manifest for version 0.7.0 

### ISSUE THREAD

**Issue by lionel-alves** [firebase/FirebaseUI-iOS#1017]
I can't add Firebase-UI with SPM.

### Environment

  * Xcode: 13.2.1
  * Mac: M1 Pro
  * Firebase SDK version: 8.11
  * FirebaseUI version: 12.1.1
  
#### Steps to reproduce:

  1. Add Firebase-UI with SPM: https://github.com/firebase/FirebaseUI-iOS

#### Observed Results:

```
Package.swift has no Package.swift manifest for version 0.7.0 in https://github.com/firebase/FirebaseUI-iOS
```

**Comment by kfujino7** [comment]
Hi,
I see the same issue and not sure where 0.7.0 is coming from. 
But if you set the Package Repository Rule setting in "Package Dependency" as "Version : [Up to Next Major] 12.1.1 > 13.0.0,  It should resolved the issue. Please try.

**Comment by lionel-alves** [comment]
Hey @kfujino7, it worked thanks!
