### ISSUE TITLE
below is the code and exception:-

### ISSUE THREAD

**Issue by lamjay2704** [firebase/FirebaseUI-iOS#1026]
below is the code and exception:-
 
C:\Users\rajkuma\Desktop>npm install node-cli -g
npm http GET http://registry.npmjs.org/node-cli
npm http 304 http://registry.npmjs.org/node-cli
npm http GET http://registry.npmjs.org/node-cli/-/node-cli-0.1.0.tgz
npm http 200 http://registry.npmjs.org/node-cli/-/node-cli-0.1.0.tgz
npm ERR! Error: shasum check failed for C:\Users\rajkuma\AppData\Local\Temp\npm-7352-ygJM5zgM\1555569954173-0.005827664863318205\tmp.tgz
npm ERR! Expected: 264c4126f8e858562d0296a677914fd709786f7a
npm ERR! Actual:   20fe2d6a30f6aeaed917667f69d0593e0a66bc51
npm ERR!     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\sha\index.js:38:8
npm ERR!     at ReadStream.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\sha\index.js:85:7)
npm ERR!     at ReadStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

__Originally posted by @Raj1071 in https://github.com/isaacs/npm/pull/2__

**Comment by morganchen12** [comment]
Seems to be a spam issue?
