### ISSUE TITLE
Account management page

### ISSUE THREAD

**Issue by alfongj** [firebase/FirebaseUI-iOS#103]
It would be nice to have a built in component that allows users to manage their account. Specifically the functionality could be:
- Change password (if you had one)
  Error conditions:
  - Invalid password (e.g. too short, empty)
  - Requires reauth (user signed-in more than 5 min ago, this could be solved if the old passwd is always required)
  - General internal error (network req, expired user, etc)
- Add/Change email
  Error conditions:
  - Invalid email (e.g. exists already, invalid format)
  - Requires reauth (user sign-in more than 5 min ago -> should be handled by asking the user to reauthenticate with one of the providers they have linked)
  - General internal error
- View linked accounts and unlink them. 
  Error conditions:
  - General internal error
- Style customization (same as authentication flows)

**Comment by alfongj** [comment]
I am working internally with a designer to obtain UX mocks for this.

**Comment by morganchen12** [comment]
Addressed by #261.
