### ISSUE TITLE
Enter email sign-in screen directly if the only provider is Email/Password

### ISSUE THREAD

**Issue by alfongj** [firebase/FirebaseUI-iOS#104]
When only using email as an option to sign-in, we could directly show the email identifier screen directly instead of showing 'Sign in with email' button. This would make it easier and faster to customize the UI that opens the flow.

This is required for feature compatibility with Android (already implemented) and [Web](https://github.com/firebase/firebaseui-web/issues/23)

**Comment by peterkos** [comment]
Should this be extended to other providers as well, or is the likelihood of that lower in comparison to just having email sign-in enabled? (I.e., if Google Sign-In is the only option, go directly to that)

**Comment by yramanchuk** [comment]
Issue is implemented in 0.6.2
Issue is not extended to other providers because we must provide mandatory entry point (e g red Google sign-in button)
