### ISSUE TITLE
We're hoping to split the typing_extensions extension module off the python/typing repo, to separate various typing discussions from the code that provides runtime support (mostly so new typing features can be used in old Python versions). See https://github.com/python/typing/issues/1182.

### ISSUE THREAD

**Issue by franckbleyer1** [firebase/FirebaseUI-iOS#1051]
We're hoping to split the typing_extensions extension module off the python/typing repo, to separate various typing discussions from the code that provides runtime support (mostly so new typing features can be used in old Python versions). See https://github.com/python/typing/issues/1182.

- Do we need permission from the SC for this?
- If not, do we need to ask anyone else for permissions? It *looks* like I have permissions to just create the repo, but I'd rather be safe than sorry.

__Originally posted by @gvanrossum in https://github.com/python/steering-council/issues/126__

**Comment by gvanrossum** [comment]
Is this a spam issue? I don't understand why this would belong in this tracker. (And the proposed split has happened quite some time ago.)

**Comment by morganchen12** [comment]
Reported as spam.
