### ISSUE TITLE
Cannot use Swift Package Manager to add FirebaseUI, missing Package.swift

### ISSUE THREAD

**Issue by AphroditeSoftware** [firebase/FirebaseUI-iOS#1094]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If your issue concerns the CocoaPods error, "...transitive dependencies that include static binaries", please take a look at any of the following issues and see if your problem is solved: #48, #47, #46, #34, #23.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Objective C or Swift: _Swift___
  * iOS version: _15.2____
  * Firebase SDK version: _9.0.0____
  * FirebaseUI version: _0.6.1___
  * Xcode Version: _14.0___
  
#### Steps to reproduce:

  1. _In Xcode, File-> Add Packages____
  2. _Enter http://github.com/firebase/firebaseui-ios____
  3. _Select firebaseui-ios____
  
#### Observed Results:

  * Xcode attempted to load in firebaseui-io but ended with this error:
  
<img width="754" alt="Screen Shot 2022-09-18 at 3 20 26 PM" src="https://user-images.githubusercontent.com/1252838/190928649-a2fbb57f-aba9-4f9f-839a-8e2f9f8be598.png">

Selecting "Add anyway" does not give the option to select modules and results in many build errors. 

I tried using Xcode 13.4.1 and got a slightly different error: 

<img width="874" alt="Screen Shot 2022-09-18 at 3 35 52 PM" src="https://user-images.githubusercontent.com/1252838/191371058-24efdc56-4abb-4d9b-bac0-2b88ad437695.png">

#### Expected Results:

Package to be added successfully.
  
#### Relevant Code:

  ```
  /n/a
  ```

**Comment by AphroditeSoftware** [comment]
Attempted this with Xcode version 13.4.1 and received a slightly different error:
<img width="874" alt="Screen Shot 2022-09-18 at 3 35 52 PM" src="https://user-images.githubusercontent.com/1252838/190928970-258e05c1-187a-45c8-ad0b-f9d5a5edb34c.png">

**Comment by cutmail** [comment]
Same issue

![image](https://user-images.githubusercontent.com/163344/193954081-9dd7acb0-ab5d-486e-a3bb-241ce94b765c.png)

**Comment by morganchen12** [comment]
Hey all, this happens if you specify a version of FirebaseUI before SPM support was added. The error should go away if you set the version to at least 12.0.

**Comment by projectxmaker** [comment]
@morganchen12 

Hi, I used w/ Xcode 14.2 (14C18) and I tried the below approaches but the package "FirebaseUI-iOS could not be resolved".  

There're 6 options in Dependency rule to pick:
- Up to next major version: its default value is 0.6.1 < 1.0.0
- Up to next minor version: its default value is 0.6.1 < 0.7.0
- Range of versions: its default value is 0.6.1 < 0.7.0
- Exact version: its default value is 0.6.1
- Branch: default value is master
- Commit: I tried w/ the commit bc6f34f6834384e64f87f50a4b77f4f7f57559eb on Nov 18, 2022

<img width="1103" alt="Screenshot 2022-12-26 at 2 08 21 PM" src="https://user-images.githubusercontent.com/7484655/209516609-82c74461-23dc-4089-a46f-70c5a12f8f01.png">

Any help is appreciated.

Thanks.

**Comment by vito-royeca** [comment]
Same Xcode version and same issue with @projectxmaker.

**Comment by morganchen12** [comment]
Hey all, sorry for the slow response. Have you tried using the exact version and changing the default value to 12.0?

**Comment by vito-royeca** [comment]
@morganchen12 

I tried to set Exact Version to 12.0 but Xcode will not allow me.

Hence, I set Exact Version to 12.0.0 but still I could not add the package.
<img width="1087" alt="Screenshot 2023-04-08 at 12 44 48 AM" src="https://user-images.githubusercontent.com/9709494/230703689-3e6676e6-71a9-4396-9383-a0286e7bbd08.png">
<img width="1085" alt="Screenshot 2023-04-08 at 12 45 34 AM" src="https://user-images.githubusercontent.com/9709494/230703691-3c21658a-7e67-445c-934a-a28b5a1b016a.png">

**Comment by toddlee** [comment]
Finally figured it out. You need to set the version to 12.0.0 even though the default suggested one is 0.6.1. You can do that by selecting your Xcode project > Package Dependencies > FirebaseUI-iOS.

![Screenshot 2023-04-09 at 7 57 53 PM](https://user-images.githubusercontent.com/169621/230817116-be8d100f-1aa1-4505-be09-6bae34045dce.png)

**Comment by reluctantguy** [comment]
Is there a potential for conflict between the FirebaseUI-iOS.git package and the firebase-ios-sdk.git if you choose incompatible versions? -- or does the swift package manager inform you of that at the time of attempted download?

**Comment by morganchen12** [comment]
SPM will inform you if there's an incompatibility in your versions, but only if you explicitly specify the versions you want. Otherwise it will downgrade Firebase or FirebaseUI to meet the version compatibility constraints.

**Comment by royyang90** [comment]
Seems everyone resolved with version dependency rule setting with 12.0.0, but I'm still having same issue. is anyone have idea with it?
<img width="1086" alt="Screenshot 2023-10-11 at 1 02 03 AM" src="https://github.com/firebase/FirebaseUI-iOS/assets/144814665/c81cce5d-6b02-4fcf-903a-186207b01e27">

**Comment by morganchen12** [comment]
@royyang90 do you have any constraints on upstream Firebase?

**Comment by royyang90** [comment]
Yes I tried to set up login with fire base basic UI in iOS, and importing
FirebaseAuthUI in Xcode seems requires FirebaseUI package for it. But
having package resolution failure when I try to push it to Xcode even
though I set the dependency rule at least 12.0.0

Can you help this out?

2023년 10월 11일 (수) 오전 7:06, Morgan Chen ***@***.***>님이 작성:

**Comment by morganchen12** [comment]
Can you share your project? You can upload it to an empty git repository.

**Comment by royyang90** [comment]
Hi Morgan

Thanks for your email

I just resolved it through setting up a new project in xcode.

I don't know what was the problem but really appreciate your help

**Comment by nmtitov** [comment]
Still an issue.
I had to remove FirebaseSDK 10.17.0 package from the project which I was already using in my app. Only after that I was able to add FirebaseUI 13.1.0 which relies on the same Firebase 10.17.0

**Comment by metedata** [comment]
I'm a relative beginner and this issue just stumped me for many hours... I appreciate the friendliness of Firebase documentation but the [FirebaseUI docs](https://firebase.google.com/docs/auth/ios/firebaseui) in particular are extremely sparse on installation details if you're not using CocoaPods in your projects. 

- [FirebaseUI docs](https://firebase.google.com/docs/auth/ios/firebaseui) should specify explicitly that that https://github.com/firebase/FirebaseUI-iOS needs to be installed separately as a dependency in your project using SPM (if not using CocoaPods). It's not clear right now that it needs to be installed on top of core Firebase package.
- [FirebaseUI docs](https://firebase.google.com/docs/auth/ios/firebaseui) and the README for Firebase-UI-iOS should document the SPM installation instructions mentioned above - i.e using 12.0.0 as a minimum version (worked for me after hours of confused google searching)
- [FirebaseUI docs](https://firebase.google.com/docs/auth/ios/firebaseui) need to explicitly call out that which package needs to be explicitly imported for each sign-in method used. That's not documented anywhere either. 

I realize some of this might be obvious to more experienced devs / wonderful engineers building FirebaseUI, but it's not not at all clear for someone just starting out and building basic apps. These changes can save a lot of frustration for folks like me. Thanks to @toddlee for the 12.0.0 solution.

**Comment by Knapiii** [comment]
Any updates on this? Has anyone been able to add `FirebaseUI` as SPM? I just tried the 15.0.0 version and it did not work

**Comment by lgvalle** [comment]
@Knapiii same situation here. As of today, the most recent version that works for me is [v14.2.6](https://github.com/firebase/FirebaseUI-iOS/releases/tag/v14.2.6)
