### ISSUE TITLE
spm facebook-ios-sdk dependency

### ISSUE THREAD

**Issue by sahbazali** [firebase/FirebaseUI-iOS#1096]
**My Environment:**
  * Firebase SDK version: 9.6.0
  * FirebaseUI version: 12.2.0
  * Swift Package Manager
  
**Problem:**
 In our project, we decided to remove CocoaPods. 
 Normally we were using (in cocoapod);
  * Firebase SDK version: 8.1.0
  * FirebaseUI version: 10.0.2
  and
  * facebook-ios-sdk version: 14.1.0 (in spm)
 
 We can't use facebook-ios-sdk(14.1.0) with FirebaseUI version: 12.2.0(spm) because there is dependency to facebook-ios-sdk defined in package.swift ;
 
 `    .package(
      name: "Facebook", 
      url: "https://github.com/facebook/facebook-ios-sdk.git",
      "11.0.0"..<"13.0.0"
    ),`
  
Can you please give support for newer facebook-ios-sdk versions?

**Comment by sahbazali** [comment]
Hi @morganchen12, thank you for your support but are you sure this pr resolve this issue? In package.swift there is still lower dependency on facebook;

`.package( name: "Facebook", url: "https://github.com/facebook/facebook-ios-sdk.git", "11.0.0"..<"13.0.0" ),`

Still, we are not allowed to use Facebook 14.1.0 with FirebaseUI. If it is possible can you update package.swift?

**Comment by morganchen12** [comment]
@sahbazali there's no reference to Facebook SDK v13 in the Package.swift. See this line:
https://github.com/firebase/FirebaseUI-iOS/blob/master/Package.swift#L70

Can you try with FirebaseUI 12.3?

**Comment by sahbazali** [comment]
hi Morgan when I upgraded FirebaseUI to 12.3 I could able to install Facebook SDK v14. 

thank you so much :)
