### ISSUE TITLE
XCode 7 Issue!

### ISSUE THREAD

**Issue by EMidee66** [firebase/FirebaseUI-iOS#11]
Hi,

I got about 200 of these errors after integrating Firebase with CocoaPods in XCode 7. It's related only to Firebase.

![screen shot 2015-09-26 at 1 33 54 am](https://cloud.githubusercontent.com/assets/6751025/10114267/c2d911dc-63ee-11e5-9077-302c2a056d81.png)
![screen shot 2015-09-26 at 1 33 11 am](https://cloud.githubusercontent.com/assets/6751025/10114268/c6d614ba-63ee-11e5-8338-49049301b67a.png)

**Comment by mcdonamp** [comment]
Hey @EMidee66, it's a know issue with the 2.4.0 release and we will be releasing a new version of it shortly :)

**Comment by EMidee66** [comment]
Thank You @mcdonamp :)
