### ISSUE TITLE
Localized strings ?

### ISSUE THREAD

**Issue by LeChatNoir69** [firebase/FirebaseUI-iOS#110]
Hi there,
Objective-C under iOS9, last Firebase SDK, last FirebaseUI version.
I try to add French support.
So I just copy/paste strings from the FirebaseAuthUI.strings in my own .strings files but it doesn't work.

I then try to add FirebaseAuthUI.strings in my project but not better.

I can't get it work.

Any idea ?

Anyway, thxs for the great job :)

**Comment by LeChatNoir69** [comment]
Hi there,
Objective-C under iOS9, last Firebase SDK, last FirebaseUI version.
I try to add French support.
So I just copy/paste strings from the FirebaseAuthUI.strings in my own .strings files but it doesn't work.

I then try to add FirebaseAuthUI.strings in my project but not better.

I can't get it work.

Any idea ?

Anyway, thxs for the great job :)

**Comment by LeChatNoir69** [comment]
Is this a real bug ?

**Comment by morganchen12** [comment]
This is a bug on the framework's side. Localization is something we'd like to do all at once, rather than one locale at a time.

Unfortunately I'm not sure when we'll get around to doing that.

**Comment by LeChatNoir69** [comment]
Ok. I understood that we can override strings file in our app project…
Can I help in something (i’m french so I can at least produce the french file :))

**Comment by morganchen12** [comment]
That's a bug on our part--you won't be able to override the strings files because we're manually localizing our strings instead of using the `NSLocalizedString` set of functions/macros.

**Comment by chaogoog** [comment]
I think if you set the custom bundle like this, you should be able to use your own translations.
`authUI.customStringsBundle = [NSBundle mainBundle];`

**Comment by LeChatNoir69** [comment]
You’re right, It works :)
Thxs !

**Comment by chaogoog** [comment]
Great! Thanks for the quick verification.

For anyone running into the same issue, this is documented at https://github.com/firebase/FirebaseUI-iOS/tree/master/FirebaseUI/Auth#custom-strings

**Comment by jrbecart** [comment]
Hi, like LeChatNoir69 I try to add french to my project.

I'am kind of lost, can I accomplish this using Podfile or should I do a manual install of FirebaseAuthUI in my project?

I already added in my appdelegate this lines: 
```
FUIAuth *authUI = [FUIAuth defaultAuthUI];
authUI.customStringsBundle = [NSBundle mainBundle];
```

And I also added in my folder String:
->en.lproj->FirebaseAuthUI.strings
->fr.lproj->FirebaseAuthUI.strings

But I can't see any change in the UI.
I'm not sure how to proceed. Any clues?

**Comment by LeChatNoir69** [comment]
You just have to define theses strings files in your project :
FirebaseAuthUI.strings
FirebaseFacebookAuthUI.strings
FirebaseGoogleAuthUI.strings

Just look at theses files in the project and you'll find all keys too translate.

**Comment by yorgosg** [comment]
@LeChatNoir69 , @jrbecart it is not as easy as it sounds. I have been trying to do this for a while now without any success. Check this question from 4-5 months ago here: https://github.com/firebase/FirebaseUI-iOS/issues/125

If, however, there has been an update on this and now it works, please let me know. Cheers.

**Comment by jrbecart** [comment]
@LeChatNoir69 It works!!!

I added this missing files: 
FirebaseFacebookAuthUI.strings
FirebaseGoogleAuthUI.strings
+ Twitter

Thanks!
