### ISSUE TITLE
FirebaseStorageUI Cannot find type 'StorageReference' in scope (SPM)

### ISSUE THREAD

**Issue by ivex001** [firebase/FirebaseUI-iOS#1115]
Xcode 14.0.1
FirebaseUI 12.3.1
Swift

Hello guys,

After adding FirebaseStorageUI via Swift Package Manager i'm not able to get  **_StorageReference_** . i get this error:
**"Cannot find type 'StorageReference' in scope"**
 Before migrating from CocoaPods to SPM the code below worked fine

  ```
  import FirebaseStorageUI

class MainMenuCell: UITableViewCell {
    let storage = Storage.storage()
    var storageRef: StorageReference?
}
  ```

**Comment by morganchen12** [comment]
Are you able to `import FirebaseStorage`? You may be running into https://github.com/firebase/FirebaseUI-iOS/issues/1028#issuecomment-1262591551.

**Comment by ivex001** [comment]
> Are you able to `import FirebaseStorage`? You may be running into [#1028 (comment)](https://github.com/firebase/FirebaseUI-iOS/issues/1028#issuecomment-1262591551).

Hi, yes i'm able to import FirebaseStorage but when i do it's like it overrides the FirebaseStorageUI and than i get this error when trying to get de reference for SDWebImage:

> Cannot convert value of type 'StorageReference' to expected argument type 'URL?'

Could you please tell me where exactly should i add this line:
` -Xcc -fmodule-map-file=$(GENERATED_MODULEMAP_DIR)/FirebaseStorage.modulemap`

**Comment by ivex001** [comment]
Hi @morganchen12  don't bother i manage to find where. 
it worked!! thank you for your assist mate

If someone else wants to know is in your Project Settings -> Build Settings -> search for Swift Compiler - Custom Flags -> Other Swift flags . I add it to degub and release config

**Comment by morganchen12** [comment]
Glad it worked!

**Comment by zakariahmusic** [comment]
#1111
