### ISSUE TITLE
Please add Facebook SDK 15.0 support, thank you.

### ISSUE THREAD

**Issue by fangyuxi** [firebase/FirebaseUI-iOS#1123]
Please add Facebook SDK 15.0 support, thank you.

**Comment by mattkwan** [comment]
Further to this, FirebaseUI 12.3.1 requires https://github.com/facebook/facebook-ios-sdk.git 11.0.0<15.0.0
But Facebook SDK versions 15+ are required to get Facebook Ads working properly with iOS 14.5+

Personally I'm only using FirebaseUI for the FirebaseStorageUI library (which doesn't use Facebook SDK), so a solution that splits out that library would also work for me.

**Comment by tidbeck** [comment]
This would also remove all warnings related to [missing local directory .pcm files from joesusnick](https://github.com/facebook/facebook-ios-sdk/issues/2091)

**Comment by fangyuxi** [comment]
@morganchen12 When will it be solved, please? Or have you encountered any difficulties?

**Comment by morganchen12** [comment]
This is fixed now, but requires a major version bump since the Facebook SDK dropped support for iOS 10.
