### ISSUE TITLE
Implement Twitter Provider

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-iOS#114]
For the next major version we should attempt to add Twitter authentication alongside Google and Facebook.

This was done in Android on a feature branch in this PR:
https://github.com/firebase/FirebaseUI-Android/pull/268

**Comment by dakeshi** [comment]
Good news. 
In twitter implementation, there are two options to use Twitter API keys. 
(reference: https://docs.fabric.io/apple/twitter/advanced-setup.html#url-scheme)

- using info.plist(recommended way)
- setting the Consumer Key and Secret in the code

I think that the former looks more simple. The latter needs the code below
(The former don't need this code):
```swift
Twitter.sharedInstance().startWithConsumerKey("your_key", consumerSecret: "your_secret")
```

**Comment by yramanchuk** [comment]
Added integration with Twitter provider (v0.5.6).
You need to start Fabric and provide twitter key/secret in info.plist
