### ISSUE TITLE
Update GoogleSignIn to version 7.0.0 to fix GTMSessionFetcher 3.x issue

### ISSUE THREAD

**Issue by ian-sayles** [firebase/FirebaseUI-iOS#1144]
To fix the issue with GTMSessionFetcher 3.x., see 1138 below,  will it be possible to change GoogleSignIn to version 7 in the next release.

https://github.com/firebase/FirebaseUI-iOS/issues/1138

**Comment by paulb777** [comment]
GoogleSignIn is updated to 7.0.0 in major version 14
