### ISSUE TITLE
Cannot assign value of type 'AppDelegate' to type '(any FUIAuthDelegate)?'

### ISSUE THREAD

**Issue by ningzhiqun** [firebase/FirebaseUI-iOS#1186]
xcode tip: Cannot assign value of type 'AppDelegate' to type '(any FUIAuthDelegate)?'

code 
`class AppDelegate: NSObject, UIApplicationDelegate {
  func application(_ application: UIApplication,
                   didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
    FirebaseApp.configure()
    let authUI = FUIAuth.defaultAuthUI()
    // You need to adopt a FUIAuthDelegate protocol to receive callback
      authUI?.delegate = self
    return true
  }
}`

<img width="964" alt="image" src="https://github.com/firebase/FirebaseUI-iOS/assets/45943965/cf4a746a-f1f9-4597-aefa-259342e6b090">

xcode version : 15.3 
ios : 17.4
firebaseui-ios : 12.3.1
firebase : 10.23.1

could you help me ? thanks

**Comment by ningzhiqun** [comment]
i use spm

**Comment by paulb777** [comment]
Add `FUIAuthDelegate` to the class declaration like:

`class AppDelegate: NSObject, UIApplicationDelegate, FUIAuthDelegate`
