### ISSUE TITLE
Module 'FirebaseAuth' not found

### ISSUE THREAD

**Issue by joaomvfsantos** [firebase/FirebaseUI-iOS#1196]
After updating to firebase 11.0.0 and firebase-ui 14.2.0 it's not possible to build the project with the error: Module 'FirebaseAuth' not found

Xcode 15.4
macOS 14.6.1 (Sonoma)
Using Swift Package Manager

<img width="987" alt="Screenshot 2024-08-12 at 11 32 26" src="https://github.com/user-attachments/assets/7fd32a68-909c-4868-ac7a-fcfd41b7972b">

<img width="633" alt="Screenshot 2024-08-12 at 11 32 38" src="https://github.com/user-attachments/assets/3648772d-5899-418a-b89d-4b9896309025">

Example project where the issue happens: https://github.com/joaomvfsantos/FirebaseUITest

**Comment by JoniGoos** [comment]
I have the same issue

**Comment by paulb777** [comment]
I'm not able to reproduce. I don't see any Swift Packages in the "Example Project". When I add FirebaseUI to it with the specified targets, it builds fine.

Please share a reproducible example.

**Comment by joaomvfsantos** [comment]
@paulb777 Thanks for checking. There was a commit missing in the example repository, which I apolagize. Please check again if possible.

**Comment by paulb777** [comment]
@joaomvfsantos Thanks! I've reproduced and will investigate a fix.

**Comment by paulb777** [comment]
Thanks for reporting and sharing the repro. The 14.2.1 release should fix the build issue.

**Comment by joaomvfsantos** [comment]
@paulb777 Thanks for the fix. Just as fyi, this change means we need to also import FirebaseAuth in places where before we only needed to import FirebaseAuthUI (if we reference classes from FirebaseAuth). That's fine for me, but for example the sample code does not compile anymore because of this, and should be updated.

**Comment by paulb777** [comment]
We updated the [Firestore quickstart](https://github.com/firebase/quickstart-ios/pull/1611). Are you seeing it in other sample code?

**Comment by joaomvfsantos** [comment]
@paulb777 I was talking specifically about the sample project in the [FirebaseUI-iOS/samples](https://github.com/firebase/FirebaseUI-iOS/tree/main/samples) folder.

**Comment by paulb777** [comment]
@joaomvfsantos Thanks for pointing that out. I fixed a few issues with the Swift sample build in #1202.
