### ISSUE TITLE
FUIAuthDelegate methods not called in v.14

### ISSUE THREAD

**Issue by joaomvfsantos** [firebase/FirebaseUI-iOS#1198]
**Problem:** FUIAuthDelegate methods are not being called anymore in v.14. I have setup two example projects with the same code, one with FirebaseUI v.13 and another with FirebaseUI v.14. On version 13 it works correctly, and on version 14 not anymore.

Specifically the function that is not being called can be found in the AppDelegate file:

```swift
func authUI(_ authUI: FUIAuth, didSignInWith authDataResult: AuthDataResult?, error: Error?)
```

Xcode 15.4
macOS 14.6.1 (Sonoma)
Using Swift Package Manager

**Example with Firebase 14 where the issue exists:** https://github.com/joaomvfsantos/FirebaseUITest/tree/fuiauthdelegate-issue (please use branch fuiauthdelegate-issue)

**Example with Firebase 13 where it works:** https://github.com/joaomvfsantos/FirebaseUITest/tree/fuiauthdelegate-issue-v13 (please use branch fuiauthdelegate-issue-v13)

**Note:** Please setup the GoogleService-Info.plist in the projects and the URL types and GIDClientID in the Info.plist before running the projects

**Comment by paulb777** [comment]
Thanks for the thorough repros!  #1200 should fix.

**Comment by joaomvfsantos** [comment]
Hello @paulb777 Unfourtunatly this seems not to be fixed. I updated the [code](https://github.com/joaomvfsantos/FirebaseUITest/tree/fuiauthdelegate-issue) to use 14.2.2 but the delegate method still does not get called. Maybe I'm missing something else here?

**Comment by paulb777** [comment]
Hi @joaomvfsantos I appreciate your persistence. While #1200 fixed signing in, I'm able to reproduce the delegate method not being called. For some reason `[self.delegate respondsToSelector:@selector(authUI:didSignInWithUser:error:)]` fails in FirebaseUI 14 and succeeds in FirebaseUI 13 with seemingly the same delegate. 

I'll reopen and continue to investigate.

**Comment by paulb777** [comment]
Removing the `respondsToSelector` test reveals a Google Utilities AppDelegate Swizzler problem:

![Screenshot 2024-08-16 at 4 09 53 PM](https://github.com/user-attachments/assets/ab863a18-c76c-4dd3-962c-3c02a749d488)

**Comment by paulb777** [comment]
I disabled swizzling and it still fails to find the selector:

`'-[FirebaseUITest.AppDelegate authUI:didSignInWithAuthDataResult:error:]: unrecognized selector sent to instance 0x600000228a20'`

Very weird since it's the exact same selector that works in FirebaseUI 13 .....

**Comment by paulb777** [comment]
I found the issue, a fix, and published v14.2.4

**Comment by joaomvfsantos** [comment]
@paulb777 I confirm it works. Thanks!

On a side note, because of the new `@objc` requirement I'm not sure if the [sample code](https://github.com/firebase/FirebaseUI-iOS/blob/main/samples/swift/FirebaseUI-demo-swift/Samples/Auth/FUICustomAuthUIDelegate.swift) need to be updated, but I trust your judgment.

**Comment by paulb777** [comment]
@joaomvfsantos Good to hear! Good catch on the sample, too. Thanks.  #1205

**Comment by ShaiAlkoby** [comment]
@paulb777 hey,
I've added @objc and I get a compilation error, any idea why?
![image](https://github.com/user-attachments/assets/5c7eeb26-d8c3-43a0-8df9-1827aeca8e8c)

**Comment by ShaiAlkoby** [comment]
nope
![image](https://github.com/user-attachments/assets/8629d9db-383e-4206-a720-02af1ee2e043)

**Comment by ShaiAlkoby** [comment]
@paulb777 I'm getting an error trying to install 14.2.4:
<img width="559" alt="image" src="https://github.com/user-attachments/assets/05afb399-26d9-4932-adaa-d55b74a42c8e">

I'm also not seeing it here, only 14.2.0: 
https://github.com/CocoaPods/Specs/blob/master/Specs/b/c/2/FirebaseUI/14.2.0/FirebaseUI.podspec.json

Could this be the issue?

**Comment by taiking** [comment]
I am experiencing the same issue in the Swift environment of Xcode 15.2.

**Comment by ShaiAlkoby** [comment]
also happens in Xcode 16. @paulb777 any suggestions?

**Comment by paulb777** [comment]
Please open another issue with a reproducible example and we can investigate.

**Comment by acgacgacgacg** [comment]
I use the FirebaseAuthUI in SwiftUI. I wrapped it in a UIViewControllerRepresentable and implemented the `makeCoordinator` method to set the delegate like the following

```swift
struct AuthView: View {
  var body: some View {
    AuthViewControllerRepresentable()
  }
}

struct AuthViewControllerRepresentable: UIViewControllerRepresentable
  ...
  func makeUIViewController(context: Context) -> UINavigationController {
    let authUI = FUIAuth.defaultAuthUI()!
    authUI.delegate = context.coordinator
```

The FUIAuthDelegate is not called if it is activated inside a `.sheet` like the following

```
.sheet(isPresented: $showAuthViewSheet) {
      AuthView()
    }
```
However, the FirebaseAuthUI method will get called if it is a stand alone page
