### ISSUE TITLE
Activity indicator is displayed in black only during the process

### ISSUE THREAD

**Issue by shosokawa** [firebase/FirebaseUI-iOS#1207]
### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 17.5.1
  * Firebase SDK version: 11.1.0
  * FirebaseUI version: 14.2.4
  
### Step 3: Describe the problem:

Activity indicator is displayed in black only.

![IMG_BBC47D495EC5-1](https://github.com/user-attachments/assets/bd35e307-74cb-46fe-b164-a451f10ed29b)

#### Steps to reproduce:

  1. Uses `FUIPhoneAuth`
  ```swift
          FeedbackGenerator.run(event: .tap)
        let authUI = FUIAuth.defaultAuthUI()!
        authUI.delegate = self
        authUI.providers = [FUIPhoneAuth(authUI: authUI)]
        let provider = authUI.providers.first as! FUIPhoneAuth
        provider.signIn(withPresenting: self, phoneNumber: nil)
  ```
  2. Follows the instructions to enter your phone number and code
  
#### Observed Results:

 Activity indicator is displayed as "black square"

#### Expected Results:

 Activity indicator is displayed as "indicator on black square" 
  
#### Relevant Code:

I guess that [this change](https://github.com/firebase/FirebaseUI-iOS/pull/1194/files#diff-c080bfba78002448be6b7c804e48b34b97ed0ca3f01ff4416dceb2c3d654db30) on https://github.com/firebase/FirebaseUI-iOS/pull/1194 is the cause.

I tried to restore the style to `UIActivityIndicatorViewStyleWhiteLarge` from `UIActivityIndicatorViewStyleLarge` locally and it worked.
![IMG_6CC5953CF6DB-1](https://github.com/user-attachments/assets/cf598eca-9fe0-4dc8-93cd-b7a668e2023b)

But `UIActivityIndicatorViewStyleWhiteLarge` is marked [deprecated](https://developer.apple.com/documentation/uikit/uiactivityindicatorview/style/whitelarge)

**Comment by LearnWithTung** [comment]
Same issue

**Comment by paulb777** [comment]
Thanks for the fix @willbattel. It's now in version 14.2.6 for Swift Package Manager and new FirebaseAuthUI podspec with the fix should be published tomorrow.

**Comment by nimamogh** [comment]
thanks for the fix. it displays correctly on v 14.2.6 now.
