### ISSUE TITLE
`Ambiguous inference of Objective-C name for instance method` when upgrading to FirebaseAuthUI 14.2.4

### ISSUE THREAD

**Issue by xaphod** [firebase/FirebaseUI-iOS#1209]
### Step 2: Describe your environment

  * Objective C or Swift:  Swift 6
  * iOS version: iOS 18.0.1
  * Firebase SDK version: 11.3.0
  * FirebaseUI version: 14.2.4
  * CocoaPods Version: 1.15.2
  
### Step 3: Describe the problem:

<img width="674" alt="Screenshot 2024-10-09 at 11 14 27 PM" src="https://github.com/user-attachments/assets/d03899ec-87a4-401c-94ef-a9e4d20f3cfd">

```
    func authUI(_ authUI: FUIAuth, didSignInWith authDataResult: AuthDataResult?, error: Error?) {
```

After updating to XCode 16, Swift 6, Firebase 11.3.0, FirebaseUI 14.2.4, I can't get past this error. 
This code worked fine in XCode 15, Swift 5.5, Firebase 10.29.0, FirebaseUI 14.0.0.

What's the correct `func` invocation for that method?

Imports above are:

```
import UIKit
import FirebaseAuth
import FirebaseEmailAuthUI
import FirebaseOAuthUI
import FirebaseGoogleAuthUI
import FirebaseAnalytics
```

**Comment by xaphod** [comment]
I tried following the documentation (using the Firebase 11 and later variation), and I tried XCode's auto fix, but it just gets into a fix loop, correcting it from one to the other and back again:

<img width="708" alt="Screenshot 2024-10-09 at 11 43 18 PM" src="https://github.com/user-attachments/assets/b77040aa-4267-481b-a93f-2b47550518bd">

**Comment by xaphod** [comment]
No it did not:

<img width="1260" alt="Screenshot 2024-10-10 at 11 28 48 AM" src="https://github.com/user-attachments/assets/1cf92b19-435d-4853-81f0-fec3c8bda84a">

I have tried following the examples (what you linked to), and the documentation at https://firebaseopensource.com/projects/firebase/firebaseui-ios/auth/readme/

I don't actually need anything from this function except the `Error?` for logging, source below. Are you able to get your example above compiling in XCode 16 / Swift 6? Please note I did a fresh install of XCode 16 on a fresh macbook running Sequoia 15.0.1 and did not customize any compiler options (beyond what the project was already using in Swift 5).

```
    @objc func authUI(_ authUI: FUIAuth, didSignInWith authDataResult: AuthDataResult?, error: Error?) {
        switch error {
        case .some(let error as NSError) where UInt(error.code) == FUIAuthErrorCode.userCancelledSignIn.rawValue:
            WLog("FUICustomAuthDelegate User cancelled sign-in")
        case .some(let error as NSError) where error.userInfo[NSUnderlyingErrorKey] != nil:
            WLog("FUICustomAuthDelegate Login error: \(error.userInfo[NSUnderlyingErrorKey]!)")
        case .some(let error):
            WLog("FUICustomAuthDelegate Login error: \(error.localizedDescription)")
        case .none:
            WLog("FUICustomAuthDelegate: Success")
            Analytics.logEvent(AnalyticsEventLogin, parameters: nil)
        }
    }
```

**Comment by ironcladbadger** [comment]
Same issue here after updating to XCode 16. Was working under XCode 15 with Firebase 10.29.0 and FirebaseUI 14.0.0. Did you find any workaround for this?
