### ISSUE TITLE
Build error on 0.5.3: Use of unresolved identifier 'FIRAuthUI'

### ISSUE THREAD

**Issue by davidsantiago** [firebase/FirebaseUI-iOS#127]
* Objective C or Swift: Swift
  * iOS version: 9.3.5
  * Firebase SDK version: 3.4.0
  * FirebaseUI version: 0.5.3
  * CocoaPods Version: 1.1.0-rc1
  * Xcode version: 8.0 GM
  
### Step 3: Describe the problem:

I had some login code that would build in 0.5.2, but failed at runtime because defaultAuthUI() would always return nil. Now 0.5.3 won't build with a "Use of unresolved identifier 'FIRAuthUI'" error on the following function in AppDelegate.

#### Steps to reproduce:

  1. Try to compile code in Swift that uses FIRAuthUI. The code in my app is basically identical to the example project, and in fact, you can reproduce this error by trying to build the samples in this repo.
  
#### Observed Results:

  * A build error on any line that attempts to use FIRAuthUI: 

/Users/David/Documents/code/FirebaseUI-iOS/samples/swift/uidemo/AppDelegate.swift:35:8: Use of unresolved identifier 'FIRAuthUI'
  
#### Expected Results:

  * I expected the code to build successfully. The same code will build when version 0.5.2 is used. 
  
#### Relevant Code:

In the sample project in this repo: 
https://github.com/firebase/FirebaseUI-iOS/blob/0c9dfffe7ec7d1c168370e83afaaf504080c43c9/samples/swift/uidemo/AppDelegate.swift#L35

As in my code: 

AppDelegate.swift
-------------------
...
import Firebase
import FirebaseAuthUI
...
    func application(app: UIApplication, openURL url: NSURL, options: [String: AnyObject]) -> Bool {
        let sourceApplication = options[UIApplicationOpenURLOptionsSourceApplicationKey] as! String
        if FIRAuthUI.defaultAuthUI()?.handleOpenURL(url, sourceApplication: sourceApplication ?? "") ?? false {
            return true
        }
        // Any other URL handling here
        return false
    }

**Comment by morganchen12** [comment]
This is a consequence of #119. I haven't found a workaround other than repeatedly clean and rebuild until it compiles.

Fortunately this seems to be solved in the latest release that hasn't shipped yet, though I'm not sure which change fixed it.

**Comment by davidsantiago** [comment]
About how many cycles does it take you before it builds? I've gone around and around a few times and there's never any change. I've also been removing the derived data folder and restarting Xcode, to no avail.

**Comment by morganchen12** [comment]
Anywhere between 0 and a lot :D it's fixed in #126, so hold tight while I go merge this thing

**Comment by morganchen12** [comment]
Fixed in 0.5.4.
