### ISSUE TITLE
Can't sign in with Simulator after update to Xcode 8.0

### ISSUE THREAD

**Issue by psopher** [firebase/FirebaseUI-iOS#130]
I just updated to Xcode 8.0, and I can't log into my with Google, Facebook, or Email/Password with the iPhone Simulator now.

Error Message for Google Sign-in:
````There was an error: Error Domain=FIRAuthUIErrorDomain Code=1 "(null)" UserInfo={FIRAuthUIErrorUserInfoProviderIDKey=google.com, NSUnderlyingError=0x600000841b00 {Error Domain=com.google.GIDSignIn Code=-2 "keychain error" UserInfo={NSLocalizedDescription=keychain error}}}````

Error Message for Facebook Sign-in:
````There was an error: Error Domain=FIRAuthUIErrorDomain Code=1 "(null)" UserInfo={FIRAuthUIErrorUserInfoProviderIDKey=facebook.com, NSUnderlyingError=0x6080008548b0 {Error Domain=com.facebook.sdk.login Code=308 "(null)"}}````

Error Message for Email/Password Sign-in:
````There was an error: Error Domain=FIRAuthErrorDomain Code=17995 "An error occurred while accessing the keychain." UserInfo={NSLocalizedDescription=An error occurred while accessing the keychain., error_name=ERROR_KEYCHAIN_ERROR, NSLocalizedFailureReason=SecItemAdd (-34018)}````

The problem only occurs on my iPhone Simulator. What's going on?

**Comment by psopher** [comment]
Just found the answer...

http://stackoverflow.com/questions/38812761/gidsignin-keychain-error-ios-10-xcode-8

**Comment by mcdonamp** [comment]
Yeah, the short answer is that the keychain in the simulator is broken on iOS 10 (yes, even the GM release). It should work on a physical device, and we've filed a radar with Apple to get this fixed in the sim.
