### ISSUE TITLE
Override FEventType Animation

### ISSUE THREAD

**Issue by mbalex99** [firebase/FirebaseUI-iOS#14]
It'd be great to be able to override the animation with respect to the cell's event changes.

For example, chat apps often have cells that are aligned left or right depending on the `userId`. The animation for inserted cells maybe `UITableViewRowAnimation.Left` for received message but `.Right` for a sent message. 

Maybe use a block API with the FEventType enum?

`dataSource.overrideAnimation{eventType: FEventType, withBlock: { (cell, snapshot) -> Void } }`

**Comment by pmodernme** [comment]
I think the easiest way to do that would be in your `FirebaseTableViewDataSource` subclass to override the `childAdded:atIndex`, `childChanged:atIndex`, etc methods, and implement your own logic. Look at the child object to determine which type of animation is applicable.

**Comment by mcdonamp** [comment]
The above was the original intention: if you want custom behavior, use `FirebaseTableViewDataSource` as a base implementation and override the specific behavior as necessary. In the future, we may try to make them properties of the tableview or of the section in the tableview.

**Comment by mcdonamp** [comment]
Closing this because the current recommendation is the subclass and override--support for this natively is a little while off.
