### ISSUE TITLE
Return OAuth access/id tokens after a successful sign-in operation

### ISSUE THREAD

**Issue by alfongj** [firebase/FirebaseUI-iOS#142]
After my users sign in with a federated provider (Google, Facebook, Twitter), I may want to have access to the access token/ id token that is obtained during the sign in flow in order to utilize it to authorize accesses to some of the provider APIs (e.g. Google Drive or Facebook graph API) on behalf of that user.

FirebaseUI should expose such a token if it has been obtained during the sign-in operation.

If multiple credentials are obtained during the sign-in flow (e.g. in case of linking required), all credentials should be returned.

**Comment by yramanchuk** [comment]
Implemented in the next way:

1. you are able to get access/id token only if you have logged-in. In case app re-launch federated provider tokens are not filled (you need to call login again)
2. Facebook provider have only access token (id token always is nil)
3. For Twitter provider: 

 - access token returns twitter authorization token.
 - id token return twitter authorization token secret.

4. FirebaseUI doesn't support account linking. But it's still possible to get all tokens from logged-in users (e g multiple logins with various providers).

**Comment by alfongj** [comment]
@yramanchuk w.r.t. point number 4: I meant that when a user tries to sign in with facebook, but he had a previously existing account with, let's say, Google, he will end up authenticating both with facebook and Google.

In such case we may want to consider returning both credentials.

**Comment by yramanchuk** [comment]
things to clarify:
1. we can have multiple access tokens only if user had sign in several times. This is already implemented
2. should we clean access token if user signed in with different email (unlinked account) without sigh out previously?

**Comment by yramanchuk** [comment]
implemented in 0.5.6-rc3
token cleaning should be done separately
