### ISSUE TITLE
Extend SDWebImage to accept a FIRStorageReference

### ISSUE THREAD

**Issue by mcdonamp** [firebase/FirebaseUI-iOS#146]
Add support for Firebase Storage image loading by extending [SDWebImage](https://github.com/rs/SDWebImage).

Sample code:
```
// Load from imageRef into UIImageView imageView
[imageView sd_setImageWithStorageReference:imageRef
                          placeholderImage:[UIImage imageNamed:@"placeholder.png"]
                                 completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
                                // ... completion code here ...
                           }];
```

**Comment by morganchen12** [comment]
Done in #150.

**Comment by Archivus** [comment]
FIRStorage doesn't seem to support `imageView.sd_setImage(with: <#T##URL?#>, placeholderImage: <#T##UIImage?#>, options: <#T##SDWebImageOptions#>)`

**Comment by morganchen12** [comment]
No. Use one of the methods in [`UIImageView+FirebaseStorage.h`](https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseStorageUI/UIImageView%2BFirebaseStorage.h) instead.

**Comment by Archivus** [comment]
@morganchen12 None of the offered methods seem to support `SDWebImageOptions`. I was looking to download progressive JPEGs using the` SDWebImageOptions.progressive` option.

**Comment by morganchen12** [comment]
I see. You can open a new issue for this, but adding support for SDWebImageOptions is very involved and likely won't happen for a while.

**Comment by admingj** [comment]
Did SDWebImageOptions ever get supported?

**Comment by morganchen12** [comment]
No, FirebaseUI Storage doesn't support any loading via SDWebImage yet unfortunately.

**Comment by admingj** [comment]
Okay thank you. Is there any way to recreate what Firebase is doing with the StorageReference? Aka can we turn it into a url somehow? Or does FirebaseUI create some sort of encrypted url path that it uses to download from Cloud Storage (that isn't replicable with a plain string Url)?

Only way I know of right now is of course doing the `getSignedUrl` method but that takes another trip to the server (or using Cloud Functions with a Service Account)

https://stackoverflow.com/questions/50706401/firebase-function-node-js-to-return-download-url-of-image-via-filename-from

**Comment by morganchen12** [comment]
The easiest way to do this would be to just generate a download URL using the Storage SDK and then pass it into SDWebImage, at which point you'd get everything for free.
