### ISSUE TITLE
return receipt  observeEventType who receive my message ! 

### ISSUE THREAD

**Issue by modiodio** [firebase/FirebaseUI-iOS#15]
Hello Guys,

I have a little question.
I am making one 2 one IOS / Android chat  with Firebase. 
I am currently facing a problem.
When a user send a message to other user, How to know that the second user really receive the message. It is important for me because if he didn't receive the message I have to send a push notification to him !  

Thanks for helps !

**Comment by mcdonamp** [comment]
@modiodio This isn't really an issue in FirebaseUI so much as a larger question of how to do read receipts in Firebase. We don't support this natively in FirebaseUI, as FirebaseUI isn't a chat system, but it could be easily built in to [Firechat](https://firechat.firebaseapp.com), our open source chat client.

A simple example of this would be to have a property `viewed` on each message in your Firebase, and when a client saw it, they would mark this property as true, which the other client could be listening on. That said, read receipts aren't going to be the best way to trigger a push notification, as you don't know if the user is offline, or just in the app but not on your chat. I would check out the [offline/background capabilities](https://www.firebase.com/docs/ios/guide/offline-capabilities.html) of Firebase, as those are going to be more in line with sending push notifications. We're also working on integrating with GCM for tighter push integration.
