### ISSUE TITLE
Update FirebaseUI cocoa pod page

### ISSUE THREAD

**Issue by yramanchuk** [firebase/FirebaseUI-iOS#151]
Update cocoa pod info on https://cocoapods.org/pods/FirebaseUI

**Comment by mcdonamp** [comment]
Pretty sure this gets populated from the `README.md` we ship with the pods... which I don't think we ship in the zip. In case you don't believe me: http://cocoadocs.org/docsets/FirebaseUI/0.3.2/ was the last full readme (it pulled from Github).

We should include a `README.md` that gets deployed in the framework zip, @morganchen12 can you add this to the build process? The current overall one is fine for now.

**Comment by morganchen12** [comment]
fixed in 279ba82437bf1aaec5398c06d99fe6205f0abc66
