### ISSUE TITLE
Customizing authPickerViewControllerForAuthUI

### ISSUE THREAD

**Issue by carliskisantiago** [firebase/FirebaseUI-iOS#159]
Hi all, 
I'm facing an issue related with authPickerViewControllerForAuthUI. I'm using my own auth screen but I have problems to customize the subsecuent screens that remain with the default UI, how can I change it as to fit the style I'm using for my custom LoginViewController?
Best,
Santiago.

**Comment by yramanchuk** [comment]
Customization of all screens if part of v0.6.2
