### ISSUE TITLE
Multiple cell types in FirebaseTableViewDataSource 

### ISSUE THREAD

**Issue by algrid** [firebase/FirebaseUI-iOS#177]
Do you have any plans implementing multiple cell kinds (multiple prototype cells) in FirebaseTableViewDataSource/FirebaseCollectionViewDataSource?

**Comment by morganchen12** [comment]
In the short term I'd like to remove the cell registration from the data source since it's not part of the data source's responsibilities, which would give devs much more flexibility in this regard at the cost of a line or two of boilerplate.

**Comment by algrid** [comment]
@morganchen12 It looks like it'd be a good solution. Look forward for new versions, thanks 👍

**Comment by morganchen12** [comment]
Added in #178, will be available in the 0.7.0 release.
