### ISSUE TITLE
Adopt a consistent objc prefix

### ISSUE THREAD

**Issue by morganchen12** [firebase/FirebaseUI-iOS#189]
FirebaseUI should adopt a consistent objc prefix naming convention. `FIR` is borrowed from the Firebase frameworks themselves and should not be used.

**Comment by mcdonamp** [comment]
FUI seems reasonable. Other thoughts @yramanchuk?

**Comment by morganchen12** [comment]
Yeah, we're adopting `FUI`. Changes are in the `v1.0.0` branch.

**Comment by morganchen12** [comment]
Resolved in FirebaseUI 1.0.0
