### ISSUE TITLE
Pull request #13 sections crash

### ISSUE THREAD

**Issue by kermankohli** [firebase/FirebaseUI-iOS#19]
Whilst updating multiple items in a tableview with sections a crash occurs at:

- (void)sectionAddedAtSectionIndex:(NSUInteger)section {
    [self.tableView insertSections:[NSIndexSet indexSetWithIndex:section]
                  withRowAnimation:UITableViewRowAnimationAutomatic];
}

**Comment by mcdonamp** [comment]
cc @pmodernme

**Comment by pmodernme** [comment]
Are you using the most recent version of my pull request? It has had
multiple updates over the last few months.

By "multi-path writes" do you mean you're updating child values? Or are you
doing a transaction? Should what you're doing create a new section, or is
that a bug in itself?

I could attempt to recreate the issue, but without any specific code, it
will be difficult.

**Comment by kermankohli** [comment]
Yeap, it's the latest version :) Oh and yeah by multi-path writes I meant updating child values. 

update: I was recently having some other crashes which I fixed up, and I think it fixed this issue up. Not sure how my code affected the tableview sectioning code though :confused:
