### ISSUE TITLE
installing cocoapods errors

### ISSUE THREAD

**Issue by abdalmajed** [firebase/FirebaseUI-iOS#196]
I'm trying to install this pod:

```ruby
platform :ios, '8.0'
use_frameworks!

target 'my First FireBase App' do
    pod 'Firebase/Core'
end
```

but I have this error :
Analyzing dependencies
Downloading dependencies
Installing Firebase (3.7.0)

[!] Error installing Firebase
[!] /usr/bin/tar xfz /var/folders/0y/wgt7vz0s3f501b_fhw8b8m5m0000gn/T/d20161105-966-1lvnaf1/file.tgz -C /var/folders/0y/wgt7vz0s3f501b_fhw8b8m5m0000gn/T/d20161105-966-1lvnaf1

tar: Unrecognized archive format
tar: Error exit delayed from previous errors.

**Comment by morganchen12** [comment]
This seems like not a FirebaseUI issue. It looks like something bad happened to your download, try clearing CocoaPods cache and installing again?
