### ISSUE TITLE
user displayName and photoURL are nil when logging in via Google

### ISSUE THREAD

**Issue by yorgosg** [firebase/FirebaseUI-iOS#199]
On logging in via Google, even though the "View your basic profile" permission is presented to me and I allow it, the user.displayName and the user.photoURL are returned nil in the didSignInWithUser method.

**Comment by morganchen12** [comment]
@yramanchuk FYI

**Comment by ahaverty** [comment]
@yorgosg I know in Android I needed to loop through the providerData to get anything of value from social sign on accounts.
Have you looked at [ProviderData](https://firebase.google.com/docs/reference/ios/firebaseauth/api/reference/Classes/FIRUser#providerdata)? _(The iOS documentation actually looks worse than the Android...)_

[Here's my answer to this problem, in Android/Java.](http://stackoverflow.com/a/38685639/2276198). I'd imagine it's the same concept, but I haven't gotten to it yet in iOS.
Essentially, each provider (google, facebook, twitter) can be linked to a Firebase account and therefore have different display names and profile images etc. You need to loop through and check if there are any providers if the user.photoUrl / user.displayName was nil.

**Comment by yorgosg** [comment]
@ahaverty I checked again and the providerData had all the info, like you said. I though I had looked there before, my bad. I am closing this, cheers guys.

**Comment by ahaverty** [comment]
It might be worth raising an issue against Firebase's documentation, you're not the first person to hit this issue 👏
