### ISSUE TITLE
Replace self.sectionKeyPath with sectionKeyPath:

### ISSUE THREAD

**Issue by kermankohli** [firebase/FirebaseUI-iOS#20]
Instead of dataSource.array.sectionKeyPath being a string, there should be something like this to return the value:

func returnSectionKeyPath(keypath: String, forSnapshot: FDataSnaphot) -> String {
// code to determine name of section
return nameOfSection
}

**Comment by mcdonamp** [comment]
cc @pmodernme

**Comment by pmodernme** [comment]
Much of the functionality in my pull request is meant to be open to
sunclassing.

I reccomend you subclass FirebaseTableViewDataSource and implement your own
titleForHeaderInSection and use [self.array.sectionValues
objectAtIndex:section] to get the raw data. Then return your version of the
title.

Your idea is interesting, but the above is the current way to achieve what
you want.

**Comment by kermankohli** [comment]
For sure, that's one way to achieve the desired result. However sometimes there needs to a slightly more detailed level of filtering. If I want to group all objects where the date is in the next 7 days then I can't really achieve that unless I created another child on my object - which would be pretty unnecessary.

**Comment by kermankohli** [comment]
So I gave it an attempt by forking pmodernme's repo, although it's a pretty hacky solution.. Can't really figure out a super elegant solution to make it work properly although idm waiting till 0.4 :)

**Comment by kermankohli** [comment]
Currently got a splitviewcontroller with the master containing FirebaseTableViewDataSource. Although when an object is changed, it crashes on 

- (void)sectionAddedAtSectionIndex:(NSUInteger)section {
    [self.tableView insertSections:[NSIndexSet indexSetWithIndex:section]
                  withRowAnimation:UITableViewRowAnimationAutomatic];
}

When I do the same thing on the iPhone (without the split view) it doesn't crash. Any ideas?

@mcdonamp When will 0.4 be released?

**Comment by kermankohli** [comment]
@mcdonamp Any updates on 0.4?

**Comment by mcdonamp** [comment]
@kermankohli we've spent some time clearning up the 0.3 stuff (mostly on Android), and then work on both platforms for 0.4 is going to move forward. Likely a bunch of the 0.4 stuff is done here (thanks to the community support :), though Android is going to be a little more work.

**Comment by kermankohli** [comment]
@mcdonamp Hey! Firebase 3.0 is really cool although still waiting on the FirebaseUI to have a sorted and sectioned tableview adapter. @pmodernme's solution is pretty good although it doesn't work with Firebase 3.0...

**Comment by pmodernme** [comment]
Sorry I haven't updated my work on the UI in a while. I've been focused on
trying to get my current project out the door. I imagine the old code
wouldn't be too hard to port if somebody was feeling adventurous.
Also, I wonder if @mcdonamp knows if there is already a more official
replacement in the works.

**Comment by morganchen12** [comment]
`sectionKeyPath` has been removed.
