### ISSUE TITLE
How to work with two identifiers in UICollectionView?

### ISSUE THREAD

**Issue by nhantrivinh** [firebase/FirebaseUI-iOS#201]
What I want is to use the first cell as a "+" button to add an item onto the list onto Firebase. Then the subsequent cells are just the list of items on Firebase. 

I want to know the recommended way to approaching this problem using FirebaseUI.

```swift
self.collectionViewDataSource =
    FUICollectionViewDataSource(query: self.query!, view: self.collectionView, populateCell: {
        (view, indexPath, snapshot) -> UICollectionViewCell in
                
        let cell = view.dequeueReusableCell(withReuseIdentifier: Constants.Identifiers.Show.MenuCell, for: indexPath) as! MenuCell
        
        let menu = Menu(snapshot: snapshot)
                
        //set a label to a title
        cell.configureCell(menu: menu)
        
        return cell
    })
        
self.collectionView.dataSource = self.collectionViewDataSource
```

![screenshot 2016-11-14 12 44 55](https://cloud.githubusercontent.com/assets/12175043/20254551/44f30ae0-aa68-11e6-8027-f62985388d1e.jpeg)

**Comment by morganchen12** [comment]
The most direct way would be to check the index path and dequeue a different cell if it's the first cell in the collection.

```swift
self.collectionViewDataSource =
    FUICollectionViewDataSource(query: self.query!, view: self.collectionView, populateCell: {
        (view, indexPath, snapshot) -> UICollectionViewCell in
                
        let cell: UICollectionViewCell

        if indexPath.item == 0 {
            cell = /* ... */
        } else {
            cell = view.dequeueReusableCell(withReuseIdentifier: Constants.Identifiers.Show.MenuCell, for: indexPath)
        }
        /* ... */
        return cell
    })
```

**Comment by nhantrivinh** [comment]
Like this:
![simulator screen shot nov 15 2016 12 04 41 pm](https://cloud.githubusercontent.com/assets/12175043/20293790/c683dddc-ab2b-11e6-90f9-0c7e018fd71e.png)

From this:
![screenshot 2016-11-15 11 58 50](https://cloud.githubusercontent.com/assets/12175043/20293702/1f8c81dc-ab2b-11e6-8606-7bc2948ab402.jpeg)

Without needing to add a child with a value of "+"
As of now the number of cell equals the number of child. So how do I add an extra cell without needing to add a child and a value to create an extra cell?

**Comment by morganchen12** [comment]
Ah, I see. You can't currently; FirebaseUI doesn't provide a way to mix Firebase and non-Firebase data in the same data source.

However, since you'd never be re-using the `+` cell, it's best to not have that be a cell at all and instead have it be a separate view on top of your collection view that hides when the user scrolls (much like many nav bars do in modern apps).
