### ISSUE TITLE
A new version of the Google Sign-IN SDK is available

### ISSUE THREAD

**Issue by snoupyrelete** [firebase/FirebaseUI-iOS#202]
### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 9+  
### Step 3: Describe the problem:
I get the error: A new version of the Google Sign-In iOS SDK is available: https://developers.google.com/identity/sign-in/ios/release

#### Steps to reproduce:
I've used this tutorial: https://blog.tamarai.ca/a-swift-introduction-to-authentication-using-firebase-ui-ios-2d9d56e09b35#.w1rkj2nxo

#### Expected Results:
Should go to the google login page- doesn't crash but doesn't do anything either
#### Relevant Code:

```swift
import Foundation
import UIKit
import Firebase
import FirebaseAuthUI
import FirebaseGoogleAuthUI
import FirebaseFacebookAuthUI

class ProfileViewController: UIViewController, FIRAuthUIDelegate
{
    @IBOutlet weak var usernameLabel: UILabel!
    @IBOutlet weak var bioLabel: UILabel!
    
    @IBAction func loginButtonPressed(_ sender: AnyObject)
    {
        let authUI = FIRAuthUI.init(auth: FIRAuth.auth()!)
        let options = FIRApp.defaultApp()?.options
        let clientId = options?.clientID
        authUI?.delegate = self
        authUI?.providers = [FIRGoogleAuthUI(clientID: clientId!)]
        let authViewController = authUI?.authViewController();
        self.present(authViewController!, animated: true, completion: nil)
        
    }
    
    
    func authUI(_ authUI: FIRAuthUI, didSignInWith user: FIRUser?, error: Error?)
    {
        
    }

    override func viewDidLoad()
    {
        let x = Profile()
        bioLabel.text = x.bio
        self.title = "Profile"
        //self.navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .action, target: self, action: #selector(messageButtonTapped))
    }
    
    func messageButtonTapped()
    {
        print("Message")
    }
}

  ```

**Comment by caldwbr** [comment]
Dylan Robson I think your problem is that you have a semicolon at the end of the line that says let authViewController = authUI?.authViewController()

**Comment by morganchen12** [comment]
@snoupyrelete when you run `pod install`, what version of GoogleSignIn does it say it's using?

**Comment by snoupyrelete** [comment]
@morganchen12 It says 4.0: "Using GoogleSignIn (4.0.0)"

**Comment by snoupyrelete** [comment]
@caldwbr oops, fixed that but still doesn't change anything.

**Comment by morganchen12** [comment]
Try running `pod update`.

**Comment by snoupyrelete** [comment]
@morganchen12 updated, still 4.0.0... Here's my podfile, I don't have the '~> 1.0' as suggested on the readme because it gives me: (and pod repo update doesn't do anything either)

[!] Unable to satisfy the following requirements:

- `FirebaseUI (~> 1.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `FirebaseUI (~> 1.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'MentorMe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MentorMe
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Database’

pod 'FirebaseUI'

end

**Comment by morganchen12** [comment]
I cloned your project and ran `pod update` and it updated GoogleSignIn to 4.0.1. Try updating your CocoaPods install.

For future reference, our issue tracker is generally not the place to go to for 1:1 technical support for your individual project.
