### ISSUE TITLE
Recommended approach to multiple node parsing

### ISSUE THREAD

**Issue by nhantrivinh** [firebase/FirebaseUI-iOS#203]
![screenshot 2016-11-15 12 33 27](https://cloud.githubusercontent.com/assets/12175043/20294322/e34aa870-ab2f-11e6-95ac-eaea094315dd.jpeg)

My parsing starts at menus, then categories, and then items. Each one having its own View Controller. The problem is the delay that comes with parsing a flatten out data. Is it recommended to structure my data as such? If yes, then what is the recommended approach to pre-parse for subsequent View Controllers?

**Comment by morganchen12** [comment]
This is covered pretty clearly in our [documentation](https://firebase.google.com/docs/database/ios/structure-data). If you're experiencing performance bottlenecks when downloading and parsing your JSON, you're likely downloading far too much at once.

Please don't use our issue tracker as your personal app dev help center.
