### ISSUE TITLE
FIRGoogleAuthUI initWithClientID and FIRFacebookAuthUI initWithAppID disappear ?

### ISSUE THREAD

**Issue by LeChatNoir69** [firebase/FirebaseUI-iOS#204]
Hi guys,

I've just updated my pods and having an issue with theses two methods. XCode tells me there is no visible @interface for initWithClientID (Google) and initWithAppID (Facebook).
I've search in code but can't find these methods :( Are they replaced by other one ? 

Thank you in advance :)

### Step 2: Describe your environment

  * Objective C or Swift: Obj-C
  * iOS version: 9
  * Firebase SDK version: Using Firebase (3.9.0)
  * FirebaseUI version: Using FirebaseUI (0.7.0)
  * CocoaPods Version: 1.0.1
  
My code : (working before pod update)
```
FIRAuthUI *authUI = [FIRAuthUI defaultAuthUI];
FIRGoogleAuthUI *googleAuthUI =
[[FIRGoogleAuthUI alloc] initWithClientID:@"193xxxg.apps.googleusercontent.com"];
FIRFacebookAuthUI *facebookAuthUI =
[[FIRFacebookAuthUI alloc]  :@"2xxxxxxxx7078"];
authUI.providers = @[googleAuthUI,facebookAuthUI];
authUI.customStringsBundle = [NSBundle mainBundle];
authUI.delegate = self;

UIViewController *authViewController = [authUI authViewController];
[self presentViewController:authViewController animated:YES completion:^(void){
    nil;
}];
```

**Comment by morganchen12** [comment]
The Auth providers were refactored to pull as much info as possible from plist files. The Facebook provider now only requires an array of permissions, and the Google provider only requires an array of scopes. The client IDs are fetched by the providers from their respective plist files.

0.7.0 was the last minor update version with breaking changes, but be aware when updating to 1.0.0 that many of the classes were renamed.

Your code could be rewritten as follows:

```objc
FIRAuthUI *authUI = [FIRAuthUI defaultAuthUI];
FIRGoogleAuthUI *googleAuthUI = [[FIRGoogleAuthUI alloc] init];
FIRFacebookAuthUI *facebookAuthUI = [[FIRFacebookAuthUI alloc] init];
authUI.providers = @[googleAuthUI, facebookAuthUI];
authUI.customStringsBundle = [NSBundle mainBundle];
authUI.delegate = self;

UIViewController *authViewController = [authUI authViewController];
[self presentViewController:authViewController animated:YES completion:^(void){
    /* ... */
}];
```
