### ISSUE TITLE
Sign in with email creation page gets stuck on loading indicator and is not being dismissed

### ISSUE THREAD

**Issue by yorgosg** [firebase/FirebaseUI-iOS#205]
After I select the "Sign in with email" button in the authViewController and then write an email address in the "Sign in with email" screen, I am presented with the "Create account" screen, where I enter the details needed and then I press "Save". The loading indicator appears but it always hangs there. If I press on "Save" once or twice after that (since there is not much to do) an error alert message comes up, saying that "The email address is already in use by another account". If I go Back to the previous screen and forward again, I am asked to sign in, which works OK and the screen is dismissed.

I have set the FUIAuthDelegate delegate for the appdelegate, where the following code is:

```objc
FUIAuth *authUI = [FUIAuth defaultAuthUI];
authUI.delegate = self; // Set the delegate to receive callback.
authUI.TOSURL = [NSURL URLWithString:@"http://..."];

FUIFacebookAuth *facebookAuthUI = [[FUIFacebookAuth alloc] initWithPermissions:@[@"email", @"public_profile", @"user_friends"]];
FUIGoogleAuth *googleAuthUI = [[FUIGoogleAuth alloc] init];
FUITwitterAuth *twitterAuthUI = [[FUITwitterAuth alloc] init];

authUI.providers = @[facebookAuthUI, googleAuthUI, twitterAuthUI];

UIViewController *userLoginViewController = [authUI authViewController];
[self presentViewController:userLoginViewController animated:YES completion:nil];
```
Please let me know if this happens to anyone else, cheers!

**Comment by yorgosg** [comment]
I would like to add something to my previous post. I have been testing registering and signing in for a couple days now and I have seen this hanging of the loading indicator happen on three different occasions:
- On pressing the "Create" button on the "Create account" screen (as I have already stated in my previous post).
- On pressing the "Next" button on the "Sign in with email" screen
- On pressing the "Sign in" button on the "Sign in" screen.

Sometimes pressing the button a second or third time leads to a successful result. Not on the first case - as I have already written before - as this way you basically retry creating an account already created. 

I believe it is something that has to do with finalizing the end result, as most of the times the result has already happened but there is no UI feedback.
 
Statistically this happens like 20-30% of the time, but it still does happen and I think this should be dealt with.

**Comment by morganchen12** [comment]
This is probably a bug.

**Comment by yramanchuk** [comment]
@yorgosg, actually I can't reproduce your case.
I was simulating slow network (including 100% packet loss).

Pressing 'Next' or 'Save' buttons several times is bad idea: you will trigger several duplicate requests . Probably we will disable that buttons while activity indicator is shown (later after 60 secs appropriate alert should be shown: _The request timeout_).

Is that issue still reproducible? Can you try on different network? What happens after 2 min waiting?

**Comment by yorgosg** [comment]
Hi again @yramanchuk, to be honest I have been trying for a while myself to reproduce this and I cannot. I haven't changed anything in my code since then, but I haven't seen it. I am closing it for now and in case I come across it again I will reopen it, cheers

**Comment by kovalskyy** [comment]
I have the same issue with infinite activity indicator but when I use phone registration.
