### ISSUE TITLE
Sign out method with completion block and ideally with a new anonymous user being returned.

### ISSUE THREAD

**Issue by yorgosg** [firebase/FirebaseUI-iOS#206]
After signing out, I am signing in the user anonymously if sign out succeeds. 
At first, it would be best if the signing in was done asynchronously with a completion block.
Ideally for me there could also be a sign out method that automatically returns an anonymous user post signing out successfully. 

What I do now is the following:

```
NSError *error;
[[FIRAuth auth] signOut:&error];
if (!error) {
            [[FIRAuth auth] signInAnonymouslyWithCompletion:^(FIRUser *_Nullable user, NSError *_Nullable error) {
...
...
```

However, I have seen the anonymous sign in fail twice with this code, among tens of successful times, but still... I am wondering if this is because the anonymous sign in happens right after the sign out. Perhaps, I should add a small delay between the two.

Please let me know if I could do something alternative, or if any of my requests could be implemented in the future. Cheers!

**Comment by morganchen12** [comment]
You should use an [auth change listener](https://firebase.google.com/docs/reference/ios/firebaseauth/api/reference/Classes/FIRAuth#/c:objc(cs)FIRAuth(im)addAuthStateDidChangeListener:).

**Comment by yorgosg** [comment]
Yes, this is the best way I think. Thanks @morganchen12 !
