### ISSUE TITLE
Is FIRAuthErrorCodeCredentialTooOld being handled in FirebaseUI?

### ISSUE THREAD

**Issue by yorgosg** [firebase/FirebaseUI-iOS#207]
I have read in the following link that FIRAuthErrorCodeCredentialTooOld might be returned when performing certain actions for a user who hasn't signed in in a while. Is this being handled by FirebaseUI internally or do we need to handle it?

https://firebase.google.com/docs/auth/ios/manage-users

**Comment by morganchen12** [comment]
FirebaseUI doesn't handle this case as far as I know.

**Comment by yorgosg** [comment]
@morganchen12 In that url I posted it says that "When this happens, re-authenticate the user by getting new sign-in credentials from the user and passing the credentials to reauthenticate."

So, we need to handle this externally without the use of FirebaseUI?

**Comment by morganchen12** [comment]
You should be able to use the same FirebaseUI auth flow again with a "session expired" message. Admittedly FirebaseUI doesn't really take this error into account, so the auth flow may require some customization. Might be worth proposing as a feature.

cc @yramanchuk
