### ISSUE TITLE
FUIArray sample in Swift

### ISSUE THREAD

**Issue by nhantrivinh** [firebase/FirebaseUI-iOS#210]
Request

**Comment by morganchen12** [comment]
There's limited information in the [FirebaseUI Database readme](https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseDatabaseUI/README.md). We probably won't add more until the functionality of FUIArray is extended, as it's currently mostly an implementation detail of the data sources. #186 extends FUIArray to be more interesting, after which some samples would be good.

I'm going to close this issue though, as your wording isn't very specific.
