### ISSUE TITLE
pod install fails with "None of your spec sources contain a spec satisfying the dependency: `FirebaseUI (~> 1.0)`."

### ISSUE THREAD

**Issue by astromme** [firebase/FirebaseUI-iOS#212]
* Objective C or Swift: Swift
  * iOS version: 10
  * CocoaPods Version: 1.0.1
  
### Step 3: Describe the problem:
I try to install with pods as referenced on README.md but get an error.

#### Steps to reproduce:

  1. Add `pod 'FirebaseUI', '~> 1.0'       # Pull in all Firebase UI features` to my Podfile
  2. Run `pod install`
  
#### Observed Results:

```
[!] Unable to satisfy the following requirements:

- `FirebaseUI (~> 1.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `FirebaseUI (~> 1.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```  
#### Expected Results:

The steps in the README.md to work

**Comment by astromme** [comment]
Apparently I needed to run `pod repo update`. Might be worth mentioning that on the README.md

**Comment by morganchen12** [comment]
That's part of standard CocoaPods usage, which is why it's not included in the readme. It applies globally to any pod for which you don't have the spec.
