### ISSUE TITLE
Recreating the exact animation effect of UITableViewCell/UICollectionViewCell from FirebaseUI

### ISSUE THREAD

**Issue by nhantrivinh** [firebase/FirebaseUI-iOS#213]
I want to recreate the exact animation effect of UITableViewCell/UICollectionViewCell from FirebaseUI. I want to recreate this exact effect without using FirebaseDatabaseUI. I will have my own cell instead and I want the same animation to apply for my own cell.

Thanks in advance :)

**Comment by morganchen12** [comment]
You can use FirebaseDatabaseUI with custom table view cells.

**Comment by nhantrivinh** [comment]
Due to the limitation of FirebaseDatabaseUI at the moment. I have decided to switch over to just using Firebase child observers. However, I do really like the animation effects that were implemented in FirebaseDatabaseUI. So I would like to know how to recreate the fade-in and fade-out like FirebaseDatabaseUI.

**Comment by morganchen12** [comment]
Those are standard UITableView animations which you can find in the [FirebaseDatabaseUI source code](https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseDatabaseUI/FUIIndexTableViewDataSource.m#L83).
