### ISSUE TITLE
Excessive build warnings

### ISSUE THREAD

**Issue by jlaws** [firebase/FirebaseUI-iOS#214]
### Step 1: Are you in the right place?

Yes

### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: iOS 10
  * Firebase SDK version: 3.10.0
  * FirebaseUI version: 1.0.0
  * CocoaPods Version: 1.1.1
  
#### Steps to reproduce:

  1. Compile a project that depends on firebase
  
#### Observed Results:

  * Lots of warnings about nullability specifiers, for example "FIREmailPasswordAuthProvider.h:35:1: Conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'"
  
#### Expected Results:

  * No Warnings

**Comment by morganchen12** [comment]
This is an issue with upstream Firebase Auth, and will be fixed in the next Firebase release. This issue will remain open until then.

Thanks for reporting!

**Comment by morganchen12** [comment]
This is fixed with the Firebase 3.11 release. Running `pod update` should resolve the issue.
