### ISSUE TITLE
Warnings on pod install from test targets overriding OTHER_LDFLAGS

### ISSUE THREAD

**Issue by paulb777** [firebase/FirebaseUI-iOS#215]
### Step 1: Are you in the right place?
Yes

### Step 2: Describe your environment

  * Objective C or Swift: N/A
  * iOS version: N/A
  * Firebase SDK version: 3.10.0
  * FirebaseUI version: 1.0.0
  * CocoaPods Version: 1.0.1
  
#### Steps to reproduce:

  1. git clone https://github.com/firebase/FirebaseUI-iOS.git
  2. cd FirebaseUI-iOS/
  3. pod install
  
#### Observed Results:

  * Eight warnings from test targets overriding OTHER_LDFLAGS

`Analyzing dependencies
Fetching podspec for `FirebaseAuthUI` from `FirebaseUI_dev_auth.podspec`
Fetching podspec for `FirebaseDatabaseUI` from `FirebaseUI_dev_db.podspec`
Fetching podspec for `FirebaseFacebookAuthUI` from `FirebaseUI_dev_fb.podspec`
Fetching podspec for `FirebaseGoogleAuthUI` from `FirebaseUI_dev_ggl.podspec`
Fetching podspec for `FirebaseStorageUI` from `FirebaseUI_dev_storage.podspec`
Fetching podspec for `FirebaseTwitterAuthUI` from `FirebaseUI_dev_tw.podspec`
Downloading dependencies
Installing Bolts (1.8.4)
Installing FBSDKCoreKit (4.17.0)
Installing FBSDKLoginKit (4.17.0)
Installing Fabric (1.6.11)
Installing Firebase (3.10.0)
Installing FirebaseAnalytics (3.6.0)
Installing FirebaseAuth (3.0.6)
Installing FirebaseAuthUI (1.0.0)
Installing FirebaseCore (3.4.5)
Installing FirebaseDatabase (3.1.1)
Installing FirebaseDatabaseUI (1.0.0)
Installing FirebaseFacebookAuthUI (1.0.0)
Installing FirebaseGoogleAuthUI (1.0.0)
Installing FirebaseInstanceID (1.0.8)
Installing FirebaseStorage (1.0.5)
Installing FirebaseStorageUI (1.0.0)
Installing FirebaseTwitterAuthUI (1.0.0)
Installing GTMOAuth2 (1.1.4)
Installing GTMSessionFetcher (1.1.7)
Installing GoogleAppUtilities (1.1.2)
Installing GoogleInterchangeUtilities (1.2.2)
Installing GoogleSignIn (4.0.1)
Installing GoogleSymbolUtilities (1.1.2)
Installing GoogleToolboxForMac (2.1.0)
Installing OCMock (3.3.1)
Installing SDWebImage (3.8.2)
Installing TwitterCore (2.6.0)
Installing TwitterKit (2.6.0)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `FirebaseUI.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There are 16 dependencies from the Podfile and 28 total pods installed.

[!] The `FirebaseStorageUITests [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-FirebaseStorageUITests/Pods-FirebaseStorageUITests.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `FirebaseStorageUITests [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-FirebaseStorageUITests/Pods-FirebaseStorageUITests.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `FirebaseGoogleAuthUITests [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-FirebaseGoogleAuthUITests/Pods-FirebaseGoogleAuthUITests.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `FirebaseGoogleAuthUITests [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-FirebaseGoogleAuthUITests/Pods-FirebaseGoogleAuthUITests.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `FirebaseFacebookAuthUITests [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-FirebaseFacebookAuthUITests/Pods-FirebaseFacebookAuthUITests.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `FirebaseFacebookAuthUITests [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-FirebaseFacebookAuthUITests/Pods-FirebaseFacebookAuthUITests.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `FirebaseTwitterAuthUITests [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-FirebaseTwitterAuthUITests/Pods-FirebaseTwitterAuthUITests.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `FirebaseTwitterAuthUITests [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-FirebaseTwitterAuthUITests/Pods-FirebaseTwitterAuthUITests.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.`
  
#### Expected Results:

  * No warnings

**Comment by morganchen12** [comment]
The OTHER_LDFLAGS from CocoaPods are deliberately overwritten as a workaround for an issue in CocoaPods. See https://github.com/CocoaPods/CocoaPods/issues/6065

**Comment by Izzyjm** [comment]
can we ignore the 'OTHER_LDFLAGS' warnings and "GCC_PREPROCESSOR_DEFINITIONS" ? my project runs find and im not sure what the warnings mean ??
