### ISSUE TITLE
No SignOut delegate

### ISSUE THREAD

**Issue by eldafito** [firebase/FirebaseUI-iOS#217]
Using FirebaseAuth v.3.0.6 and FirebaseUI v.1.0.0

I noticed that the delegate method 
`authUI(_ authUI: FUIAuth, didSignInWith user: FIRUser?, error: Error?)`
is not called on **SignOut**

**Comment by morganchen12** [comment]
That method is only called on sign in, not on sign out. If you need to handle sign out events, take a look at [`-[FIRAuth addAuthStateDidChangeListener:]`](https://firebase.google.com/docs/reference/ios/firebaseauth/api/reference/Classes/FIRAuth#/c:objc(cs)FIRAuth(im)addAuthStateDidChangeListener:).
