### ISSUE TITLE
No such module 'FirebaseFacebookAuthUI'

### ISSUE THREAD

**Issue by revolter** [firebase/FirebaseUI-iOS#219]
### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 10.1
  * Firebase SDK version: 3.10.0
  * FirebaseUI version: 1.0.0
  * CocoaPods Version: 1.2.0.beta.1
  
### Step 3: Describe the problem:

After following the instruction [here](https://github.com/firebase/FirebaseUI-iOS/tree/master/FirebaseAuthUI) and building the project, I get this error message:

> No such module 'FirebaseFacebookAuthUI'

**Comment by morganchen12** [comment]
You'll need to add each provider that you plan on using to your Podfile as well.

```ruby
pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Facebook'
```

The documentation should be updated to reflect this.
