### ISSUE TITLE
Aggregate data changes in FUIArray

### ISSUE THREAD

**Issue by morganchen12** [firebase/FirebaseUI-iOS#222]
It'd be better to present changes in bulk rather than one element at a time, since the UIKit collection views support batch updating. This lets our API consumers build more responsive UIs.

**Comment by ugiacoman** [comment]
Doesn't observing by `.childValue` resolve this?

**Comment by morganchen12** [comment]
Yeah, that's the plan.

**Comment by ugiacoman** [comment]
I think .`childValue` has already been implemented with that functionality.

**Comment by morganchen12** [comment]
Right, but that isn't exposed in FUIArray in any way, so consumers of FUIArray have no way of aggregating updates.

**Comment by ugiacoman** [comment]
Oh gotcha, it's not exposed, yes this would be fantastic :D

**Comment by morganchen12** [comment]
Apologies for my vague wording :)

**Comment by morganchen12** [comment]
Support for this added to #186, dependent on the changes in that PR.

**Comment by morganchen12** [comment]
#186 has been merged. Release coming soon.

**Comment by morganchen12** [comment]
v2.0.0 has been released.
