### ISSUE TITLE
Unable to localize "Trouble signing in?" string in FirebaseAuthUI.strings

### ISSUE THREAD

**Issue by raugustinas** [firebase/FirebaseUI-iOS#223]
There is a FirebaseAuthUI.strings where I've localized all the strings for DefaultAuthUI but there's "Trouble signing in?" string in Email login view that won't change.

**Comment by raugustinas** [comment]
@mbleigh 
@brendanlim 
@proppy 
@danielpassos 
@ultrasaurus  
Thank you!

**Comment by morganchen12** [comment]
Hey, please don't just tag random people.

That said, it looks like `"Trouble signing in?"` is missing from the [Strings file](https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseAuthUI/Strings/en.lproj/FirebaseAuthUI.strings). @yramanchuk FYI

**Comment by yorgosg** [comment]
@raugustinas have you by any chance changed the strings for the sign in buttons? I have posted a question for this here: http://stackoverflow.com/questions/41829364/use-different-bundles-to-load-strings-from-on-runtime-in-ios

If you have please share, cheers!

**Comment by semihcihan** [comment]
@raugustinas subclass FUIPasswordSignInViewController and do the following in viewDidLoad.

`        if let button = (self.view.subviews.first as? UITableView)?.tableFooterView as? UIButton
        {
            button.setTitle("Giriş yapamıyor musunuz?", for: .normal)
        }
`

**Comment by yramanchuk** [comment]
@raugustinas I've added this string to localized list.
Please notice that in the next weeks we are going to submit localizations for most of the languages.
