### ISSUE TITLE
createSignInIntentBuilder() exits with RESULTCODE=0 in activity result

### ISSUE THREAD

**Issue by rave1502** [firebase/FirebaseUI-iOS#226]
device: Android 5.1

starting activity like this:

> startActivityForResult(AuthUI.getInstance()
>                     .createSignInIntentBuilder()
>                     .setProviders(Arrays.asList(new AuthUI.IdpConfig.Builder(AuthUI.GOOGLE_PROVIDER).build()))
>                     .setTosUrl("https://mytestsite/terms-of-service.html")
>                     .build(), REQUESTCODE_LOGIN);
> 

When I start the sign-in activity, I can see the account selection pop-up. When I select any of the google account to sign-in, the activity returns with result code '0' (RESULT_CANCELED). If I use any non-google account, then sign-in gets complete successfully. In firebase console, Google authentication is enabled, and I did login with with gmail account in the past. 

In my android console, I see the following debug lines:

> V/FA: Recording user engagement, ms: 5031
> D/FA: Logging event (FE): _e, Bundle[{_o=auto, _et=5031, _sc=MainActivity, _si=-4492839841470160947}]
> V/FA: onActivityCreated
> D/AutoManageHelper: starting AutoManage for client 1 false false
> D/AutoManageHelper: onStart true {1=com.google.android.gms.internal.zzzt$zza@27a3fd6a}
> V/FA: Activity paused, time: 495093
> V/FA: Activity resumed, time: 495194
> W/khrn_client: init_window num_buffers 3 min undequeued buffers 1
> W/khrn_client: init_window window 0x53567368, 552x270 hintTransform 0x0 do_pre 1
> W/khrn_client: init_window num_buffers 3 min undequeued buffers 1
> W/khrn_client: init_window window 0x536e1818, 480x800 hintTransform 0x0 do_pre 1
> I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@3bae1e3c time:495331
> V/FA: Screen exposed for less than 1000 ms. Event not sent. time: 278
> V/FA: Activity paused, time: 495472
> V/FA: Activity resumed, time: 499120
> D/AutoManageHelper: starting AutoManage for client 0 true false
> D/AutoManageHelper: connecting com.google.android.gms.internal.zzaal@266e951a
> I/Timeline: Timeline: Activity_launch_request id:com.logithreads.oorjaclient time:499136
> V/FA: Screen exposed for less than 1000 ms. Event not sent. time: 36
> V/FA: Activity paused, time: 499154
> V/FA: onActivityCreated
> V/FA: Activity resumed, time: 499192
> W/khrn_client: init_window num_buffers 3 min undequeued buffers 1
> W/khrn_client: init_window window 0x528956a8, 480x800 hintTransform 0x0 do_pre 1
> V/FA: Screen exposed for less than 1000 ms. Event not sent. time: 60
> V/FA: Activity paused, time: 499252
> E/GoogleProvider: Error logging in with Google. 10 null
> V/FA: Activity resumed, time: 500060
> W/khrn_client: init_window num_buffers 3 min undequeued buffers 1
> W/khrn_client: init_window window 0x536d4360, 480x800 hintTransform 0x0 do_pre 1
> W/khrn_client: init_window num_buffers 3 min undequeued buffers 1
> W/khrn_client: init_window window 0x53b3c6f8, 576x494 hintTransform 0x0 do_pre 1
> I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@13556b34 time:500194
> V/FA: Inactivity, disconnecting from the service
> V/FA: Recording user engagement, ms: 59329
> V/FA: Using measurement service
> V/FA: Connecting to remote service
> V/FA: Activity paused, time: 559387
> D/FA: Logging event (FE): _e, Bundle[{_o=auto, _et=59329, _sc=MainActivity, _si=-4492839841470160947}]
> V/FA: Using measurement service
> V/FA: Connection attempt already in progress
> D/FA: Connected to remote service
> V/FA: Processing queued up service tasks: 2
> V/FA: Inactivity, disconnecting from the service
>

**Comment by morganchen12** [comment]
Looks like you're looking for [FirebaseUI-Android](https://github.com/firebase/FirebaseUI-Android) :)
