### ISSUE TITLE
Build error when linking to FirebaseUI/Facebook with CocoaPods

### ISSUE THREAD

**Issue by mmenu-mantano** [firebase/FirebaseUI-iOS#228]
### Step 2: Describe your environment

  * Objective C or Swift: Obj-C
  * iOS version: 10
  * Firebase SDK version: 3.11.0
  * FirebaseUI version: 1.0.0
  * CocoaPods Version: 1.1.1
  
### Step 3: Describe the problem:

I'm trying to use FirebaseUI with Facebook on an Objective-C project, with CocoaPods. Unfortunately the build fails with the following error:

`ld: framework not found FBSDKCoreKit for architecture arm64`

#### Steps to reproduce:

I was able to reproduce the issue with a new empty project and a minimal Podfile:

```
workspace 'Test.xcworkspace'

target 'Test' do
  project 'Test.xcodeproj'

  pod 'Firebase/Auth'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Facebook'

end
```
[You can download the Test project from here](https://www.dropbox.com/s/9jsx6ozhd46m2ng/TestFirebase.zip?dl=1)
 

Thanks for your help.

**Comment by morganchen12** [comment]
`use_frameworks!` is required for ObjC. See #194
