### ISSUE TITLE
Any example on sectioning for swift

### ISSUE THREAD

**Issue by rslim087g** [firebase/FirebaseUI-iOS#229]
Thank You for this awesome framework!
However, I've been stuck for a couple of days trying to figure out.

I need to implement multiple sections in my table. Has anyone been able to implement that with firebase UI directly from firebase?

I tried using these with swift but they weren't working

```
          dataSource.array.sectionKeyPath = "value";
          dataSource.array.sectionsOrderedAscending = true
```
It would be really useful to others if this was added to the docs.
any help to get me started would be greatly appreciated!

**Comment by morganchen12** [comment]
FirebaseUI doesn't really do anything to help people implement sections. With the newer release, you should be able to write a custom data source around `FUIArray`, but that's about it.

I'm not sure what version of FirebaseUI your example code is using, since our data source/array classes don't even expose those methods.

**Comment by rslim087g** [comment]
Thanks for the quick reply!

Would it be possible to get a hint to get me moving in the right direction.

I tired subclassing FUITableViewDataSource and FUIArray, but I'm not able to get any of the function triggered.

Anything would help at this point, 

Thanks

**Comment by morganchen12** [comment]
FUIArray is intentionally reusable, but you shouldn't have to subclass FUITableViewDataSource since it's much simpler to just build your own object that conforms to UITableViewDataSource.

If none of the callbacks are being invoked, you've probably forgotten to call `observeQuery` on the FUIArray.
