### ISSUE TITLE
Add support for disabling email/password signup

### ISSUE THREAD

**Issue by morganchen12** [firebase/FirebaseUI-iOS#230]
Add support for disabling email/password sign-up in the case where people want to use FirebaseUI for invite-only services. 

Mirrors https://github.com/firebase/FirebaseUI-Android/pull/536

**Comment by long1eu** [comment]
any news on this?

**Comment by morganchen12** [comment]
This has been released.

You can disable email sign-in with the [`signInWithEmailHidden`](https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseAuthUI/FUIAuth.h#L177) property on `FUIAuth`.

**Comment by long1eu** [comment]
I have only Phone Auth selected, will this automatically start the phone auth?

**Comment by morganchen12** [comment]
No. You should use [this method](https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebasePhoneAuthUI/FUIPhoneAuth.h#L52) on the phone auth provider directly.

**Comment by long1eu** [comment]
thanks!

**Comment by johncovele** [comment]
This issue was to disable email SIGN UP, not SIGN IN.  signInWithEmailHidden has nothing to do with Sign Up. Why is this closed? Looks like this feature is very sorely needed, and is apparently already present on Android.

There are many use cases where you don't want the user creating their own accounts, you only want them to log in via a mobile app, with a email/password that is previously created.

**Comment by johncovele** [comment]
Since I'm building with source code, I was able to do something like this (for email auth):

FUIEmailEntryViewController.m:
`
// New user.

if ( DISABLE_ACCOUNT_CREATION ) {}
	UIAlertController *alertController = [UIAlertController alertControllerWithTitle:@"Email Not Found"
			message:@"That email was not found" preferredStyle:UIAlertControllerStyleAlert];
	[alertController addAction: [UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleCancel handler:nil] ];
	[self presentViewController:alertController animated:YES completion:nil];

} else {
	UIViewController *controller;
	if ([self.authUI.delegate respondsToSelector:@selector(passwordSignUpViewControllerForAuthUI:email:)]) {
		 controller = [self.authUI.delegate passwordSignUpViewControllerForAuthUI:self.authUI email:emailText];
	} else {
		controller = [[FUIPasswordSignUpViewController alloc] initWithAuthUI:self.authUI email:emailText];
	}
	[self pushViewController:controller];
}
`

**Comment by morganchen12** [comment]
Sign-up can now be disabled via the [`allowNewEmailAccounts`](https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseAuthUI/FUIAuth.h#L182) property.
