### ISSUE TITLE
Missing displayName in email auth workflow

### ISSUE THREAD

**Issue by garyfoster** [firebase/FirebaseUI-iOS#231]
Should the email provider auth flow require and capture the user's name? I'm not 100% sure, but I thought in the past it did, but doesn't seem to work now.

I recreated this problem by a fresh clone of the sample project this morning at https://github.com/firebase/FirebaseUI-iOS/tree/master/samples/swift. All I did was clone it, pod install, copy my GoogleService-Info.plist and run. I navigated to the auth sample, signed in via email, entered my email and password at the prompt and after the successful sign in, my display name is nil, I was never prompted to enter my name.

Trying to determine if this is a bug or do I need to plan for the case when displayName is nil.

**Comment by morganchen12** [comment]
Seems like auth could benefit from some more customizability so we don't have to implement all these features one at a time.

**Comment by morganchen12** [comment]
Closing in favor of #245.
