### ISSUE TITLE
FirebaseStorageUI Raising Unrecognized Selector error

### ISSUE THREAD

**Issue by codemodouk** [firebase/FirebaseUI-iOS#232]
### Step 1: Are you in the right place?

My issue relates to FirebaseUI-iOS, particularly FirebaseStorageUI 

### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 9.3
  * Firebase SDK version: 3.6.0
  * FirebaseUI version: 2.0
  * CocoaPods Version: 1.1 rc2
  
### Step 3: Describe the problem:

I am using FirebaseStorageUI to download and cache my images. I recently upgrade my pods, and I'm now seeing this error appear:

[SDImageCache storeImage:forKey:]: unrecognized selector sent to instance 0x14926b460
2017-02-01 17:11:34.984 AppName[1569:460359] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SDImageCache storeImage:forKey:]: unrecognized selector sent to instance 0x14926b460'

#### Steps to reproduce:

  Download any image that isn't currently in the cache
  
#### Observed Results:

  As above
  
#### Expected Results:

  The image to be downloaded and stored in the cache
  
#### Relevant Code:

 The stack trace shows me:

; __111-[UIImageView(FirebaseStorage) sd_setImageWithStorageReference:maxImageSize:placeholderImage:cache:completion:]_block_invoke_2 at UIImageView+FirebaseStorage.m:117

The offending line appears to be

`// Cache downloaded image
        [cache storeImage:image forKey:storageRef.fullPath];`

**Comment by morganchen12** [comment]
In your build settings under **Other Linker Flags**, can you check that you're not overwriting CocoaPods' settings? If you are deliberately overwriting CocoaPods' settings, can you explicitly add a `-ObjC` flag?

**Comment by codemodouk** [comment]
Hi, thanks for the quick response. I don't believe there is anything being overwritten. The -ObjC flag already appears to be present

![image](https://cloud.githubusercontent.com/assets/17314445/22522255/d9685936-e8b2-11e6-96e1-c872634c9f0f.png)

**Comment by morganchen12** [comment]
Yep, this is a bug on our end. Thanks for reporting.

You can work around this currently by explicitly adding `'SDWebImage', '~> 3.8'` in your Podfile.

**Comment by codemodouk** [comment]
No worries, thank you.

**Comment by morganchen12** [comment]
This should be fixed in v2.0.1. Feel free to reopen if you run into it again.

**Comment by basiralam** [comment]
I am having the same issue. Please let me know whether new version released.!

**Comment by codemodouk** [comment]
It's been merged into the current release.

**Comment by basiralam** [comment]
Yes i have installed the new one. thanks its working
