### ISSUE TITLE
Database UI: Add documentation for customizing FUICollections

### ISSUE THREAD

**Issue by swftvsn** [firebase/FirebaseUI-iOS#235]
Hi,

first of all, thanks for the awesome tools you have built! 

I tried to find an example, preferably in swift, that would demonstrate how to correctly use the new sorting functionality with fuitableviewdatasource, but couldn't find any. Please let me know if I overlooked the documentation or examples. Looking at the sources, it seems that I must supply my own fuicollection and not pass the query directly?

**Comment by morganchen12** [comment]
Yeah, you'll have to first instantiate an `FUICollection` and then pass it to the data source's initializer.

```swift
let sortedArray = FUISortedArray(query: query, delegate: nil) { (lhs, rhs) -> ComparisonResult in
    return lhs.compare(rhs)
}

let dataSource = FUITableViewDataSource(collection: sortedArray, view: tableView) { tableView, indexPath, snapshot in
    /* ... */
}
```

**Comment by swftvsn** [comment]
Hi, thanks for the input. I've updated the  firebaseui dependency to 2.0.2, but I can't seem to import FUISortedArray to my swift project. 

My swift file imports include: 

```
import Firebase
import FirebaseAuth
import FirebaseDatabaseUI
```

The error is "Use of unresolved identifier 'FUISortedArray'"

If I browse the Pods, I can see that it's missing in headers. Is this a problem in my environment or in the distributed binary? (Sorry if this is obvious question, I don't have much XCode experience under my belt yet.)

![nayttokuva 2017-02-03 kello 10 28 47](https://cloud.githubusercontent.com/assets/25097010/22584531/9934c2e2-e9fb-11e6-9675-c09c20dcd0c2.png)

**Comment by morganchen12** [comment]
That's an issue with the binary I uploaded.

**Comment by morganchen12** [comment]
This should be fixed now.

**Comment by swftvsn** [comment]
The binary issue is fixed, however now I'm facing this issue: https://github.com/firebase/FirebaseUI-iOS/issues/234#issuecomment-277953684

**Comment by morganchen12** [comment]
Added some barebones docs, let me know if these are sufficient.
