### ISSUE TITLE
Documentation on adding supplemental views to UICollectionViewDataSource

### ISSUE THREAD

**Issue by WikipediaBrown** [firebase/FirebaseUI-iOS#236]
### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 10.2.1
  * Firebase SDK version: 3.12.0
  * FirebaseUI version: 1.0.0
  * CocoaPods Version: 1.1.1
  
#### Steps to reproduce:

  1. Add datasource
  2. Try and add header to UICollectionView
  
#### Observed Results:

  * I just can't figure out how to do it or if it is even supported. Basically, all I want to do is add a header above the content in my collection view. Nothing fancy, just a header.
  
#### Expected Results:

  * I expected to be able to call `func collectionView(UICollectionView, viewForSupplementaryElementOfKind: String, at: IndexPath)` and then populate the header view. But this method isn't available unless I set the ViewController as the dataSource. When I set the ViewController as the dataSource, `FUICollectionViewDataSource` no longer works. I don't know what to do. I've even tried subclassing `FUICollectionViewDataSource` but the docs say to call `bind` on the collection view itself so I don't even know how to use my subclass. I also tried extending `FUICollectionViewDataSource` and adding the `func collectionView(UICollectionView, viewForSupplementaryElementOfKind: String, at: IndexPath)` method there but, again, to no avail.
  
#### Relevant Code:
Here is the current code I have.
  ```
 class profileDataSource: FUICollectionViewDataSource {

    override func collectionView(_ collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, at indexPath: IndexPath) -> UICollectionReusableView {
        print(indexPath)
        switch kind {
        case UICollectionElementKindSectionHeader:
            guard let headerView = collectionView.dequeueReusableSupplementaryView(ofKind: kind, withReuseIdentifier: "profileCell", for: indexPath) as? ProfileCollectionViewCell else {return UICollectionReusableView()}
            headerView.creditsLabel.text = "work"
            return headerView
        default:
            assert(false, "Unexpected element kind\(kind)")
        }
    }

}


  ```

**Comment by morganchen12** [comment]
The default data sources are very basic and intended to solve simple but common use cases. If you need a more complex data source, you can build your own around `FUIArray`.

**Comment by WikipediaBrown** [comment]
Thanks for replying!! So I'm using it all wrong in the first place. Thanks for the help. I would've banged my head against this forever.

**Comment by morganchen12** [comment]
You're welcome!
