### ISSUE TITLE
FUITableViewDataSource raising  'attempt to perform an insert and a move to the same index path'

### ISSUE THREAD

**Issue by codemodouk** [firebase/FirebaseUI-iOS#237]
### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 9.3
  * Firebase SDK version: 3.6
  * FirebaseUI version: 2.0.2
  * CocoaPods Version: 1.1
  
### Step 3: Describe the problem:

I have MasterVC table view controller and DetailVC view controller. MasterVC uses a FUITableViewDataSource with a query using queryOrderedByValue. 

When an update is made in DetailVC that causes the the .child_changed event to trigger in the MasterVC an NSInternalInconsistencyException is raised with reason: 'attempt to perform an insert and a move to the same index path'

#### Steps to reproduce:

  1. Select a row in the MasterVC to navigate to the DetailVC
  2. Update the record in the DetailVC which triggers the observer in the MasterVC
  
#### Observed Results:

  * What happened?  The app crashes with the error described above. However, when the queryOrderedByValue is removed from the query it functions as expected
  
#### Expected Results:

  * What did you expect to happen? I would expect that when the .child_changed event is triggered in the MasterVC the location of the record in the UITableView would be ordered to the top.

It is the attempt to re-order the cells in the UITableView that is causing the exception

**Comment by morganchen12** [comment]
Can you post the code here? This is most likely a bug on our end.

**Comment by codemodouk** [comment]
Sure. The below example updates the display order of a Color to 0 in the DetailVC. This will trigger the .child_changed event in the MasterVC, which changes the order of rows in the tableView.

**The following example assumes a reference colors with firebase data model as follows:**

`{
  "blue" : {
    "displayOrder" : 0
  },
  "green" : {
    "displayOrder" : 2
  },
  "red" : {
    "displayOrder" : 1
  }
}`

**Master TableViewController:**

`
import UIKit
import Firebase
import FirebaseDatabaseUI

class MasterTableViewController: UITableViewController {
    
    var ref: FIRDatabaseReference!
    var dataSource: FUITableViewDataSource!

    override func viewDidLoad() {
        super.viewDidLoad()

        
        ref = FIRDatabase.database().reference().child("colors")
        
        let query = ref.queryOrdered(byChild: "displayOrder")
        
        dataSource = FUITableViewDataSource(query: query, view: tableView, populateCell: { (tableView, indexPath, snapshot) -> UITableViewCell in
            let cell = tableView.dequeueReusableCell(withIdentifier: "reuseIdentifier", for: indexPath)
            
            cell.textLabel?.text = snapshot.key
            
            return cell
        })
        
        tableView.dataSource = dataSource
        
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        let destVC = segue.destination as! DetailViewController
        
        destVC.colour = tableView.cellForRow(at: tableView.indexPathForSelectedRow!)?.textLabel?.text
    }
    
    
}`

**Detail View Controller:**

`import UIKit
import Firebase


class DetailViewController: UIViewController {

    
    var colour: String!
    
    @IBOutlet weak var colourLabel: UILabel!
    
    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        
        
    }

    @IBAction func changeDisplayOrder(_ sender: Any) {
        
        let ref = FIRDatabase.database().reference().child("colors").child(colour)
        
        ref.updateChildValues(["displayOrder" : 0])
        
    }


}`

**Comment by swftvsn** [comment]
This affects us too. It seems to be triggered any time an existing record is updated, and one of the updated fields is the one that is used to do sorting in the query. 

I actually tried to go around this using FUISortedArray, but got bitten by https://github.com/firebase/FirebaseUI-iOS/issues/234#issuecomment-277953684

**Comment by morganchen12** [comment]
I think this was introduced when we started batching updates.

**Comment by morganchen12** [comment]
This is fixed in the latest release (by dropping batch updates in table views).
