### ISSUE TITLE
Possible completionHandler for FUIArray's observequery?

### ISSUE THREAD

**Issue by rslim087g** [firebase/FirebaseUI-iOS#238]
The problem I'm having is I have 1000s of values. I need to make sure all my data is synced before i can accomplish the next task. Is there a completion handler or a notification that lets you know when all the batch updates are done, for swift?

**Comment by morganchen12** [comment]
This is exposed in a [FUICollectionDelegate method](https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseDatabaseUI/FUICollection.h#L79).
