### ISSUE TITLE
Don't require display name during email sign up

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-iOS#245]
This is a mirror of https://github.com/firebase/FirebaseUI-Android/issues/467

We should increase the flexibility of email sign up by:
  * Not making display name a required field
  * Allowing the developer to easily customize the label on the display name field

**Comment by samtstern** [comment]
cc @yramanchuk

**Comment by samtstern** [comment]
Web issue: https://github.com/firebase/firebaseui-web/issues/41

**Comment by aleczadikian** [comment]
Any resolution here? Maybe I'm missing something, but I don't see an obvious way to do this.

**Comment by jburke1203** [comment]
Per documentation https://firebase.google.com/docs/auth/web/firebaseui

```
ui.start('#firebaseui-auth-container', {
  signInOptions: [
    {
      provider: firebase.auth.EmailAuthProvider.PROVIDER_ID,
      requireDisplayName: false
    }
  ]
});
```

**Comment by hendrep** [comment]
Any update on this? I cannot find a way to disable the name field for iOS?

**Comment by renkelvin** [comment]
Add support on iOS https://github.com/firebase/FirebaseUI-iOS/pull/680
