### ISSUE TITLE
Question about accessing the retrieved snapshots in the FUIIndexTableViewDataSource

### ISSUE THREAD

**Issue by codemodouk** [firebase/FirebaseUI-iOS#248]
The FUIIndexTableViewDataSource is great, but, I find that I need access to the snapshots from the index query. For example, when I navigate from a cell in the tableview to a detail view controller, it would be helpful to get the snapshot corresponding to that cell to pass to the detail view controller.

What are your thoughts on exposing the snapshots returned from the index query?

**Comment by morganchen12** [comment]
We could certainly expose a readonly view of the loaded index snapshots, all we'd have to do is add a property that returns the [internal index array's contents](https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseDatabaseUI/FUIIndexArray.m#L29). Would this suit your needs?

Exposing delegate behavior would be more complex, but having loaded the contents of any query would imply that the index that produced the query had loaded already as well.

**Comment by codemodouk** [comment]
Yes, that sounds like what I need. Thanks

**Comment by morganchen12** [comment]
This is exposed in the latest release as `FUIIndexArray.indexes`.

**Comment by codemodouk** [comment]
Hi, sorry for the delay replying. I've updated my FirebaseUI pod to v3.1.0. I've had a look at this, but, can't seem to work out how to use this directly from a dataSource of type FUIIndexTableViewDataSource.

I was expecting to be able to do something like this:

`var dataSource: FUIIndexTableViewDataSource!
 ...
self.dataSource = tableView.bind(etc, etc)
...

let indexSnapshot = dataSource.array.indexes(indexPath.row)

`

However, dataSource doesn't seem to have an array property in order to be able to get to the indexes property you've exposed. Can you help me understand where I'm going wrong?

**Comment by morganchen12** [comment]
The property exists on `FUIIndexArray`, not the data sources. I'll add it to the data sources as well.

**Comment by morganchen12** [comment]
This is now merged and released.

**Comment by codemodouk** [comment]
Great! Thank you.
