### ISSUE TITLE
Customizing authPickerViewController

### ISSUE THREAD

**Issue by HamzaGhazouani** [firebase/FirebaseUI-iOS#249]
Hi, 

I would like to customise my AuthPickViewController, but I have encountered some issues: 

- I can't use storyboard 
- I can't customise the position of buttons (we can, but only by doing some workaround...)
- I can't customise the appearance of buttons  (possible by workaround also)
- The AuthPickViewController dismisses if I click , for example, in twitter button and cancel 

Best regards,
Hamza

**Comment by yramanchuk** [comment]
@HamzaGhazouani FUIAuthPickerViewController was designed in the way that it doesn't support customization of UI elements.
Please check corresponding answers:
1. Currently FUIAuthPickerViewController can be used only with XIB. We don't plan to change this in the nearest future.
2. This was done intentionally;
3. This was done intentionally;
4. This was fixed, please see issue #253

**Comment by Shoshin23** [comment]
Hi!
I just wanted to know what kind of workarounds are you guys using for customising the buttons and also the position of the buttons.

**Comment by marlhex** [comment]
/// Delegate function that allows us to create a custom FUIAuthPickerViewController
    ///
    /// - Parameter authUI: FUIAuth instance
    /// - Returns: The custom FUIAuthPickerViewController
    func authPickerViewController(forAuthUI authUI: FUIAuth) -> FUIAuthPickerViewController {
        // Create an instance of the FirebaseAuth login view controller
        let customLoginVC = FUIAuthPickerViewController(authUI: authUI)

        customLoginVC.navigationItem.leftBarButtonItem = nil
        
        customLoginVC.navigationController?.isToolbarHidden = true
        customLoginVC.navigationController?.isNavigationBarHidden = true
        
        
        //Original Frame
        let drawableFrame = CGRect(x: 0, y: -44, width: UIScreen.main.bounds.width, height: UIScreen.main.bounds.height)
        
        
        let drawableImageView = UIImageView(frame: drawableFrame)
        drawableImageView.image = UIImage(named: "pdf2")
        drawableImageView.contentMode = .scaleAspectFill
        
        //vc
        customLoginVC.view.subviews[0].subviews[0].backgroundColor = UIColor.clear
        customLoginVC.view.subviews[0].insertSubview(drawableImageView, at: 0)
        
        customLoginVC.view.backgroundColor = .black
        
        
        let statusBar = UIApplication.shared.value(forKeyPath: "statusBarWindow.statusBar") as? UIView
        statusBar?.backgroundColor = UIColor.clear
        
        return customLoginVC
    }

Unfortunately, toolBar is not hidden, navBar is not hidding or setting it's text even if I set another title e.g. navBar.title = "hi" or even nil. background also doesn't change and it is white.

The unique thing that I'm able to modify is the back button which I'm already setting in up as nil and it works but the remaning code it is just like ignoring it... any thoughts? I'm all ears.

**Comment by marlhex** [comment]
https://www.youtube.com/watch?v=d_byFfP3cTw&feature=youtu.be solved
