### ISSUE TITLE
FUITableViewDataSource Crashes

### ISSUE THREAD

**Issue by kermankohli** [firebase/FirebaseUI-iOS#252]
### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 10.2
  * Firebase SDK version: 3.14.0
  * FirebaseUI version: 2.0.3
  * CocoaPods Version: ?
  
### Step 3: Describe the problem:

When deleting a row from a FUITableViewDataSource, the app crashes.

2017-02-28 09:10:43.283 TheHWApp[70489:2933313] *** Assertion failure in -[UITableView _endCellAnimationsWithContext:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3600.6.21/UITableView.m:1273
2017-02-28 09:10:43.313 TheHWApp[70489:2933313] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to perform a delete and a move from the same index path (<NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0})'

#### Steps to reproduce:

  1. Add row
  2. Delete row
#### Observed Results:

  * What happened?  This could be a description, log output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

This is all the code that the tableivewcontroller uses.

func setupDataSource() {
        let ref: FIRDatabaseQuery = generateRefForChild(.subject).queryOrdered(byChild: "name")
        array = self.tableView.bind(to: ref, populateCell: { [weak self] tableView, indexPath, snapshot in
            let cell = tableView.dequeueReusableCell(withIdentifier: "Cell", for: indexPath)
            ...
            return cell
        })

**Comment by morganchen12** [comment]
Can you update your FirebaseUI version to the latest one and then try again?

**Comment by kermankohli** [comment]
@morganchen12 isn't 2.0.X the latest version?

As stated by the readme:
`pod 'FirebaseUI', '~> 2.0'       # Pull in all Firebase UI features`

**Comment by morganchen12** [comment]
Oops, that needed updating. I've bumped the version numbers in the readme.

Can you try again with 3.0?

**Comment by kermankohli** [comment]
That did the trick :) I think it’s safe to close this issue now.

On Wed, Mar 1, 2017 at 5:13 PM, Morgan Chen <notifications@github.com> wrote:
Oops, that needed updating. I've bumped the version numbers in the readme.

Can you try again with 3.0?

**Comment by morganchen12** [comment]
Thanks!
