### ISSUE TITLE
Authentication with Twitter 

### ISSUE THREAD

**Issue by HamzaGhazouani** [firebase/FirebaseUI-iOS#253]
### Environment

  * Objective C or Swift: Swift
  * iOS version: 10.0
  * Firebase SDK version: 3.14.0
  * FirebaseUI version: 3.1.0
  * CocoaPods Version: 1.0
  
### Step 3: Describe the problem:
After the click in Twitter Button, the navigation bar is shown, and after the click in the cancel button 
the `FUIAuthPickerViewController` dismissed, we should dismiss only twitter controller 

#### Steps to reproduce:

  1. Tap Twitter Button in the `FUIAuthPickerViewController`
  2. Tap Cancel button 
  
#### Observed Results:

  * the `FUIAuthPickerViewController` dismissed
  
#### Expected Results:

  * Only Twitter controller should dismiss, and we should land in `FUIAuthPickerViewController`

**Comment by yramanchuk** [comment]
Committed fix to master. Issue is going to be fixed in the nearest release
