### ISSUE TITLE
Use FUIAuthPickerViewController like RootViewController of the application 

### ISSUE THREAD

**Issue by HamzaGhazouani** [firebase/FirebaseUI-iOS#254]
### Environment

  * Objective C or Swift: Swift
  * iOS version: 10.0
  * Firebase SDK version: 3.14.0
  * FirebaseUI version: 3.1.0
  * CocoaPods Version: 1.0
  
### Step 3: Describe the problem:
All the callbacks are in the completion block of the dismiss method of the navigation controller, which does not allow to use `FUIAuthPickerViewController` like RootViewController 
I think we should separate callBack and dismiss actions, and we should not dismiss the controller 
if the user implement the protocol, Like [UIImagepickercontroller](https://developer.apple.com/reference/uikit/uiimagepickercontroller)

#### Steps to reproduce:
  1. Use `FUIAuthPickerViewController` as root view controller of the application 
  
#### Observed Results:
  * The callbacks are not received 
  
#### Expected Results:
  * We should receive the callbacks

**Comment by yramanchuk** [comment]
@HamzaGhazouani Sounds reasonable, we will discuss issue internally and I'll update ticket with time frame.

**Comment by praveenvvstgy** [comment]
@yramanchuk do you have an ETA on this?

**Comment by morganchen12** [comment]
@praveenvvstgy this isn't on our roadmap for the near future, but we're happy to review external contributions.

**Comment by najdanovicivan** [comment]
I've been struggling with this for a couple of hours in order to find why delegate is not being called 

The issue can be easily solved by modifying code for dismissing view from
 
I am working on fixing this and I'll submit pull request when its done
