### ISSUE TITLE
FirebaseUI-Auth: auth with Digits

### ISSUE THREAD

**Issue by rostopira** [firebase/FirebaseUI-iOS#255]
Digits works pretty well already, because it's credentials are compatible with Twitter credentials
Also, since Google bought Fabric, I think it will work better soon
So, when Digits button will be available in library?
Is contributions for this are welcome?
Thanks

**Comment by morganchen12** [comment]
@drishi94 what's the plan around Digits?

**Comment by drishi94** [comment]
Hi rostopira, we are still formulating our final plans with Digits please stay tuned for updates!

**Comment by rrallo** [comment]
Is there a recommended alternative for the time being?

**Comment by drishi94** [comment]
As of today, Firebase Authentication supports phone auth :)

**Comment by rrallo** [comment]
Talk about timing!
