### ISSUE TITLE
Populate UICollectionView with Firebase Data

### ISSUE THREAD

**Issue by troy21688** [firebase/FirebaseUI-iOS#258]
My structure is as follows:

[![enter image description here][1]][1]

I want to populate the UICollectionView with the "question" field in the Firebase Database for each child. Here is my current code, I would presume that the FIrebaseUI tools would know how many children are in my node and populate the correct number of views as needed. Very new to iOS (previous experience with Android):

    import UIKit
    import FirebaseDatabase
    import FirebaseDatabaseUI

    private let reuseIdentifier = "PollCell"

    class TrendingViewController: UICollectionViewController {
    
    var ref: FIRDatabaseReference!
    var dataSource: FUICollectionViewDataSource!

    override func viewDidLoad() {
        super.viewDidLoad()
        
        ref = FIRDatabase.database().reference()
        

        // Uncomment the following line to preserve selection between presentations
        // self.clearsSelectionOnViewWillAppear = false

        // Register cell classes
        
        self.dataSource = self.collectionView?.bind(to: self.ref.child("Polls")) { collectionView, indexPath, snap in
            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: reuseIdentifier, for: indexPath) as! PollCell
            /* populate cell */

            //Where I am having difficutlty
            cell.pollQuestion.text = snap.get
            
            return cell
        }

        // Do any additional setup after loading the view.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
     }
    }

  [1]: https://i.stack.imgur.com/E7AA5.png

**Comment by morganchen12** [comment]
`FIRDataSnapshot` has a `value` property that returns a Foundation data type (NSDictionary, NSArray, NSString, or NSNumber) which you should use to populate your cells. Take a look at the [FIRDataSnapshot](https://firebase.google.com/docs/reference/ios/firebasedatabase/api/reference/Classes/FIRDataSnapshot) documentation for more info.

In general questions of this format are better suited for [StackOverflow](https://stackoverflow.com).
