### ISSUE TITLE
Showcase of products built with FirebaseUI? Check out mine!

### ISSUE THREAD

**Issue by yorgosg** [firebase/FirebaseUI-iOS#263]
Hey everyone!

I was wondering if we could have a section here where people post the apps they have been using FirebaseUI on. This way we'll be able to give better feedback on one another about our implementation.

My app has launched today on Product Hunt, it is called Sporteventus for iOS.
You may check it out here: https://www.producthunt.com/posts/sporteventus-for-ios

Any feedback is welcome! Thank you in advance!

**Comment by morganchen12** [comment]
Feel free to make a pull request with a showcase document and a clause in the README telling people to add their projects to the showcase doc :)
