### ISSUE TITLE
Error `framework not found FBSDKLoginKit` for obj-c project

### ISSUE THREAD

**Issue by DevAlloy** [firebase/FirebaseUI-iOS#266]
# My environment:
- O-C
- iOS 10.2
- Cocoapods 1.2.0
- Xcode 8.2.1
  
# Issue
Error `framework not found FBSDKLoginKit` at build time. In case I remove FirebaseUI pod, error gone.

# Trials (new repo with podfile like below)
- Tried to add `use_frameworks!` but other pods break because of it.
- Tried to add path to pods for project's `framework search path`, but error is still here.

# Podfile:
```
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'FirebaseTest' do

pod 'FirebaseCore', '~> 3.5'
pod 'FirebaseDatabase', '~> 3.1'
pod 'FirebaseUI', '~> 3.1'

pod 'Typhoon', '~> 3.5'
pod 'RamblerTyphoonUtils/AssemblyCollector', '~> 1.5'

# Auth
pod 'Firebase/Auth'
pod 'FBSDKLoginKit', '~> 4.15'
pod 'FBSDKShareKit', '~> 4.17'
pod 'VK-ios-sdk', '~> 1.4'
pod 'InstagramKit', '~> 3.0'
pod 'InstagramKit/UICKeyChainStore'

# Amazon
pod 'AWSS3', '~> 2.4'
pod 'AWSCognito', '~> 2.4'

# Image manipulation
pod 'DBCamera', '~> 2.4'
pod 'SDWebImage', '~> 4.0'

# Table View
pod 'Nimbus/Models', :git => 'https://github.com/rambler-ios/nimbus'

# Fabric
pod 'Fabric', '~> 1.6'
pod 'Crashlytics', '~> 3.7'

# Helpers
pod 'PureLayout', '~> 3.0'
pod 'CrutchKit/Proxying', :git => 'https://github.com/CognitiveDisson/CrutchKit', :tag => '0.0.10'
pod 'EasyMapping', '~> 0.18'
pod 'libextobjc', '~> 0.4'

# Animations
pod 'pop', '~> 1.0'

end
```

**Comment by DevAlloy** [comment]
Hey, @morganchen12, how can I help you?

**Comment by morganchen12** [comment]
This is all the info I need, I just haven't had the time to look at it yet. Sorry!

**Comment by morganchen12** [comment]
Using FirebaseUI without `use_frameworks!` is technically not something we support, but if you manually exclude the FirebaseFacebookAuthUI dependency does your project build?

```ruby
pod 'FirebaseUI/Database'
pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Google'
pod 'FirebaseUI/Twitter'
pod 'FirebaseUI/Storage'
```

In the meantime you can still use FirebaseUI but just

**Comment by DevAlloy** [comment]
I needed firebase data source and resolved my issue via adding 'FirebaseUI/Database' pod only. Thanks for your help, @morganchen12 !
