### ISSUE TITLE
Images slow to load

### ISSUE THREAD

**Issue by mattyb** [firebase/FirebaseUI-iOS#276]
* Objective C
  * iOS version: 10.3 (simulator)
  * Firebase SDK version: 
  * FirebaseUI version: 
```
  - FirebaseAuth (3.1.0):
    - FirebaseAnalytics (~> 3.6)
    - GoogleToolboxForMac/NSDictionary+URLArguments (~> 2.1)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseUI/Auth (1.0.0):
    - Firebase/Auth
  - FirebaseUI/Facebook (1.0.0):
    - FBSDKLoginKit (~> 4.0)
    - FirebaseUI/Auth
  - FirebaseUI/Google (1.0.0):
    - FirebaseUI/Auth
    - GoogleSignIn (~> 4.0)
  - FirebaseUI/Twitter (1.0.0):
    - FirebaseUI/Auth
    - TwitterKit (~> 2.4)
```
  * CocoaPods Version: 1.1.1
  * React Native version: 0.39
  
#### Observed Results:

  * After loading the AuthUI screen, neither login images nor the Cancel button appear immediately. Waiting around a minute or clicking on one of the buttons will cause the images to appear. 
  * If returning to the screen later, images will load immediately
  
#### Expected Results:

  * Images to load quickly.
  
#### Relevant Code:
ProfileScreen.js
```
pushLoginScreen = () => {
  var loginUI = NativeModules.FirebaseAuthUI
  loginUI.showLogin(this.setUid)
}
```

RCTFirebaseAuthUI.m
```
RCT_EXPORT_METHOD(showLogin:(nonnull RCTResponseSenderBlock )onLogin)
{
  RCTLogInfo(@"showLogin method");

 if(authViewController == nil) {
   authViewController = [authUI authViewController];
   authViewController.delegate = authUI;
  }

  rnOnLogin = onLogin;

  UIWindow *window = [UIApplication sharedApplication].keyWindow;
  UIViewController *rootViewController = window.rootViewController;
  [rootViewController presentViewController:authViewController animated:YES completion:nil];
  RCTLogInfo(@"pushed view controller");
}
```

![slowlogin](https://cloud.githubusercontent.com/assets/52160/26035849/7eb7841e-38a1-11e7-8017-bea68324b0a3.gif)

**Comment by mattyb** [comment]
Hey @yramanchuk. Any more info I could provide here? This is unfortunately now blocking our app from being launched.

**Comment by mattyb** [comment]
I solved this by ensuring that the view controller initialization ran in the main thread. I wrapped the showLogin code with `dispatch_async(dispatch_get_main_queue(), ...`

**Comment by morganchen12** [comment]
View controller initialization should always happen on the main thread according to UIKit documentation, otherwise the behavior of your UI elements is undefined.
