### ISSUE TITLE
sd_setImageWithStorageReference not working for gifs

### ISSUE THREAD

**Issue by superdev89** [firebase/FirebaseUI-iOS#278]
Before using sd_setImageWithStorageReference, I uploaded gifs to firebase storage and used sd_setImage after downloading the image. By default SDWebImage is working for gifs. But replacing sd_setImage with sd_setImageWithStorageReference only showing the static image for the gif file.

**Comment by superdev89** [comment]
Hello,  I wrote myself an FLAnimatedView+FirebaseStroage.swift to make gif file work on the FLAnimatedView with firebase storage and it appears sometimes, but not working for cached images. Can you review and let me know what's wrong?

import Foundation
import FLAnimatedImage
import SDWebImage
import FirebaseStorageUI

let FUIMaxImageDownloadSize: UInt64 = UInt64(10e6)

private var xoAssociationKey: UInt8 = 0

extension FLAnimatedImageView {
    
    open override func sd_setImage(with storageRef: FIRStorageReference) -> FIRStorageDownloadTask? {
        return sd_setImage(with: storageRef, placeholderImage: nil, completion: nil)
    }
    
    override open func sd_setImage(with storageRef: FIRStorageReference, placeholderImage placeholder: UIImage?) -> FIRStorageDownloadTask? {
        return sd_setImage(with: storageRef, placeholderImage: placeholder, completion: nil)
    }
    
    open override func sd_setImage(with storageRef: FIRStorageReference, placeholderImage placeholder: UIImage?, completion: ((UIImage?, Error?, SDImageCacheType, FIRStorageReference) -> Void)? = nil) -> FIRStorageDownloadTask? {
        return sd_setImage(with: storageRef, maxImageSize: UIImageView.sd_defaultMaxImageSize(), placeholderImage: placeholder, completion: completion)
    }
    
    open override func sd_setImage(with storageRef: FIRStorageReference, maxImageSize size:UInt64, placeholderImage placeholder: UIImage?, completion: ((UIImage?, Error?, SDImageCacheType, FIRStorageReference) -> Void)? = nil) -> FIRStorageDownloadTask? {
        return sd_setImage(with: storageRef, maxImageSize: size, placeholderImage: placeholder, cache: SDImageCache.shared(), completion: completion)
    }
    
    func sd_setImage(with storageRef: FIRStorageReference, maxImageSize size:UInt64, placeholderImage placeholder: UIImage?, cache: SDImageCache, completion: ((UIImage?, Error?, SDImageCacheType, FIRStorageReference) -> Void)? = nil) -> FIRStorageDownloadTask? {
        
        sd_currentDownloadTask?.cancel()
      
        self.image = placeholder
    
        let key = storageRef.fullPath
    
        if let cached = cache.imageFromCache(forKey: key) {

            if key.lowercased().hasSuffix(".gif") {
                self.image = nil
                self.animatedImage = FLAnimatedImage(gifData: cached.sd_imageData())
                
            } else {
                self.animatedImage = nil
                self.image = cached
            }
            
            completion?(cached, nil, .memory, storageRef)
            return nil
        }
        
        if let cached = cache.imageFromDiskCache(forKey: key) {
            
            if key.lowercased().hasSuffix(".gif") {
                self.image = nil
                self.animatedImage = FLAnimatedImage.init(animatedGIFData: cached.sd_imageData())

            } else {
                self.animatedImage = nil
                self.image = cached
            }
            completion?(cached, nil, .disk, storageRef)
            
            return nil
        }
        
        let download = storageRef.data(withMaxSize: Int64(size), completion: { (data, error) in
            DispatchQueue.main.async {
                if let data = data {
                    if key.lowercased().hasSuffix(".gif") {
                        let image = UIImage.sd_animatedGIF(with: data)
                        
                        self.image = nil
//                        self.animatedImage = FLAnimatedImage(animatedGIFData: data)
                        self.animatedImage = FLAnimatedImage(gifData: data)
                        
                        
                        cache.store(image, imageData: data, forKey: storageRef.fullPath, toDisk: true, completion: {
                            completion?(image, nil, .none, storageRef)
                        })
                        
                        
                    } else {
                        let image = UIImage.sd_image(with: data)
                        self.animatedImage = nil
                        self.image = UIImage(data: data)
                        
                        cache.store(image, imageData: data, forKey: storageRef.fullPath, toDisk: true, completion: {
                            completion?(image, nil, .none, storageRef)
                        })
                    }
                } else {
                    completion?(nil, error, .none, storageRef)
                }
            }
        });
        
        sd_currentDownloadTask = download
        return download
    }
    
    
    open override var sd_currentDownloadTask:FIRStorageDownloadTask? {
        get {
            return objc_getAssociatedObject(self, &xoAssociationKey) as? FIRStorageDownloadTask
        }
        set {
            objc_setAssociatedObject(self, &xoAssociationKey, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
        }
    }
}

**Comment by morganchen12** [comment]
Using the key's suffix as a way of detecting gifs is unreliable as users could conceivably upload a gif to a storage reference with no file extension. You should use [`NSData.sd_imageFormatForImageData(_:)`](https://github.com/rs/SDWebImage/blob/master/SDWebImage/NSData%2BImageContentType.m#L15) instead.

If you'd like to make a PR in objc I'd be happy to review it :)

**Comment by superdev89** [comment]
Yes, for the extension, I wrote it only for testing purposes(assuming all the uploaded gifs have .gif extension and I confirmed it.) I will replace it with above.

**Comment by morganchen12** [comment]
Some more notes, now that I've had more time to look at this code:

- You probably want to use `cached.sd_imageDataAsFormat(.gif)` instead of `cached.sd_imageData()`, as the latter will return a default of PNG data.
- Inside the cached logic block you should use `FLAnimatedImage(gifData:)` instead of `FLAnimatedImage.init(animatedGIFData:)` for consistency with the rest of the code.

**Comment by superdev89** [comment]
I'lll try with above replacement

**Comment by superdev89** [comment]
What about this line for storing gif to cache? 
```
let image = UIImage.sd_animatedGIF(with: data)
cache.store(image, imageData: data, forKey: storageRef.fullPath, toDisk: true, completion: {
                            completion?(image, nil, .none, storageRef)
                        })
```

**Comment by morganchen12** [comment]
Should be fine. Are gifs still not loading?

**Comment by superdev89** [comment]
not loading yet

**Comment by morganchen12** [comment]
I'll try to take a look tomorrow.

**Comment by superdev89** [comment]
When storing to cache, gif is showing and gif data seems stored normally. But when loading the gif from the cache, it doesn't load the gif file correctly.

Here is the code piece for loading gif from the cache I wrote above: 
```
    if let cached = cache.imageFromMemoryCache(forKey: key){
            if cached.isGIF() {
                
                **let gifData = cached.sd_imageData(as: SDImageFormat.GIF)**
                 DispatchQueue.main.async {
                    self.image = nil
                    self.animatedImage = FLAnimatedImage(gifData: gifData)
                }
                
            } else {
                DispatchQueue.main.async {
                    self.animatedImage = nil
                    self.image = cached
                }
            }
            
            completion?(cached, nil, .memory, storageRef)
            return nil
        }
```
I debugged into the code and found an issue inside
`let gifData = cached.sd_imageData(as: SDImageFormat.GIF)`

Here is the function defined in SDWebImage:

```
- (nullable NSData *)sd_imageDataAsFormat:(SDImageFormat)imageFormat {
    NSData *imageData = nil;
    if (self) {
#if SD_UIKIT || SD_WATCH
        int alphaInfo = CGImageGetAlphaInfo(self.CGImage);
        BOOL hasAlpha = !(alphaInfo == kCGImageAlphaNone ||
                          alphaInfo == kCGImageAlphaNoneSkipFirst ||
                          alphaInfo == kCGImageAlphaNoneSkipLast);
        
        BOOL usePNG = hasAlpha;
        
        // the imageFormat param has priority here. But if the format is undefined, we relly on the alpha channel
        if (imageFormat != SDImageFormatUndefined) {
            usePNG = (imageFormat == SDImageFormatPNG);
        }
        
        if (usePNG) {
            imageData = UIImagePNGRepresentation(self);
        } else {
            **imageData = UIImageJPEGRepresentation(self, (CGFloat)1.0);**
        }
#else
        NSBitmapImageFileType imageFileType = NSJPEGFileType;
        if (imageFormat == SDImageFormatGIF) {
            imageFileType = NSGIFFileType;
        } else if (imageFormat == SDImageFormatPNG) {
            imageFileType = NSPNGFileType;
        }
        
        imageData = [NSBitmapImageRep representationOfImageRepsInArray:self.representations
                                                             usingType:imageFileType
                                                            properties:@{}];
#endif

```
Here the gif data is processed as JPEG file. Any idea for this?

**Comment by morganchen12** [comment]
You're right, caching a UIImage isn't a reliable way to preserve GIF animations. Instead we should use [`SDWebImageCache.queryCacheOperation(forKey:done:)`](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDImageCache.h#L167) to load the raw data, which can then be displayed as a GIF the same way we display data downloaded from Firebase Storage.

**Comment by superdev89** [comment]
Thanks it works

**Comment by superdev89** [comment]
I finished all wrapped up.
