### ISSUE TITLE
FUIIndexTableViewDataSource: Swift compiler error "extra argument 'data' in call"

### ISSUE THREAD

**Issue by ghowen** [firebase/FirebaseUI-iOS#281]
I am trying to get FUIIndexTableViewDataSource to work in a Swift project (iOS 10.3.2, Firebase SDK 4.0.0, FirebaseUI 4.0.0, CocoaPods 1.2.1)

The code is like this inside a UITableViewController:

        let indexQuery = App.db.child("userVehicles").child(App.user.id!).child(App.user.currentCommunityId!)
        let dataRef = App.db.child("vehicles").child(App.user.currentCommunityId!)
        
        self.dataSource = self.tableView.bind(
            toIndexedQuery: indexQuery,
            data: dataRef,
            delegate: self,
            populateCell: { (tableView, indexPath, snapshot) -> UITableViewCell in
            
                let cell = tableView.dequeueReusableCell(withIdentifier: "VehiclesTableViewCell", for: indexPath)
            
                if let vehicle = RSVehicle(snapshot: snapshot) {
                
                    cell.textLabel?.text = vehicle.name
                                
                }
            
                return cell
            
            }
        
        )

But I fail to compile with the error "extra argument 'data' in call" which points to the second parameter in self.tableView.bind call.

When I tried the notation from https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseDatabaseUI/FUIIndexTableViewDataSource.h I received the message

'bindToIndexedQuery(_:data:delegate:populateCell:)' has been renamed to 'bind(toIndexedQuery:data:delegate:populateCell:)'

so my call should be correct.

**Comment by ghowen** [comment]
Interestingly if I manually implement the tableview.bind extension it works. So my guess is that there is some bug in the Pod regarding the bind signature (but I don't have much experience with libraries and pods). Here is the code I got to compile:

        let indexQuery = App.db.child("userVehicles").child(App.user.id!).child(App.user.currentCommunityId!)
        let dataRef = App.db.child("vehicles").child(App.user.currentCommunityId!)
        
        self.dataSource = FUIIndexTableViewDataSource(
            index: indexQuery,
            data: dataRef,
            tableView: self.tableView,
            delegate: self,
            populateCell: { (tableView, indexPath, snapshot) -> UITableViewCell in
                
                let cell = tableView.dequeueReusableCell(withIdentifier: "VehiclesTableViewCell", for: indexPath)
                
                if let snapshot = snapshot, let vehicle = RSVehicle(snapshot: snapshot) {
                    
                    cell.textLabel?.text = vehicle.name
                    
                }
                
                return cell
                
            }

        )
        
        self.tableView.dataSource = self.dataSource

**Comment by ghowen** [comment]
No idea why but now it is compiling.

**Comment by morganchen12** [comment]
Smells like a Swift compiler bug or Xcode getting really confused.

If in the future this issue reappears in more permanent form, feel free to reopen this ticket or re-file.

**Comment by ghowen** [comment]
Yes, will do. I cleaned the product and the build folder several times but this did not change anything. Does smell like a compiler bug. Anyway, thanks for replying 👍
