### ISSUE TITLE
Unable to instal cocoapods

### ISSUE THREAD

**Issue by Tayphoon** [firebase/FirebaseUI-iOS#283]
Then try install pods via cocoapods 1.2.1. This is the output:

[!] Unable to find host target(s) for Database, Storage, Auth, Facebook, Google, Phone, Twitter. Please add the host targets for the embedded targets to the Podfile.
Certain kinds of targets require a host target. A host target is a "parent" target which embeds a "child" target. These are example types of targets that need a host target:
- Framework
- App Extension
- Watch OS 1 Extension
- Messages Extension (except when used with a Messages Application)

**Comment by morganchen12** [comment]
This is a known bug in CocoaPods. You can work around it by using CocoaPods master (pre-release).

**Comment by Tayphoon** [comment]
It doesn't help.

**Comment by morganchen12** [comment]
You'll need to specify CocoaPods from git source, not just using prerelease gems. Take a look at this [Gemfile](https://github.com/firebase/FirebaseUI-iOS/pull/280/files#diff-8b7db4d5cc4b8f6dc8feb7030baa2478) and have a look at the [bundler docs](http://bundler.io/docs.html) if you're unfamiliar with bundler.

**Comment by CarlosLabrado** [comment]
I really don't understand what we have to do here in order to make the pod install work. Install bundler?

**Comment by morganchen12** [comment]
Install bundler, run `bundle install`, and then prefix all your gem commands with `bundle exec`. So your `pod install` invocation should look like

```
bundle exec pod install
```

**Comment by eliotstock** [comment]
Upgrading to CocoaPods 1.3.0.beta.1 also worked for me.
