### ISSUE TITLE
FirebaseAuthUI file not found

### ISSUE THREAD

**Issue by kovalskyy** [firebase/FirebaseUI-iOS#284]
Objective C & swift
  iOS version: 10.2
  Firebase SDK version: 4.0
  FirebaseUI version: 4.0
  CocoaPods Version: 1.2.1
  

I have been trying to use firebaseAuthUI and specifically firebasePhoneAuthUI in my project but I can't get through compilation error: FirebaseAuthUI/FirebaseAuthUI.h file not found

My project is split with different modules (pods), which represent appropriate repository. Firstly, I have tried building those frameworks with Cocoapods and it worked fine on the main project. For the login/signup flow I am using another project, LoginKit and when I have imported those frameworks into this repository and tried building main project I got error mentioned above. I thought it might be problem with Cocoapods versions on those projects, but I have tried importing those frameworks manually and it still not compiling. 

I have added appropriate path from LoginKit podspec to the main project.
spec.ios.vendored_frameworks = 
'Frameworks/FirebaseAuth.framework',
 'Framework/FirebaseAuthUI.framework',
 'Framework/FirebasePhoneAuthUI.framework'

//Project
#import <FirebaseAuthUI/FirebaseAuthUI.h>
#import <FirebasePhoneAuthUI/FirebasePhoneAuthUI.h>

I know that the Firebase framework is there since my project is already using it and it was installed with Cocoapods. Cleaning and re-building doesn't fix the issue.

Any suggestions?

**Comment by morganchen12** [comment]
Can you share a project that reproduces this issue? If you're trying to build pods on top of FirebaseUI you'll need to expose the frameworks as dependencies, not vendored binaries. Also you'll run into lots of trouble at link time, so I encourage you try not to wrap FirebaseUI via CocoaPods if you can avoid it.

**Comment by kovalskyy** [comment]
I can't share this project actually. Problem was resolved considering issue mentioned here : https://www.bountysource.com/issues/42551498-missing-header-file-with-use_frameworks.
