### ISSUE TITLE
Missing headers in FirebasePhoneAuthUI framework

### ISSUE THREAD

**Issue by kovalskyy** [firebase/FirebaseUI-iOS#292]
* Objective C or Swift: both
  * iOS version: latest
  * Firebase SDK version: 4.0
  * FirebaseUI version: 4.0
  * CocoaPods Version: 1.2.1
  
I have got problem with FirebasePhoneAuthUI.framework and specifically with missing header files. I am seeing and have access to only two of them (FirebasePhoneAuthUI.h and FUIPhoneAuth.h). What's with the others (like FUIPhoneEntryViewController.h etc.)?
  

Pods: 
pod 'Firebase/Auth'
pod 'FirebaseUI/Phone', ' 4.0'
pod 'FirebaseUI/Auth', ' 4.0'

// my project 
#import <FirebaseAuthUI/FirebaseAuthUI.h>
#import <FirebasePhoneAuthUI/FirebasePhoneAuthUI.h>

**Comment by SebastianBO** [comment]
+1 
Had this problem for like a week so had to go back to an older version after trying all possible "fixes"

**Comment by kovalskyy** [comment]
@SebastianBO What was the older version that worked for you? I have to use phone authentication in my project.

**Comment by SebastianBO** [comment]
Sorry to give you the wrong idea, in order to use phone-auth you have to do it without FirebaseUI until they've solved this problem.

**Comment by kovalskyy** [comment]
@SebastianBO Okey. Thanks for making this clear.

**Comment by doanbahai** [comment]
#48, #47, #46, #34, #23.

**Comment by yramanchuk** [comment]
@kovalskyy we are not supporting customization of PhoneAuth flow.
Why do you need mentioned controller?

**Comment by kovalskyy** [comment]
@yramanchuk I just have issues with dismissing controller and proceeding with code verification, so I thought maybe I have to use different controllers. These issues happened to other users, so I am gonna adjust to your responses in open subjects.

**Comment by zampelis** [comment]
There are no frameworks in the Phone section.
<img width="826" alt="screen shot 2017-08-04 at 17 09 34" src="https://user-images.githubusercontent.com/6816642/28976953-e48a7f2c-7937-11e7-9124-2f89fec7fd23.png">
