### ISSUE TITLE
Cancel Button of FUIPhoneAuth doesn't dismiss the view controller

### ISSUE THREAD

**Issue by jeandavid** [firebase/FirebaseUI-iOS#293]
I have a "Sign In with Phone" Button (screenshot 1) on a single view controller. When tapped, the button shows the UI for phone number sign up (screenshot 2). 

But the Cancel Button on top of screen 2 doesn't take me back to screen 1. 

[This is a gist of the view controller](https://gist.github.com/jeandavid/7de78f53a1c432f790268a8db4239db0) 

 * Swift: 3 
 * Xcode: 8.1
 * iOS version:10.1
 * FirebaseUI version: 4.0
 * CocoaPods Version: 1.2.1
Podfile only includes pod 'FirebaseUI/Phone', '~> 4.0'

Screenshot 1:
![screenshot1](https://user-images.githubusercontent.com/3328783/26846174-8f7fe3aa-4b01-11e7-9814-2ddbc37def5f.png)

Screenshot2: 
![screenshot2](https://user-images.githubusercontent.com/3328783/26846196-9a3d29ba-4b01-11e7-9081-340f3eac5e54.png)

**Comment by kovalskyy** [comment]
+ Have the same issue. @jeandavid Have you succeed with registration process and verifying code?

**Comment by yramanchuk** [comment]
@jeandavid @kovalskyy How do you present Phone Auth?
You should be using something like this:
```
        let provider = self.authUI?.providers.first as! FUIPhoneAuth;
        provider.signIn(withPresenting: self);

```
You should added phone auth provider to `authUI.providers`.
You can check out how we're dismissing controller. [Here's link](https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebasePhoneAuthUI/FUIPhoneEntryViewController.m#L276-L287).

**Comment by jeandavid** [comment]
@yramanchuk this is exactly what I did but in swift. Please have a look at this very short[ gist](https://gist.github.com/jeandavid/7de78f53a1c432f790268a8db4239db0). And it doesn't work. Cancel button doesn't work and verification triggers this error: "Something went wrong. Please try again" ( I tried and tried again)

@kovalskyy Indeed phone verification raises an error

**Comment by jeandavid** [comment]
@yramanchuk @kovalskyy I resolved the issue concerning the cancel button by adding the `self.authUI?.providers = [phoneProvider]` line when I present the PhoneAuthUI: 

     let phoneProvider = FUIPhoneAuth.init(authUI: authUI)
     self.authUI?.providers = [phoneProvider] // NEEDED!?
     phoneProvider.signIn(withPresenting: self)

But I still can't make the verification process go through...

**Comment by kovalskyy** [comment]
@jeandavid @yramanchuk  thanks for help. I have got this working now. Here is my code in obj-c.

        FUIAuth *auth = [FUIAuth defaultAuthUI];
        auth.delegate = self;
        //
        FUIPhoneAuth *phoneAuth = [[FUIPhoneAuth alloc] initWithAuthUI:auth];
        auth.providers = @[phoneAuth];
        [phoneAuth signInWithPresentingViewController:self];

**Comment by morganchen12** [comment]
Thanks for following up! Feel free to reopen if this issue appears again in the future.
