### ISSUE TITLE
Custom emailEntryViewController not showing custom view

### ISSUE THREAD

**Issue by ryandailey100** [firebase/FirebaseUI-iOS#294]
I have my project set up just like the sample project provided. I have used the work-around (stated in https://github.com/firebase/FirebaseUI-iOS/issues/128 ) to get the Custom authPickerViewController to successfully show. When I tap the Sign in with email button, it brings me to the default email entry view controller, rather than the custom i have set up. 

The below function seems to never trigger, but the similar authPickerViewController function does trigger.

```
func emailEntryViewController(forAuthUI authUI: FUIAuth) -> FUIEmailEntryViewController {
    return CustomEmailEntryVC(authUI: authUI)
}
```

**Comment by yramanchuk** [comment]
@ryandailey100 Have you assigned `authUI.delegate`?
Please check [this sample](https://github.com/firebase/FirebaseUI-iOS/blob/master/samples/swift/FirebaseUI-demo-swift/Samples/Auth/FUIAuthViewController.swift#L127).

**Comment by ryandailey100** [comment]
Yes I have. Like i said, the authPickerViewController function gets successfully called from the delegate, but the emailEntryViewController doesn't get called when it should.

**Comment by yramanchuk** [comment]
Hm... let's go over check list:

1. Are you using exactly this method (it's different method signature than you specified). Is next method was called?  
```
func emailEntryViewController(forAuthUI authUI: FUIAuth) -> FUIEmailEntryViewController {
    return FUICustomEmailEntryViewController(nibName: "FUICustomEmailEntryViewController",
                                             bundle: Bundle.main,
                                             authUI: authUI)
  }
```
2. How are you presenting `authViewController`? You should use:
```
      UIViewController *controller = [self.authUI authViewController];
      [self presentViewController:controller animated:YES completion:nil];

```
4. Do you retain `AuthUI.delegate`? This property is weak, so you should take care of it's ownership.
3. I recommend [analyze code](https://github.com/firebase/FirebaseUI-iOS/blob/ea1a21cbaf55bff28b1c2552a2097c1dacaf8da1/FirebaseAuthUI/FUIAuthPickerViewController.m#L142-L150) where we present email controller (assuming you're presenting `AuthPicker` which has 'sign in with email' button).
1. Can you provide error? Console logs? If no messages, can you send link to your repo?

**Comment by ryandailey100** [comment]
Okay thanks! It looks like i didn't retain AuthUI.delegate properly. Thanks for the help!
