### ISSUE TITLE
Should skip auth picker view if single provider

### ISSUE THREAD

**Issue by adriano-di-giovanni** [firebase/FirebaseUI-iOS#295]
I initialize FUIAuth instance as follows:

    FUIAuth *authUI = [FUIAuth defaultAuthUI];

    NSArray<id<FUIAuthProvider>> *providers = @[[[FUIGoogleAuth alloc] init]];
    [authUI setSignInWithEmailHidden:YES];

    authUI.providers = providers;

and I'd expect to have the Google Sign In screen presented directly.

I get the auth picker view instead.

I think FirebaseUI iOS should skip the auth picker view if only one provider is configured.

Additionally, this is the behavior of FirebaseUI Android.

**Comment by yramanchuk** [comment]
@adriano-di-giovanni you can achieve this by calling Phone Auth provider directly:
```
      FUIPhoneAuth *provider = self.authUI.providers.firstObject;
      [provider signInWithPresentingViewController:viewController];
```
Please notice that should add provider to the list of providers anyway (you're already doing this).

Here is [sample code link](https://github.com/firebase/FirebaseUI-iOS/blob/master/samples/objc/FirebaseUI-demo-objc/Samples/Auth/FUIAuthViewController.m#L195-L197).
