### ISSUE TITLE
Phone Auth screen does not disappear on cancel

### ISSUE THREAD

**Issue by donnywals** [firebase/FirebaseUI-iOS#300]
Hi there, 

I am attempting to migrate from Digits to Firebase and so far it hasn't been easy. We use a custom button to open the phone ui and since we'd like to keep using this flow it seems that I have to jump though a few hoops.

Based on the sample code you have provided I was able to make the Phone auth UI appear after tapping on a button, but when I verify my phone number or tap the cancel button, the modal never disappears and it isn't clear to me how I should proceed..

  * Objective C or Swift: Swift
  * iOS version: 10.3.2
  * Firebase SDK version: 4.x
  * FirebaseUI version: 4.0.0
  * CocoaPods Version: 1.1.1
  
## The problem

The Phone auth UI dialog does not get dismissed after verifying my phone number or when tapping cancel.

### Steps to reproduce:
Implement a custom button that directly displays the Phone auth ui.
  
### Observed Results:
The Phone auth appears, when tapping cancel it does not dissappear. Also, it gets stuck after validating a phone number; the spinners remains on screen and the window is never dismissed
  
### Expected Results:
I would expect the didSignIn delegate callback to be called and / or the window to be dismissed when I tap cancel
  
### Relevant Code:

This snippet shows the phone auth UI
  ```
func confirmPhoneNumber(withViewController viewController: UIViewController,
                        completionHandler: @escaping PhoneConfirmationHandler) {
    
    guard let authUI = FUIAuth.defaultAuthUI() else {
        completionHandler(.error(GenericError.unkownError))
        return
    }
    
    authUI.delegate = self
    let provider = FUIPhoneAuth(authUI: authUI)
    provider.signIn(withPresenting: viewController)
}
  ```

Delegate implementation
```
extension AuthenticationManager: FUIAuthDelegate {
    func authUI(_ authUI: FUIAuth, didSignInWith user: FirebaseAuth.User?, error: Error?) {
        guard let user = user else {
            return
        }
        
        print(user)
    }
}
```

**Comment by yramanchuk** [comment]
@donnywals probably you forgot to call:
` self.authUI?.providers = [phoneProvider] 
`
Check this comment: https://github.com/firebase/FirebaseUI-iOS/issues/293#issuecomment-306688524

Please let me know if that helped you.
We will update code to verify this case in the next release.

**Comment by donnywals** [comment]
@yramanchuk yes! That seems to have solved the issue :) Thanks.
Also, sorry for posting this duplicate..
