### ISSUE TITLE
"Your request couldn't be completed" when using Phone Auth

### ISSUE THREAD

**Issue by donnywals** [firebase/FirebaseUI-iOS#301]
## Environment
  * Objective C or Swift: Swift
  * iOS version: 10.3
  * Firebase SDK version: 4.x
  * FirebaseUI version: 4.0.0
  * CocoaPods Version: 1.1.1
  
## The problem
When I tap the "verify" button, I immediately get a pop-up saying "Your request couldn't be completed. Please try again." I don't get any errors in the log and I'm not sure whether there is anything I might have missed.

The strange thing is that I have successfully received an sms message in the past yet I can't find anything in my code that has changed. Checking out several commits did not make a difference..

I also tried running my app with both the debug and release configs to if that makes a difference.

Just for the record, I feel like migrating from Digits to Firebase is way too intensive. Why couldn't the existing Digits SDK be ported to Firebase? Mixing Firebase + Firebase UI is causing me a lot of troubles so far because everything seems to work different. I know that this is the UI repo and you can't fix it but I just wanted to throw this frustration out there..

### Steps to reproduce:
Fill out phone number, tap verify, see error message.

### Observed Results:
I see an error message
  
### Expected Results:
I would expect to receive an sms message to verify my phone number or a more descriptive error
  
#### Relevant Code:

```
func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    Auth.auth().setAPNSToken(deviceToken, type: AuthAPNSTokenType.prod)
}

func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
    if Auth.auth().canHandleNotification(userInfo) {
        completionHandler(UIBackgroundFetchResult.noData)
        return
    }
}
```

```
func confirmPhoneNumber(withViewController viewController: UIViewController,
                        completionHandler: @escaping PhoneConfirmationHandler) {
    
    guard let authUI = FUIAuth.defaultAuthUI() else {
        completionHandler(.error(GenericError.unkownError))
        return
    }
    
    phoneNumberConfirmedHandlers.append(completionHandler)
    
    authUI.delegate = self
    let provider = FUIPhoneAuth(authUI: authUI)
    authUI.providers = [provider]
    provider.signIn(withPresenting: viewController)
}
```

**Comment by yramanchuk** [comment]
@donnywals I understand your frustration. Here're some suggestions:
1. Have you tried[ Digits migration helper](https://github.com/firebase/digits-migration-helper-ios)s? 
1. There is [headless Firebase API](https://github.com/firebase/firebase-ios-sdk). You can use it if you don't need UI.
1. Can you please [check this issue](https://github.com/firebase/FirebaseUI-iOS/issues/299#issuecomment-309094639) and send us logs (you should enabled `GTMSessionFetcher`)?

**Comment by yramanchuk** [comment]
@donnywals Can you please provide more info otherwise I'll close this ticket.

**Comment by donnywals** [comment]
@yramanchuk I'm going to look into this more today, didn't have much time the past week. I'll let you know what I find asap :)

**Comment by donnywals** [comment]
@yramanchuk I may have found the problem. The error I see is "Token mismatch", what could this mean and how can I go about fixing it?

**Comment by donnywals** [comment]
Looking in to this further, it seems that `signInWithCustomToken:completion:` is called on the `Auth` instance. Shouldn't this be `signInwithCredential:completion:`?

**Comment by yramanchuk** [comment]
`Token mismatch` problems:
- you should change token type for production and development;
- you haven't uploaded distribution/dev APNS certificate
- your APNS certificate is wrong: verify `bundeID`

**Comment by donnywals** [comment]
Thanks for your help @yramanchuk, it seems to be working now. Our app uses multiple bundle ids and schemes, trans out I was using a bad combination of the two... 
I will close the issue
