### ISSUE TITLE
numberOfRowsInSection for FirebaseTableViewDatasource

### ISSUE THREAD

**Issue by psopher** [firebase/FirebaseUI-iOS#31]
In the example, there's no number of rows in section called for FirebaseTableViewDatasource. I assumed it was because it was built in that it would stop populating automatically when nodes ran out. However, when I ran the program without calling number of rows in section it gave me this error:

[LanguagesListFUITest tableView:numberOfRowsInSection:]: unrecognized selector sent to instance 0x1465d5770

Any advice on how to get around this?

**Comment by mcdonamp** [comment]
@psopher can you post what your TableView code looks like? We've got `-numberOfRowsInSection` implemented [here](https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseUI/Core/Implementation/FirebaseTableViewDataSource.m#L303-L305)

Are you sure that you're setting the datasource property on your tableview?

**Comment by psopher** [comment]
Thanks for the answer. I figured out that I was setting the dataSource incorrectly. I had set it to self instead of self.dataSource
