### ISSUE TITLE
Could not load NIB in bundle FUIAuthPickerViewController

### ISSUE THREAD

**Issue by freedoom1984** [firebase/FirebaseUI-iOS#311]
* Swift
  * iOS version: 10.3
  * Firebase SDK version: latest
  * FirebaseUI version: latest
  
### Step 3: Describe the problem:

MantoApp[65711:1867445] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </Users/luigimarino/Library/Developer/CoreSimulator/Devices/AB5267D2-F786-4420-BC6C-1D56B49BBA5B/data/Containers/Bundle/Application/4CEF2D6C-204C-4420-A991-797FA909F608/MantoApp.app> (loaded)' with name 'FUIAuthPickerViewController''

**Comment by eirikvaa** [comment]
Having this exact problem myself!

**Comment by yramanchuk** [comment]
@freedoom1984 @eirikvaa There're [`FUIAuthDelegate` methods ](https://github.com/firebase/FirebaseUI-iOS/blob/master/samples/swift/FirebaseUI-demo-swift/Samples/Auth/FUICustomAuthUIDelegate.swift#L38-L42)for specifying nib name:

```
func authPickerViewController(forAuthUI authUI: FUIAuth) -> FUIAuthPickerViewController {
   return FUICustomAuthPickerViewController(nibName: "FUICustomAuthPickerViewController",
                                             bundle: Bundle.main,
                                             authUI: authUI)
}
```

@freedoom1984 Please let me know if that helped you.

**Comment by eirikvaa** [comment]
@yramanchuk Yes, you can see I found the solution a couple of days ago (in the post above yours), but thank you!

**Comment by eirikvaa** [comment]
I'm having a very similar issue like this one. When running the app and I try to log in, I will sometimes get an exception before the authPicker is presented. 

<img width="350" alt="screenshot at okt 04 14-16-55" src="https://user-images.githubusercontent.com/6376002/31175815-d2b035fe-a910-11e7-80f1-9cccfa4fd044.png">

I get no sensible error message, only that the exception occurred. When inspecting the stack trace I can see that in `FUIAuthPickerViewController` the `_buttonContainerView` is `nil`, but I don't know if this is the source of the bug or if I have done anything. I have implemented the fix mentioned above. It worked for a while, but now it suddenly stopped working.

**Comment by eirikvaa** [comment]
**Update**: It seems that the problem has been fixed by removing CocoaPods from the project and reinstalling it. I got this bug earlier, and fixed it by doing the same thing I did now. This bugs me, because I have no idea what caused this.

**Comment by elgawady14** [comment]
`Product -> Clean` `command+shift+k`

**Comment by kamalupasena** [comment]
I have mange to add a customized UI but issue was after adding the UI `Sign in with email` option not working that button not even touch

**Comment by arminasr** [comment]
@kamalupasena have you found a way how to fix this issue?

**Comment by kamalupasena** [comment]
@arminasr  i have with the help of `FUIAuthPickerViewController`

**Comment by tyridw** [comment]
I had a similar issue when trying to hide the "Cancel" button in the navigation bar. When I subclassed FUIEmailEntryViewController I had to follow the leads in:
https://stackoverflow.com/questions/41252812/could-not-load-nib-when-subclassing-fuiauthpickerviewcontroller
and came up with
```
class CustomFUIEmailEntryViewController : FUIEmailEntryViewController {
    open override func viewWillAppear(_ animated: Bool) {
        self.navigationItem.leftBarButtonItem = nil
    }
    
    override init(nibName: String?, bundle: Bundle?, authUI: FUIAuth) {
          super.init(nibName: "FUIEmailEntryViewController", bundle: bundle, authUI: authUI)
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
}
```
which is returned by my view controller (that is set as delegate on my FUIAuth instance)
```
    func emailEntryViewController(forAuthUI: FUIAuth) -> FUIEmailEntryViewController {
        return CustomFUIEmailEntryViewController(authUI: forAuthUI)
    }
```

**Comment by arminasr** [comment]
The issue I had was solved by creating a navigation controller `rootNavigationController = authUI.authViewController()` and placing `fuiAuthPickerViewController` into it `rootNavigationController.setViewControllers([fuiAuthPickerViewController!], animated: true)`

```swift
    func presentAuthPickViewController() {
        rootNavigationController = authUI.authViewController()
        
        let fuiAuthPickerViewController = authUI.delegate?.authPickerViewController!(forAuthUI: authUI)
        rootNavigationController.setViewControllers([fuiAuthPickerViewController!], animated: true)
        rootNavigationController.modalTransitionStyle = .coverVertical
        rootViewController.present(rootNavigationController!, animated: true, completion: nil)
    }
```

**Comment by aleczadikian** [comment]
> This might be a solution to the above, since we have almost identical error messages.
> 
> ### Meta
> * Swift
> * iOS version: 10.3
> * Firebase SDK version: latest
> * FirebaseUI version: latest
> 
> ### Description of the problem:
> FerskFiskiOS[17707:2225373] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </Users/Eirik/Library/Developer/CoreSimulator/Devices/4849CDF8-2B1E-4032-BC77-2C10E530C415/data/Containers/Bundle/Application/2C5CA1C3-E7B5-49C1-8891-0F1F6F205DC0/FerskFiskiOS.app/FirebaseAuthUI.bundle> (not yet loaded)' with name 'FIRCustomPasswordSignUpViewController''
> 
> ### Solution
> Finally found the solution. Go to your view controller associated with the nib file that Xcode can't find and in the `override init(nibName ...)` method, use custom values for nibNameOrNil and nibBundleOrNil instead of those passed in.
> 
> ```swift
> override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?, authUI: FUIAuth, email: String?) {
>     super.init(nibName: "FIRCustomPasswordSignUpViewController", bundle: Bundle.main, authUI: authUI, email: email)
>  }
> ```
> 
> I don't like to hardcode stuff, but this solved the problem.

Since I don't have a NIB, I specified nil for the NIB name, and that worked:

```
override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?, authUI: FUIAuth, email: String?) {
    super.init(nibName: nil, bundle: Bundle.main, authUI: authUI, email: email)
 }
```
