### ISSUE TITLE
FUIPhoneAuth user.phoneNumber null in updateUI:withUser

### ISSUE THREAD

**Issue by wayneforrest** [firebase/FirebaseUI-iOS#312]
After a successful signup, I managed to see the phoneNumber used during registration,
in the delegate method:

`- (void)authUI:(FUIAuth *)authUI didSignInWithUser:(nullable FIRUser *)user error:(nullable NSError *)error`

But on restart of the application I register to received a callback:
`- (void)updateUI:(FIRAuth * _Nonnull) auth withUser:(FIRUser *_Nullable) user {`

Inside this method I can see the user.uid and user.ProviderID but the user.phoneNumber is null.

As a temp fix / hack I stored the user's PhoneNumber in NSUserDefaults.

I can also confirm that the user is registered when I look at the FB Web Console, I do notice
the phoneNumber listed there.

Am I missing something important here or is this a bug?

**Comment by protocol86** [comment]
It's a bug that has been addressed but not yet released.  In the meantime a work around would be to obtain the phone number from the provider data like the following code snippet:

NSString *phoneNumber = [[FIRAuth auth] currentUser].providerData[0].phoneNumber;

Here we assume that the first user in your provider data is the phone number user in question, if you have several entries you can simply iterate the providerData array.

**Comment by yramanchuk** [comment]
Issue was fixed in the latest FirebaseUI version
