### ISSUE TITLE
TableView not reloading anymore after leaving and coming back to it

### ISSUE THREAD

**Issue by warhost** [firebase/FirebaseUI-iOS#314]
Hey,

### Step 2: Describe your environment

Objective C or Swift: Swift
iOS version: 10.3
Firebase SDK version: 4.0.0
FirebaseUI version: 4.0.0
CocoaPods Version: 1.1.1
  
### Step 3: Describe the problem:

I have a tableview bound to a query, and doing live updates to the database shows the child immediately in the tableview, however only as long as I am still on the first "instance" of that tableview. When I leave to a different view and come back, there are no more updates to it. I am following the practices from the example.

#### Steps to reproduce:

  1. Create a TableView and bind it to a query like I do in the code below
  2. Update the table, it will update accordingly
  3. Close the app or leave the TableView, then come back to it. It won't update anymore.
  
#### Observed Results:

  * The TableView doesn't update anymore after leaving and coming back to it, only in the first 'instance' of the view it "live-updates" according to the query. The app needs to be closed an re-opened to then see the updates.
  
#### Expected Results:

  * I expect the tableview to update also after leaving and coming back to it.
  
#### Relevant Code:

  ```
  func getQuery() -> DatabaseQuery {
    let myTopPostsQuery = (ref.child("users")).child(getUid()).child("data").queryOrderedByPriority()
    return myTopPostsQuery
}

override func viewDidLoad() {
    super.viewDidLoad()
    
    ref = Database.database().reference()
    
    dataSource = FUITableViewDataSource.init(query: getQuery()) { (tableView, indexPath, snap) -> MGSwipeTableCell in
        let cell = tableView.dequeueReusableCell(withIdentifier: "linksCellident", for: indexPath) as! LinksCell
        
        
        guard let post = LinksPost.init(snapshot: snap) else { return cell }
        
        cell.ogImageView.sd_setImage(with: URL(string: post.ogImageURL))
        cell.titleLabel.text = post.title
        cell.urlLabel.text = post.url
        
        return cell
    }
    
    dataSource?.bind(to: linksTableView)
    linksTableView.delegate = self
}

override func viewWillAppear(_ animated: Bool) {
    self.linksTableView.reloadData()
}
override func viewWillDisappear(_ animated: Bool) {
    getQuery().removeAllObservers()
}
  ```

**Comment by morganchen12** [comment]
You're detaching the query's observers in `viewWillDisappear`, but not reattaching them elsewhere. Instead of directly managing the query's observers, use the data source's `bind` and `unbind` methods.

**Comment by warhost** [comment]
Thanks for your reply, I changed it to the following, however I still have the same issue:

```
    override func viewWillAppear(_ animated: Bool) {
        dataSource?.bind(to: linksTableView)
        self.linksTableView.reloadData()
    }
```
```
    override func viewWillDisappear(_ animated: Bool) {
        dataSource?.unbind()
    }
```

**Comment by morganchen12** [comment]
It seems there's currently a bug with FUIArray not correctly handling being re-attached to its query after being detached.

**Comment by warhost** [comment]
@morganchen12 Okay, well I tried basically all combinations, and not unbinding will result in what I described in #309.

**Comment by praveenragul** [comment]
i have the same problem in objective c
