### ISSUE TITLE
Do not present view controller with providers

### ISSUE THREAD

**Issue by aetsyss** [firebase/FirebaseUI-iOS#315]
Hello,
I have only phone authorization. Is it possible to present directly the phone authorization controller without presenting the view controller with the list of providers?

Thanks

The code is:

     guard let authUI = FUIAuth.defaultAuthUI() else {
        return
      }
      
      authUI.delegate = self
      authUI.isSignInWithEmailHidden = true
      authUI.providers = [FUIPhoneAuth(authUI:authUI)]

      
      
      let authViewController = authUI.authViewController()
      present(authViewController, animated: true, completion: nil)

**Comment by yramanchuk** [comment]
Please refer to #295
