### ISSUE TITLE
Should not allow user to tap "Sign in with Google" when a signing is in progress

### ISSUE THREAD

**Issue by whchan** [firebase/FirebaseUI-iOS#317]
* Objective C or Swift: Swift
  * iOS version: 10.3.2
  * Firebase SDK version: latest release
  * FirebaseUI version: latest release
  * CocoaPods Version: latest release
  
#### Steps to reproduce:

  1. Show picker view screen
  2. tap google, then login
  3. Show picker view with a progress bar.

#### Observed Results:

User can tab the login buttons even though previous is already in progress.
  
#### Expected Results:

User cannot tab any login buttons

**Comment by yramanchuk** [comment]
@whchan Thanks for the feedback.
I will review issue with our UX designer, probably will add transparent view below activity indicator.

**Comment by yramanchuk** [comment]
Fixed in FirebaseUI 4.3.2
