### ISSUE TITLE
Forgot password callback feature enhancement

### ISSUE THREAD

**Issue by jombie** [firebase/FirebaseUI-iOS#318]
Can we have callback method when email request for forgot password has been sent either with success or failure. This can be used to redirect the user to PasswordSignIn scree when the user has clicked recover password.

Similar flow could be added to the PasswordSignUp so that we can decide whether to login the user or wait till the user has verified his/her emailId.

**Comment by morganchen12** [comment]
This is unlikely to be added as a feature, since most apps just redirect to the sign in screen after sending a recovery email anyway.
