### ISSUE TITLE
Sign in with e-mail button no longer responding after subclassing FUIAuthPickerViewController

### ISSUE THREAD

**Issue by ChrisVerhagen** [firebase/FirebaseUI-iOS#319]
Swift, iOS version 8.0, Firebase SDK version 4.0.4, FirebaseUI version 4.1.1;

I am trying to customize the looks of the FUIAuthPickerViewController and following the technique of Brad Caldwell ([video tutorial](https://www.youtube.com/watch?v=d_byFfP3cTw&feature=youtu.be)) I've subclassed the FUIAuthPickerViewController. This created a runtime-error:

> 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle

I've fixed this by adding the following code to my subclass:
```
    override init(nibName: String?, bundle: Bundle?, authUI: FUIAuth) {
        super.init(nibName: "FUIAuthPickerViewController", bundle: bundle, authUI: authUI)
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
```
 
However, ever since I did this the 'Sign in with e-mail' button is no longer responding even though the 'Sign in with Google' button works just fine... Any Idea's? Full code below:

```
import UIKit
import FirebaseAuthUI

class CustomAuthViewController: FUIAuthPickerViewController {

    override init(nibName: String?, bundle: Bundle?, authUI: FUIAuth) {
        super.init(nibName: "FUIAuthPickerViewController", bundle: bundle, authUI: authUI)
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
 
    override func viewDidLoad(){
        super.viewDidLoad()
        
        // Set up the subview that will display the custom layout
        let width = UIScreen.main.bounds.size.width
        let height = UIScreen.main.bounds.size.height
        let subviewRect = CGRect(x: 0, y: 0, width: width, height: height)
        let subview = UIView(frame: subviewRect)
        subview.backgroundColor = .black

        // Add the logo to our subview
        let logoImageRect = CGRect(x: ((width/2)-100) ,y: ((height/3)-100) , width: 200, height: 200)
        let logoImage = UIImage(named: "Logo black background")
        let logoImageView = UIImageView()
        logoImageView.frame = logoImageRect
        logoImageView.contentMode = UIViewContentMode(rawValue: 2)!
        logoImageView.image = logoImage
        subview.addSubview(logoImageView)

        // Prepare label with the added textmessage and add to subview
        let addedMessageRect = CGRect(x: 0,y: 0, width: 300, height: 20)
        let addedMessage = UILabel(frame: addedMessageRect)
        addedMessage.text = "Please register or login"
        addedMessage.textColor = .white
        addedMessage.adjustsFontSizeToFitWidth = true
        addedMessage.center = CGPoint(x: width/2, y: ((height/3)+200))
        addedMessage.textAlignment = .center
        subview.addSubview(addedMessage)
        
        view.insertSubview(subview, at: 0)
    }
}
```

**Comment by morganchen12** [comment]
Seems like one of your views may be clipping over the email/password button. If you take a look in the view debugger, are any of the custom views you've added obscuring any buttons?

**Comment by ChrisVerhagen** [comment]
Hi Morgan. I've checked and this does not seem to be the problem. I can even comment out all of my added views and the problem will still remain... Here's a screenshot of the  debugger view hierarchy:

<img width="1183" alt="screenshot" src="https://user-images.githubusercontent.com/30442058/28589791-d661a3ea-717f-11e7-963c-96871119616e.png">

**Comment by yramanchuk** [comment]
Considering issue to be fixed.

**Comment by shivavattem** [comment]
hi , i am using FirebaseUI for phone authentication IOS - swift which is working fine, but the thing is my Whole app them color is blue  but the firebase pickerview thing is in white colour 
could you tell me how to resolve this issue. because the digits are closing by this month and i have to release this version ASAP.
thank you so much

**Comment by jamiedaniel** [comment]
Making a custom auth view is a pain and not very straight forward. every time I update Pods something else gets whacky.

Can someone post an example that actually WORKS...
I can't get any buttons at all to show up. and yes everything in my Podfile is updated to current version.

**Comment by dhaneshgosai** [comment]
I am also Facing same problem any one have idea how to solve enable Email sign in ?

**Comment by Antuaaan** [comment]
**Solved** this by adding the custom subclass to a navigationController. The **email sign in button works with the nav bar so that why its not responding.** [https://github.com/firebase/FirebaseUI-iOS/issues/311#issuecomment-406946647](url) Arminas Ruzgas solved it for me : 
"The issue I had was solved by creating a navigation controller 
rootNavigationController = authUI.authViewController() and placing fuiAuthPickerViewController into it rootNavigationController.setViewControllers([fuiAuthPickerViewController!], animated: true)"

    func presentAuthPickViewController() {
        rootNavigationController = authUI.authViewController()
        
        let fuiAuthPickerViewController = authUI.delegate?.authPickerViewController!(forAuthUI: authUI)
        rootNavigationController.setViewControllers([fuiAuthPickerViewController!], animated: true)
        rootNavigationController.modalTransitionStyle = .coverVertical
        rootViewController.present(rootNavigationController!, animated: true, completion: nil)
    }

**Comment by sipersso** [comment]
@Antuaaan Thanks! I wasted hours on this. Can't believe it isn't documented that you need a navigationController
