### ISSUE TITLE
Value of type "ViewController" has no member 'dataSource'

### ISSUE THREAD

**Issue by nkalkounis** [firebase/FirebaseUI-iOS#32]
Having an issue with the sample code for swift.  I'm creating a new project with a single ViewController.  I follow the storyboard instructions:

> Create a storyboard that has either a UITableViewController, UICollectionViewController or a UIViewController with a UITableView or UICollectionView. Drag a prototype cell onto the UITableView or UICollectionView and give it a custom reuse identifier which matches the reuse identifier being used when instantiating the Firebase*ViewDataSource. When using prototype cells, make sure to use prototypeReuseIdentifier instead of cellReuseIdentifier.

> Drag and other properties onto the cell and associate them with properties of a UITableViewCell or UICollectionViewCell subclass. Code samples are otherwise similar to the above.

But I'm receiving an error of:

```
"Value of type "ViewController" has no member 'dataSource'
```
my ViewController.swift code is: 

```
import UIKit
import Firebase
import FirebaseUI

class ViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        let firebaseRef = Firebase(url:"https://<MYFIREBASEID>.firebaseio.com/")
        
        let dataSource: FirebaseTableViewDataSource!
        
        self.dataSource = FirebaseTableViewDataSource(ref: self.firebaseRef, cellReuseIdentifier: "myCell", view: self.tableView)
        
        self.dataSource.populateCellWithBlock { (cell: UITableViewCell, obj: NSObject) -> Void in
            let snap = obj as! FDataSnapshot
            
            cell.textLabel?.text = snap.key as String
        }
        
        self.tableView.dataSource = self.dataSource;
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }


}
```

What am I missing?

**Comment by nkalkounis** [comment]
Resolved...moved firebaseRef and dataSource outside of viewDidLoad()

```
import UIKit
import Firebase
import FirebaseUI

class ViewController: UIViewController {
     @IBOutlet weak var tableView: UITableView! //wired to the tableview in storyboard
     let firebaseRef = Firebase(url:"https://<MYFIREBASEID>.firebaseio.com/")
     let dataSource: FirebaseTableViewDataSource!
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.


        self.dataSource = FirebaseTableViewDataSource(ref: self.firebaseRef, cellReuseIdentifier: "myCell", view: self.tableView)

        self.dataSource.populateCellWithBlock { (cell: UITableViewCell, obj: NSObject) -> Void in
            let snap = obj as! FDataSnapshot

            cell.textLabel?.text = snap.key as String
        }

        self.tableView.dataSource = self.dataSource;
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }


}
```

**Comment by jayantsingh924** [comment]
import UIKit

class ViewController: UIViewController {

    
    var tableArray = [String] ()
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
    }
    
    func parseJSON() {
        let url = URL(string: "https://api.myjson.com/bins/vi56v")
        
        let task = URLSession.shared.dataTask(with: url!) {(data, response, error) in
            
            guard error == nil else {
                print("returning error")
                return
            }
            
            guard let content = data else {
                print("not returning data")
                return
            }
            
            
            guard let json = (try? JSONSerialization.jsonObject(with: content, options: JSONSerialization.ReadingOptions.mutableContainers)) as? [String: Any] else {
                print("Not containing JSON")
                return
            }
            
            if let array = json["companies"] as? [String] {
                self.tableArray = array
            }
            
            print(self.tableArray)
            
            DispatchQueue.main.async {
                self.tableView.reloadData()
            }
            
        }
        
        task.resume()
        
    }


}

**Comment by jayantsingh924** [comment]
i,m getting the same error here
