### ISSUE TITLE
iOS 11 beta crash loading NIB for FUIPhoneEntryViewController

### ISSUE THREAD

**Issue by martinc** [firebase/FirebaseUI-iOS#322]
* Objective C or Swift: Swift
  * iOS version: iOS 11.0 (15A5354b)
  * Firebase SDK version: 4.0.4
  * FirebaseUI version: 4.1.1
  * CocoaPods Version: 1.3.1
  
### Step 3: Describe the problem:

Starting phone authentication causes a crash with the following message:

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle <...> (loaded)' with name 'FUIPhoneEntryViewController''

#### Steps to reproduce:

  1. Press a button to start phone auth flow on iOS 11 beta
  
#### Observed Results:

  1. It crashes before the phone auth view appears
  
#### Expected Results:

  1. Phone auth view should appear
  
#### Relevant Code:

  ```
        let authUI = FUIAuth.defaultAuthUI()!
        authUI.delegate = self
        let phoneAuth = FUIPhoneAuth(authUI: authUI)
        authUI.providers = [phoneAuth]
        phoneAuth.signIn(withPresenting: presentingController)
  ```

**Comment by martinc** [comment]
This seems to be an issue with the new build system in Xcode 9 beta 4, where it was having an issue running the CocoaPods Copy Resources script. I switched it to the legacy build system in Workspace Settings and the script is running again.

**Comment by sanchofox** [comment]
@martinc can you explain with more details how to fix this issue? I didn't understand the steps you did. If you can attach some images it would be perfect.

Thanks a lot
