### ISSUE TITLE
swift and obj-c sample are both can't build.

### ISSUE THREAD

**Issue by zip520123** [firebase/FirebaseUI-iOS#323]
Objective C & swift
iOS version: 8.0
Firebase SDK version: 4.0
FirebaseUI version: 4.0
CocoaPods Version: 1.2.0.beta.1
Xcode 8.3.2

I clone the whole project, install pods and build then fail.
How can I do?

There are build log below.

/Users/zip520123/Documents/appfolder/FirebaseUI-iOS/samples/swift/FirebaseUI-demo-swift/Samples/Auth/FUICustomAuthUIDelegate.swift:23:54: Use of undeclared type 'User'
/Users/zip520123/Documents/appfolder/FirebaseUI-iOS/samples/swift/FirebaseUI-demo-swift/Samples/Auth/FUICustomAuthUIDelegate.swift:71:100: Use of undeclared type 'AuthCredential'
/Users/zip520123/Documents/appfolder/FirebaseUI-iOS/samples/swift/FirebaseUI-demo-swift/Samples/StorageViewController.swift:26:32: Use of unresolved identifier 'Storage'
/Users/zip520123/Documents/appfolder/FirebaseUI-iOS/samples/swift/FirebaseStorage.FIRStorage:12:12: Did you mean 'FIRStorage'?
/Users/zip520123/Documents/appfolder/FirebaseUI-iOS/samples/swift/FirebaseUI-demo-swift/Samples/StorageViewController.swift:50:23: Use of unresolved identifier 'Storage'
/Users/zip520123/Documents/appfolder/FirebaseUI-iOS/samples/swift/FirebaseStorage.FIRStorage:12:12: Did you mean 'FIRStorage'?
/Users/zip520123/Documents/appfolder/FirebaseUI-iOS/samples/swift/FirebaseUI-demo-swift/Samples/StorageViewController.swift:26:19: Did you mean 'storageRef'?
/Users/zip520123/Documents/appfolder/FirebaseUI-iOS/samples/swift/FirebaseUI-demo-swift/Samples/Chat/ChatCollectionViewCell.swift:75:49: Use of undeclared type 'User'
/Users/zip520123/Documents/appfolder/FirebaseUI-iOS/samples/swift/FirebaseUI-demo-swift/Samples/Auth/FUIAuthViewController.swift:55:45: Use of undeclared type 'AuthStateDidChangeListenerHandle'
/Users/zip520123/Documents/appfolder/FirebaseUI-iOS/samples/swift/FirebaseUI-demo-swift/Samples/Auth/FUIAuthViewController.swift:57:30: Use of undeclared type 'Auth'
/Users/zip520123/Documents/appfolder/FirebaseUI-iOS/samples/swift/FirebaseUI-demo-swift/Samples/Auth/FUIAuthViewController.swift:142:54: Use of unresolved identifier 'PhoneAuthProviderID'
/Users/zip520123/Documents/appfolder/FirebaseUI-iOS/samples/swift/FirebaseUI-demo-swift/Samples/Auth/FUIAuthViewController.swift:142:54: Did you mean 'FIRGoogleAuthProviderID'? (FirebaseAuth.FIRGoogleAuthProviderID)
/Users/zip520123/Documents/appfolder/FirebaseUI-iOS/samples/swift/FirebaseUI-demo-swift/Samples/Auth/FUIAuthViewController.swift:156:23: Use of undeclared type 'Auth'
/Users/zip520123/Documents/appfolder/FirebaseUI-iOS/samples/swift/FirebaseUI-demo-swift/Samples/Auth/FUIAuthViewController.swift:156:35: Use of undeclared type 'User'

**Comment by morganchen12** [comment]
I'm unable to reproduce this error. Can you try updating Xcode to 8.3.3 and CocoaPods to 1.3.1 and run `pod update`?
