### ISSUE TITLE
  "_FIRPhoneAuthProviderID", referenced from: 

### ISSUE THREAD

**Issue by Cristy4** [firebase/FirebaseUI-iOS#325]
Hi, I get this error, I want to sign with phone and use FirebasePhoneAuthUI and FirebaseUI.
Downgrade   pod 'TwitterCore', '~>2.8.0' to fix the linker command failed with exit code 1 but the errors continue,
![captura de pantalla 2017-08-22 a la s 11 49 58](https://user-images.githubusercontent.com/30754740/29577156-11a0121e-8730-11e7-8dfc-033d198bbc2e.png)
 somebody can help me?

**Comment by morganchen12** [comment]
What version of Xcode/CocoaPods are you using? This doesn't seem to be an error related to TwitterCore.

Can you upload a sample project with this issue?

**Comment by Cristy4** [comment]
Xcode 8.3.2 and Cocoapods 1.2.0

**Comment by morganchen12** [comment]
Can you update your CocoaPods to 1.3.1 and retry?

**Comment by Cristy4** [comment]
I have problems with update cocoa pods, the error says that  Could not find 'cocoapods' (>= 0.a) among 7 total gem(s) (Gem::MissingSpecError). I'm trying to fixed

**Comment by Cristy4** [comment]
I've try, but still not working, any idea?

**Comment by morganchen12** [comment]
Can you share your project? Also, make sure you're using the generated xcworkspace and not the xcproject file.

**Comment by Cristy4** [comment]
the project is private, I don't have permission to share it, but you have some example to authenticate with phone in swift 3

**Comment by morganchen12** [comment]
Take a look at the [provided samples ](https://github.com/firebase/FirebaseUI-iOS/tree/master/samples).

I'm going to close this issue as it's an integration issue with no repro steps. If you have a sample project that demonstrates this issue, please share it and reopen the issue.

**Comment by Cristy4** [comment]
Hi, I solved the problem, the firebase was version 3 and the firebaseUI 4, I did update firebase and builded successfully.
Thank you for your answers.

**Comment by gsobrevilla** [comment]
Thank you! you've saved my day. I've run into the same issue. Solve it by setting the Pods' versions, like this:

```
pod 'FirebaseUI/Phone', '~> 4.1.1' 
pod 'Firebase/Auth', '~> 4.0.4'
pod 'Firebase/Core', '~> 4.0.4'
pod 'Firebase/Messaging', '~> 4.0.4'
```
