### ISSUE TITLE
SMS don't received

### ISSUE THREAD

**Issue by Cristy4** [firebase/FirebaseUI-iOS#326]
Objective C or Swift: Swift
iOS version: 10.3.2
Firebase SDK version: 4.1
FirebaseUI version: 4.1.1
CocoaPods Version: 1.3.1

Perform 5 attempts with 2 different numbers and only 1 time I get the message as the third attempt. How can I improve this?

**Comment by yramanchuk** [comment]
@Cristy4 
- What country code you were using?
- Did you get server error after sending phoneVerification request (e g after entering phone number and tapping next)?
- Can you please enable logging and send us server logs? Here sample how to [enabled logs](https://github.com/firebase/FirebaseUI-iOS/blob/master/samples/swift/FirebaseUI-demo-swift/FUIAppDelegate.swift#L33). Path to the logs is shown in the console.

**Comment by yramanchuk** [comment]
Please re-open if issue is reproducible.
