### ISSUE TITLE
Error parameter used when calling didChangeEmail

### ISSUE THREAD

**Issue by zhanglei0321** [firebase/FirebaseUI-iOS#328]
In file [FUIPasswordSignUpViewController.m](https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseAuthUI/FUIPasswordSignUpViewController.m)
textFieldDidChange called didChangeEmail, but the order of the parameters is wrong, 
the password and nickname should be exchanged in order.
like this
`[self didChangeEmail:_emailField.text orPassword:_passwordField.text orUserName:_nameField.text]`

**Comment by morganchen12** [comment]
已修正 c1fac83de2cee0ec274e2d5bffbc9a6d45635a46.

謝謝！

**Comment by zhanglei0321** [comment]
good job!
