### ISSUE TITLE
Is there a way to sort by child value using FirebaseUI?

### ISSUE THREAD

**Issue by psopher** [firebase/FirebaseUI-iOS#33]
I am using FirebaseUI for a table view. I know that using Firebase, I can sort by child value, but I can't figure out how to do this using FirebaseUI. Is it possible?

**Comment by mcdonamp** [comment]
@psopher You can simply pass in a query instead of a reference in any of the constructors, for instance:

```objective-c
Firebase *query = [[rootRef queryOrderedByChild:@"foo"] queryEqualToValue:@"bar"];
FirebaseTableViewDataSoource *dataSource = [[FirebaseTableViewDataSource alloc] initWithQuery:query ...];
```

See https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseUI/Core/API/FirebaseTableViewDataSource.h#L243-L391 for the method signatures.
