### ISSUE TITLE
Pulling "Enter Phone Number" screen up leads to country getting copied in Number field

### ISSUE THREAD

**Issue by anup2812013** [firebase/FirebaseUI-iOS#330]
### Step 2: Describe your environment

  * iOS version: _10.3.2____
  * Firebase SDK version: _4.1.1____
  * FirebaseUI version: __4.2.0__
 FirebaseAnalytics 4.0.3
 FirebaseAuth 4.1.1
 FirebaseCore 4.0.6
 FirebaseInstanceID 2.0.2 
* CocoaPods Version: __1.3.0__
  
### Step 3: Describe the problem:
Whenever "Enter Phone Number" screen is scrolled up on seeing it for 1st time, Country code gets copied in phone number field. It can be deleted but if we click Cancel button at this point, it leads to keypad not disappearing on next screen.

#### Steps to reproduce:

  1. __Get the "Enter Phone Number" screen.
![number field](https://user-images.githubusercontent.com/31729731/30160016-5882bb36-93e8-11e7-85d8-fbf0fef63352.jpg)

  2. __Scroll the screen up.
  3. Observe that Number field gets populated with Country code.
4.At this point if you click Cancel button, the keypad doesn't disappear.
5.Make sure the number field too disappears when the "Enter Phone Number" page is pulled above.
  
#### Expected Results:

On scrolling the screen above, the country code should not get populated in number field.
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by morganchen12** [comment]
@yramanchuk seems we're missing a `resignFirstResponder` call on cancellation.

**Comment by yramanchuk** [comment]
@anup2812013 Thanks for you report.
I've fixed loading of country code.

Unfortunately I can't reproduce your issue with keyboard.
@anup2812013 Can you please provide more detailed steps about that case (preferably on the latest FirebaseUI version) and info how you're calling phone auth.

@morganchen12 Yes, resigning first responder should help, but entire controller is dismissed, so we should hide keyboard. Let's wait for more detailed steps.

**Comment by anup2812013** [comment]
@yramanchuk I won't be able to reproduce it now as we have changed our app flow.
