### ISSUE TITLE
compress png files error

### ISSUE THREAD

**Issue by jadslim313** [firebase/FirebaseUI-iOS#331]
### Step 2: Describe your environment

  * Objective C or Swift: swift
  * iOS version: 10
  * Firebase SDK version: 4.1.1
  * FirebaseUI version: 4.2.0
  * CocoaPods Version: ____
  
### Step 3: Describe the problem:
I keep getting this error whenever I try to run the app:

> xcrun: error: unable to find utility "pngcrush", not a developer tool or in PATH
> Can't exec "": No such file or directory at /Applications/Xcode-beta.app/Contents/Developer/usr/bin/copypng line 89.

> ERROR: Failed to run  -q -iphone -f 0 -rem text /Users/rayanslim/Desktop/fosterway/Pods/FirebaseUI/FirebaseUIFrameworks/FirebaseAuthUI/Frameworks/FirebaseAuthUI.framework/ic_email@2x.png /Users/rayanslim/Library/Developer/Xcode/DerivedData/fosterWayLogin-dvaavqnabtfzczgqktizkugpvodc/Build/Products/Debug-iphoneos/FirebaseUI/FirebaseAuthUI.bundle/ic_email@2x.png
> Command /Applications/Xcode-beta.app/Contents/Developer/usr/bin/copypng failed with exit code 255

#### Steps to reproduce:

Run App with firebase Auth

  
<img width="273" alt="screen shot 2017-09-07 at 1 25 27 pm" src="https://user-images.githubusercontent.com/12466304/30177468-f1195964-93d3-11e7-9e84-b4e131da6b57.png">
#### Observed Results:

This randomly started happening, and only happens when firebaseUI is installed. I have no clue what is causing it.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by morganchen12** [comment]
`pngcrush` is a standard utility that comes with Xcode, and is used by Xcode to package all png files when bundling apps or frameworks. You can check that Xcode can find it by running `xcrun pngcrush -h` in terminal. If Xcode can't find this utility you'll get errors elsewhere too, not just when using Firebase.

I'm not sure why Xcode would be unable to find `pngcrush`, as iirc it's usually bundled with Xcode. Maybe try reinstalling Xcode?
