### ISSUE TITLE
Firebase phone auth doesn't send SMS if number is different from device's phone number.

### ISSUE THREAD

**Issue by nitesh-homage** [firebase/FirebaseUI-iOS#337]
Hey guys I am trying to implement firebase phone auth but it doesn't work if I try to send SMS to number other than device's number. Is this something firebase doesn't support. Please help me this issue is killing me. 

  * Swift
  * iOS version: 10.3.3
  * FirebaseUI version: 4.0

If the number is same as device's number I receive notification and its fine but if I use any other number then it doesn't work. 

Please help 🙏🏻

**Comment by morganchen12** [comment]
Are you expecting to send a phone number to a different device than the one that requested it? What use case are you trying to accommodate?

**Comment by nick-potts** [comment]
Note that phone verification doesn't work in the simulator.

**Comment by yramanchuk** [comment]
@nitesh-homage Please use latest FirebaseUI 4.3.0
Can you please provide error you've got from FirebaseUI?

Can you please enable GTMSessionFetcher https://github.com/firebase/FirebaseUI-iOS/blob/master/samples/swift/FirebaseUI-demo-swift/FUIAppDelegate.swift#L33

GTMSessionFetcher logs all requests to server side. Please attach them.
Path to the logs is added to Xcode console.

**Comment by nitesh-homage** [comment]
Hello Yuri,

It worked for me now. I checked it. But Implemented my own UI. As I couldn’t compile the code for Firebase UI repo (Swift)

Thanks
Nitesh
