### ISSUE TITLE
Unable to run FirebaseUISample.

### ISSUE THREAD

**Issue by mohdabdurraafay** [firebase/FirebaseUI-iOS#342]
It seems like one of the dependencies, `FirebaseAuth` isn't being cleared fully as needed by the FirebaseUISample target. The file `FIRAuthUIDelegate.h` seems to have been ignored by the dependent pod.spec. I tried digging in through, but since it's the pod.spec which is being managed by the other repo, makes it little challenging.

Running on Xcode 9, Swift 3.
  
Just simply, clone the repo and run `pod install` followed by running the project. You'll see Xcode complaining about the `FIRAuthUIDelegate.h` file not found.

I should able to run the sample app with no issues, since I just wanna explore the FirebaseUI-iOS suite.

**Comment by morganchen12** [comment]
Running a pod update should solve this. FirebaseAuthUI now depends on the most recent version of FirebaseAuth, which wasn't released until recently.
