### ISSUE TITLE
Cannot verify the number using OTP

### ISSUE THREAD

**Issue by sidjdev** [firebase/FirebaseUI-iOS#345]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If your issue concerns the CocoaPods error, "...transitive dependencies that include static binaries", please take a look at any of the following issues and see if your problem is solved: #48, #47, #46, #34, #23.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?
Yes
  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Objective C or Swift: 3_2___
  * iOS version: 11_0_1___
  * Firebase SDK version: _____
  * FirebaseUI version: 4_3_1__
  * CocoaPods Version: 1_2_1__
  
### Step 3: Describe the problem:
When I entered the phone number for authentication, I got a UIAlert saying "Something went wrong. Please try again later"
#### Steps to reproduce:

  1. Enter the phone number required, in the PhoneUI
  2. Click Verify
  3. Alert pops up
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.
An alert saying "Something went wrong, please try again" pops up

Nothing much is shown in the Console except-

**Can't find keyplane that supports type 4 for keyboard iPhone-PortraitChoco-NumberPad; using 4072550144015629828_PortraitChoco_iPhone-Simple-Pad_Default**
  
#### Expected Results:

  * What did you expect to happen?
Expected it to send an OTP for verification
  
#### Relevant Code:

 ```
func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data)
    {
        Auth.auth().setAPNSToken(deviceToken, type: AuthAPNSTokenType.prod)
     }
```
```
 func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        

        
        if Auth.auth().canHandleNotification(userInfo) {
            completionHandler(UIBackgroundFetchResult.noData)
            return
        }

}
  ```
In ViewController-

   ```
 let authUI = FUIAuth.defaultAuthUI()
    let providers: [FUIAuthProvider] = [FUIPhoneAuth(authUI:FUIAuth.defaultAuthUI()!)]
```
 ```
func proceedToFirebaseAuth()
    {
        let providers: [FUIAuthProvider] = [FUIPhoneAuth(authUI:FUIAuth.defaultAuthUI()!)]
        authUI?.providers = providers
        let phoneAuth = FUIPhoneAuth.init(authUI: authUI!)
        phoneAuth.signIn(withPresenting: self, phoneNumber: mobNumber)
    }
```

  // TODO(you): code here to reproduce the problem
  ```

**Comment by yramanchuk** [comment]
I guess that problem is that you are creating to instances of `FUIPhoneAuth`
First one here:
> let providers: [FUIAuthProvider] = [FUIPhoneAuth(authUI:FUIAuth.defaultAuthUI()!)]

Second here:
> let phoneAuth = FUIPhoneAuth.init(authUI: authUI!)

You can use this sample to sign in with Phone Auth:

```
// Init code:
    FUIAuth.defaultAuthUI()?.delegate = self
    let phoneProvider = FUIPhoneAuth.init(authUI: FUIAuth.defaultAuthUI()!)
    FUIAuth.defaultAuthUI()?.providers = [phoneProvider]

```
```
 func proceedToFirebaseAuth(=) {
    let phoneProvider = FUIAuth.defaultAuthUI()?.providers.first as! FUIPhoneAuth
    phoneProvider.signIn(withPresenting: self, phoneNumber: nil)
  }
```

BTW, if you are not doing anything else in `didRegisterForRemoteNotificationsWithDeviceToken` and `didReceiveRemoteNotification` that just delete them: FirebaseAuth with dynamically add that code for you.

@sidjdev Please let me know if that helped you.

**Comment by bfjfm2** [comment]
I am having the same problem. Any solution?

**Comment by Vinaykumar-dev** [comment]
@yramanchuk 
Solution you provided above also didn't work. 

Does anyone know the root cause for the above issue? Many are facing this issue including me, Please let us know if anyone know the solution for this.
