### ISSUE TITLE
gRPC warnings in FirebaseUI/Firestore

### ISSUE THREAD

**Issue by morganchen12** [firebase/FirebaseUI-iOS#346]
gRPC and its subdependencies bring in several new warnings (Pointer not aligned, Control may reach end of non-void function). This is something they are aware of, and will likely fix within the next few weeks.

The latter warning may be promoted to an error by newer versions of CocoaPods/Xcodeproj. If you're running into this, you can fix it by running `pod update` and ensuring your `gRPC-Core` pod version is `1.6.5` or higher.

**Comment by unittesting0** [comment]
@morganchen12 
```
Installing gRPC (1.6.5)
Installing gRPC-Core (1.6.5)
Installing gRPC-ProtoRPC (1.6.5)
Installing gRPC-RxLibrary (1.6.5)
```

And I'm getting these 24 errors:

https://i.imgur.com/3kC8tHx.png

**Comment by morganchen12** [comment]
@unittesting0 can you expand those errors and paste them here or share a project that reproduces the issue? What CocoaPods and Xcode versions are you using?

**Comment by elmateo487** [comment]
@morganchen12  I think this is closed, but I am having the same issue. But the problem is I am not using Cocoapods, I manually linked everything using the guide here [https://firebase.google.com/docs/ios/setup](url). "Integrate without CocoaPods"

I am on Xcode 9.0.1, with a target of iOS 11.

So are the linked frameworks out of date? [https://firebase.google.com/download/ios](url) Firebase 4.4?

**Comment by morganchen12** [comment]
@elmateo487 yours is a different issue than this one, and lies in upstream Firestore. I'm not sure what the timeline is for resolving it. Those warnings are harmless (though annoying), and you should be able to ignore them for now.

**Comment by unittesting0** [comment]
![screen shot 2018-01-03 at 12 07 58 pm](https://user-images.githubusercontent.com/17980890/34518577-389f1108-f080-11e7-958a-ba9f649add41.png)

I tried in a new project, same issue.
Used Xcode 8.3.3 , 9.0, 9.1 - same issue.
pod repo update - same issue

How can I resolve this issue.

**Comment by unittesting0** [comment]
![screen shot 2018-01-03 at 12 07 58 pm](https://user-images.githubusercontent.com/17980890/34518577-389f1108-f080-11e7-958a-ba9f649add41.png)

I tried in a new project, same issue.
Used Xcode 8.3.3 , 9.0, 9.1 - same issue.
pod repo update - same issue

How can I resolve this issue.

**Comment by morganchen12** [comment]
What's the contents of your Podfile.lock?
