### ISSUE TITLE
Is it possible to remove the 'Sign in with Email' option?

### ISSUE THREAD

**Issue by dilizarov** [firebase/FirebaseUI-iOS#349]
For my app, users only login through phone number. This was great on Digits, but now I'm migrating over. I don't really like the UX this offers so I might just rebuild Digits UX, but assuming I do use FirebaseUI, it doesn't seem like I can get rid of the Email sign-in option.

How do I remove this?

**Comment by axelsoedarsono** [comment]
https://stackoverflow.com/questions/42344885/how-to-remove-sign-in-with-email-from-firebase-auth-in-objective-c @dilizarov 

btw, r you migrating to firebase using objective c ?? 

im still confused how to implement it FirebasePhoneAuth, any suggestion or project example to implement in objective c ?? thanks in advance!
