### ISSUE TITLE
Can't remove dataSource observer in viewDidDisapear

### ISSUE THREAD

**Issue by zhubofei** [firebase/FirebaseUI-iOS#35]
In [This firebase official blog](https://www.firebase.com/blog/2015-10-15-best-practices-uiviewcontroller-ios-firebase.html), the article suggests that we need to remove observer in viewDidDisappear. Should we do that with firebaseDataSource? If yes, how?

**Comment by mcdonamp** [comment]
@zhubofei Good reading, and glad you found that post helpful.

We handle observer cleanup in FirebaseArray in it's `- (void)dealloc` method [here]( https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseUI/Core/Implementation/FirebaseArray.m#L60-L64), so we shouldn't have to do anything in any of the other methods, as FirebaseArray should be cleaned up after the view disappears taking those listeners with it.

**Comment by zhubofei** [comment]
Great! Thx.
