### ISSUE TITLE
FUIFirestoreCollectionViewDataSource Cannot convert value of type 'Query' to expected argument type 'DatabaseQuery'

### ISSUE THREAD

**Issue by adornoventura** [firebase/FirebaseUI-iOS#353]
* Swift
  * iOS 10.3
  * Firebase SDK version: 4.3
  * FirebaseUI version: 4.4
  * CocoaPods Version: 1.2
  
### Describe the problem:

When using the FirebaseFirestoreUI CollectionView binding to bind a query the .bind method says it takes a parameter of type "Query", however, when building an error appears saying it cannot convert type "Query" to expected type of "DatabaseQuery". It seems as if somehow it is mixing the Realtime Database Query with the Firestore Query, even though the underlying method does in fact take type Query not DatabaseQuery.

#### Steps to reproduce:

  1. Create FUIFirestoreCollectionViewDataSource variable
  2. Create/setup CollectionView
  3. Assign datasource variable to collectionView.bind method
  
#### Observed Results:

Error: Cannot convert value of type 'Query' to expected argument type 'DatabaseQuery' on datasource assignment line.
  
#### Expected Results:

No error.

#### Relevant Code:

        let forSaleQuery = Firestore.firestore().collection(Const.users).document(user!.uid).collection(Const.books).whereField("isActive", isEqualTo: true)

        self.forSaleDataSource = forSaleCollectionView.bind(to: forSaleQuery) { collectionView, indexPath, snap in
            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "reuseIdentifier", for: indexPath)
            return cell
        }

**Comment by morganchen12** [comment]
The method signature is the same in both FirestoreUI and DatabaseUI. Can you check that you only have FirestoreUI installed (and imported) and not DatabaseUI?

The [header file](https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseFirestoreUI/FUIFirestoreCollectionViewDataSource.h) seems to have the right types.

**Comment by adornoventura** [comment]
I only had FirebaseFirestoreUI imported to that file but I still had the FirebaseDatabaseUI pod installed and it was causing it to look for the database method signature instead of the Firestore one. However, I thought the RTDB and Firestore could co-exist within one project? I had to completely remove the RTDB pods in order to clear up that error.

**Comment by morganchen12** [comment]
That was our original intention, but I messed up one of the selectors so it's no longer the case.

**Comment by morganchen12** [comment]
This should be fixed now. The new selector for FirebaseFirestoreUI is `bindToFirestoreQuery:`
