### ISSUE TITLE
CRASH USING PRHONE AUTH

### ISSUE THREAD

**Issue by expertalex** [firebase/FirebaseUI-iOS#357]
When Using Phone Auth ONLY!

***
    [FUIAuth defaultAuthUI].delegate = self; // delegate should be retained by you!
    FUIPhoneAuth *phoneProvider = [[FUIPhoneAuth alloc] initWithAuthUI:[FUIAuth defaultAuthUI]];
    [FUIAuth defaultAuthUI].providers = @[phoneProvider];
***
    FUIPhoneAuth *provider = self.authUI.providers.firstObject;
    [provider signInWithPresentingViewController:self phoneNumber:nil];
****

I have this error:

2017-10-20 00:28:42.348022+0200 TalkerMessenger[383:35203] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Please register custom URL scheme 'com.googleusercontent.apps.365129796748-7phob5uk0lm0t50kq4a916n50518i43s' in the app's Info.plist file.'
*** First throw call stack:
(0x183cafd38 0x1831c4528 0x183cafc80 0x104ee7d98 0x1050604d4 0x105060300 0x18d0f420c 0x18da8d650 0x18da8d578 0x18d0f420c 0x18d0f418c 0x18d0def4c 0x18d0f3a80 0x18d0f35a0 0x18d0eea70 0x18d0c0078 0x1a2990b58 0x18d9fff98 0x18da02408 0x18d9fb574 0x183c58358 0x183c582d8 0x183c57b60 0x183c55738 0x183b762d8 0x185a07f84 0x18d123880 0x1043b1a80 0x18369a56c)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by morganchen12** [comment]
Have you tried adding that URL scheme to your project? See [this doc](https://developers.google.com/identity/sign-in/ios/start-integrating) under 'Add a URL scheme to your project'.
