### ISSUE TITLE
Phone authentication failing on iOS simulator.

### ISSUE THREAD

**Issue by CoderXpert** [firebase/FirebaseUI-iOS#358]
### Step 2: Describe your environment

  * Swift: 3.2
  * iOS version: 11.0/10.3 
  * Firebase SDK version: 4.4.0
  * FirebaseUI version: 4.5.0
  * CocoaPods Version: 1.2.0
  
### Step 3: Describe the problem:
Phone authentication is not working on simulator.
I have added the firebase_reverse_client_id in the url schemes, but keep getting following error.

```
Verificaiton error: Error Domain=FIRAuthErrorDomain Code=17053 "There seems to be a problem with your project's Firebase phone number authentication set-up, please make sure to follow the instructions found at https://firebase.google.com/docs/auth/ios/phone-auth" UserInfo={error_name=ERROR_MISSING_APP_TOKEN, NSLocalizedDescription=There seems to be a problem with your project's Firebase phone number authentication set-up, please make sure to follow the instructions found at https://firebase.google.com/docs/auth/ios/phone-auth, NSUnderlyingError=0x604000e4db90 {Error Domain=NSCocoaErrorDomain Code=3010 "remote notifications are not supported in the simulator" UserInfo={NSLocalizedDescription=remote notifications are not supported in the simulator}}}
```
#### Steps to reproduce:

Try to signup with phone authentication
  
#### Observed Results:

  *Authentication failed 
  
#### Expected Results:

  * Use should signup successfully

**Comment by dilizarov** [comment]
Glad this was answered.

**Comment by morganchen12** [comment]
Hey all,

This is an issue in upstream FirebaseAuth, not FirebaseUI. I've made a PR there (https://github.com/firebase/firebase-ios-sdk/pull/742) addressing this.

Thanks for your patience!

**Comment by morganchen12** [comment]
@CoderXpert @dilizarov can either of you share a project that reproduces this?

**Comment by nezhyborets** [comment]
By looking here https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebasePhoneAuthUI/FUIPhoneEntryViewController.m

we can see that `verifyPhoneNumber:UIDelegate:completion:` is being called, but I still get the following error
> Error Domain=NSCocoaErrorDomain Code=3010 "remote notifications are not supported in the simulator" UserInfo={NSLocalizedDescription=remote notifications are not supported in the simulator}

**Comment by morganchen12** [comment]
@nezhyborets there's not enough information here to debug your error.

This issue is going off topic; please file a new issue with repro steps or a project attached that we can debug if you're still seeing this error.
