### ISSUE TITLE
Can we customise the UINavigationBar

### ISSUE THREAD

**Issue by hamzahrmalik** [firebase/FirebaseUI-iOS#360]
If i try to change the colour using 

self.navigationController?.navigationBar.tintColor

From within a custom FUIAuthPickerController

Nothing changes. Is some base class blocking this? Why?

**Comment by morganchen12** [comment]
How are you presenting the controller?

Are you able to set the bar color globally with `UINavigationBar.appearance()`?

**Comment by hamzahrmalik** [comment]
I'm presenting it using 

        let authUI = FUIAuth.defaultAuthUI()
        var providers: [FUIAuthProvider] = [
            FUIGoogleAuth(),
            FUIFacebookAuth()
        ]
        authUI?.providers = providers
        authUI?.delegate = self
        
        if let vc = authUI?.authViewController() {
            present(vc, animated: false, completion: nil)
        }

I have found that I can customise the nav bar during viewDidAppear, i was previously trying in viewDidLoad

**Comment by anelad** [comment]
`FUIAuth.authViewController()` returns an UINavigationController. So you can do it like this:

```
guard let authUI = FUIAuth.defaultAuthUI() else { return }
let authController = authUI.authViewController()
authController.navigationBar.barTintColor = .red
```

Also, you can use `UIAppearence`.

In your `application:didFinishLaunchingWithOptions:` do:
```
UINavigationBar.appearance().barTintColor = .red
```
