### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by antonijap** [firebase/FirebaseUI-iOS#365]
Social login buttons have a controller that appears when you want it. Is it possible that these buttons are present immediately in my ie. 'LoginViewController'. I would like to have one screen for login so I am trying to find a way.

**Comment by morganchen12** [comment]
Not quite sure what you're requesting here. Would you like drop-in login buttons that can be used outside of the FirebaseUI Auth flow?

**Comment by antonijap** [comment]
Or is it possible to use it as an initial screen. Currently, I have an empty screen and then I present this one. Seems super unnecessary. Sorry if I am asking a stupid question, I am just starting to dig in this nice library.

**Comment by morganchen12** [comment]
It's currently not usable as an initial screen. @yramanchuk was considering this feature at one point, but hasn't implemented it yet.

**Comment by antonijap** [comment]
How did you imagine a flow? This part is unclear to me. Should I have some button on the first screen that triggers this controller, or should I remove cancel and put some image?

**Comment by morganchen12** [comment]
For now, you can present the auth controller modally when your app is launched and disable the cancel button.
