### ISSUE TITLE
How to obtain the verificationID when using FUIPhoneAuth in order to re-authenticate a user

### ISSUE THREAD

**Issue by wayneforrest** [firebase/FirebaseUI-iOS#366]
I want to deregister a user, but this requires a recent authentication to have taken place.

In order to deregister the user I first need to re-authenticate the user which requires
FIRAuthCredential parameter.

`[user reauthenticateWithCredential:credential completion:^(NSError *_Nullable error) {`

Firebase [doc](https://firebase.google.com/docs/auth/ios/phone-auth) mentions that one should save FIRAuthCredential  when a delegate gets called.
```
[[FIRPhoneAuthProvider provider] verifyPhoneNumber:userInput
                                        UIDelegate:nil
                                        completion:^(NSString * _Nullable verificationID,
```

I have used FUIPhoneAuth with `signInWithPresentingViewController:` and did not receive a FIRAuthCredential upon registration.

How do I get hold of the FIRAuthCredential in order to deregister a user?

**Comment by wayneforrest** [comment]
I have posted this question on stackoverflow located [here.](https://stackoverflow.com/questions/47311502/how-to-deregister-firebase-user-when-registered-using-fuiphoneauth)

**Comment by morganchen12** [comment]
@wayneforrest closing since it seems your StackOverflow question was answered. If you still have issues, feel free to reopen.
