### ISSUE TITLE
Expected declaration of FUICustomAuthDelegate.swift

### ISSUE THREAD

**Issue by ranahaani** [firebase/FirebaseUI-iOS#369]
I'm facing build time error, declaration of FUICustomAuthDelegate function
![error](https://user-images.githubusercontent.com/28961554/33304023-34f242b0-d428-11e7-99c3-968a88031b1e.png)

**Comment by morganchen12** [comment]
Fixed in https://github.com/firebase/FirebaseUI-iOS/commit/f504bd46ab20ff574edd3999be6163b544c02d89,

Thanks!
