### ISSUE TITLE
Add UI for User Registration

### ISSUE THREAD

**Issue by Vortec4800** [firebase/FirebaseUI-iOS#37]
It seems that the user can use this UI to log in to an existing account, but not register for a new one. Is that correct? I think having new-user flow that integrates with this login UI will be very important for apps where users need to sign up accounts.

**Comment by mcdonamp** [comment]
Yes, this is correct--we picked a pretty simple flow here (existing accounts only, with a focus on social providers, whose registration flows may be different).

We're working on some improvements to the flow that would add this (along with things like password recovery), so stay tuned for more :)

**Comment by Vortec4800** [comment]
That would be great - looking forward to it!

**Comment by mcdonamp** [comment]
This has been added with the new AuthUI components in 0.4.0

**Comment by smorin** [comment]
Seems like adding any of this is not there
