### ISSUE TITLE
Who is writing FirebaseUI-iOS, contributors or Google Employees? 

### ISSUE THREAD

**Issue by SpaHaDow** [firebase/FirebaseUI-iOS#370]
This git repo has so many contributors it is hard to tell who wrote the code and if any of it is reliable.

Who is writing FirebaseUI-iOS, contributors?, Google Employees? or both?

There is a license agreement that must be distributed with the ap. Seems like a grab bag of code owned by everybody here.

I am afraid to use any of this unless I see some kind of explanation from a Google Employee.

Thanks in advance.

**Comment by morganchen12** [comment]
All contributors are either Google employees or 3rd party developers who have signed a [CLA](https://cla.developers.google.com/about/google-individual) allowing Google to use their code as part of this repository.
