### ISSUE TITLE
FirebaseAuthUI works only with the default Firebase app, and not support multiple Firebase apps

### ISSUE THREAD

**Issue by v-lavrentikov** [firebase/FirebaseUI-iOS#371]
The problem exists in the latest version of the Firebase SDK downloaded via CocoaPods.

In the application I use two Firebase applications for the dev and prod environment.

I use the next Swift code for initializing AuthUI with Google accounts, where "app" is the previously configured Firebase app:

```
authUI = FUIAuth(uiWith: Auth.auth(app: app))!
assert(authUI != nil)
authUI.delegate = self
authUI.providers = [FUIGoogleAuth()]
```

I receive exception after calling authViewController method from the FUIAuth instance

`let controller = authUI.authViewController()`

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The default FIRApp instance must be configured before the default FIRAuthinstance can be initialized. One way to ensure that is to call `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) in the App Delegate's `application:didFinishLaunchingWithOptions:` (`application(_:didFinishLaunchingWithOptions:)` in Swift).'

After the short analysis of the FirebaseAuthUI I found the problem in the FUILocalizedStringFromTableInBundle function, that calls default FUIAuth instance [FUIAuth defaultAuthUI]. This function is called from the FUIGoogleAuth.signInLabel method, that called from FUIAuthSignInButton.initWithFrame:providerUI: method.

```
NSString *FUILocalizedStringFromTableInBundle(NSString *key,
                                              NSString *table,
                                              NSString *_Nullable bundleName) {
  
  NSBundle *customStringsBundle = [FUIAuth defaultAuthUI].customStringsBundle;
  if (customStringsBundle) {
    NSString *localizedString = [customStringsBundle localizedStringForKey:key
                                                                     value:kKeyNotFound
                                                                     table:table];
    if (![kKeyNotFound isEqual:localizedString]) {
      return localizedString;
    }
  }
  NSBundle *frameworkBundle = [FUIAuthUtils bundleNamed:bundleName];
  return [frameworkBundle localizedStringForKey:key value:nil table:table];
}
```

Also after the analysis of the FirebaseAuthUI and FirebaseGoogleAuthUI I found some references to default Firebase instanses such as: [FUIAuth defaultAuthUI], [FIRApp defaultApp]. They may cause the problems in the future:

FUIStaticContentTableViewController.m

```
- (instancetype)initWithContents:(nullable FUIStaticContentTableViewContent *)contents
                       nextTitle:(nullable NSString *)actionTitle
                      nextAction:(nullable FUIStaticContentTableViewCellAction)nextAction
                      headerText:(nullable NSString *)headerText
                      footerText:(nullable NSString *)footerText
                    footerAction:(nullable FUIStaticContentTableViewCellAction)footerAction {
  if (self = [super initWithNibName:NSStringFromClass([self class])
                             bundle:[FUIAuthUtils bundleNamed:FUIAuthBundleName]
authUI:[FUIAuth defaultAuthUI]]) {
```

FUIGoogleAuth.m

```
- (GIDSignIn *)configuredGoogleSignIn {
  GIDSignIn *signIn = [GIDSignIn sharedInstance];
  signIn.delegate = self;
  signIn.uiDelegate = self;
  signIn.shouldFetchBasicProfile = YES;
  signIn.clientID = [[FIRApp defaultApp] options].clientID;
  signIn.scopes = _scopes;
  return signIn;
}
```

**Comment by morganchen12** [comment]
For now can you work around this by manually naming your non-default app `__FIRAPP_DEFAULT`?

**Comment by v-lavrentikov** [comment]
Now I work with the prototype app, so in the nearest future I can work only with default app.

**Comment by fabiotk** [comment]
I have a similar issue.

I'm building an SDK with the purpose of separate my entire login/auth logic of all apps that I have.
I have a same login/auth logic for many apps.

The initialization is inside the SDK, and I think that will be a good approach that my custom SDK initialize the Firebase Auth as a second project, and not the default project of the firebase inside the application.

When I try to do the UI sign in, the app crash and tell me that it doesn't have a Firebase Default configuration.

Do you guys have some tip for this case?

This is the error that was printed:
2018-04-25 11:53:20.658752-0300 testes[15665:3908086] 4.13.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
2018-04-25 11:53:20.710201-0300 testes[15665:3907986] *** Terminating app due to uncaught exception 'com.firebase.core', reason: '`[FIRApp configure];` (`FirebaseApp.configure()` in Swift) could not find a valid GoogleService-Info.plist in your project. Please download one from https://console.firebase.google.com/.'


Thanks!

**Comment by morganchen12** [comment]
Expose the initialize call in your wrapped SDK and call it before calling any other Firebase SDK methods.

**Comment by fabiotk** [comment]
@morganchen12 Could you please show me an example of how do this wrapped SDK? I'm trying to solve this problem since last week and nothing works

**Comment by morganchen12** [comment]
This will be fixed partially in the next release. It'll no longer cause crashes, but may not correctly load strings from your bundled FUIAuth instances.

**Comment by morganchen12** [comment]
Closing for now. If you run into strings issues, please comment here.
