### ISSUE TITLE
Updating UI on non-main Thread

### ISSUE THREAD

**Issue by mrugeshtank** [firebase/FirebaseUI-iOS#372]
* Objective C or Swift:  Swift
  * iOS version: 10.2.1
  * Firebase SDK version: 4.4.0
  * FirebaseUI version: 4.5.0
  * CocoaPods Version: 1.3.1

Getting crash on some devices while presenting FirebaseUI for Phone verification. When user enters Phone number and selecting next for enter verification code app met crash. 
Here with this issue I'm attaching  screenshot of Xcode which is fetch via build crash reports and Crash Stacktrace which got from crashlytics.

![firebaseui crash](https://user-images.githubusercontent.com/11042449/33793646-ffbada5a-dce0-11e7-951b-276c21e0ea5b.png)
[com.reboundvm_issue_15_crash_ae89358563ba476bae01fe5b5ec54f73_5946777adcae11e7aa7956847afe9799_0_v2.txt](https://github.com/firebase/FirebaseUI-iOS/files/1544472/com.reboundvm_issue_15_crash_ae89358563ba476bae01fe5b5ec54f73_5946777adcae11e7aa7956847afe9799_0_v2.txt)

**Comment by morganchen12** [comment]
@yramanchuk looks like we need a dispatch in the FIRPhoneAuthProdiver's verify completion block. Has this always been an issue?

**Comment by mrugeshtank** [comment]
While I was debugging on my device iPhone 6 (iOS 10.3) no any issue, but friend of mine is using this in remote place via testFlight has this issue every time on device iPhone 6 (iOS 10.2).

**Comment by morganchen12** [comment]
There was an older auth background queue issue that was fixed, but I can't remember what version of Firebase it was in. If you update Firebase to 4.8.0, does the issue go away?

**Comment by mrugeshtank** [comment]
Tried to update Firebase to 4.8.0, but got an error of "required a higher minimum deployment target".
I've iOS 9.0 as the minimum deployment target. Do you have any other option other than set my project to iOS 10.0 as the minimum deployment target?

**Comment by morganchen12** [comment]
Firebase 4.8.0 should be compatible with iOS 8 and above, so it's likely one of your other pods causing the issue.
