### ISSUE TITLE
Trying to change the BG of FUIEmailEntryViewController not working 

### ISSUE THREAD

**Issue by sultan-arshi** [firebase/FirebaseUI-iOS#373]
working with IOS/Swift
i am trying to get the Background colour of the FUIEmailEntryViewController i tried many Techniques but no gain
`func emailEntryViewController(forAuthUI authUI: FUIAuth) -> FUIEmailEntryViewController {
       // custom.email
        return FUICustomEmailEntryViewController(authUI: authUI)
    }`

and int the  FUICustomEmailEntryViewController.swift
`override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?, authUI: FUIAuth) {
        super.init(nibName: "FUIEmailEntryViewController", bundle: nibBundleOrNil, authUI: authUI)
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }`

and in the ViewDidLoad
`override func viewDidLoad() {
        super.viewDidLoad()
        let backgroundView = UIView()
        backgroundView.frame = CGRect(x: 0, y: 0, width: fullScreenWidth, height: fullScreenHeight)
        backgroundView.backgroundColor = UIColor.green
        view.insertSubview(backgroundView, at: 0) // it is also not working at: 1
        view.addSubview(backgroundView)
        // even i also tired code below it is woking in the "func authPickerViewController(forAuthUI authUI: FUIAuth) -> FUIAuthPickerViewController"
        view.backgroundColor = UIColor.hllBlackBackground
    }`

**Comment by protocol86** [comment]
@sultan-arshi 

Are you correctly setting you custom delegate? 

You should be doing some thing like `_authUI.delegate = myCustomAuthUIDelegate;` somewhere in you code.

Where _authUI is an instance of `FUIAuth`.
