### ISSUE TITLE
FUIPhoneAuth doesn't dismiss it self on Auth completion or Cancel button click

### ISSUE THREAD

**Issue by emad-ir** [firebase/FirebaseUI-iOS#376]
This issue is a bit similar to #293 but it doesn't solve my problem.

Swift: 3
Xcode: 8.1
iOS version:10.1
FirebaseUI version: 4.0
  
### Problem:
The general suggested answer to this problem was that to present the view like so:
```
let provider = self.authUI?.providers.first as! FUIPhoneAuth;
provider.signIn(withPresenting: self);
```
And this will fire ``` func authUI(_ authUI: FUIAuth, didSignInWith user: FirebaseAuth.User?, error: Error?) ``` the delegate function upon cancelation or authentication.

But this method doesn't provide the credentials. I need the credentials so I can get the user's accessToken.

so I use a signIn method that provides the credentials, but this method doesn't close the FUIPhoneAuth view up on cancelation or authentication:

```
let phoneAuth = FUIPhoneAuth.init(authUI: authUI!)
self.authUI?.providers = [phoneAuth]
phoneAuth.signIn(withDefaultValue: nil, presenting: self, completion: { (credentials, error, result) in
    if (error != nil) {
        //user cancelled
    }
    } else {
        //User is authenticated
        //We have credentials
    }
})
```

How can I fix this issue?

**Comment by protocol86** [comment]
@emad-ir 

You mentioned that you are interested in obtaining the user's access token. But you do not need a credential to accomplish that, you can get the token from the user object by invoking `getTokenWithCompletion`.
