### ISSUE TITLE
[Auth] Customize only one screen but not the others

### ISSUE THREAD

**Issue by bernaferrari** [firebase/FirebaseUI-iOS#377]
Hi! I am trying to replicate Android's Firebase UI Auth and therefore, I only want to customize the first page, with a title and an image (which is not a problem). The problem is, I can't opt to customize only the first page: it is all or nothing. The app crashes if I only include the main page delegate and not the others; I think it should open them without any modification when it doesn't find the customized version.

I found #87 and #159, but none of them are exactly what is happening to me.

Steps to reproduce:
- Clone sample project
- Open FUICustomAuthDelegate
- Remove everything except authPickerViewController and authUI
- Compile and run

- Auth -> Tap "Custom Auth UI" -> Tap "Sign in"
- Tap Email
Crash

**Comment by morganchen12** [comment]
Can you post the stack trace?

**Comment by bernaferrari** [comment]
No and thanks for asking! I was trying to reproduce but couldn't.. 😄
