### ISSUE TITLE
Twitter updated their framework's name 

### ISSUE THREAD

**Issue by SirArkimedes** [firebase/FirebaseUI-iOS#380]
* Objective C or Swift: Swift
  * iOS version: 11.2
  * Firebase SDK version: 4.8.0
  * FirebaseUI version: 4.5.0
  * CocoaPods Version: 1.3.1
  
### Problem:

Twitter updated their framework name and ```FirebaseTwitterAuthUI``` uses the old name. This is a breaking change if ```TwitterKit``` & ```TwitterCore``` are updated and FirebaseUI is included in the project.

#### Steps to reproduce:

  1. Clone this repo
  2. pod install
  3. Start a build of ```FirebaseTwitterAuthUI```
  4. Notice that ```TwitterKit.h``` is not found
  
#### Observed Results:

  * Get a "```TwitterKit/TwitterKit.h``` is not found" error.
  
#### Expected Results:

  * FirebaseUI works with latest ```TwitterKit``` & ```TwitterCore```.

I am willing to submit a PR to fix this issue:
#381

**Comment by morganchen12** [comment]
Nice catch. PRs are always welcome, if not I'll fix this in the new year since I'm on vacation soon.

For the time being, people who run into this issue can work around it by pinning the Twitter SDK to an older version.

**Comment by morganchen12** [comment]
This is fixed in the latest release.
