### ISSUE TITLE
After sign out, login screen immediately shows

### ISSUE THREAD

**Issue by antonijap** [firebase/FirebaseUI-iOS#385]
Although I am not sure what triggers that behavior when this code is finished, the login screen appears. I would like to trigger that manually. Is that possible?

```
let firebaseAuth = Auth.auth()
        do {
            try firebaseAuth.signOut()
        } catch let signOutError as NSError {
            print ("Error signing out: %@", signOutError)
        }
```

**Comment by morganchen12** [comment]
You most likely have an auth state change listener somewhere in your code that's presenting the login controller if the user isn't authenticated.
