### ISSUE TITLE
Build error: objc-class-ref in FirebaseTwitterAuthUI(FUITwitterAuth.o)

### ISSUE THREAD

**Issue by iosboffin** [firebase/FirebaseUI-iOS#387]
Undefined symbols for architecture x86_64:
"OBJC_CLASS$_Twitter", referenced from:
objc-class-ref in FirebaseTwitterAuthUI(FUITwitterAuth.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by morganchen12** [comment]
What's the output of running `pod install`? You can most likely work around this issue for now by pinning an older version of TwitterKit.

**Comment by cantonalex** [comment]
Getting same error, anyone found a solution?

**Comment by HamzaGhazouani** [comment]
It's working fine when I add this `pod 'TwitterCore', '2.8.0'` to the Podfile

**Comment by morganchen12** [comment]
This is fixed in the latest release.
