### ISSUE TITLE
ld: framework not found FBSDKLoginKit for architecture arm64

### ISSUE THREAD

**Issue by redbullhorns** [firebase/FirebaseUI-iOS#389]
* Objective C
  * iOS version: 11.2
  * Firebase SDK version: _____
  * FirebaseUI version: ____
  * CocoaPods Version: ____

After adding FirebaseAuthUI/Facebook pod to the workspace, getting an error as 'ld: framework not found FBSDKLoginKit for architecture arm64' and not able to compile.

#### Steps to reproduce:

  1. add 'pod FirebaseAuthUI/Facebook' to pod file
  2. pod update
  
#### Observed Results:

  * getting an error as 'ld: framework not found FBSDKLoginKit for architecture arm64' 
  
#### Expected Results:

  * Compile without link error
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by morganchen12** [comment]
What versions of Xcode and CocoaPods are you using? What's the output of `pod install`?

**Comment by redbullhorns** [comment]
I'm using Xcode 9.2 (9C40b), earlier I was using CocoaPods 1.3.1. Now updated to 1.4.0.rc.1 after this, its stuck after this

Analyzing dependencies
Downloading dependencies
Installing Bolts (1.9.0)
Installing FBSDKCoreKit (4.29.0)

**Comment by morganchen12** [comment]
If you run `pod install --verbose`, what's the command it's getting stuck on?

**Comment by morganchen12** [comment]
closing as this isn't a FirebaseUI issue,but if you continue to comment here I'll try to help you out

**Comment by fareast555** [comment]
Same issue here. New to Firebase. Installed FB via CocoaPods. Got the framework not found FBSDKLoginKit for architecture arm64 error. Installed the FBSDK via cocoa pods thinking that might silence it. It didn't.

Note that this issue doesn't exist in Swift.
