### ISSUE TITLE
Can't tap through Terms of Service link in FUIPasswordSignUpViewController

### ISSUE THREAD

**Issue by dev-pitcher** [firebase/FirebaseUI-iOS#390]
swift, iOS 11, FirebaseUI 4.5.0

FUIPasswordSignUpViewController (i.e. sign up new user screen) shows a footer view with a link via attributed text if you've specified a Terms of Service URL. That link highlights, but tapping it does nothing. The footer UITextField needs to be set "selectable" (see IB screenshot).

![screen shot 2018-01-10 at 3 48 15 pm](https://user-images.githubusercontent.com/26881196/34800013-5695b9ba-f61f-11e7-9b09-ce6aa5a9c7c8.png)

**Comment by mikewadhera** [comment]
+1 any update on this bug? At best this negatively impacts an app's sign up conversion and at worst can cause App Store rejections.

**Comment by morganchen12** [comment]
This is fixed in b1e7ea3dfd11c102c96b4210016b3050fdda8290 and will be out with the next release.

The next release of FirebaseUI will be a major version release with breaking changes, and likely won't be out for at least another month. If this is severely blocking you, let me know and I can push a bugfix release earlier.

**Comment by mikewadhera** [comment]
@morganchen12 thanks for the reply. We can confirm this is blocking App Store updates. Can you please provider an earlier release ASAP? Thanks

**Comment by morganchen12** [comment]
Hey all, I'm out traveling this week and will be back 3/3. I should have time to push a release then.

Sorry for the delay.

**Comment by morganchen12** [comment]
This is fixed in v4.5.2. Please re-open if it's still an issue.

**Comment by mikewadhera** [comment]
Can you please push 4.5.2 to CocoaPods?

**Comment by morganchen12** [comment]
4.5.2 was pushed a while ago. https://cocoapods.org/pods/FirebaseUI
