### ISSUE TITLE
Duplicate TwitterKit/TwitterCore classes at runtime

### ISSUE THREAD

**Issue by morganchen12** [firebase/FirebaseUI-iOS#402]
This seems to be an issue in TwitterKit/TwitterCore.

https://twittercommunity.com/t/runtime-warnings-about-duplicate-class-implementations-twitterkit-or-twittercore/98904

**Comment by Bruce9487** [comment]
Same issue here.

**Comment by tjbarber** [comment]
Same issue here, can't use FirebaseUI because of this.

**Comment by gesabo** [comment]
same

**Comment by Yue-Wang-Google** [comment]
Resolved in master.
