### ISSUE TITLE
Se produjo un error. Vuelve a intentarlo

### ISSUE THREAD

**Issue by Cristy4** [firebase/FirebaseUI-iOS#404]
Swift 3
iOS version: 11
Firebase SDK version: 4.6.0
FirebaseUI version: 4.6.0
CocoaPods Version: 1.3.1

When I send a verification code, it displays this message "Se produjo un error. Vuelve a intentarlo.".
This only happens with iPhone X. iPhone 6 iOS 11 works perfect.

**Comment by morganchen12** [comment]
Is this when using Phone auth? Can you include some other logs from when this happens as well as how you've implemented phone auth?

**Comment by morganchen12** [comment]
@Cristy4 if you're still having this issue, please add extra information to the ticket and reopen it.
