### ISSUE TITLE
TableView datasource not updated after re-biding

### ISSUE THREAD

**Issue by victor-sarda** [firebase/FirebaseUI-iOS#406]
Hello Firebase 👋

### Step 2: Describe your environment

  * Objective C or Swift: **Swift**
  * iOS version: **11.2.5**
  * Firebase SDK version: **4.8.2**
  * FirebaseUI version: **4.5.1**
  * CocoaPods Version: **1.3.1**
  
### Step 3: Describe the problem:

I have a TableView populated by FirebaseUI. I'm doing dataSource.unbind on viewDidDisappear() and dataSource.bind in viewWillAppear(). I expect the data to still be updated after I do .bind but it is not anymore.

#### Steps to reproduce:

1. Create a tableView and the FUITableViewDataSource object with a query (viewDidLoad)
2. Do dataSource.bind(to: tableView)  into viewWillAppear()
3. Do dataSource.unbind() into viewDidDisappear()
4. Open another ViewController to trigger viewDidDisappear() and .unbind()
5. Update a value on Firebase
6. Go back to the current ViewController to trigger viewWillAppear() and .bind()
  
#### Observed Results:

  * What happened? 

The data isn't updated after coming back to the current ViewController with the TableView (so after unbind & bind again).

#### Expected Results:

  * What did you expect to happen?
I expect the data to be live updated after I come back and do .bind.
The TableView is populated but the data source is not updated. 
  
#### Relevant Code:

  ```
  override func viewDidLoad() {
        super.viewDidLoad()
        self.dataSource = getDataSource()
    }

  override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.dataSource.bind(to: self.tableView)
    }

  override func viewDidDisappear(_ animated: Bool) {
        super.viewDidDisappear(animated)
        self.dataSource.unbind()
    }

func getDataSource() -> FUITableViewDataSource {

        return FUITableViewDataSource(query: firebaseRef, populateCell: { (tableView, indexPath, snapshot) -> UITableViewCell in
           // Return cells here
        })
    }

  ```

___

This looks like the original issue here that wasn't actually implemented: #314 
It also looks like the issue was fixed in the latest release but only with Firestore:

> Fixed a bug in FirestoreUI where arrays wouldn't properly resync after disconnecting listeners.

**Comment by morganchen12** [comment]
This is most likely going to be in the next major release, which won't come out for some time.

For the time being you'll have to work around this by either not unbinding your data sources or removing the data source entirely and emptying your table view before rebinding.

Both are not great solutions, unfortunately.

**Comment by victor-sarda** [comment]
Thanks for your answer 👌
An idea of when this will come out? Thanks!

**Comment by morganchen12** [comment]
The next major release will probably be around Google I/O.

**Comment by victor-sarda** [comment]
Hi, 
Any news on this issue? I haven't tried FirebaseUI 5 yet but I just wanted to know if it's been added to this release? Thanks 👍

**Comment by morganchen12** [comment]
This hasn't been fixed in Firebase 5. I don't have an ETA on when it'll be fixed, unfortunately.

**Comment by victor-sarda** [comment]
Cool, thanks 👍

**Comment by morganchen12** [comment]
The proposed fix for this would just remove all elements in the array when it's invalidated, which increases the amount of computation but allows for FUIArray instances to be reused after invalidation. 

Note that this is currently not an issue with FirestoreUI.
