### ISSUE TITLE
FUITwitterAuth does not work (TwitterKit v3.2.2 or later)

### ISSUE THREAD

**Issue by m-hosoi** [firebase/FirebaseUI-iOS#409]
## FUITwitterAuth
https://github.com/firebase/FirebaseUI-iOS/blob/f9e7d8c0432f522e996839a472e9c5fd7e71890e/FirebaseTwitterAuthUI/FUITwitterAuth.m#L142

## TwitterKit
https://github.com/twitter/twitter-kit-ios/blob/22ec0a5159da1b00945cbd48a259b3de6c914e78/TwitterKit/TwitterKit/TWTRTwitter.m#L408
```
if ([self.mobileSSO verifySourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]]) {
```

https://github.com/twitter/twitter-kit-ios/blob/22ec0a5159da1b00945cbd48a259b3de6c914e78/TwitterKit/TwitterKit/Social/Identity/TWTRMobileSSO.m#L75
```
BOOL isExpectedSourceApplication = [sourceApplication hasPrefix:@"com.twitter"] || [sourceApplication hasPrefix:@"com.apple"] || [sourceApplication hasPrefix:@"com.atebits"] || [sourceApplication isEqualToString:bundleID];

```

**Comment by bbookman** [comment]
Not sure if this is 100% related, but I keep getting an empty framework for Twitter when doing `pod FirebaseUI` or `pod FirebaseUI/Twitter`.  See [This image for proof](https://imgur.com/a/5AwrB)

**Comment by morganchen12** [comment]
@bbookman, yours looks like a packaging issue and isn't related to the original issue filed. What version of CocoaPods are you using? If you clear your CocoaPods cache (`pod cache clean FirebaseUI --all`) does it fix the issue?

**Comment by morganchen12** [comment]
This is fixed and will be available in the next major version.
