### ISSUE TITLE
Multiple FUIArray in the same ViewController

### ISSUE THREAD

**Issue by rohaaa** [firebase/FirebaseUI-iOS#411]
Hi!

In my ViewController I have two **FUISortedArray**.

Here is my code to know which array has been updated:

```
func array(_ array: FUICollection, didAdd object: Any, at index: UInt) {        
        switch array.description {
        case Array1.description:
            //do something
        case Array2.description:
            //do something
        default:
            break
        }
}
```

Is there a more secure and faster way to do it?

**Comment by morganchen12** [comment]
If you're doing this via Swift's pattern matching (which it looks like you are), you can just match the arrays directly for pointer equivalence.

```swift
switch array {
case array1:
  // do something
case array2:
  // do something
case _:
  break
}
```

**Comment by rohaaa** [comment]
@morganchen12 I have already tested I get an error "Expression pattern of type 'FUISortedArray' cannot match values of type 'FUICollection'"

**Comment by morganchen12** [comment]
Got it, looks like you can't match classes conforming to the protocol type. In this case you could either cast `array` explicitly to an `FUIArray` or use NSObjectProtocol's `hash` property to match instead of description.

```swift
guard let array = array as? FUIArray else { return }
switch array {
case array1:
  // do something
case array2:
  // do something
case _:
  break
}
```

**Comment by rohaaa** [comment]
@morganchen12 Perfect! Thank you!
