### ISSUE TITLE
Remove Sign In With Email Option

### ISSUE THREAD

**Issue by namsoila** [firebase/FirebaseUI-iOS#415]
### Environment

  * Objective C or Swift: Swift
  * iOS version: 11.2
  * Firebase SDK version: 4.9.0
  * FirebaseUI version: 4.5.1
  * CocoaPods Version: 1.4.0
  
### Description:

Is it possible to remove the Sign In With Email option? I started a project where it was enabled along with the phone auth. However, when I turned it off in my panel it still remains in the sign in screen. I am listing only the phone auth my provider but email is still there.

#### Steps to reproduce:

  1. Create a project and have the phone option and email options activated.
  2. Integrate sign in and confirm user addition via phone auth.
  3. Turn off email auth but it will still remain an option in sign in screen.
 
#### Expected Results:

I expected that the removal of the email auth option from the project panel would remove the button from the available screen options but this was not the case.
  
#### Relevant Code:

```
self.auth = Auth.auth()
        self.authUI = FUIAuth.defaultAuthUI()
        self.authUI?.delegate = self
        self.authUI?.providers = [FUIPhoneAuth(authUI: self.authUI!),]
        
        self.authStateListenerHandle = self.auth?.addStateDidChangeListener { (auth, user) in
            guard user != nil else {
                //self.signInWithPhone(sender: UIButton!)
                return
            }
        }
```

**Comment by morganchen12** [comment]
You can set the `signInWithEmailHidden` property on `FIRAuth`.

https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseAuthUI/FUIAuth.h#L177
