### ISSUE TITLE
How to set a default value for name field in the password sign up view

### ISSUE THREAD

**Issue by yunpengn** [firebase/FirebaseUI-iOS#423]
### Step 1: Are you in the right place?

Yes

### Step 2: Describe your environment

  * Objective C or Swift: _Swift_
  * iOS version: _iOS 11_
  * Firebase SDK version: _Firebase/Auth (4.10.1)_
  * FirebaseUI version: _FirebaseUI/Auth (4.5.4)_
  * CocoaPods Version: _1.4.0_
  
### Step 3: Describe the problem:

I am trying to add a default value for the name field in password sign up view, but it seems that I cannot find any possible ways to do so.

This is relevant to https://github.com/firebase/FirebaseUI-iOS/issues/245

**Comment by yunpengn** [comment]
Hi,

I found the solution already. See the code below.

```swift
if let nameField = value(forKey: "_nameField") as? UITextField {
    nameField.text = name
}
```

Will close this issue for now. If anyone found has potential problems, please point out. If need discussion, please re-open it.

**Comment by FrancoSabadini** [comment]
@yunpengn where did you put that code? I'm trying to use it inside `passwordSignUpViewController()` but `value(forKey: "_nameField")` keeps returning `nil`.
