### ISSUE TITLE
PhoneAuthentication Something went wrong. Please try again. 

### ISSUE THREAD

**Issue by bfjfm2** [firebase/FirebaseUI-iOS#425]
Guys,
   I have no clue, why I am getting this **# Something went wrong. please try again.**  It is working on another project with the same configuration. I have changed new GoogleServiceInfo.plist and also added URL types in Target Info.  I have tried with all versions from 4.5 to 4.2.   Very annoying error message.  Any help?

![img-4647](https://user-images.githubusercontent.com/280136/38028452-8bef898c-32c5-11e8-9c29-d50d34ddcecf.jpg)

**Comment by morganchen12** [comment]
@bfjfm2 can you share your implementation?

**Comment by bfjfm2** [comment]
Thanks, @morganchen12  I managed to fix it. 

**Issue .**
If we set APNSToken for FIRAuthAPNSTokenTypeSandbox and respective credentials are not updated in Firebase Cloud then I got this error. 
[[FIRAuth auth] setAPNSToken:deviceToken type:FIRAuthAPNSTokenTypeSandbox];

**Fix:**
I have changed to
[[FIRAuth auth] setAPNSToken:deviceToken];

Everything is working fine. Please update respective error message instead of a very annoying error message that I didn't expect from a Google team.

**Comment by morganchen12** [comment]
The method you mentioned is deprecated and will be removed in the next major version update.

cc @protocol86

**Comment by ShreyanshAlchemy** [comment]
@morganchen12 @skparticles  Facing the same issue. 
I have added   **Auth.auth().setAPNSToken(deviceToken, type: .sandbox)** code in **didRegisterForRemoteNotificationsWithDeviceToken** method.

The build is uploaded on the test flight.
Some user can able to login using the phone number and some users can't. They are getting the same error as above. 
Any suggestion must be appreciated.Thanks

**Comment by Vinaykumar-dev** [comment]
I am facing the same issue after updating the pod from 'Firebase/Auth', '~> 4.5.0' to 'Firebase/Auth'

As someone mentioned in github, tried removing didRegisterForRemoteNotificationsWithDeviceToken and didReceiveRemoteNotification methods as FUIAuthDelegate implements these functions automatically. This solution also didn't work.

Does anyone facing the same issue? Please let us know if you have any solution for the same. Thanks in advance.

**Comment by shaniceweiwei** [comment]
i am also facing the same issue, ios 13 works, but not on ios12... please help :(
