### ISSUE TITLE
Support silent sign-in for seamless device upgrades

### ISSUE THREAD

**Issue by SUPERCILEX** [firebase/FirebaseUI-iOS#426]
Blocking https://github.com/firebase/FirebaseUI-Android/pull/1212

Is this feasible on iOS? (i.e. should we wait on it?) It'd be really cool if this was possible since the experience is _sooooo_ slick! 👍

**Comment by samtstern** [comment]
cc @morganchen12

**Comment by morganchen12** [comment]
This already exists on iOS since session info is stored in keychain, which persists across system upgrades and app reinstalls.

**Comment by Ankish** [comment]
@morganchen12 : How do we access the session info from keychain. 
Is there a snippet we can take a look at or possible keys with which it is stored ? 
Can we also access that from an extension and authenticate the user ?

**Comment by morganchen12** [comment]
You can't explicitly fetch session information from keychain, but fetching authentication state will load session information from keychain if it's available. You cannot access it from an extension and authenticate the user; you must pass information from the host app.
