### ISSUE TITLE
FirebaseUI iOS - Phone Auth, accepts arabic numbers for phone number but not the code

### ISSUE THREAD

**Issue by turk-jk** [firebase/FirebaseUI-iOS#430]
### Step 2: Describe your environment

  *  Swift: 4.1
  * iOS version: 11.3
  * Firebase SDK version: 4.7.0
  * FirebaseUI version: 4.1.1
  * CocoaPods Version: 1.4.0.beta
  
### Step 3: Describe the problem:
the default FUIAuth.defaultAuthUI() with phoneProvider, it accepts the Arabic numbers for the phone number but it doesn't accepts Arabic numbers for the code validation.
 

thanks

**Comment by morganchen12** [comment]
@protocol86 this seems like a bug (ideally both or neither should be supported)

**Comment by turk-jk** [comment]
I agree with you.

**Comment by morganchen12** [comment]
@Yue-Wang-Google can you take a look at this? If it's no longer a bug please close it, otherwise we can disable support for a quick solution (or add support for a longer-term solution).

**Comment by Yue-Wang-Google** [comment]
what are Arabic numbers?

**Comment by morganchen12** [comment]
Arabic phone numbers, I think. We can close this issue until we get more information, since I'm not sure which territory in particular @turk-jk is referring to.
