### ISSUE TITLE
Swift subclass of `FUIAuthPickerViewController` crashes

### ISSUE THREAD

**Issue by AndriyGo** [firebase/FirebaseUI-iOS#433]
I am trying to subclass the `FUIAuthPickerViewController`. Here is my implementation so far:

`class FUICustomAuthPickerViewController: FUIAuthPickerViewController {}`

Unfortunately, it crashes with the exception `libc++abi.dylib: terminating with uncaught exception of type NSException`.

Is this related to me using Swift in my project? If so, do you have any idea how this could be fixed?

**Comment by morganchen12** [comment]
Unlikely. What's the full stack trace? I'm guessing it may be related to https://github.com/firebase/firebase-ios-sdk/issues/1072.

**Comment by AndriyGo** [comment]
Having below methods fixes the issue for me:

```override init(nibName: String?, bundle: Bundle?, authUI: FUIAuth) {
        super.init(nibName: "FUIAuthPickerViewController", bundle: bundle, authUI: authUI)
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }```
