### ISSUE TITLE
Cocoapods import, no AccountManagement files

### ISSUE THREAD

**Issue by cerupcat** [firebase/FirebaseUI-iOS#435]
I'm including FireBaseUI pod in my project, but none of the `AccountManagement` files are being included. Is this a known issue or am I doing something wrong?

**Comment by morganchen12** [comment]
What errors are you getting?

**Comment by cerupcat** [comment]
I'm not getting any errors. It just appears none of the source files in the Account Management folder are being downloaded through cocoapods. The only file I'm seeing is`FUIAccountSettingsViewController.nib`, but all the other source files are missing from what I can tell.

**Comment by cerupcat** [comment]
<img width="371" alt="screenshot 2018-04-21 12 05 55" src="https://user-images.githubusercontent.com/204151/39087866-654b4e8e-455c-11e8-94d9-65380f92a8c5.png">

**Comment by morganchen12** [comment]
They're not part of the public headers, so you won't be able to find them in the headers folder.
