### ISSUE TITLE
FUIIndexTableViewDataSource reverse the stack

### ISSUE THREAD

**Issue by joemerritt** [firebase/FirebaseUI-iOS#436]
Hi All,

I am using the FUIIndexTableViewDataSource method and it works nicely. However I need to revers the loading order of the stack. I.e. the last node in FB needs to be the first cell in the Table View. 

Is there a way to reverse the stack? 

self.dataSource = FUIIndexTableViewDataSource(
            
            index: indexQuery,
            data: dataRef,
            tableView: self.listTableView,
            delegate: self as? FUIIndexTableViewDataSourceDelegate,
            populateCell: { (tableView, indexPath, snapshot) -> UITableViewCell in
                
                self.cell = self.listTableView.dequeueReusableCell(withIdentifier: "customMessageCell", for: indexPath) as! CustomMessageCell
                
                             
                if snapshot != nil {
                    
                    
                    let snapShotValue = snapshot?.value as! NSDictionary
                    
                    self.cell.businessName.text = snapShotValue["companyName"] as? String    ?? ""
                    self.cell.tagLine.text = snapShotValue["tagLine"] as? String ?? ""
                    self.cell.webAddress.text = snapShotValue["webaddress"] as? String ?? ""
                    
                }
                
                return self.cell
                
        }
            
        )
        
        self.listTableView.dataSource = self.dataSource

Thank you for your help !

**Comment by morganchen12** [comment]
Use one of the [ordering methods on FIRDatabaseQuery](https://firebase.google.com/docs/reference/ios/firebasedatabase/api/reference/Classes/FIRDatabaseQuery#-queryorderedbychild) to reverse your query before passing it to FirebaseUI.

**Comment by joemerritt** [comment]
I'm not sure this will work as I would need to reverse the database reference. From my understanding it's not the query that's the issue. I want the last post from Firebase Ref first. in Java there is a "setReverseLayout" function that can be called. I can't seem to find anything similar for Swift?

**Comment by morganchen12** [comment]
You can do this manually by subclassing `FUIArray`.

**Comment by joemerritt** [comment]
MorganChen12. I"m having trouble relating this back to indexTableView. Do you have an example I can reference?

**Comment by morganchen12** [comment]
Sorry, this is actually not possible currently because the initializer of FUIIndexArray doesn't take an FUIArray. I'll add this to the next release.

**Comment by morganchen12** [comment]
This is released in FirebaseUI 5.0.0. You can now manually construct an FUIArray and pass it into the FUIIndexArray initializer.
