### ISSUE TITLE
Move Sign In buttons higher

### ISSUE THREAD

**Issue by ryandailey100** [firebase/FirebaseUI-iOS#438]
My current app has three login methods: Google, Facebook, and Email. These buttons are automatically placed at the bottom of the screen. I would like to raise these buttons more up. The reason for this is that I want to add a Terms of Service and Privacy Policy buttons at the bottom of the screen, below the Sign In buttons. Is this possible to achieve? Please let me know, thanks!

**Comment by ethanzh** [comment]
How did you end up solving this?
