### ISSUE TITLE
Error installing with Pods - Swift

### ISSUE THREAD

**Issue by boardmain** [firebase/FirebaseUI-iOS#44]
i tried to install it with CocoaPods
but whitout success,  the samples in the docs are obsolete i think

can you provide a step guide to install this module with CocoaPods and use it with Swift?

**Comment by mcdonamp** [comment]
Thanks for submitting an issue--can you give us a little more info on what's not working (is CocoaPods not letting you install, is the module not found, etc.)? The docs do mention that if you're using Swift, you should use `use_frameworks!` when installing.

**Comment by boardmain** [comment]
hi,
im trying to use the login ui

my pod is this:

~~~
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'FirebaseUI/Core', '~> 0.3'
pod 'FirebaseUI/Facebook', '~> 0.3.2'
pod 'FirebaseUI/Password', '~> 0.3.2'
~~~


but if i include the facebook module i have this errors
~~~
FBSDKAppLinkResolver.h:26:10: Include of non-modular header inside framework module 'FBSDKCoreKit.FBSDKAppLinkResolver'

FirebaseFacebookAuthProvider.h:35:9: Could not build module 'FBSDKCoreKit'

~~~

**Comment by mcdonamp** [comment]
Which version of Cocoapods are you using? Looks like 1.0.0+ might have broken Facebook: https://github.com/CocoaPods/CocoaPods/issues/4713

**Comment by boardmain** [comment]
pod --version
0.39.0

**Comment by mcdonamp** [comment]
I just successfully installed everything using the same `Podfile`, using `0.39.0`:

```
Analyzing dependencies
Downloading dependencies
Installing Bolts (1.6.0)
Installing FBSDKCoreKit (4.10.0)
Installing FBSDKLoginKit (4.10.0)
Installing Firebase (2.5.1)
Installing FirebaseUI (0.3.2)
Generating Pods project
Integrating client project
Sending stats
Sending stats
Pod installation complete! There are 3 dependencies from the Podfile and 5 total pods installed.
```

Have you tried in a separate project (sometimes Cocoapods can get corrupted)?

**Comment by boardmain** [comment]
yes it install but if you try to setup a base app with login ui it crash on launch

with this errors

FBSDKAppLinkResolver.h:26:10: Include of non-modular header inside framework module 'FBSDKCoreKit.FBSDKAppLinkResolver'

FirebaseFacebookAuthProvider.h:35:9: Could not build module 'FBSDKCoreKit'

**Comment by mcdonamp** [comment]
Do you have `Enable Modules` set to `YES` in your Project's Build Settings?

Thanks,
--Mike

**Comment by sveinnv** [comment]
I'm getting the same error as above and I have set the Enable Modules to YES in my build settings.

The pods install fine but when I try to build the project i get the error 

> Include of non-modular header inside framework module 'FBSDKCoreKit.FBSDKAppLinkResolver'

> While building module 'FBSDKCoreKit' imported from */FirebaseAppDelegate.h:47
> In file included from */FBSDKCoreKit-umbrella.h:6

Also get 
> Could not build module 'FBSDKCoreKit'

> In file included from */FirebaseAppDelegate.m:31
> In file included from */FirebaseLoginViewController.h:50

**Comment by Vortec4800** [comment]
I also ran into this issue this morning. I was able to fix it by going to the FirebaseUI target build settings in the Pod project and setting the allow non-modular includes setting to yes.

http://stackoverflow.com/questions/29435377/facebook-ios8-sdk-build-module-error-for-fbsdkcorekit

**Comment by mcdonamp** [comment]
@Vortec4800 Hrm, interesting, similar idea pushed up into the Podspec. Mind submitting a PR to the Podspec to add `CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES` to the build and testing to see if it works.

**Comment by sveinnv** [comment]
@Vortec4800 This solves the issue for me. I had already tried to allowing non-modular includes on my app target, didn't think to do it on the FirebaseUI target in the pod project!
