### ISSUE TITLE
sd_setImage: How do you get rounded images once retrieved from server.

### ISSUE THREAD

**Issue by justdan0227** [firebase/FirebaseUI-iOS#441]
How do you go about making the returned image rounded.  I set the layer and you can see that the default image is rounded, however when the returned image is displayed it is square.

**Comment by morganchen12** [comment]
If you want to round the image itself, you should use a Cloud Function.

If you want to display the rectangular image as rounded, set the image view's layer's cornerRadius property and clip to bounds.

```swift
let imageView = UIImageView()
imageView.layer.cornerRadius = imageView.bounds.size.width / 2
imageView.layer.clipsToBounds = true
```

**Comment by morganchen12** [comment]
This is probably a bug. In the meantime you can probably work around it by wrapping your image view in a regular view and setting the corner radius and clipping on the container view.

**Comment by justdan0227** [comment]
Thanks.. I’ll try that

**Comment by GuiWill1** [comment]
You must to create a View Class of type UIImage with your code for Rounded Image like the code below. then you need to select your image in storyboard and set the class of type ImageCircle. 

import UIKit

class ImageCircle: UIImageView {

    override func awakeFromNib(){
        super.awakeFromNib()
        self.layer.cornerRadius = self.frame.width/2
        self.clipsToBounds = true
        
    }

}

**Comment by morganchen12** [comment]
Closing this since we won't be adding image masks/filters as a storage feature.
