### ISSUE TITLE
Phone Verification - Invalid Token - FIRAuth Error Domain Code 17048 - With APN Authentication key

### ISSUE THREAD

**Issue by RachitTechnology** [firebase/FirebaseUI-iOS#442]
### Step 2: Describe your environment

  * Objective C or Swift:  Objective C
  * iOS version:  All Versions
  * Firebase SDK version:  latest pod update ( as of 6-May-2018)
  * FirebaseUI version: latest pod update ( as of 6-May-2018)
  * CocoaPods Version: latest pod update ( as of 6-May-2018)
  
### Step 3: Describe the problem:
We have Phone Verification working without any issue in Android. Tried integrating with FirebaseUI for iOS and was getting error with phone verification "Invalid Token - FIRAuth Error Domain Code 17048" ( Other verifications are working correctly ) 

Followed instruction from this link https://firebase.google.com/docs/auth/ios/firebaseui

#### Steps to reproduce:

1. Setup Phone number verification as mention in link https://firebase.google.com/docs/auth/ios/firebaseui. 
Uploaded "APNs Authentication Key" 
"APNs authentication key under iOS app configuration, click the Upload button. "  

If we delete APN's Authentication key and upload APNs Certificates ( prod and dev ) phone verification is done without any issue 
#### Observed Results:

Phone Verification fails with error Invalid Token - FIRAuth Error Domain Code 17048
If we delete APN's Authentication key and upload APNs Certificates ( prod and dev ) phone verification is done without any issue
  
#### Expected Results:

allos phone verification
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by RachitTechnology** [comment]
@morganchen12  - Thanks for your reply.  When we remove APN's Authentication key and upload APNs certificates - Phone verfication starts working in production as well as in development without any ios code change.  Can you please tell us what change is required on ios side to make it working with APN's Authentication key? I have followed the instructions provided on developer.google.com

**Comment by morganchen12** [comment]
Make sure your Auth key belongs to the same Team ID as the one used to sign your application. For most teams this is the same as the App ID Prefix, but for others it may not be.

**Comment by RachitTechnology** [comment]
yes I veritify its same Team ID as signing ID

**Comment by morganchen12** [comment]
To check if it's an auth key issue, are you able to send notifications directly through APNs with the auth key? [This link](https://stackoverflow.com/questions/39943701/how-to-send-apns-push-messages-using-apns-auth-key-and-standard-cli-tools) may be helpful.

**Comment by RachitTechnology** [comment]
Thanks we will test and share result.

**Comment by morganchen12** [comment]
@RachitTechnology is this still an issue?

**Comment by RachitTechnology** [comment]
Got it working with APNs certificates but never got chance to test with your solution for APN's Authentication key.  Will close this for now

**Comment by arunpkumar92** [comment]
https://stackoverflow.com/a/54800057/4295614

**Comment by tlynchlaw** [comment]
I know this issue is closed, but one thing to check is whether you uploaded the .p8 Auth key to firebase at all.  That was my problem.  I duplicated an app to make a new one and forgot to upload the .p8 key.  It's in the firebase project - click the gear, then Project Settings, then upload it under APNS App configuration.  More details here: https://firebase.google.com/docs/auth/ios/phone-auth
