### ISSUE TITLE
auth UI not translated to my native lang

### ISSUE THREAD

**Issue by nole87** [firebase/FirebaseUI-iOS#444]
Dear,

I add new String file to my swift project and call it FirebaseAuthUI and put into this file all strings from here https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseAuthUI/Strings/sr-Latn.lproj/FirebaseAuthUI.strings they are already translated to Serbian latin. This code I use:

if let bundlePath = Bundle.main.path(forResource: "FirebaseAuthUI", ofType: "strings") {
            print("called")
            let bundle = Bundle(path: bundlePath)
            authUI?.customStringsBundle = bundle;
        }

and in console there is "called" but strings in firebase auth is in English not Serbian. Where is the problem?

Thanks,
Milan

**Comment by morganchen12** [comment]
You shouldn't need to use a custom bundle path to use the stock translations that ship with FirebaseUI. Use a custom bundle path to supply your own translations.

FirebaseUI will use the language that the user has set on their phone, so if your phone is using en-US it won't display Serbian latin.

**Comment by nole87** [comment]
I think I use it, there is code in my first post, if code isn't good can you give me correct code. 

Thanks,
Milan

**Comment by morganchen12** [comment]
It should work by default, so you should be able to remove that code from your codebase.

**Comment by nole87** [comment]
I want to set default language to Serbian because my app is for Balkan and here Serbian is native language, all other apps for Balkan region are in Serbian by default, no matter device language settings! Is this possible with firebase auth UI for iOS swift or not, on Android I set firebase UI to be always Serbian latin.

**Comment by nole87** [comment]
Any help with this issue ...
