### ISSUE TITLE
Change Min OS Version mention in description to 9.0

### ISSUE THREAD

**Issue by RachitTechnology** [firebase/FirebaseUI-iOS#446]
On Main page it says support for 8.0 + . However if we run on a device 4s we get below error 

dyld: Symbol not found: _UIApplicationOpenURLOptionsSourceApplicationKey
  Referenced from: XXXX/Frameworks/TwitterKit.framework/TwitterKit (which was built for iOS 9.0)

**Comment by morganchen12** [comment]
This is _only_ the case for FirebaseTwitterAuthUI. All other components support 8.0.

If you want 8.0 support, remove Twitter from your Podfile (note that Twitter is included by default, so you may have to specify individual subspecs).
