### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by jeffpyke** [firebase/FirebaseUI-iOS#447]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If your issue concerns the CocoaPods error, "...transitive dependencies that include static binaries", please take a look at any of the following issues and see if your problem is solved: #48, #47, #46, #34, #23.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 9.0
  * Firebase SDK version: 5.0
  * FirebaseUI version: 5.0
  * CocoaPods Version: ____
  
### Step 3: Describe the problem:
The documentation is out of date for setting up FirebaseUI. In particular, the swift import fails with "no module FirebaseAuthUI" https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseAuthUI/README.md

This is confusing being new to iOS development and trying to use FirebaseUI but the tutorial doesn't work.

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.
  no such module 'FirebaseAuthUI'

#### Expected Results:

  * What did you expect to happen?
  import succesfully
#### Relevant Code:

  ```
import FirebaseAuthUI
  ```

**Comment by morganchen12** [comment]
Fixed in 42816a5f1f53bdb2d4c54de18a9eb8b9d517d660
