### ISSUE TITLE
2 deprecation warnings, 1 documentation issue and 1 semantic issue after update to Firebase 5 / Xcode 9.3.1

### ISSUE THREAD

**Issue by ghowen** [firebase/FirebaseUI-iOS#448]
Pods/FirebaseUI/FirebaseAuthUI/AccountManagement/FUIAccountSettingsOperation.m:181:37: 'reauthenticateWithCredential:completion:' is deprecated: Please use reauthenticateAndRetrieveDataWithCredential:completion: for Objective-C or reauthenticateAndRetrieveData(WithCredential:completion:) for Swift instead.

Pods/FirebaseUI/FirebaseAuthUI/FUIPasswordSignUpViewController.m:183:14: 'createUserAndRetrieveDataWithEmail:password:completion:' is deprecated: Please use createUserWithEmail:password:completion: for Objective-C or createUser(withEmail:password:completion:) for Swift instead.

Pods/FirebaseUI/FirebaseAuthUI/FUIAuth.m:218:12: Parameter 'signInResult' not found in the function declaration

Pods/FirebaseUI/FirebaseAuthUI/FUIAuthBaseViewController.m:316:61: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior

**Comment by morganchen12** [comment]
Fixed in e32847a7e7b6a3a9a1072254b2a6268aea2242e9.

Thanks for flagging these!

**Comment by ghowen** [comment]
I think these are actually fixed now, but we got a new one with the latest release:

Pods/FirebaseUI/FirebaseAuthUI/FUIPasswordSignUpViewController.m:179:16: 'createUserAndRetrieveDataWithEmail:password:completion:' is deprecated: Please use createUserWithEmail:password:completion: for Objective-C or createUser(withEmail:password:completion:) for Swift instead.
