### ISSUE TITLE
Customization Example : Modifying the screen flow (combining screens or skipping particular screens)

### ISSUE THREAD

**Issue by jtressle** [firebase/FirebaseUI-iOS#459]
The readme states that screen flow can be combined or skipped.  Are there any examples of this?

In particular, the email login / signup flow is a little excessive with new ViewControllers for each state change.  I'd like to hide / unhide relevant view items depending on whether an email exists or not.

If this is not possible, what does "Modifying the screen flow (combining screens or skipping particular screens)" imply?

A custom FUIAuthDelegate does not appear to be the correct solution.

Thanks

**Comment by morganchen12** [comment]
This is a bit of a stretch in our documentation. What it really means is you can skip the initial screen displaying the list of providers if you'd like to move directly to one of the providers. I'll clean up the docs to reflect this.

What sort of UI are you trying to build?

**Comment by jtressle** [comment]
@morganchen12 thanks for the clarification.

Basically, I was trying to skip the EmailEntryViewController and go directly into the PasswordSignInViewController.

I'm going to use the standard flow as it works well.  The documentation had me curious though about the possibilities of customizing the flow.

**Comment by morganchen12** [comment]
Sounds good, I'll close this issue for now. If you have a more specific feature request in mind later, feel free to comment here or open a new issue.
