### ISSUE TITLE
How to link custom firebase Email / Password sign up to FirebasePhoneAuthUI user

### ISSUE THREAD

**Issue by johnlandish** [firebase/FirebaseUI-iOS#461]
I have a custom sign up View controller using Firebase Email and password Auth create user. Once customer signs up, He has to verify phone number(Using FirebasePhoneAuthUI). I want to link the accounts once the user verifies phone number, but i cannot retrieve the verification code and Verification ID to link auth credential.

**Comment by morganchen12** [comment]
If you're not using the phone number for any auth purposes, you may want to consider just storing it as user information in a database somewhere. If you're using it as two-factor auth, linking accounts through FirebaseUI is the wrong approach. If you're using phone and email and password, it seems redundant for auth purposes.

**Comment by johnlandish** [comment]
Hi,

I wanted to have 2 factor auth on sign up but then allow users the ability
to sign in with email or username & password. I believe Musical.ly &
Snapchat do this.

**Comment by morganchen12** [comment]
FirebaseUI's email password flow doesn't support 2FA. You'll have to use a third-party provider or your own web service that requires 2FA.

Note that Firebase doesn't provide a way to distinguish between users who have 2FA enabled or disabled, nor does it provide a way to force 2FA at signup.

Unfortunately you'll have to do most of the legwork to support this use case.

**Comment by johnlandish** [comment]
Sorry not 2FA. I meant I wanted user to have both email/password and phone
log in. Need number to as it’s a messaging app, so like WhatsApp and
Snapchat. Basic point is how do I link email/password auth user
(firebase)with firebasePhoneAuthUI password verification. I just need to be
able to obtain the the verificationID and verificiation code. Examples are
described for Email/password linked with FacebookAuth or googleAuth sign
up. But I cannot see any for phoneAuth.

**Comment by johnlandish** [comment]
Is there a way to implement this?

**Comment by morganchen12** [comment]
Sounds like you'll want to link a phone auth credential to an email/password account. You can do this through Firebase, but this is likely not going to be a feature we add to FirebaseUI in the near future since it supports a fairly narrow use case.

If you'd like to submit this feature, I'm happy to review a PR.

**Comment by johnlandish** [comment]
I figured out how to do it already.

Thanks for the help
