### ISSUE TITLE
iPad Email Sign In

### ISSUE THREAD

**Issue by dschlaba** [firebase/FirebaseUI-iOS#464]
### Step 1: Are you in the right place?

  Yes. :)

### Step 2: Describe your environment

  * Objective C
  * iOS version: Deployment 10.0 / Devices 11.4
  * Firebase SDK version: 5.0.1
  * FirebaseUI version: 5.0.0
  * CocoaPods Version: 1.5.2
  
### Step 3: Describe the problem:

If the user selects Sign In with EMail, Name only appears if that e-mail address hasn't been used before. I'm assuming this is local to the app. However they can change the EMail address on the second screen where password is entered at which point no name is submitted to Google.

Maybe always display Name and populate prepopulate for known emails. Then if they change the email address on the second screen it would update. Also making name a required field would be a nice addition.

**Comment by morganchen12** [comment]
This probably won't be a priority feature for us, but we're always happy to review a PR.

**Comment by morganchen12** [comment]
Should be fixed in #757.
