### ISSUE TITLE
Runtime error for customized AuthPickViewController

### ISSUE THREAD

**Issue by steathy** [firebase/FirebaseUI-iOS#466]
Error message:
terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle <xxxxxxx/FirebaseAuthUI.bundle> (not yet loaded)' with name 'xxxxxx.CustomizedAuthPickViewController

Here `CustomizedAuthPickViewController` is a subclass of `FUIAuthPickerViewController`. If I use the default `AuthViewController` everything works fine. 

  * Swift: 4
  * iOS version: 11
  * Firebase SDK version: default from CocoaPods
  * FirebaseUI version: default from CocoaPods
  * CocoaPods Version: newest
  
Describe the problem:
I created a customized `FUIAuthPickerViewController` and initiated from main viewcontroller by
`let authViewController = CustomizedAuthPickViewController(authUI: authUI!)`

**Comment by morganchen12** [comment]
If you're not using a custom nib, you'll need to override the `initWithNibName:bundle:authUI:` method to use the nib named `FUIAuthPickerViewController`.

This will be fixed in the next version of FirebaseUI.

**Comment by steathy** [comment]
Thanks for the quick reply. Do you mean overriding the init method of `FUIAuthPickerViewController` like below? What `nibName` should I use? I'm currently just using email and google login.

`override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?, authUI: FUIAuth) {
        super.init(nibName: "", bundle: Bundle.main, authUI: authUI, email: email)
 }`

 I'm pretty new to swift. If you could please give me some details. Thanks!

**Comment by morganchen12** [comment]
All you have to do is override the method; FirebaseUI will call it when creating the auth flow.

```swift
override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?, authUI: FUIAuth) {
        super.init(nibName: "FUIAuthPickerViewController", bundle: nibBundleOrNil, authUI: authUI)
}
```

**Comment by steathy** [comment]
Thanks I finally got it worked. This project really needs better tutorial and/or examples.
