### ISSUE TITLE
No such module 'FirebaseUI'

### ISSUE THREAD

**Issue by fobass** [firebase/FirebaseUI-iOS#467]
### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 11.2
  * Firebase SDK version: 5.2.0
  * FirebaseUI version: 5.0.1
  * CocoaPods Version: 1.5.3
  
### Step 3: Describe the problem:
my pod
target 'Project' do
	pod 'Firebase', '>= 2.5.1'
	pod 'Firebase/Database'
	pod 'Firebase/Core'
	pod 'FirebaseUI'
  # Pods for Project
end
Open my project and build after in AppDelegate I try to import FirebaseUI and get a error 
No such module 'FirebaseUI'
  ```
  // TODO(you): code here to reproduce the problem
import UIKit
import Firebase
import FirebaseUI
  ```

**Comment by morganchen12** [comment]
Can you share your `Podfile.lock`?

**Comment by morganchen12** [comment]
For people running into this issue, please make sure you're using FirebaseUI 5.0 or higher.

**Comment by maurostancato** [comment]
I have the same problem. I've installed FirebaseUI in my podfile ( pod 'FirebaseUI'), and I hadn't problems but when I import that on xcode I have that message error: no such module FirebaseUI.
I've downloaded the last version of FirebaseUI and import to my project but I still having the error.

**Comment by morganchen12** [comment]
What version of CocoaPods are you using? Can you upload a sample that reproduces this issue?

**Comment by machoblue** [comment]
I want to authenticate with FirebaseUI. But, I have the save problem. Please tell me how to resolve it.

### Step 2: Describe your environment

  * Objective C or Swift: Swift 4.1.2
  * iOS version: 11.4.1
  * Firebase SDK version: I can't find this version. Please see Podfile.lock.
  * FirebaseUI version: 5.2.1
  * CocoaPods Version: 1.5.3
  
### Step 3: Describe the problem:

#### Steps to reproduce:

  1. `$pod init`, `$vi Podfile`, add `pod FirebaseUI` and `$pod install`
  2. Add `import FirebaseUI` AppDelegate.swift
  
#### Observed Results:

  * Compile error `No such module 'FirebaseUI'` occured. Neither `clean` nor `build` didn't work.

![2018-09-09 7 54 19](https://user-images.githubusercontent.com/38399456/45259351-a328db00-b405-11e8-885a-055203b3a6cd.png)
  
#### Expected Results:

  * Running app succeeds.
  
#### Relevant Code:

**AppDelegate.swift** is here.
  ```
import UIKit
import FirebaseUI // No such module 'FirebaseUI'

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        FirebaseApp.configure()
        // ...
        return true
    }
}
  ```

**Podfile** is here.
```
target 'MyApp' do
  use_frameworks!
  pod 'FirebaseUI'

  target 'MyAppTests' do
    inherit! :search_paths
  end

  target 'MyAppUITests' do
    inherit! :search_paths
  end
end
```

**Podfile.lock** is here.
```
PODS:
  - Bolts (1.9.0):
    - Bolts/AppLinks (= 1.9.0)
    - Bolts/Tasks (= 1.9.0)
  - Bolts/AppLinks (1.9.0):
    - Bolts/Tasks
  - Bolts/Tasks (1.9.0)
  - BoringSSL (10.0.6):
    - BoringSSL/Implementation (= 10.0.6)
    - BoringSSL/Interface (= 10.0.6)
  - BoringSSL/Implementation (10.0.6):
    - BoringSSL/Interface (= 10.0.6)
  - BoringSSL/Interface (10.0.6)
  - FBSDKCoreKit (4.36.0):
    - Bolts (~> 1.7)
  - FBSDKLoginKit (4.36.0):
    - FBSDKCoreKit
  - Firebase/Auth (5.7.0):
    - Firebase/CoreOnly
    - FirebaseAuth (= 5.0.3)
  - Firebase/CoreOnly (5.7.0):
    - FirebaseCore (= 5.1.2)
  - Firebase/Database (5.7.0):
    - Firebase/CoreOnly
    - FirebaseDatabase (= 5.0.2)
  - Firebase/Firestore (5.7.0):
    - Firebase/CoreOnly
    - FirebaseFirestore (= 0.13.2)
  - Firebase/Storage (5.7.0):
    - Firebase/CoreOnly
    - FirebaseStorage (= 3.0.1)
  - FirebaseAuth (5.0.3):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.0)
    - GoogleUtilities/Environment (~> 5.2)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseAuthInterop (1.0.0)
  - FirebaseCore (5.1.2):
    - GoogleUtilities/Logger (~> 5.2)
  - FirebaseDatabase (5.0.2):
    - FirebaseCore (~> 5.0)
    - leveldb-library (~> 1.18)
  - FirebaseFirestore (0.13.2):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.0)
    - FirebaseFirestore/abseil-cpp (= 0.13.2)
    - gRPC-ProtoRPC (~> 1.0)
    - leveldb-library (~> 1.18)
    - nanopb (~> 0.3.8)
    - Protobuf (~> 3.1)
  - FirebaseFirestore/abseil-cpp (0.13.2):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.0)
    - gRPC-ProtoRPC (~> 1.0)
    - leveldb-library (~> 1.18)
    - nanopb (~> 0.3.8)
    - Protobuf (~> 3.1)
  - FirebaseStorage (3.0.1):
    - FirebaseCore (~> 5.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseUI (5.2.1):
    - FirebaseUI/Anonymous (= 5.2.1)
    - FirebaseUI/Auth (= 5.2.1)
    - FirebaseUI/Database (= 5.2.1)
    - FirebaseUI/Facebook (= 5.2.1)
    - FirebaseUI/Firestore (= 5.2.1)
    - FirebaseUI/Google (= 5.2.1)
    - FirebaseUI/Phone (= 5.2.1)
    - FirebaseUI/Storage (= 5.2.1)
    - FirebaseUI/Twitter (= 5.2.1)
  - FirebaseUI/Anonymous (5.2.1):
    - FirebaseUI/Auth
  - FirebaseUI/Auth (5.2.1):
    - Firebase/Auth (~> 5.0)
  - FirebaseUI/Database (5.2.1):
    - Firebase/Database (~> 5.0)
  - FirebaseUI/Facebook (5.2.1):
    - FBSDKLoginKit (~> 4.0)
    - FirebaseUI/Auth
  - FirebaseUI/Firestore (5.2.1):
    - Firebase/Firestore
  - FirebaseUI/Google (5.2.1):
    - FirebaseUI/Auth
    - GoogleSignIn (~> 4.0)
  - FirebaseUI/Phone (5.2.1):
    - FirebaseUI/Auth
  - FirebaseUI/Storage (5.2.1):
    - Firebase/Storage (~> 5.0)
    - SDWebImage (~> 4.0)
  - FirebaseUI/Twitter (5.2.1):
    - FirebaseUI/Auth
    - TwitterKit (~> 3.0)
  - GoogleSignIn (4.2.0):
    - "GoogleToolboxForMac/NSDictionary+URLArguments (~> 2.1)"
    - "GoogleToolboxForMac/NSString+URLArguments (~> 2.1)"
    - GTMOAuth2 (~> 1.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - GoogleToolboxForMac/DebugUtils (2.1.4):
    - GoogleToolboxForMac/Defines (= 2.1.4)
  - GoogleToolboxForMac/Defines (2.1.4)
  - "GoogleToolboxForMac/NSDictionary+URLArguments (2.1.4)":
    - GoogleToolboxForMac/DebugUtils (= 2.1.4)
    - GoogleToolboxForMac/Defines (= 2.1.4)
    - "GoogleToolboxForMac/NSString+URLArguments (= 2.1.4)"
  - "GoogleToolboxForMac/NSString+URLArguments (2.1.4)"
  - GoogleUtilities/Environment (5.2.3)
  - GoogleUtilities/Logger (5.2.3):
    - GoogleUtilities/Environment
  - gRPC (1.14.1):
    - gRPC-RxLibrary (= 1.14.1)
    - gRPC/Main (= 1.14.1)
  - gRPC-Core (1.14.1):
    - gRPC-Core/Implementation (= 1.14.1)
    - gRPC-Core/Interface (= 1.14.1)
  - gRPC-Core/Implementation (1.14.1):
    - BoringSSL (~> 10.0)
    - gRPC-Core/Interface (= 1.14.1)
    - nanopb (~> 0.3)
  - gRPC-Core/Interface (1.14.1)
  - gRPC-ProtoRPC (1.14.1):
    - gRPC-ProtoRPC/Main (= 1.14.1)
  - gRPC-ProtoRPC/Main (1.14.1):
    - gRPC (= 1.14.1)
    - gRPC-RxLibrary (= 1.14.1)
    - Protobuf (~> 3.0)
  - gRPC-RxLibrary (1.14.1)
  - gRPC/Main (1.14.1):
    - gRPC-Core (= 1.14.1)
    - gRPC-RxLibrary (= 1.14.1)
  - GTMOAuth2 (1.1.6):
    - GTMSessionFetcher (~> 1.1)
  - GTMSessionFetcher (1.2.0):
    - GTMSessionFetcher/Full (= 1.2.0)
  - GTMSessionFetcher/Core (1.2.0)
  - GTMSessionFetcher/Full (1.2.0):
    - GTMSessionFetcher/Core (= 1.2.0)
  - leveldb-library (1.20)
  - nanopb (0.3.8):
    - nanopb/decode (= 0.3.8)
    - nanopb/encode (= 0.3.8)
  - nanopb/decode (0.3.8)
  - nanopb/encode (0.3.8)
  - Protobuf (3.6.1)
  - SDWebImage (4.4.2):
    - SDWebImage/Core (= 4.4.2)
  - SDWebImage/Core (4.4.2)
  - TwitterCore (3.2.0)
  - TwitterKit (3.4.0):
    - TwitterCore (>= 3.1.0)

DEPENDENCIES:
  - FirebaseUI
...
COCOAPODS: 1.5.3
```

**Comment by Swoop12** [comment]
I'm having the same issue.  I'm on FirebaseUI (5.2.2) and I've aslo installed Firebase/Core, but still I get the same error.  New to developing and would love any suggestions anyone has?
![screen shot 2018-10-25 at 6 52 00 am](https://user-images.githubusercontent.com/30995492/47501349-8fed9580-d822-11e8-9318-3b7f2fe5a2bb.png)

Here is my Podfile:
# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'SpiltCoffee' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SpiltCoffee

pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'FirebaseUI'


end


And here is my Podfile.lock:
PODS:
  - Bolts (1.9.0):
    - Bolts/AppLinks (= 1.9.0)
    - Bolts/Tasks (= 1.9.0)
  - Bolts/AppLinks (1.9.0):
    - Bolts/Tasks
  - Bolts/Tasks (1.9.0)
  - BoringSSL (10.0.6):
    - BoringSSL/Implementation (= 10.0.6)
    - BoringSSL/Interface (= 10.0.6)
  - BoringSSL/Implementation (10.0.6):
    - BoringSSL/Interface (= 10.0.6)
  - BoringSSL/Interface (10.0.6)
  - FBSDKCoreKit (4.38.0):
    - Bolts (~> 1.9)
  - FBSDKLoginKit (4.38.0):
    - FBSDKCoreKit
  - Firebase/Auth (5.11.0):
    - Firebase/CoreOnly
    - FirebaseAuth (= 5.0.4)
  - Firebase/Core (5.11.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 5.3.0)
  - Firebase/CoreOnly (5.11.0):
    - FirebaseCore (= 5.1.6)
  - Firebase/Database (5.11.0):
    - Firebase/CoreOnly
    - FirebaseDatabase (= 5.0.3)
  - Firebase/Firestore (5.11.0):
    - Firebase/CoreOnly
    - FirebaseFirestore (= 0.13.6)
  - Firebase/Storage (5.11.0):
    - Firebase/CoreOnly
    - FirebaseStorage (= 3.0.2)
  - FirebaseAnalytics (5.3.0):
    - FirebaseCore (~> 5.1)
    - FirebaseInstanceID (~> 3.3)
    - GoogleAppMeasurement (~> 5.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 5.2)
    - GoogleUtilities/MethodSwizzler (~> 5.2)
    - GoogleUtilities/Network (~> 5.2)
    - "GoogleUtilities/NSData+zlib (~> 5.2)"
    - nanopb (~> 0.3)
  - FirebaseAuth (5.0.4):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.0)
    - GoogleUtilities/Environment (~> 5.2)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseAuthInterop (1.0.0)
  - FirebaseCore (5.1.6):
    - GoogleUtilities/Logger (~> 5.2)
  - FirebaseDatabase (5.0.3):
    - FirebaseCore (~> 5.0)
    - leveldb-library (~> 1.18)
  - FirebaseFirestore (0.13.6):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.1)
    - FirebaseFirestore/abseil-cpp (= 0.13.6)
    - "gRPC-C++ (~> 0.0.3)"
    - gRPC-ProtoRPC (~> 1.0)
    - leveldb-library (~> 1.20)
    - nanopb (~> 0.3.8)
    - Protobuf (~> 3.1)
  - FirebaseFirestore/abseil-cpp (0.13.6):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.1)
    - "gRPC-C++ (~> 0.0.3)"
    - gRPC-ProtoRPC (~> 1.0)
    - leveldb-library (~> 1.20)
    - nanopb (~> 0.3.8)
    - Protobuf (~> 3.1)
  - FirebaseInstanceID (3.3.0):
    - FirebaseCore (~> 5.1)
    - GoogleUtilities/Environment (~> 5.3)
    - GoogleUtilities/UserDefaults (~> 5.3)
  - FirebaseStorage (3.0.2):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseUI (5.2.2):
    - FirebaseUI/Anonymous (= 5.2.2)
    - FirebaseUI/Auth (= 5.2.2)
    - FirebaseUI/Database (= 5.2.2)
    - FirebaseUI/Facebook (= 5.2.2)
    - FirebaseUI/Firestore (= 5.2.2)
    - FirebaseUI/Google (= 5.2.2)
    - FirebaseUI/Phone (= 5.2.2)
    - FirebaseUI/Storage (= 5.2.2)
    - FirebaseUI/Twitter (= 5.2.2)
  - FirebaseUI/Anonymous (5.2.2):
    - FirebaseUI/Auth
  - FirebaseUI/Auth (5.2.2):
    - Firebase/Auth (~> 5.0)
  - FirebaseUI/Database (5.2.2):
    - Firebase/Database (~> 5.0)
  - FirebaseUI/Facebook (5.2.2):
    - FBSDKLoginKit (~> 4.0)
    - FirebaseUI/Auth
  - FirebaseUI/Firestore (5.2.2):
    - Firebase/Firestore
  - FirebaseUI/Google (5.2.2):
    - FirebaseUI/Auth
    - GoogleSignIn (~> 4.0)
  - FirebaseUI/Phone (5.2.2):
    - FirebaseUI/Auth
  - FirebaseUI/Storage (5.2.2):
    - Firebase/Storage (~> 5.0)
    - SDWebImage (~> 4.0)
  - FirebaseUI/Twitter (5.2.2):
    - FirebaseUI/Auth
    - TwitterKit (~> 3.0)
  - GoogleAppMeasurement (5.3.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 5.2)
    - GoogleUtilities/MethodSwizzler (~> 5.2)
    - GoogleUtilities/Network (~> 5.2)
    - "GoogleUtilities/NSData+zlib (~> 5.2)"
    - nanopb (~> 0.3)
  - GoogleSignIn (4.3.0):
    - "GoogleToolboxForMac/NSDictionary+URLArguments (~> 2.1)"
    - "GoogleToolboxForMac/NSString+URLArguments (~> 2.1)"
    - GTMOAuth2 (~> 1.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - GoogleToolboxForMac/DebugUtils (2.1.4):
    - GoogleToolboxForMac/Defines (= 2.1.4)
  - GoogleToolboxForMac/Defines (2.1.4)
  - "GoogleToolboxForMac/NSDictionary+URLArguments (2.1.4)":
    - GoogleToolboxForMac/DebugUtils (= 2.1.4)
    - GoogleToolboxForMac/Defines (= 2.1.4)
    - "GoogleToolboxForMac/NSString+URLArguments (= 2.1.4)"
  - "GoogleToolboxForMac/NSString+URLArguments (2.1.4)"
  - GoogleUtilities/AppDelegateSwizzler (5.3.4):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (5.3.4)
  - GoogleUtilities/Logger (5.3.4):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (5.3.4):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (5.3.4):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (5.3.4)"
  - GoogleUtilities/Reachability (5.3.4):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (5.3.4):
    - GoogleUtilities/Logger
  - gRPC (1.14.0):
    - gRPC-RxLibrary (= 1.14.0)
    - gRPC/Main (= 1.14.0)
  - "gRPC-C++ (0.0.3)":
    - "gRPC-C++/Implementation (= 0.0.3)"
    - "gRPC-C++/Interface (= 0.0.3)"
  - "gRPC-C++/Implementation (0.0.3)":
    - "gRPC-C++/Interface (= 0.0.3)"
    - gRPC-Core (= 1.14.0)
    - nanopb (~> 0.3)
  - "gRPC-C++/Interface (0.0.3)"
  - gRPC-Core (1.14.0):
    - gRPC-Core/Implementation (= 1.14.0)
    - gRPC-Core/Interface (= 1.14.0)
  - gRPC-Core/Implementation (1.14.0):
    - BoringSSL (~> 10.0)
    - gRPC-Core/Interface (= 1.14.0)
    - nanopb (~> 0.3)
  - gRPC-Core/Interface (1.14.0)
  - gRPC-ProtoRPC (1.14.0):
    - gRPC-ProtoRPC/Main (= 1.14.0)
  - gRPC-ProtoRPC/Main (1.14.0):
    - gRPC (= 1.14.0)
    - gRPC-RxLibrary (= 1.14.0)
    - Protobuf (~> 3.0)
  - gRPC-RxLibrary (1.14.0)
  - gRPC/Main (1.14.0):
    - gRPC-Core (= 1.14.0)
    - gRPC-RxLibrary (= 1.14.0)
  - GTMOAuth2 (1.1.6):
    - GTMSessionFetcher (~> 1.1)
  - GTMSessionFetcher (1.2.0):
    - GTMSessionFetcher/Full (= 1.2.0)
  - GTMSessionFetcher/Core (1.2.0)
  - GTMSessionFetcher/Full (1.2.0):
    - GTMSessionFetcher/Core (= 1.2.0)
  - leveldb-library (1.20)
  - nanopb (0.3.901):
    - nanopb/decode (= 0.3.901)
    - nanopb/encode (= 0.3.901)
  - nanopb/decode (0.3.901)
  - nanopb/encode (0.3.901)
  - Protobuf (3.6.1)
  - SDWebImage (4.4.2):
    - SDWebImage/Core (= 4.4.2)
  - SDWebImage/Core (4.4.2)
  - TwitterCore (3.2.0)
  - TwitterKit (3.4.1):
    - TwitterCore (>= 3.1.0)

DEPENDENCIES:
  - Firebase/Core
  - Firebase/Firestore
  - Firebase/Storage
  - FirebaseUI

SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - Bolts
    - BoringSSL
    - FBSDKCoreKit
    - FBSDKLoginKit
    - Firebase
    - FirebaseAnalytics
    - FirebaseAuth
    - FirebaseAuthInterop
    - FirebaseCore
    - FirebaseDatabase
    - FirebaseFirestore
    - FirebaseInstanceID
    - FirebaseStorage
    - FirebaseUI
    - GoogleAppMeasurement
    - GoogleSignIn
    - GoogleToolboxForMac
    - GoogleUtilities
    - gRPC
    - "gRPC-C++"
    - gRPC-Core
    - gRPC-ProtoRPC
    - gRPC-RxLibrary
    - GTMOAuth2
    - GTMSessionFetcher
    - leveldb-library
    - nanopb
    - Protobuf
    - SDWebImage
    - TwitterCore
    - TwitterKit

SPEC CHECKSUMS:
  Bolts: ac6567323eac61e203f6a9763667d0f711be34c8
  BoringSSL: e10f92a27043805c01071fe815a5cd98ae8212e7
  FBSDKCoreKit: 2ab7fdbf600dc6b628ba7a49aa29d357a7b4c74e
  FBSDKLoginKit: 634fa27e72e33620eb6389253337342c03d4a407
  Firebase: b48f9e653da971ecce5b8c749684bc8bb2d26bd3
  FirebaseAnalytics: 63202d2665de4e6adcbdce189135255d8b5962ba
  FirebaseAuth: 504b198ceb3472dca5c65bb95544ea44cfc9439e
  FirebaseAuthInterop: 0ffa57668be100582bb7643d4fcb7615496c41fc
  FirebaseCore: d16552f06821489ce1affe2e5e3e5593402ddfe3
  FirebaseDatabase: e2bcbc106adc4b11a2da3ec2eb63c0c4a44f2f54
  FirebaseFirestore: 162502df850b584126c609f3449acfb7230d8c1a
  FirebaseInstanceID: e2fa4cb35ef5558c200f7f0ad8a53e212215f93e
  FirebaseStorage: fd82e5e5c474897e19972b34b22ac0f589dce04e
  FirebaseUI: 09519bf436a055cd696bf68687d624423150e4c0
  GoogleAppMeasurement: 5029d78f2b438bd30ffb44e6c558b57c21622727
  GoogleSignIn: 11183592dc63e105475c7305a325045ff95e02b7
  GoogleToolboxForMac: 91c824d21e85b31c2aae9bb011c5027c9b4e738f
  GoogleUtilities: abb092d2c12e817fa3e0e7b274987dd72fb86ec3
  gRPC: 9d4c549f37c7cef22478634bac7a0405b6e3dbfb
  "gRPC-C++": ee0b01db3122f0b6c2be28b5b11039f62fa15fe6
  gRPC-Core: f4836515817c0eb479aeeb9cc27c91c4ba62a9f6
  gRPC-ProtoRPC: 76f6053639a842e1fb45fa82aa598bf3f4d9f66f
  gRPC-RxLibrary: 3c305f32155024b116b780f389323c73a28197e6
  GTMOAuth2: c77fe325e4acd453837e72d91e3b5f13116857b2
  GTMSessionFetcher: 0c4baf0a73acd0041bf9f71ea018deedab5ea84e
  leveldb-library: 08cba283675b7ed2d99629a4bc5fd052cd2bb6a5
  nanopb: 2901f78ea1b7b4015c860c2fdd1ea2fee1a18d48
  Protobuf: 1eb9700044745f00181c136ef21b8ff3ad5a0fd5
  SDWebImage: 624d6e296c69b244bcede364c72ae0430ac14681
  TwitterCore: 8cbc9ad34d91c63a0035ea05bfbfc0d7ca72a28c
  TwitterKit: 054005edf5350aa9074af74b41456e5a61e3f322

PODFILE CHECKSUM: e4cd6b422dd13ae60c63584f89248b93b42c76ae

COCOAPODS: 1.5.3

**Comment by morganchen12** [comment]
@Swoop12 you'll need to uncomment `use_frameworks!` in your Podfile.

**Comment by Swoop12** [comment]
Morgan, You’re the man!

Reading through the forums it seem like you’ve got the answer to everything!

Thank you!

Trevor Adcock

**Comment by pocharlebois** [comment]
In my case (using Kotlin Multiplatform, xCode 12), the solution that worked was to change "use_frameworks!" for "use_modular_headers!". 

```
target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  use_modular_headers!

  # Pods for iosApp
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Email'
  pod 'FirebaseUI/OAuth'
end
```
