### ISSUE TITLE
target has transitive dependencies that include static binaries

### ISSUE THREAD

**Issue by fqszfm** [firebase/FirebaseUI-iOS#47]
when i tried to install it through pod, it gives me the following error:
[!] The 'Pods-tephra' target has transitive dependencies that include static binaries: (/Users/mike/Desktop/tephra/Pods/Google/Libraries/libGGLCore.a and /Users/mike/Desktop/tephra/Pods/Google/Libraries/libGGLSignIn.a)

**Comment by mcdonamp** [comment]
Thanks for reporting this--it's a known issue that we can't do anything about (see #46, #34, #23). Looks like we should update the docs so people stop running into this.

You can use static libs only (remove `use_frameworks!`) to have it work.
