### ISSUE TITLE
Issue Updating FirebaseUI 5.0. 

### ISSUE THREAD

**Issue by joemerritt** [firebase/FirebaseUI-iOS#471]
I've come across and issue when trying to update to version to 5.0. Below is the error msg.

I"m using xcode 9.4 cocoapods 1.5.3

[!] CocoaPods could not find compatible versions for pod "Firebase/Storage":
  In snapshot (Podfile.lock):
    Firebase/Storage (= 4.11.0, ~> 4.0)

  In Podfile:
    Firebase/Storage

    FirebaseUI (~> 5.0) was resolved to 5.0.0, which depends on
      FirebaseUI/Storage (= 5.0.0) was resolved to 5.0.0, which depends on
        Firebase/Storage (~> 5.0)

**Comment by morganchen12** [comment]
what command did you run to update?

**Comment by joemerritt** [comment]
HI Morganchen,

I updated the line in my podfile as normal.
pod rep update, followed by pod install.

am i missing something here?

**Comment by morganchen12** [comment]
You should be running `pod update` to update your pods.
