### ISSUE TITLE
sd_setImage(with: StorageReference, placeholder: UIImage) not working

### ISSUE THREAD

**Issue by Idomo** [firebase/FirebaseUI-iOS#472]
### Step 1: Are you in the right place?

  Yes

### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 11.4
  * Firebase SDK version: 5.3.0
  * FirebaseUI version: 5.0.1
  * CocoaPods Version: 1.5.2
  
#### Steps to reproduce:

I used the example from this page: https://github.com/firebase/FirebaseUI-iOS/tree/master/FirebaseStorageUI
  
#### Observed Results:

  * _What happened?  This could be a description, log output, etc._
The UIImage is empty and I got this as error from the callback:
`Optional(Error Domain=FIRStorageErrorDomain Code=-13040 "User cancelled the upload/download." UserInfo={NSLocalizedDescription=User cancelled the upload/download.})`
  
#### Expected Results:

  * _What did you expect to happen?_
The image from firebase storage should be displayed in UIImage
  
#### Relevant Code:

  ```
  itemImage.sd_setImage(with: StorageReference().child(item.imageUrl), placeholderImage: #imageLiteral(resourceName: "image")) { (image, error, cacheType, storageReference) in
       print(storageReference) // gs://my-warranty-155ff.appspot.com/itemsImages/2263.0-1907.0-1530054884661.jpg 
       print(error) // Optional(Error Domain=FIRStorageErrorDomain Code=-13040 "User cancelled the upload/download." UserInfo={NSLocalizedDescription=User cancelled the upload/download.})
  }
  ```

**Comment by morganchen12** [comment]
@Idomo I'm unable to reproduce this issue.

**Comment by flamurbeqiri1** [comment]
Anything new about this issue? as I'm having the same
