### ISSUE TITLE
Issue with FirebaseUI 5.0.1 and FUIIndexTableView

### ISSUE THREAD

**Issue by joemerritt** [firebase/FirebaseUI-iOS#474]
Hi All,

I've updated to FIrebaseUI 5.0.1 and when using FUIIndexTableViewDataSource no results are being returned. When using 4.0 this worked as expected however after the update nothing comes through. There are no errors it just does not work.

Can anyone else help with this or experiencing the same issue?
**************CODE********************************************
        
        var ref: DatabaseReference!
        
        ref = Database.database().reference()
        
        let indexQuery = ref.child("Keys").child(uid)
        
        let dataRef = ref.child("Adverts")
        
        self.dataSource = FUIIndexTableViewDataSource(index: indexQuery, data: dataRef, delegate: self, populateCell: { (tableView, indexPath, snapshot) -> UITableViewCell in
            
            
            self.cell = self.listTableView.dequeueReusableCell(withIdentifier: "customMessageCell", for: indexPath) as! CustomMessageCell
            self.cell.selectionStyle = .none
            
            if snapshot != nil {
                
                let snapShotValue = snapshot?.value as! NSDictionary
                print("SNAPSHOT 4 \(String(describing: snapshot))")
                               
            }
            
            return self.cell
            
        })
        
        self.listTableView.dataSource = self.dataSource

**Comment by morganchen12** [comment]
The behavior of the indexed data sources was changed in 5.0+. You now need to call the `observeQuery` method to start pulling data from Firebase.

See the [release notes](https://github.com/firebase/FirebaseUI-iOS/releases/tag/v5.0.0) for more details, and please comment here if you run into related issues.

**Comment by joemerritt** [comment]
Thanks for you help as always Morganchen12, I'm still having trouble with what I want to achieve. Essentially I was to use an FUIIndexTableVIew with and Index and a data source to pull data. However when this gets up and running I was to reverse the stack to have the newest data first. I.e. like facebook/instagram etc etc. 

Can you give me some advice on how to achieve this? (if you have an example, that would be even better)..... Thanks for you time!

**Comment by morganchen12** [comment]
You'll probably want to [reverse the items in your database via the query](https://stackoverflow.com/a/44443042/4158089) directly. `FUIIndexArray` is still a little inflexible and doesn't allow for reversing as easily as `FUIArray` does.

This will change in a future update, but I don't have a timeframe to give.
