### ISSUE TITLE
FirebaseUI / FirebaseAuth Crash on phone number validation

### ISSUE THREAD

**Issue by gelosi** [firebase/FirebaseUI-iOS#476]
Welcome to FirebaseUI and thanks for submitting an issue!

✅ Please take a look at [open issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

✅ If your issue concerns the CocoaPods error, "...transitive dependencies that include static binaries", please take a look at any of the following issues and see if your problem is solved: #48, #47, #46, #34, #23.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

 * I'm in the right place * ✅

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Objective C 
  * iOS version: 11.4
  * Firebase SDK version: 5.0.2
  * FirebaseUI version: 5.0.1
  * CocoaPods Version: 1.5.3
  
### Step 3: Describe the problem:

Getting a crash inside Firebase components logic. (right after typing in phone number and taping 'Verify')

I understand it can be wrong use of GTMSessionFetcher in the Firebase Auth code, but also, crash happens inside this code: `GTMSessionFetcherService fetcherDidBeginFetching:`

Maybe you can suggest at least correct configuration for session fetcher to work properly? 

#### Steps to reproduce:

  1. open Firebase Phone login page (see code example below)
  2. input your phone number
  3. press "Verify'
💥
  
#### Observed Results:

```
Fatal Exception: NSInvalidArgumentException-[GTMSessionFetcher setFetcher:forTask:]: unrecognized selector sent to instance 0x10e429360 Raw Text
--
0 | CoreFoundation | __exceptionPreprocess
4 | CoreFoundation | _CF_forwarding_prep_0
5 | GTMSessionFetcher | GTMSessionFetcherService.m line 441-[GTMSessionFetcherService fetcherDidBeginFetching:]
6 | GTMSessionFetcher | GTMSessionFetcher.m line 894-[GTMSessionFetcher beginFetchMayDelay:mayAuthorize:]
7 | - | FIRAuthBackend.m line 545-[FIRAuthBackendRPCIssuerImplementation asyncPostToURLWithRequestConfiguration:URL:body:contentType:completionHandler:]
8 | - | FIRAuthBackend.m line 809-[FIRAuthBackendRPCImplementation postWithRequest:response:callback:]
9 | - | FIRAuthBackend.m line 701-[FIRAuthBackendRPCImplementation sendVerificationCode:callback:]
10 | - | FIRAuthBackend.m line 469+[FIRAuthBackend sendVerificationCode:callback:]
11 | - | FIRPhoneAuthProvider.m line 401__110-[FIRPhoneAuthProvider verifyClientAndSendVerificationCodeToPhoneNumber:retryOnInvalidAppCredential:callback:]_block_invoke.205
12 | - | FIRPhoneAuthProvider.m line 410-[FIRPhoneAuthProvider verifyClientWithCompletion:]
13 | - | FIRPhoneAuthProvider.m line 402-[FIRPhoneAuthProvider verifyClientAndSendVerificationCodeToPhoneNumber:retryOnInvalidAppCredential:callback:]
14 | - | FIRPhoneAuthProvider.m line 340__61-[FIRPhoneAuthProvider internalVerifyPhoneNumber:completion:]_block_invoke
15 | - | FIRAuthNotificationManager.m line 173-[FIRAuthNotificationManager callBack]
16 | - | FIRAuthNotificationManager.m line 146-[FIRAuthNotificationManager canHandleNotification:]
17 | - | FIRAuth.m line 1412__33-[FIRAuth canHandleNotification:]_block_invoke

```
  
#### Expected Results:

  * Would like to proceed to the SMS code entry page
  
#### Relevant Code:

_Here's how I'm using FirebaseAuth_
  ```
 FUIAuth *authUI = [FUIAuth defaultAuthUI];
    authUI.signInWithEmailHidden = YES;
    authUI.delegate = self;
    
    FUIPhoneAuth *provider = [[FUIPhoneAuth alloc] initWithAuthUI:authUI];
    authUI.providers = @[provider];
    [provider signInWithPresentingViewController:vc phoneNumber:mobileNumber];
  ```

**Comment by morganchen12** [comment]
Can you try adding the `-ObjC` linker flag to your build settings and running it again?

**Comment by gelosi** [comment]
@morganchen12 it's there, I'm using a lot of ObjC stuff from pods...

**Comment by morganchen12** [comment]
Can you share your project?

**Comment by gelosi** [comment]
Hello @morganchen12 - want to save your eyes from bleeding, and my ass from infringement,
I'm happy to give you some part of data, let's start from `OTHER_LDFLAGS ` : 


`grep "OTHER_LDFLAGS" -R . | grep GTM`

`./Pods/Target Support Files/GTMSessionFetcher/GTMSessionFetcher.xcconfig:OTHER_LDFLAGS = -framework "Security"`

`grep "OTHER_LDFLAGS" -R . | grep Firebase`

`./Pods/Target Support Files/FirebaseCore/FirebaseCore.xcconfig:OTHER_LDFLAGS = -framework "Foundation" -framework "SystemConfiguration"
./Pods/Target Support Files/FirebaseAuth/FirebaseAuth.xcconfig:OTHER_LDFLAGS = -framework "Security"
./Pods/Target Support Files/FirebaseUI/FirebaseUI.xcconfig:OTHER_LDFLAGS = -framework "UIKit"
`

Meanwhile, main project configured that way:

`./Pods/Target Support Files/Pods-☣️-dev/Pods-☣️-dev.release.xcconfig:OTHER_LDFLAGS = $(inherited) -ObjC -l"CardIO" -l"GoogleAnalytics" -l"c++" -l"opencv_core" -l"opencv_imgproc" -l"sqlite3" -l"z" -framework "AFNetworking" -framework "AVFoundation" -framework "Accelerate" -framework "AudioToolbox" -framework "Bolts" -framework "CMPopTipView" -framework "CRToast" -framework "CoreData" -framework "CoreGraphics" -framework "CoreLocation" -framework "CoreMedia" -framework "CoreVideo" -framework "Crashlytics" -framework "FBSDKCoreKit" -framework "Fabric" -framework "FirebaseAuth" -framework "FirebaseCore" -framework "FirebaseUI" -framework "Foundation" -framework "GTMSessionFetcher" -framework "GoogleMapsBase" -framework "GooglePlaces" -framework "GoogleToolboxForMac" -framework "MessageThrottle" -framework "MobileCoreServices" -framework "NKJWT" -framework "OpenGLES" -framework "QuartzCore" -framework "SCLAlertView_Objective_C" -framework "Security" -framework "Stripe" -framework "SystemConfiguration" -framework "Toast" -framework "TrustKit" -framework "UICKeyChainStore" -framework "UIKit" -framework "☣️Core" -framework "libPhoneNumber_iOS"`

**Comment by gelosi** [comment]
Actually, I see now where's -ObjC is missing...

**Comment by morganchen12** [comment]
Your comment seems to be missing the flags for your main app target (shows only Pod targets, unless I'm mistaken). Were you able to solve this?

**Comment by hawk-ukr** [comment]
@gelosi hi, i'm having the same issue. Did you manage to fix it? Could you please provide more details?

**Comment by hawk-ukr** [comment]
My issue was resolved only by moving back to FirebaseAuth 4.6.1 (version that I previously used) instead of the latest 5.0.4 atm.

**Comment by thetminko** [comment]
How is this issue fixed?

**Comment by gelosi** [comment]
@thetminko  issue is inside another dependency: google session fetcher

there's approved MR solving the issue

https://github.com/google/gtm-session-fetcher/pull/142/files

**Comment by thetminko** [comment]
@gelosi I was using pod version 1.7.5. 
This is my Podfile.lock
FirebaseAuth (6.1.2):
FirebaseAuthInterop (~> 1.0)
FirebaseCore (~> 6.0)
GoogleUtilities/AppDelegateSwizzler (~> 6.2)
GoogleUtilities/Environment (~> 6.2)
**GTMSessionFetcher/Core (~> 1.1)**

Is it because FirebaseAuth was using GTMSessionFetcher 1.1? I saw the fix is in 1.2.2.

**Comment by gelosi** [comment]
@thetminko  Yepp, try to update GTMSessionFetcher pod

**Comment by thetminko** [comment]
@gelosi, 
I tried using
**Pod 'Firebase/Auth'** instead of specifying the version.
This installed 6.7.0 version.
It is still crashing.

This is my Podfile.lock
  - Firebase/Auth (6.7.0):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 6.2.3)
  - Firebase/CoreOnly (6.7.0):
    - FirebaseCore (= 6.2.1)
  - FirebaseAuth (6.2.3):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.2)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.2)
    - GoogleUtilities/Environment (~> 6.2)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseAuthInterop (1.0.0)

**Comment by gelosi** [comment]
well, yepp, looking at firebase's dependencies:
https://github.com/firebase/firebase-ios-sdk/blob/5fd5ed2131730bf8806b405410d1dd8ddda37ecf/FirebaseAuth.podspec#L68

we can tell, it's still using buggy version of fetcher ¯\_(ツ)_/¯

maybe you can try cloning firebase, updating dependency and use it for yourself now, 
also – if it fixes your problem – you can send back MR

**Comment by thetminko** [comment]
@gelosi Thanks and appreciate for helping.
