### ISSUE TITLE
Unable to install through CocoaPods

### ISSUE THREAD

**Issue by pvub** [firebase/FirebaseUI-iOS#48]
Using cocoapods 0.39.0

Using with swift. This is what I have in my podfile:

platform :ios, '8.0'
use_frameworks!

# Only pull in the "Core" FirebaseUI features
pod 'FirebaseUI/Core', '~> 0.3'

# Pull in the "Auth" FirebaseUI features: Facebook, Google, Twitter, and Email/Password auth
pod 'FirebaseUI/Auth', '~> 0.3'

# Selectively pull in Auth providers
pod 'FirebaseUI/Facebook', '~> 0.3.2'
pod 'FirebaseUI/Google', '~> 0.3.2'
pod 'FirebaseUI/Twitter', '~> 0.3.2'
pod 'FirebaseUI/Password', '~> 0.3.2'

Seeing this error:

[!] The 'Pods' target has transitive dependencies that include static binaries: (...../Pods/Google/Libraries/libGGLCore.a and ...../Pods/Google/Libraries/libGGLSignIn.a)

**Comment by mcdonamp** [comment]
Hey there, thanks for submitting the issue. This is a known issue (see #47, #46, #34, #23) that we can't solve until Google makes their pod able to be dynamic (or CocoaPods fixes this issue).
