### ISSUE TITLE
Login with Facebook error: "User can not view this application due to developer settings"

### ISSUE THREAD

**Issue by oligazar** [firebase/FirebaseUI-iOS#485]
Describe your environment

  * Objective C or Swift: ____Swift
  * iOS version: _____10.0
  * Firebase SDK version: _____4.0.20
  * FirebaseUI version: ____4.5.5
  * CocoaPods Version: ____1.5.0
  
### Describe the problem:

At first I was getting known `"This app is in development mode”` error when trying to auth with FirebaseUI + Facebook. This was solved by making the app "available to the general public". After that I'm getting another error which reads:
`"The user does not have sufficient rights to view the application. User can not view this application due to developer settings"`

I followed all official instructions on setting up firebase & facebook in my app (info.plist, url types), tried different settings on developers.facebook.com, still don't understand what might cause the issue. On android version of the app login with Facebook works fine.
  
#### Relevant Code:
Presenting AuthViewController
  ```
  func showAuthUI(delegate: FUIAuthDelegate) {
    presentModalViewControllerDerivedFrom({ (_) -> UIViewController in
        let authUI = FUIAuth.defaultAuthUI()
        authUI?.delegate = delegate
        let authViewController = authUI!.authViewController()
        return authViewController
    }, animation: true, completion: nil)
}
  ```
FUIAuthDelegate
```
extension ProfilePresenter: FUIAuthDelegate {

    func authUI(_ authUI: FUIAuth, didSignInWith authDataResult: AuthDataResult?, error: Error?){
        if let error = error as NSError? {
            if let errorMessage = error.userInfo["NSLocalizedDescription"] as? String {
                //Show Alert with message provided in 'errorMessage'
                print("auth ui didSignInWith authDataResult, error: \(errorMessage)")
            } else {
                //Show General Alert
                print("auth ui didSignInWith authDataResult, general error")
            }
        } else if let user = authDataResult?.user {
            //Logged in
            // ...
        } else {
            // Unknow State
            print("auth ui didSignInWith authDataResult, unknown state")
        }
    }
}
```

AppDelegate
```
override init() {
        super.init()
        FirebaseApp.configure()
        let authUI = FUIAuth.defaultAuthUI()
    }

  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey : Any]? = nil) -> Bool {

        let authUI = FUIAuth.defaultAuthUI()

        let providers: [FUIAuthProvider] = [
            FUIGoogleAuth(),
            FUIFacebookAuth(permissions: ["public_profile", "email"]),
            FUIPhoneAuth(authUI:FUIAuth.defaultAuthUI()!),
            ]
        authUI?.providers = providers

        return true
    }

  func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any]) -> Bool {
        let sourceApplication = options[UIApplicationOpenURLOptionsKey.sourceApplication] as! String?
        if FUIAuth.defaultAuthUI()?.handleOpen(url, sourceApplication: sourceApplication) ?? false {
            return true
        }
        // other URL handling goes here.
        return false
    }
```
Login with other providers works just fine. Thanks in advance for any help.

**Comment by morganchen12** [comment]
This sounds like a Facebook issue and not a FirebaseUI issue. Consider also asking on StackOverflow or sending a ticket to [Facebook developer support](https://developers.facebook.com/support).

**Comment by oligazar** [comment]
I've asked on SO, with no luck. Facebook support replied that they "don't support unofficial Facebook SDKs". Maybe somebody can explain what the error message "User can not view this application due to developer settings" actually means?

**Comment by morganchen12** [comment]
The only thing I was able to find was this [Facebook developers page](https://developers.facebook.com/docs/apps/security/), which seems to suggest that all you have to do is toggle a setting in the app dashboard. However, since you're able to sign in on Android without issue, I doubt this is the cause of your problems. Are you able to reproduce this issue without FirebaseUI?
