### ISSUE TITLE
Localization missing for privacy policy

### ISSUE THREAD

**Issue by xuaninbox** [firebase/FirebaseUI-iOS#489]
* Objective C or Swift: swift
  * iOS version: 12.0
  * Firebase SDK version: 5.4.1
  * FirebaseUI version: 5.1.3
  * CocoaPods Version: latest
  
Localization is missing for the newly added terms of service and privacy policy

![photo-1](https://user-images.githubusercontent.com/5108256/43343156-0da9a1a0-919a-11e8-9fcb-641cd5a68de1.jpg)
![photo-1 1](https://user-images.githubusercontent.com/5108256/43343157-0dbd0c2c-919a-11e8-9f88-57f1decd5c76.jpg)

**Comment by xuaninbox** [comment]
Also the cell selection style should be .none

**Comment by Yue-Wang-Google** [comment]
We're working on the translation strings. It will take some time.
