### ISSUE TITLE
Different apps use the same authentication. How to disable it？

### ISSUE THREAD

**Issue by yujia917** [firebase/FirebaseUI-iOS#492]
Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 11.2.6
  * Firebase SDK version: 4.9.0
  * FirebaseUI version: 4.5.5
  * CocoaPods Version: 1.5.3
  
Describe the problem:

I have three different targets in the same project. All the targets use the same database and they are for different types of users. Currently, if I install these three apps on my phone and login one of them, it will automatically login when I open the other two apps (Auth.auth().currentUser is not nil). How to avoid this? For my use case,  one user needs three different accounts to access these three apps.

**Comment by morganchen12** [comment]
You should use three different Firebase projects in this case. Is there any reason you're using the same Firebase project for all three apps?
