### ISSUE TITLE
Accessing keychain error!!

### ISSUE THREAD

**Issue by r9hacks** [firebase/FirebaseUI-iOS#508]
During auth by phone after entering the 6-digit I got this error:

An error occurred when accessing the keychain. The @c NSLocalizedFailureReasonErrorKey field in the @c NSError.userInfo dictionary will contain more information about the error encountered

first I try enable keychain sharing in the capabilities its work for the first time then after sign-out and re-auth I get this error. 

Any idea how to fix it?

**Comment by morganchen12** [comment]
Can you print the full error object and post it here?

**Comment by r9hacks** [comment]
how to print full error object? I can have two variable only under error,
localizedDescription (same as above) &  debugDescription 

Optional(Error Domain=FIRAuthErrorDomain Code=17995 "An error occurred when accessing the keychain. The @c NSLocalizedFailureReasonErrorKey field in the @c NSError.userInfo dictionary will contain more information about the error encountered" UserInfo={NSLocalizedDescription=An error occurred when accessing the keychain. The @c NSLocalizedFailureReasonErrorKey field in the @c NSError.userInfo dictionary will contain more information about the error encountered, error_name=ERROR_KEYCHAIN_ERROR, NSLocalizedFailureReason=SecItemAdd (-34018)})

is that what you need ?

**Comment by r9hacks** [comment]
Im running this on device.
Also I try disable keychain sharing from capabilities and the error is gone, but only for one time.
then it start showing again even when keychain sharing is On.

**Comment by r9hacks** [comment]
After adding my phone number for test in firebase the error is gone, is this a random error or just in development? also can I disable the alert message that come on screen, I don't wanna show this kind of message to the user.

**Comment by morganchen12** [comment]
From what you've described, it sounds like a random error/bug. Adding your phone number in Firebase console for testing purposes shouldn't affect Keychain behavior.

**Comment by r9hacks** [comment]
I think It's a random bug, because sometimes it logged me in without errors.Now, after I sign out using Auth.auth().signOut() and try to use FurebaseUI phones I get this Error

Sep 11 08:20:57 <Error>: 5.7.0 - [Firebase/InstanceID][I-IID010003] Unable to generate keypair.
Sep 11 08:20:57 <Error>: 5.7.0 - [Firebase/InstanceID][I-IID010009] Keypair could not be loaded from Keychain. Error: Error Domain=com.firebase.iid Code=-34018 "(null)"
Sep 11 08:20:57 <Warning>: 5.7.0 - [Firebase/Analytics][I-ACS020001] Failed to get InstanceID: Error Domain=com.firebase.iid Code=-34018 "(null)"
Sep 11 08:20:57 <Error>: 5.7.0 - [Firebase/InstanceID][I-IID009001] Error removing keypair status: -34018
Sep 11 08:20:57 <Error>: 5.7.0 - [Firebase/InstanceID][I-IID010007] Unable to remove RSA keypair

I think this may be the main reason for the first error.
by the way I'm running the app on iPhone 6.

I tried to reinstall the app, enable/disable keychain sharing. but none of these seems to work.
now I can't use FUIPhoneAuth anymore.

**Comment by morganchen12** [comment]
@r9hacks I commented in your other issue--make sure you have the appropriate background modes enabled.

**Comment by victor-sarda** [comment]
Hi, we just got a report with the same issue this morning. 
I'm using **Firebase 5.10** with **FirebaseUI 5.2.2**
This happened on an **iPhone 5** running **iOS 10.3.3**.

Reports says:
> An error occurred when accessing the keychain. The @c NSLocalizedFailureReasonErrorKey field in the @c NSError.userInfo dictionary will contain more information about the error encountered

I don't have keychain sharing enabled, do you think enabling it would fix the issue? Thanks
