### ISSUE TITLE
how to change FUIPhoneAuth language?

### ISSUE THREAD

**Issue by r9hacks** [firebase/FirebaseUI-iOS#509]
I wanna change the language to Arabic for FUIPhoneAuth so try using this:

FUIAuth.defaultAuthUI()?.auth?.languageCode = "ar"

but still it give me the default language of the device.

**Comment by morganchen12** [comment]
This is currently unsupported; FirebaseUI always uses the default language of the device. We're unlikely to add this feature in the near future but if you're willing to submit a PR I'm happy to review it.

**Comment by morganchen12** [comment]
Closing since this hasn't seen much interest.
