### ISSUE TITLE
Twitter Login

### ISSUE THREAD

**Issue by radvansky-tomas** [firebase/FirebaseUI-iOS#520]
With latest firebase UI, I cannot login/register using twitter social login.

First of all, library is making duplicate classes:

`objc[2726]: Class TWTRUserAuthRequestSigner is implemented in both /private/var/containers/Bundle/Application/2167ED41-636F-4826-8EDA-606398020CFB/timerush.app/Frameworks/TwitterKit.framework/TwitterKit (0x1071982e8) and /private/var/containers/Bundle/Application/2167ED41-636F-4826-8EDA-606398020CFB/timerush.app/Frameworks/TwitterCore.framework/TwitterCore (0x106ecd2a0). One of the two will be used. Which one is undefined.`

Then documentation is outdated, as to start twiter you have to call: 
TWTRTwitter.sharedInstance().start

But even after that, i cannot login, twitter page is not presented!

**Comment by meilers** [comment]
Having the same issue. This is the error I see in my logs:
`[TwitterKit] Error obtaining user auth token`

**Comment by meilers** [comment]
This might help: https://twittercommunity.com/t/ios-twitter-login-error-code-415/107775

**Comment by radvansky-tomas** [comment]
I tried new version of FirebaseUI 5.2.2

I have configuration in app delegate:
```
TWTRTwitter.sharedInstance().start(withConsumerKey:"A54...",
                                        consumerSecret:"1lgd...")
```

I've set URL Scheme to:
`twitterkit-A54...`

On my view controller I've added twitter provider:
`providers.append(FUITwitterAuth())`

And yet after clicking to Firebase UI Twitter button got exception: 
Selected Auth provider is not yet configured

Provider is enabled in console!

**Comment by morganchen12** [comment]
Closing since this has staled and seems to be a configuration issue.
