### ISSUE TITLE
"Module 'FirebaseUI' not found" ('FirebaseCore' also not found)

### ISSUE THREAD

**Issue by msaia35** [firebase/FirebaseUI-iOS#526]
Step 2: Describe your environment

  * Objective C or Swift: Objective C
  * iOS version: 10.3
  * Firebase SDK version: 5.8.0
  * FirebaseUI version: 5.2.2
  * CocoaPods Version: 1.5.3
  
Step 3: Describe the problem:

I added the Firebase framework to my podfile with no issue. I followed that up with trying to add the FirebaseUI framework. When I try to run my project, I receive an error in AppDelegate.m (Module 'FirebaseUI' not found), and in FUIAuthStrings.m (Module 'FirebaseCore' not found).

Steps to reproduce:

  1. add "pod 'FirebaseUI/Auth'" to podfile
![screen shot 2018-09-17 at 7 53 56 pm](https://user-images.githubusercontent.com/26585209/45658229-8484ad00-bab3-11e8-97c5-46dd9f2c37ca.png)
  2. $ pod install
  3. add "@import FirebaseUI" to AppDelegate.m
  4. Cmd R 
  
Observed Results:

Build Failed with two errors:
![screen shot 2018-09-16 at 6 42 09 pm](https://user-images.githubusercontent.com/26585209/45658350-21474a80-bab4-11e8-939d-702520d201e8.png)
![screen shot 2018-09-16 at 6 42 24 pm](https://user-images.githubusercontent.com/26585209/45658353-24423b00-bab4-11e8-992d-296d393765da.png)

  
Expected Results:

Build Succeeded

**Comment by morganchen12** [comment]
`FirebaseUI` should have a lowercase `b` and you should be specifying `use_frameworks!` in your Podfile.

**Comment by msaia35** [comment]
Neither of those worked, I am going to post a new issue

**Comment by Rj707** [comment]
@msaia35 did you open a new issue???? M facing the same issue.  @morganchen12  Need a solution for this..

**Comment by morganchen12** [comment]
I wasn't able to reproduce the issue you're describing. Consider asking on StackOverflow, since it seems like this may not be a FirebaseUI-specific issue.
