### ISSUE TITLE
Country codes in phone number field being treated as invalid

### ISSUE THREAD

**Issue by andyboyd** [firebase/FirebaseUI-iOS#529]
### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 12
  * Firebase SDK version: 5.8.1
  * FirebaseUI version: 5.2.2
  * CocoaPods Version: 1.5.3
  
### Step 3: Describe the problem:

Phone number validation fails if the user enters the country code in the phone number field

#### Steps to reproduce:

  1. Enter phone number authentication flow
  2. Select a country (e.g. UK +44)
  3. Enter valid phone number including country code (e.g. +44 7xx xxx xxx). This is often provided by the iOS default keyboard as a suggestion.
  
#### Observed Results:

  * Alert is presented saying "Enter a valid phone number"
  
#### Expected Results:

  * Phone number should be accepted, verification code sent, and user should be navigated to the verification screen

**Comment by cspecter** [comment]
Has this issue been looked in to? We are running across this frequently. Many users are reporting that the iOS default keyboard suggestion is formatted like this: "+1 (444) 444-4444" or "+1234567890" both which fail. It will only accept numbers without the + in front.

**Comment by Yue-Wang-Google** [comment]
@cspecter, I believe the fix was already merged last Sep.

**Comment by cspecter** [comment]
I am on FirebaseUI 5.2.2, which is listed as the latest, released on Sept 12 and it is definitely still happening.

**Comment by Yue-Wang-Google** [comment]
Then it's just a versioning issue. 
You can fix your app by manually patching/using the trunk version/swizzling the method. 
when the next version is able to cut @morganchen12  will release it.

**Comment by cspecter** [comment]
Ok, will do. Thanks!

**Comment by Yue-Wang-Google** [comment]
sounds good. the commit you want to cherrypick is https://github.com/firebase/FirebaseUI-iOS/commit/e2612ec5075c8eb679ad0430b98e6e3a301df38f.
