### ISSUE TITLE
FirebaseAppDelegate requires a deprecated method

### ISSUE THREAD

**Issue by psopher** [firebase/FirebaseUI-iOS#55]
Hi,

This isn't an urgent issue, but I've noticed that FirebaseAppDelegate requires this method:

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation;

But that method is deprecated in iOS 9. It has been changed to this:

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(nonnull NSDictionary<NSString *,id> *)options

**Comment by mcdonamp** [comment]
Hrm, yeah, sounds good. Mind submitting a PR for this?

**Comment by psopher** [comment]
Ok, sure. What's a PR haha? I'm on the newer side to all this and don't know all the lingo yet

**Comment by mcdonamp** [comment]
PR == Pull Request, essentially where you submit a proposed change, and the owners of the repo can review and merge. [Here's a good overview of the flow](https://www.thinkful.com/learn/github-pull-request-tutorial/#Time-to-Submit-Your-First-PR) that you can follow and apply to this project.

**Comment by morganchen12** [comment]
Hey @psopher, are you still working on this?

**Comment by psopher** [comment]
No, you can close it. It's irrelevant now with the new Firebase anyways
