### ISSUE TITLE
Ability to reverse the contents of the FirebaseArray.

### ISSUE THREAD

**Issue by cgossain** [firebase/FirebaseUI-iOS#57]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If your issue concerns the CocoaPods error, "...transitive dependencies that include static binaries", please take a look at any of the following issues and see if your problem is solved: #48, #47, #46, #34, #23.

If not, please feel free to fill in the following info so we can help faster!

### Details:
Not relevant for this issue.

### Explanation of your issue

Currently, a "queryOrderedByChild:" with Firebase can only returns results in ascending order. A quick fix for this would be to provide a flag on the FirebaseArray that would simply reverse the order of the returned results. This would also mean that change notifications would be interpreted in the reverse order as well (i.e. inserts, deletes, moves, would have their indices interpreted in the reverse order if this flag were enabled). Of course this flag should not care about the type of query you are doing, all it would do is interpret any data in the array in the reverse order.

### Steps to reproduce
Not relevant for this issue.

**Comment by mcdonamp** [comment]
This is fixed in #12, so feel free to fork that code and try it out, I'd love some feedback on the API.
