### ISSUE TITLE
GIDSignInButton in Swift doesn't work

### ISSUE THREAD

**Issue by av8ramit** [firebase/FirebaseUI-iOS#574]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If your issue concerns the CocoaPods error, "...transitive dependencies that include static binaries", please take a look at any of the following issues and see if your problem is solved: #48, #47, #46, #34, #23.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 11.0
  * Firebase SDK version: 4.13.0
  * GoogleSignIn (4.2.0)

### Step 3: Describe the problem:
I am following [these instructions](https://firebase.google.com/docs/auth/ios/google-signin) and I have added a GIDSignInButton. For some reason pressing it does nothing. I expect it to launch a view where I log into gmail. Do I need the gmail app on the phone as well? I'm running in a simulator. I've followed all the other steps and have done the necessary updates to my UIViewController where login logic occurs.

#### Steps to reproduce:

  1. Setup AppDelegate, and the Login ViewController.
  2. Add a UIView and set up the class.
  3. Run the simulator and press the G-SignIn button.
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.
The button doesn't do anything.
  
#### Expected Results:

  * What did you expect to happen?
Pressing the gmail button should allow me to authenticate with gmail.
  
#### Relevant Code:

```

    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.hideKeyboard()
        self.emailOrUsernameTextField.delegate = self
        self.passwordTextField.delegate = self
        self.spinner = setupSpinner(view: self.view, inverted: true)
        
        
        // Enable the Google Sign In Button
        GIDSignIn.sharedInstance().uiDelegate = self
        GIDSignIn.sharedInstance().signIn()
    }

func sign(_ signIn: GIDSignIn!, didSignInFor user: GIDGoogleUser!, withError error: Error?) {
  // ...
  if let error = error {
    // ...
    return
  }

  guard let authentication = user.authentication else { return }
  let credential = GoogleAuthProvider.credential(withIDToken: authentication.idToken,
                                                    accessToken: authentication.accessToken)
  // Authentication logic
}
```

**Comment by morganchen12** [comment]
Does pressing the button cause your app to crash?

**Comment by morganchen12** [comment]
Can you share your code or a reproducible example?
