### ISSUE TITLE
sample apps?

### ISSUE THREAD

**Issue by abbeyjackson** [firebase/FirebaseUI-iOS#58]
Are there any sample apps? I am having a difficult time with this. FIRAuthUI is not recognized as a class, only FIRAuth is and I'm not sure why.

**Comment by mcdonamp** [comment]
Hey @abbeyjackson, good question. We haven't yet updated the sample app (sorry :( ), though I'll get to it in the next day or so (after the madness of this release has settled down some).

If you use `pod 'FirebaseUI/Auth'` and `import Firebase` and `import FirebaseAuthUI` both of these classes should be recognized (`FIRAuth` from the former, `FIRAuthUI` from the latter). Can you give me some additional info on which version of CocoaPods you're using, if you're using Swift or Obj-C, etc.?

**Comment by abbeyjackson** [comment]
oh well you know what, it was quite late and I didn't even clue in to the fact that I wasn't importing. I was just following the readme and it doesn't mention import. I'm sure if I had done `import FirebaseAuthUI` it would have worked fine as the normal `import Firebase` works for the standard framework. Now that Parse is gone a lot of newer devs are going to be using Firebase, especially with the new update, you should probably add that to your readme for those that don't know better.

**Comment by mcdonamp** [comment]
Yep, looks like we forgot that :( added in 569f368b3ead286b8285f16cc287b2dcf3a97e01

I totally understand the new devs sentiment: we're working hard to ensure that our onboarding experience is rock solid, even for people who have never programmed before.
