### ISSUE TITLE
Firebase Phone Number Validation not working properly

### ISSUE THREAD

**Issue by Nilesh-Jha-14** [firebase/FirebaseUI-iOS#580]
When I am selecting India as Country code. The validation which is must is the phone number should be 10 digits. But when I am entering 4 digits its giving me proper error code phone number TOO SHORT. But when I enter 9 digits it allows me and take me to OTP screen. How to solve this problem?

**Comment by morganchen12** [comment]
@Nilesh-Jha-14 I'm not entirely sure what you mean. Can you upload a video/gif of the issue?

**Comment by Nilesh-Jha-14** [comment]
Uploaded document FireBase PhoneNumber verification issue, Please revert back asap.

[FireBasePhoneNumberValidation.docx](https://github.com/firebase/FirebaseUI-iOS/files/2812418/FireBasePhoneNumberValidation.docx)

**Comment by morganchen12** [comment]
This doc doesn't contain any new information. Please upload a sample project that reproduces the issue.
