### ISSUE TITLE
PhoneAuth Doesn't work in App Store But Works In Simulator

### ISSUE THREAD

**Issue by dahn88** [firebase/FirebaseUI-iOS#584]
Swift - 4
Xcode - 10.1
Deployment Target - 12.1
Firebase - 5.3.0
FirebaseUI - 5.0.1
CocoaPods - 1.5.3

I'm currently using the FirebaseUI iOS Phone Auth and have been for a few months with no issues. I've released an iOS specific mobile app in the app store with no problems because everything went smoothly with Apple but it doesn't seem to want to log in after I download from the store. It just displays an alert saying "Something went wrong. Please try again."

![img_0370](https://user-images.githubusercontent.com/2236563/50943620-112bf000-1442-11e9-838c-e0b0d6a5cc7b.PNG)

The funny thing is that it works 100% fine in the simulator or if I build it directly with Xcode and use my physical device and occasionally will work when it's downloaded from the app store but it's pretty rare.

Any suggestions?

**Comment by morganchen12** [comment]
@renkelvin, any idea why this could be happening?

**Comment by dahn88** [comment]
Hey ya'll sorry for the late response, it's been a busy couple days for me.

Yeah so I think the issue had to do with APNS certificate. I honestly don't exactly know what the problem was but I was messing around with the APNS stuff and it just seemed to work one day.
It probably is due to the new iOS update.

Thanks for the help.

**Comment by wboelte** [comment]
Found this posting while searching for an answer to a very similar problem:

Our phone # verification was working in simulators but not on any physical devices - we finally saw this article and changed the APN key in firebase cloud messaging tab to a 2nd one that we created and it now works - no idea why the first APN key was not working.
