### ISSUE TITLE
Any plans to support React Native?

### ISSUE THREAD

**Issue by joonhocho** [firebase/FirebaseUI-iOS#59]
Any plans to support React Native both ios and android in the future?

**Comment by mcdonamp** [comment]
It looks like there are a number of people asking about this on our [Google Group](https://groups.google.com/forum/#!forum/firebase-talk), which is probably going to be the better place to discuss.

**Comment by joonhocho** [comment]
thanks!

Regards,
Joon Ho Cho

On Sun, May 22, 2016 at 10:40 AM, Michael McDonald <notifications@github.com

**Comment by sbefort** [comment]
+1

**Comment by sibelius** [comment]
👍

**Comment by sagivo** [comment]
+1

**Comment by MichelDiz** [comment]
+1

**Comment by morganchen12** [comment]
I currently have no plans to support React Native. I know RN generates an xcodeproj which you can presumably use CocoaPods with; what are we missing in this project for RN support?

**Comment by MichelDiz** [comment]
Some devs are moving to RN. RN is improving support to multi-platform and that means "popularity". You code can be used by far for more projects. Even creating a module whose support only the IOS has value. You can open the door to others fork you and support others platforms.

The question is - Why not? Enjouy the Hype. Get traction, get atention. Improove your self! We thankful!

**Comment by morganchen12** [comment]
I'm aware of the benefits of RN, but we don't have plans because supporting platforms comes with a non-trivial maintenance cost. The reason I ask what FirebaseUI is missing is because I'd like to know what that cost is, to assess if supporting RN is worthwhile.

Can you not [already use CocoaPods with RN](https://facebook.github.io/react-native/releases/0.23/docs/embedded-app-ios.html) and then just call FirebaseUI code natively?

**Comment by joonhocho** [comment]
@morganchen12 
Yes, it can be done.
In my own experience, creating a RN bridge for iOS or Android native libraries is not too hard, but also not trivial. It requires a bit of experience on both iOS and Android,
 thus Objective-C/Swift and Java. I have done it for few SDKs such as Google SignIn or LinkedIn SDK, and each took around a week to setup and publish without any automatic tests. They also require some maintenance as people file issues on different platforms and devices.
They were rather simple ones as they only wrap around simple api calls, but FirebaseUI involves UI interactions, so I'd assume there will be more issues and edge cases.
I just hope Firebase officially supports React Native as it seems like a promising and increasingly popular platform that will be around for a while.
I'd prefer to install official library and not worry about versions, breaking changes, and testing edge cases, and so on, than bridging it manually.

**Comment by MichelDiz** [comment]
Okay, I'm determined to do that. But I do not know where to start (I start to Google it). Are there any articles that teach how to do this work? step by step? IOS and Android. In particular RN. How maintenance is costly, I think doing something individual (even if complicated) is the best thing to so.

**Comment by joonhocho** [comment]
@MichelDiz You can look at https://facebook.github.io/react-native/docs/native-modules-ios.html native modules sections for iOS and Android. They are helpful, then also look at some existing projects on GitHub.

**Comment by morganchen12** [comment]
Thanks @joonhocho.

Increasing adoption of RN will definitely be the biggest driver in FirebaseUI adopting RN support, but  it probably still won't be a priority for a while.
