### ISSUE TITLE
OSX Support

### ISSUE THREAD

**Issue by mcdonamp** [firebase/FirebaseUI-iOS#6]
`NSTableView` and `NSCollectionView` deserve to be supported too.
  1. Add an `NSTableViewDataSource` and `NSCollectionViewDataSource`.
  1. Change build process to generate both iOS and OSX libraries.
  1. Update FirebaseUI.podspec for both iOS and OSX.

**Comment by grantkemp** [comment]
Yes please

**Comment by mcdonamp** [comment]
Will close for now, open for re-evaluation in the future (especially when looking at watchOS and tvOS support).
