### ISSUE TITLE
FUIEmailAuth not found

### ISSUE THREAD

**Issue by wimbledon** [firebase/FirebaseUI-iOS#601]
In the latest SDK version 6.0.0, the FUIEmailAuth is not included. Thus, there is no way to add FUIEmailAuth to the auth providers to enable email sign in.

**Comment by wimbledon** [comment]
Solved my own issue by:
`pod 'FirebaseUI/Email'`

**Comment by AndrewGable** [comment]
To hopefully help others: I ran into a similar issue when customizing `FUIEmailEntryViewController`

> `Use of undeclared type 'FUIEmailEntryViewController'`

[This](https://github.com/firebase/FirebaseUI-iOS/issues/601#issuecomment-458337176) fixed it 👍
