### ISSUE TITLE
Rare crash with password generator keyboard

### ISSUE THREAD

**Issue by xuaninbox** [firebase/FirebaseUI-iOS#605]
In Jun last year i did a pr to add support for the iOS12 password generator keyboard:

https://github.com/firebase/FirebaseUI-iOS/commit/5f78b9a2eb34bdbcefbb0b3c2780922726f56478

but due to this issue:

https://openradar.appspot.com/46094354

We have seen crashes happening on the FUIPasswordSignUpViewController, maybe this feature should be removed for now until apple fix it?

**Comment by morganchen12** [comment]
The linked stackoverflow question mentions the Firebase/Performance as being a contributor to the crash. Are you using Performance, or does the crash reproduce without it?

**Comment by xuaninbox** [comment]
Yes we do use Performance but we haven't seen this crash before adding the auto password generator, maybe they are related?

**Comment by morganchen12** [comment]
Seems related to this issue: https://github.com/firebase/firebase-ios-sdk/issues/2283

We can disable the password autofill, but I'd also like to leave it available for users who aren't using Firebase Performance.

**Comment by morganchen12** [comment]
This should be reverted once https://github.com/firebase/firebase-ios-sdk/issues/2283 has been released.

**Comment by xuaninbox** [comment]
This can now be reverted. thx~

**Comment by xuaninbox** [comment]
https://github.com/firebase/FirebaseUI-iOS/pull/667

**Comment by renkelvin** [comment]
@xuaninbox Seems the pr above is discarded. Do you want to revert it again?

**Comment by xuaninbox** [comment]
https://github.com/firebase/FirebaseUI-iOS/pull/682
