### ISSUE TITLE
Crash using Twitter Login 

### ISSUE THREAD

**Issue by leverdeterre** [firebase/FirebaseUI-iOS#616]
Welcome to FirebaseUI and thanks for submitting an issue!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.

### Step 2: Describe your environment

  * Objective C or Swift: Swift 4
  * iOS version: 12
  * Firebase SDK version: 
  * FirebaseUI version: 6.1.0
  * CocoaPods Version: 1.6
  
### Step 3: Describe the problem:
If i'm using the awesome auth providers (FUITwitterAuth + FUIEmailAuth) the application crash when i try to log on  a Twitter account (problem during the handle url in the application delegate)

#### Steps to reproduce:

  1. Enable FUITwitterAuth
  2. Use FUIAuth.defaultAuthUI()?.handleOpen() in the application delegate
  3. Try to log to a Twitter account 
  
#### Observed Results:

  * App crash in an the next handler FUIEmailAuth, because of a call `[NSURLComponents componentsWithString` with a nil string. A part of the problem seems to be the TwitterKit behavior to handle openUrl. FUITwitterAuth failed to handle openUrl ... but for me it's a bug of implementation and  I'have made a pull request to try to fix this (https://github.com/twitter/twitter-kit-ios/pull/109).
  
#### Expected Results:

  * App must no crash.
  
#### Relevant Code:

  ```
  if (!continueURLString) {
    [FUIAuthBaseViewController showAlertWithMessage:@"Invalid link! Missing continue URL."];
    // It's not enought ! it must retour NO ! Because next lines [NSURLComponents componentsWithString will crash because of a nil continueURLString
}
  ```

**Comment by morganchen12** [comment]
Twitter has been deprecated. Please use FirebaseUI OAuth instead.
