### ISSUE TITLE
Twitter Login failed

### ISSUE THREAD

**Issue by leverdeterre** [firebase/FirebaseUI-iOS#618]
Welcome to FirebaseUI and thanks for submitting an issue!

If not, please feel free to fill in the following info so we can help faster!

### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 12
  * Firebase SDK version: 5.14.0
  * FirebaseUI version: 6.1.0
  * CocoaPods Version: 1.6
  
### Step 3: Describe the problem:

Failed to login with Twitter Login 

#### Steps to reproduce:

  1. Use TwitterAuth provider
  2. Try to login
  3. Login failed
  
#### Observed Results:
  * User account is not created in Firebase Authentication
  * Log failed because of - some : Error Domain=FIRAuthErrorDomain Code=17004 "Failed to fetch resource from https://api.twitter.com/1.1/account/verify_credentials.json?include_email=true, http status: 401, http response: {"errors":[{"code":32,"message":"Could not authenticate you."}]}" UserInfo={NSLocalizedDescription=Failed to fetch resource from https://api.twitter.com/1.1/account/verify_credentials.json?include_email=true, http status: 401, http response: {"errors":[{"code":32,"message":"Could not authenticate you."}]}, error_name=ERROR_INVALID_CREDENTIAL}
   * [FIRAuthBackend verifyAssertion:request
                         callback:^(FIRVerifyAssertionResponse *response, NSError *error) return an error
  
#### Expected Results:

  * Account creation, with or without email 
  
#### Relevant Code:

  ```
[FIRAuthBackend verifyAssertion:request
                         callback:^(FIRVerifyAssertionResponse *response, NSError *error) return an error failed 
  ```

**Comment by leverdeterre** [comment]
This issue is only available is we configure the App on Twitter Settings to request the user email

**Comment by morganchen12** [comment]
TwitterKit has been deprecated. For Twitter Auth, you should be using the FirebaseOAuthUI library instead.
