### ISSUE TITLE
"Invalid link!" popup every time

### ISSUE THREAD

**Issue by xuaninbox** [firebase/FirebaseUI-iOS#622]
There might be other deep link that's handled at launch and this should just return No if its not for email link signin

https://github.com/firebase/FirebaseUI-iOS/blob/88329370497e38c105a8ccb02c4c999bd0e92239/EmailAuth/FirebaseEmailAuthUI/FUIEmailAuth.m#L221

**Comment by morganchen12** [comment]
Fixed in 36afbf183ecd7366d792b53461e8c3d9cff772c2.
