### ISSUE TITLE
Customisation of email entry, password sign-in/sign-up/recovery shows as undeclared type

### ISSUE THREAD

**Issue by catherjet** [firebase/FirebaseUI-iOS#624]
![screenshot 2019-02-20 at 3 50 38 am](https://user-images.githubusercontent.com/36517442/53052229-26298380-34c4-11e9-936c-44981ef03f15.png)

  * Objective C or Swift: swift
  * iOS version: 12.0
  * Firebase SDK version: 5.16.0
  * FirebaseUI version: 6.1.0
  * CocoaPods Version: 1.6.0
  
### Step 3: Describe the problem:

Earlier used customised firebaseUI ver 4.5.1, and it worked perfectly. But after updating to version 6.1.0 today Xcode failed to compile with error "Use of undeclared type 'FUIPasswordRecoveryViewController'".
"Use of undeclared type 'FUIPasswordSignUpViewController'".
"Use of undeclared type 'FUIPasswordSignInViewController'".
"Use of undeclared type 'FUIEmailEntryViewController'".

#### Steps to reproduce:

  1. Used working version 4.5.1
  2. update pod using ( pod update firebaseui )
  3. Build and run
  
#### Observed Results:

  * Xcode prompted failure in compiling the subclassed file and wherever the FUIEmailEntryVC,FUIPasswordSignInVC,etc are declared, with an error message "Use of undeclared type 'FUIEmailEntryViewController'"
  
#### Expected Results:

  * To compile, build and run like it did earlier version 4.5.1 before updating
  
#### Relevant Code:

  ```
func emailEntryViewController(forAuthUI authUI: FUIAuth) -> FUIEmailEntryViewController {
        return customFUIEmailEntryController(nibName: "custom   ",
                                                 bundle: Bundle.main,
                                                 authUI: authUI)
    }
    
  ```

**Comment by morganchen12** [comment]
See https://github.com/firebase/FirebaseUI-iOS/issues/601
