### ISSUE TITLE
Firebase Auth violating Facebook's policies?

### ISSUE THREAD

**Issue by ghowen** [firebase/FirebaseUI-iOS#626]
I have integrated Firebase-UI Auth 6.1.1 into my app which pulled in the following pods

```
Using FBSDKCoreKit (4.40.0)
Using FBSDKLoginKit (4.40.0)

```
I am using vanilla login with Firebase-UI with no customizations.

Now I received this email from Facebook:

> 
> Hi,
> 
> In working to create a great Platform experience for everyone, we ask developers to ensure the apps they build comply with our Platform Policies. Your app xxx  (AppId: 1234567890) doesn't comply with the following:
> 
> Platform Policy 8.2: Native iOS and Android apps that implement Facebook Login must use our official SDKs for Login. 
> 
> Please make sure your iOS app is using the most recent version of our SDK for Login. You can find more information on our iOS SDK for Login and other Login-related products here: https://developers.facebook.com/docs/facebook-login/ios.
> 
> You can see our visual example for this policy here: https://developers.facebook.com/policy#7-2-photo.
> 
> You can access the full list of our Platform Policies here: https://developers.facebook.com/policy/.
> 
> Please make the requested changes by 2019-02-27 at 12:00 PST.
> 
> Let us know when you've updated your app by replying to this email. If we do not hear back from you, your app will be subject to enforcement. If you have outstanding questions, respond here and we'll do our best to help. 
> 
> Thanks,
> 

When checking the link for the visual example it says something like iOS apps are only allowed to use the web based login dialog if they are kiosk apps (litteral translation from German).

My app is iOS only so it cannot be an Android issue.

Could it be that FirebaseUI Auth is in violation of this policy or is Facebook in error here? I have emailed them but not received any reply yet.

**Comment by morganchen12** [comment]
FirebaseUI uses the official Facebook SDKs directly, but doesn't use the latest version due to [a bug that caused login failures](https://github.com/firebase/FirebaseUI-iOS/issues/577). I'll keep this issue open until Facebook responds to you and we'll proceed from there.

**Comment by ghowen** [comment]
I got a reply from FB now, though not a very helpful one:

> We would like to verify if you are using Native iOS Facebook login. 
> 
> Our scope is to create a great platform experience both for end users and developers. Given this fact, do not hesitate in future to request a reasonable further extension.

I asked them (again) what this means for my app and for all other developers using FirebaseUI Auth. Let's see if and what they respond...

**Comment by ghowen** [comment]
New reply as of just now:

> Please allow me to come back with an answer in the shortest period possible.
> 
> Please be ensured that during this time your App will not be subject to enforcement. 
> 
> Thank you for your understanding.

**Comment by morganchen12** [comment]
FirebaseUI has been updated to use the latest Facebook SDK version. I'm going to close this issue since it seems to no longer be actionable, but feel free to comment here if you run into any more Facebook support issues.
