### ISSUE TITLE
Skip authPickerViewController 

### ISSUE THREAD

**Issue by Goule** [firebase/FirebaseUI-iOS#629]
### Describe your environment

  * Objective C or Swift: Swift
  * iOS version: iOS 12
  * Firebase SDK version: latest
  * FirebaseUI version: latest
  * CocoaPods Version: 1.6.0
  
### Describe the problem:

I can't find how to skip the authPickerViewController choice. I want to skip this screen and directly go to the email screen (like in the https://github.com/firebase/friendlyeats-ios which are on the v5 of FIRAuth).

#### Here is my code : 

```swift
guard let auth = FUIAuth.defaultAuthUI() else { return }
auth.delegate = self
if auth.auth?.currentUser == nil {
     auth.providers = [FUIEmailAuth()]
     present(auth.authViewController(), animated: true, completion: nil)
 }
```
Is there any way to skip the providers selection screen when there is only one provider or this is the bug with v6 ? 

Thanks

**Comment by morganchen12** [comment]
Just call [this method](https://github.com/firebase/FirebaseUI-iOS/blob/master/EmailAuth/FirebaseEmailAuthUI/FUIEmailAuth.h#L87) on `FUIEmailAuth`.

**Comment by Goule** [comment]
Thanks for your answer. But this solution seems to broke the register capability :(

**Comment by morganchen12** [comment]
That sounds like a bug.

**Comment by floriangbh** [comment]
Hello,
Same issue for me, there is any workaround ? 
Thanks

**Comment by renkelvin** [comment]
@Goule @floriangbh Hi all, could you please elaborate how to reproduce the issue you met? I'm able to skip the auth picker view to email sign in view and then create a user with https://github.com/firebase/FirebaseUI-iOS/issues/629#issuecomment-467115920

**Comment by renkelvin** [comment]
Closing this issue. Feel free to reopen if you still encounter this issue with the latest SDK.
