### ISSUE TITLE
Creating the authentication providers fails

### ISSUE THREAD

**Issue by j-jorge** [firebase/FirebaseUI-iOS#632]
* Objective C
  * iOS version: 12.1.4
  * Firebase SDK version: 5.17.0
  * FirebaseUI version: 6.1.1
  * CocoaPods Version: N/A
  
### The problem:

Initializing the authentication providers returns nil.

I have initialized Firebase with `[ FIRApp configure ]`. Then I try to initialize the providers ` [ FUIGoogleAuth new ]` or `[ FUIFacebookAuth new ]` or `[ [ FUIPhoneAuth alloc ] initWithAuthUI: [ FUIAuth defaultAuthUI ] ]` but each of these calls return `nil`.

There is no log nor any error message.

Note that I do not use CocoaPods. The `FirebaseUI` frameworks have been compiled with the `xcodebuild` command.

**Comment by morganchen12** [comment]
Can you share a repro sample?

**Comment by j-jorge** [comment]
The project is too large right now to be able to share something relevant :/

My guess is that there is an issue when accessing the resources of FirebaseUI. They were missing when I just included the framework in Xcode. Now I have them in the Copy Bundle Resources build phase of my project but still have no UI.

**Comment by morganchen12** [comment]
Can you create a smaller sample that reproduces this issue and share that, or try to reproduce the issue in one of the samples in the `samples/` folder of this repo?

**Comment by j-jorge** [comment]
It seems that the framework I had built without CocoaPods was a total failure. After using the version from CocoaPods these issues are gone.
