### ISSUE TITLE
Facebook / Google Sign In Question

### ISSUE THREAD

**Issue by tccpg288** [firebase/FirebaseUI-iOS#633]
I have implemented the Firebase UI auth for my iOS app. I had some friends test it, and one thing I noticed - when they attempted to log in with Facebook, they were still prompted to enter their Facebook credentials.

My idea was that Facebook would automatically sign them in on click without the need to enter additional credentials. Is this possible? Is it something that can be handled in Swift? Are their Facebook security settings requiring third-party apps to still prompt the credentials?

**Comment by morganchen12** [comment]
IIRC if your friends are signed into Facebook in Safari already the Facebook app (and you've added support for the Facebook URL schemes in your app) they shouldn't have to re-input their credentials. Is this not what you're seeing?

**Comment by tccpg288** [comment]
I am trying it right now on iOS and it is still prompting me to enter my Facebook and Google login credentials when I select those sign-in methods. I have those apps installed. Is it possible I am handling incorrectly?

**Comment by tccpg288** [comment]
![Image-1 (1)](https://user-images.githubusercontent.com/11081309/54065208-0fcd3880-41e3-11e9-913e-0e720d2fa99a.jpg)

**Comment by tccpg288** [comment]
I found this article: https://www.theverge.com/2017/6/5/15743010/apple-ios-11-wwdc-2017-facebook-twitter-social-accounts-login

Is it true that as of iOS 11 it simply is not possible due to security that has been implemented by Apple?

**Comment by morganchen12** [comment]
Yes, that's correct. I updated my previous comment since it was misleading, but if your user is logged into facebook in Safari they won't have to reenter their credentials.
