### ISSUE TITLE
Compiler warning: 'FIRAuthUpdatedCredentialKey' is deprecated

### ISSUE THREAD

**Issue by ghowen** [firebase/FirebaseUI-iOS#638]
This must have been introduced with the lastest Firebase release (5.18.0 - March 5, 2019):

.../Pods/FirebaseUI/Auth/FirebaseAuthUI/FUIAuth.m:246:42: 'FIRAuthUpdatedCredentialKey' is deprecated

**Comment by renkelvin** [comment]
Fixed here https://github.com/firebase/FirebaseUI-iOS/pull/640
