### ISSUE TITLE
Error when executing pod install

### ISSUE THREAD

**Issue by jjoaquim** [firebase/FirebaseUI-iOS#64]
Right after checkout a simple `pod install` asks for username and password:

```
$ pod install
Cloning spec repo `googlesource-spec` from `https://cpdc-eap.googlesource.com/spec.git`
Username for 'https://cpdc-eap.googlesource.com':
``` 

Is this happening to me only?

**Comment by mcdonamp** [comment]
Would you mind posting your `Podfile`? Presumably it's got a source `https://cpdc-eap.googlesource.com/spec.git` line at the top that you don't need, which you can safely remove and forget about it's existence.

Let me know if this solves the issue!

**Comment by jjoaquim** [comment]
Of course, here it is:

```
source 'https://cpdc-eap.googlesource.com/spec.git'
source 'http://github.com/CocoaPods/Specs.git'

target 'FirebaseUI' do
  # Pods for FirebaseUI as a whole
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'FBSDKLoginKit', '~> 4.0'
  pod 'GoogleSignIn', '~> 4.0'
end

target 'Database' do
  # Pods for Database
  pod 'Firebase'
  pod 'Firebase/Database'
end

target 'Auth' do
  # Pods for Auth
  pod 'Firebase'
  pod 'Firebase/Auth'
end

target 'Facebook' do
  # Pods for Facebook Auth
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'FBSDKLoginKit', '~> 4.0'
end

target 'Google' do
  # Pods for Google Auth
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn', '~> 4.0'
end
```

**Comment by jjoaquim** [comment]
Thank you for the tip. Removed the line but got back a 
```
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `GoogleSignIn (~> 4.0)` required by `Podfile`
- `GoogleSignIn (~> 4.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `GoogleSignIn (~> 4.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

Now performing a `pod repo update` (that takes an awful long time). I'll comment as soon as it ends.

**Comment by mcdonamp** [comment]
Ooooooh you're trying to build the local version, got it. Yeah, looks like I committed something I didn't mean to--it's been removed as of c387680, and a `pod repo update` should ensure you're ready to go.

**Comment by Ajay-Megadev** [comment]
Found any proper solution?

**Comment by Ajay-Megadev** [comment]
![Screenshot 2022-01-26 at 9 42 30 AM](https://user-images.githubusercontent.com/83632506/151151504-aab95bca-5dfa-455b-a2ab-f4999a182529.png)

**Comment by Ajay-Megadev** [comment]
Getting this type of error
![Screenshot 2022-01-26 at 4 29 17 PM](https://user-images.githubusercontent.com/83632506/151151602-3032bbcd-b00f-44a2-b443-b1199c3962cd.png)
.

**Comment by paulb777** [comment]
@Ajay-Megadev That is an error accessing the RecaptchaEnterprise SDK EAP.  You probably need to follow up with that team and may need to be in the proper Google group.

**Comment by Ajay-Megadev** [comment]
Hello, Paul

Thank you so much for replay.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
