### ISSUE TITLE
Terms of Service and Privacy Policy UI bugs

### ISSUE THREAD

**Issue by AndrewGable** [firebase/FirebaseUI-iOS#645]
### Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 12.1.4
  * Firebase SDK version: 5.18.0
  * FirebaseUI version: 6.1.1
  * CocoaPods Version: 1.5.2
  
### Step 3: Describe the problem:
Terms of service and privacy policy cut off in safe area:
![IMG_0681](https://user-images.githubusercontent.com/2838819/54333710-c44ecc00-45e0-11e9-9f26-27b25aff2645.jpg)

Terms of Service and Privacy policy not centered:
![IMG_0682](https://user-images.githubusercontent.com/2838819/54333707-c0bb4500-45e0-11e9-9d9a-4d7385ebb342.jpg)

#### Steps to reproduce:
1. Set terms of service and privacy policy:

```swift
let kFirebaseTermsOfService = URL(string: "https://example.com/TermsOfService.html")!
authUI?.tosurl = kFirebaseTermsOfService
let kFirebasePrivacyPolicy = URL(string: "https://example.com/PrivacyPolicy.html")!
authUI?.privacyPolicyURL = kFirebasePrivacyPolicy
```

2. Start login with email
3. Enter existing user
4. See bug 2

  
#### Expected Results:

I would expect the terms of service to be centered when applicable and/or follow safe area conventions.
  
#### Relevant Code:

  ``` swift
let kFirebaseTermsOfService = URL(string: "https://example.com/TermsOfService.html")!
authUI?.tosurl = kFirebaseTermsOfService
let kFirebasePrivacyPolicy = URL(string: "https://example.com/PrivacyPolicy.html")!
authUI?.privacyPolicyURL = kFirebasePrivacyPolicy
  ```

**Comment by renkelvin** [comment]
1st issue fixed. As for the 2nd issue, it has to be left aligned due to legal issue.

**Comment by AndrewGable** [comment]
@renkelvin - Awesome, thanks for the fix on the first bug! 🎉 

Sorry if I wasn't super clear on the second bug, but I think the `By Continuing...` text should have a bit of vertical padding from the safe area as it's hard for the user to tap `Privacy Policy` button as the iPhone X home button thinks it's being tapped. I moving it up vertically a bit would make the `Privacy Policy` button easier to tap. Thanks as always for your hard work!

**Comment by renkelvin** [comment]
Yeah, that is fixed. The text in the second bug has to be right aligned.

**Comment by AndrewGable** [comment]
Gotcha, thanks again for the fix!

**Comment by romrell4** [comment]
Could I get some additional clarification on what the legal ramifications of centering the ToS / Privacy Policy links? It looks pretty tacky for our users, and before I try and rip our all of the super helpful AuthUI features that we're getting by using this library, I'd love to see if there's a way this could be addressed still :)
