### ISSUE TITLE
Anonymous user remains anonymous after upgrade using email link authentication sign-in

### ISSUE THREAD

**Issue by tndttan** [firebase/FirebaseUI-iOS#651]
### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 12.1
  * Firebase SDK version: 5.14.0
  * FirebaseUI version: 6.1.1
  * CocoaPods Version: 1.5.3
  
### Step 3: Describe the problem:

Starting with an anonymous user, after successfully logging in using email-link authentication with auto-upgrade enabled, the user's status remains anonymous.

#### Steps to reproduce:

  1. Log in as an anonymous user.
  2. Log in using email-link authentication with FUIAuth's 'shouldAutoUpgradeAnonymousUsers' flag set to true.
  3. Wait for the "Signed in!" message.
  
#### Observed Results:

After signing in using email-link authentication, the flag 'Auth.auth().currentUser.isAnonymous', 
is still set to 'true'. Checking the Authentication->Users section on the Firebase console shows that the anonymous user has been upgraded to a user with an email address, but with a caveat that the 'Providers' column is empty.
  
#### Expected Results:

The 'Providers' column in the console should have an 'envelope' symbol, and 'Auth.auth().currentUser.isAnonymous' should be 'false'.

Note that there did not seem to be a problem when signing up or signing in using email-link authentication whilst the user is logged into another non-anonymous account.

**Comment by morganchen12** [comment]
@tndttan can you test this with upstream Firebase without using FirebaseUI? This is a bug that should have been resolved with https://github.com/firebase/firebase-ios-sdk/issues/1331.

**Comment by tndttan** [comment]
No problems. I will try it shortly and report how it goes.

**Comment by tndttan** [comment]
Okay, I've tried it using the upstream Firebase, and I get the same result. I had a quick look at what's going on. In FIRUser method updateEmail:password:callback:, self.anonymous is set to 'NO' on the condition that userAccountInfo.providerUserInfo.count > 0. But providerUserInfo is nil. The providerUserInfo array seems to be set by the FIRUser method, executeUserUpdateWithChanges:callback:, after calling the method setAccountInfo:callback: that subsequently calls the backend. Also, couple this with the fact that, on the console, the 'Providers' column disappears for the user, the situation seems to imply that it is the backend that is registering zero providers. With zero knowledge of how the backend works, my assumption is that the problem could be in the backend. Or maybe something incorrect was sent to the backend in the set account info request.

**Comment by morganchen12** [comment]
@renkelvin can you investigate? This seems like an upstream Firebase bug.

**Comment by renkelvin** [comment]
Yeah, I verified it's an upstream bug. Fix is here: https://github.com/firebase/firebase-ios-sdk/pull/3030
