### ISSUE TITLE
Spelling mistake in email-link authentication alert box

### ISSUE THREAD

**Issue by tndttan** [firebase/FirebaseUI-iOS#652]
### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 12.1
  * Firebase SDK version: 5.14.0
  * FirebaseUI version: 6.1.1
  * CocoaPods Version: 1.5.3
  
### Step 3: Describe the problem:

Spelling mistake in 'Sign-in email Sent' alert box, where 'instrucitons' should be 'instructions'.

#### Steps to reproduce:

  1. Choose email-link authentication
  2. Provide an email and tap 'Next'

**Comment by Yue-Wang-Google** [comment]
I'll just take it
