### ISSUE TITLE
FUIPasswordSignUpViewController didChangeEmail

### ISSUE THREAD

**Issue by nicolasFernandez** [firebase/FirebaseUI-iOS#656]
In file FUIPasswordSignUpViewController:305, didChangeEmail is being called this way

https://github.com/firebase/FirebaseUI-iOS/blob/021f26903e1b4498a4db12a75f668d565ac5e3af/EmailAuth/FirebaseEmailAuthUI/FUIPasswordSignUpViewController.m#L305

I guess this should be: 
`[self didChangeEmail:_emailField.text orPassword:_passwordField.text orUserName:_nameField.text];`

I've just logged in to Google CLA so I can make a PR for this change in case it needs to be fixed. Otherwise, maybe someone could change this. Thanks in advance!

**Comment by renkelvin** [comment]
Thanks! Fixed here https://github.com/firebase/FirebaseUI-iOS/pull/658
