### ISSUE TITLE
Feature request: Add functionality to preload image using SDWebImage

### ISSUE THREAD

**Issue by otusweb** [firebase/FirebaseUI-iOS#657]
The current SDK allows to load an image straight to an UIImageView. In my case i'd like to preload the image before setting in the imageView as I have to calculate some layout that requires having the image locally.

here is a swift version of the method I created to do just that:

```
class func imageForReference(_ reference: StorageReference, completion: @escaping (UIImage?, Error?) -> Void) {
        // Query cache for image before trying to download
        let cache = SDImageCache.shared()
        let key = reference.fullPath
        var cached = cache.imageFromMemoryCache(forKey: key)
        if cached != nil {
            completion(cached, nil)
            return
        }

        cached = cache.imageFromDiskCache(forKey: key)
        if cached != nil {
            completion(cached, nil)

            return
        }

        // If nothing was found in cache, download the image from Firebase Storage
        let filePath = FileManager.default.temporaryDirectory.appendingPathComponent(key)
        reference.write(toFile: filePath) { (file: URL?, error: Error?) in
            DispatchQueue.main.async {
                guard error == nil, let file = file else {
                    completion(nil, error)
                    return
                }
                let image = UIImage(contentsOfFile: file.absoluteString)
                cache.store(image, forKey: key, completion: nil)

                completion(image, nil)
            }
        }
    }

**Comment by dreampiggy** [comment]
@otusweb See #654 .

When using the Custom Loader API of SDWebImage 5.0, you can share the same logic for all built-in methods.

For example, you can even use `SDWebImagePrefetcher` to prefetch `FIRStorageRef` instance. Show the demo code:

```objectivec
// Setup code. If you using the global `loadersManager`, to bind multiple loaders like (downloader, firebaseloader), you don't need this code.
let manager = SDWebImageManager(cache: SDImageCache.shared, loader: SDFIRStorageLoader.shared)
let prefetcher = SDWebImagePrefetcher(manager: manager)

// Now let's prefetch
let references : [FIRStorageRef]
let urls = references.map { URL.sd_URL(with: $0) }
prefetcher.prefetch(urls: urls)

// Done :)
```

**Comment by morganchen12** [comment]
645 has been merged and released.

**Comment by Spiderpowa** [comment]
In case anyone found this issue, `SDWebImageFIRStorageLoader` is now `StorageImageLoader` in the example code.

> @otusweb See #654 . I've create PR to use the SDWebImage 5.0 for better integration.
> 
> When using the Custom Loader API of SDWebImage 5.0, you can share the same logic for all built-in methods from SD.
> 
> For example, you can even use `SDWebImagePrefetcher` to prefetch `FIRStorageRef` instance. Show the demo code:
> 
> ```swift
> // Setup code. If you using the global `loadersManager`, to bind multiple loaders like (downloader, firebaseloader), you don't need this code.
> let manager = SDWebImageManager(cache: SDImageCache.shared, loader: SDWebImageFIRStorageLoader.shared)
> let prefetcher = SDWebImagePrefetcher(manager: manager)
> 
> // Now let's prefetch
> let references: [StorageReference]
> let urls = references.compactMap { URL.sd_URL(with: $0) }
> prefetcher.prefetch(urls: urls)
> 
> // Done :)
> ```
