### ISSUE TITLE
Can't build/run New Firebase sample For Swift

### ISSUE THREAD

**Issue by glennposadas** [firebase/FirebaseUI-iOS#66]
I successfully figured out how to make the sample database project run in a device. But that's only for Objective-C, when I tried to run the Swift Example, Xcode wasn't able to find the libraries to import. It's telling me that import FirebaseDatabaseUI <-- is undeclared. Libraries are written in objective-C. Is there a good docu about it?

**Comment by grantkemp** [comment]
Please add / document Swift support..

**Comment by mcdonamp** [comment]
#45 covers updating the docs, and includes better Swift support.

As for the FirebaseDatabaseUI undeclared, I have a feeling it's a modulemap issue, and I'm working on resolving it.

**Comment by PVKonovalov** [comment]
For build and run that example you need to perform the following step:
1. Create GoogleService-Info.plist in the firebase console and add it to the project
2. Open the project directory in the terminal app and run 'pod install' command
3. Open DatabaseExample.xcworkspace in XCode.app and build the example

**Comment by morganchen12** [comment]
I just added a Swift sample with #89--if you're still struggling with setting up FirebaseUI in Swift, can you take a look at that repo and see if it helps?

**Comment by morganchen12** [comment]
closing via #95, #96, #98

**Comment by ritesh124** [comment]
I am not using cocoa pods, i am facing the same issues.

**Comment by morganchen12** [comment]
@ritesh124 please open a new issue and describe what steps you took to reproduce the issue.
