### ISSUE TITLE
Unexpected CFBundleExecutable Key. The bundle at 'Payload/MyApp.app/FirebaseAuthUI.bundle' does not contain a bundle executable

### ISSUE THREAD

**Issue by yusuftor** [firebase/FirebaseUI-iOS#661]
* Xcode version: 10.2
  * Firebase SDK version: 5.20.1
  * Firebase Component: FirebaseAuthUI
  * Component version: 6.2.1

I am trying to build and submit my app to Testflight. It builds fine and then when it goes to upload it to testflight, it comes back with the error:

>ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/MyApp.app/FirebaseAuthUI.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

Why? I haven't had this issue before.

**Comment by morganchen12** [comment]
The FirebaseUI Auth bundle should contain only assets, so you're safe removing the bundle executable key as the error says.

I'm not sure what could have caused this issue. Are you using CocoaPods to integrate FirebaseUI?

**Comment by yusuftor** [comment]
@morganchen12 I am using Cocoapods. Weirdly this error was caused on CircleCI when building and submitting my app. However when I built it on my computer and submitted it (without changing anything), no error occurred.

**Comment by morganchen12** [comment]
Strange. Can you file this bug on CircleCI's bug tracker? We'll keep this issue open for now in case anyone else runs into it.

**Comment by yusuftor** [comment]
@morganchen12 Will do. I just tried uploading a new build and CircleCI gives me the same error. I notice they're not using the release version of XCode 10.2, could that be an issue?

**Comment by mefilt** [comment]
@yusuftor Did you find fix?

**Comment by yusuftor** [comment]
@mefilt Its to do with Xcode 10.2 not being supported. They are working on releasing it very soon apparently: https://discuss.circleci.com/t/when-can-we-expect-the-final-xcode-10-2-image-to-be-released/29261/33

**Comment by morganchen12** [comment]
Closing this bug, since it's not actionable here. Please feel free to continue commenting if this issue resurfaces.
