### ISSUE TITLE
Name and last name text field should start with upper case by default

### ISSUE THREAD

**Issue by FrancoSabadini** [firebase/FirebaseUI-iOS#662]
### Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 12
  * Firebase SDK version: 5.16.0
  * FirebaseUI version: 6.1.0
  * CocoaPods Version: 1.5.3
  
### Describe the problem:

I can't force the name and last name on the email sign-up screen to start with an uppercase letter (the keyboard appears as lowercase by default). 

#### Steps to reproduce:

  1. Try to create a new account using email.
  2. Click on the "First and last name" text field.
  
#### Observed Results:

  * The keyboard appears with lower case letters by default.
  
#### Expected Results:

  * The keyboard should appear with uppercase letters by default. 

This can be achieved by setting the **Capitalization** param in the **Text Input Traits** section to **Sentences** (the default is **None**) in the text field.

**Comment by FrancoSabadini** [comment]
@morganchen12 is there any workaround I can use in my app until this is added to the lib?

**Comment by morganchen12** [comment]
Looks like there's no workaround for now. We'd have to make [this member](https://github.com/firebase/FirebaseUI-iOS/blob/master/EmailAuth/FirebaseEmailAuthUI/FUIPasswordSignUpViewController.m#L75) public to allow customization.

**Comment by FrancoSabadini** [comment]
Thanks for the answer @morganchen12. Can you make that property public on the next version as a quick fix for this until you have time to provide a more robust solution?

**Comment by renkelvin** [comment]
Fixed here: https://github.com/firebase/FirebaseUI-iOS/pull/679

**Comment by morganchen12** [comment]
The fix has been released.
