### ISSUE TITLE
"Sign in with email" button doesn't appear

### ISSUE THREAD

**Issue by Ryo01297804** [firebase/FirebaseUI-iOS#665]
* Swift5
 *Xcode version 10.2 
 * Firebase SDK version: 5.20.2
  * FirebaseUI version: 6.2.1
  * CocoaPods Version: 1.6.1
  
### Step 3: Describe the problem:

I'm trying to create sign-in forms by FirebaseUI.

I followed the official instruction to set up FirebaseUI, but it doesn't show anything on my screen but title "Welcome".

![スクリーンショット 2019-04-10 0 16 33](https://user-images.githubusercontent.com/45932261/55942248-f7878800-5c7e-11e9-80e0-bd5f63d5fcb7.png)

#### Expected Results:

  * There should be "Sign in with email" button appearing.
  
#### Relevant Code:

  import UIKit
  import Firebase
  import FirebaseUI

 class ViewController: UIViewController, FUIAuthDelegate {

      @IBOutlet weak var loginButton: UIButton!
    
      var authUI: FUIAuth { get { return FUIAuth.defaultAuthUI()! } }
    
      override func viewDidLoad() {
          super.viewDidLoad()
        
          authUI.delegate = self
          let providers: [FUIAuthProvider] = []
          authUI.providers = providers
          loginButton.addTarget(self, action: #selector(self.loginButtonTapped(_:)), for: .touchUpInside)
      }

      @objc func loginButtonTapped(_ : AnyObject) {
          let authViewController = authUI.authViewController()
          self.present(authViewController, animated: true, completion: nil)
      }
    
      public func authUI(_ authUI: FUIAuth, didSignInWith user: User?, error: Error?) {
          if error == nil {
              self.performSegue(withIdentifier: "toTalkRoomTableViewController", sender: nil)
          }
      }
    
  }

and I did "FirebaseApp.configure()" in AppDelegate.swift

Is there any problem in my code?

**Comment by KrisConrad** [comment]
The was a change recently that made the email option explicit instead of implicit. 

Try changing:
`let providers: [FUIAuthProvider] = []`

to:
`let providers: [FUIAuthProvider] = [FUIEmailAuth()]`

You might also need to add the email provider to you Podfile depending on your setup.
`pod 'FirebaseUI/Email'`

**Comment by Ryo01297804** [comment]
It worked! Thanks😁
