### ISSUE TITLE
"Trouble Signing In?" is cut off on smaller phones

### ISSUE THREAD

**Issue by AndrewGable** [firebase/FirebaseUI-iOS#668]
### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 12.1
  * Firebase SDK version: 5.20.1
  * FirebaseUI version:  6.2.1
  * CocoaPods Version: 1.6.0
  
### Step 3: Describe the problem:
The label `Trouble Signing In?` is cut off on smaller devices (e.g. iPhone SE)

<img width="400" alt="Screen Shot 2019-04-16 at 3 37 32 PM" src="https://user-images.githubusercontent.com/2838819/56254855-1eb6ce80-605e-11e9-85f6-bd1dcf69334a.png">

#### Steps to reproduce:
1. Sign in with existing email
2. On password page you will see the bug
  
#### Expected Results:

  * What did you expect to happen?
  
I would expect the label to not be cut off on all supported devices.

**Comment by renkelvin** [comment]
Hi @AndrewGable , I'm not able to reproduce this issue. Do you use any layout framework other than Auto Layout? Like LayoutKit or something else?
<img width="408" alt="Screen Shot 2019-05-16 at 3 46 34 PM" src="https://user-images.githubusercontent.com/869251/57891874-d8d25f00-77f1-11e9-8b99-56ef601f5eb0.png">

**Comment by AndrewGable** [comment]
I updated to `7.0.0` and it's fixed 🎉

Thanks!
