### ISSUE TITLE
Add support for SDWebImage 5.0.0

### ISSUE THREAD

**Issue by jdanthinne** [firebase/FirebaseUI-iOS#669]
### Environment

  * Objective C or Swift: Swift
  * iOS version: 12
  * Firebase SDK version: 5.20.2
  * FirebaseUI version: 6.2.1
  * CocoaPods Version: 1.6
  
### Problem:

I'd like to use the new SDWebImage 5.0.0, bringing many improvements.

**Comment by morganchen12** [comment]
See #654

**Comment by morganchen12** [comment]
This has been released.
