### ISSUE TITLE
Wrong FBSDKLoginKit pod

### ISSUE THREAD

**Issue by AndriyGo** [firebase/FirebaseUI-iOS#673]
I have the following entries in my Podfile:

```
pod 'Firebase/Analytics'
    pod 'Firebase/DynamicLinks'
    pod 'Firebase/Core'
    pod 'FirebaseUI/Auth'
    pod 'FirebaseUI/Facebook'
    pod 'FirebaseUI/Email'
    pod 'Firebase/Functions'
    pod 'Firebase/Firestore'
```

If I comment out `pod 'FirebaseUI/Facebook'`, `FBSKCoreKit` and `FBSDKLoginKit` are not added to my project. However, if I leave this entry, there is some mismatch with versions of two frameworks which are added:

```
Installing FBSDKCoreKit (5.0.0)
Installing FBSDKLoginKit (4.44.1)
```

As you can see, one has a version 5.x whereas the other has version 4.x and it causes errors when I build my app.

Do you know if there is a way around this?

**Comment by morganchen12** [comment]
This seems like a bug in Facebook's podfiles. They shouldn't be allowing multiple major versions to be installed at the same time. You can work around this for now by explicitly including FBSDKLoginKit and FBSDKCoreKit versions in your Podfile.

```ruby
pod 'FBSDKCoreKit', '~> 4.0'
pod 'FBSDKLoginKit', '~> 4.0'
```

**Comment by morganchen12** [comment]
Closing since this isn't actionable in FirebaseUI.
