### ISSUE TITLE
Hi i have a problem with Installing BoringSSL-GRPC (0.0.2)

### ISSUE THREAD

**Issue by boardmain** [firebase/FirebaseUI-iOS#678]
Unable to install with pod

i blocked to Installing BoringSSL-GRPC (0.0.2)

**Comment by morganchen12** [comment]
Please add your CocoaPods version, Podfile, and command line invocation and error output.

**Comment by gypsicoder** [comment]
I have following in the pod file
```
  pod 'Firebase/Core' # , '~> 6.2.0'
  pod 'Firebase/Auth' #, '~> 6.2.0'
  pod 'Firebase/Database' #, '~> 6.2.0'
  pod 'Firebase/Storage' #, '~> 6.2.0'
  pod 'Firebase/Firestore' #, '~> 6.2.0'
  
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
```

My cocoapods version is 
`1.7.5`

**Comment by jessalbarian** [comment]
This worked for me, and I'm on Catalina

`brew install ruby`
`sudo gem install -n /usr/local/bin cocoapods`
`pod install`

**Comment by ch-muhammad-adil** [comment]
Let it install for a while, Actually it takes some time like 10-15 minutes.

**Comment by ch-muhammad-adil** [comment]
Let it install for a while, Actually it takes some time like 10-15 minutes.

**Comment by ghasemikasra39** [comment]
Same here, any solution ?
