### ISSUE TITLE
Add screenshots to Readme

### ISSUE THREAD

**Issue by aschuch** [firebase/FirebaseUI-iOS#68]
It would be nice to get some insight into the design of this UI component from the Readme.

**Comment by yramanchuk** [comment]
Also add demo integration steps:
1. pod try FirebaseUI
2. add Google-info.plist
3. set IDPs settings (facebook app id, twitter secret etc)
4. enable keychain sharing permission

**Comment by dakeshi** [comment]
> enable keychain sharing permission

Do you mean that enabling keychain sharing in Target-Capability can solve the sign-in issue of simulator, such as #130 ? I got failed if I did not turn on the option.

**Comment by yramanchuk** [comment]
mentioned changed were implemented in branch v0.6.3
