### ISSUE TITLE
FacebookSDK  dependency

### ISSUE THREAD

**Issue by nanshanyi** [firebase/FirebaseUI-iOS#687]
I use another SDK depend on FacebookSDK 5.0.0，but FirebaseUI depend on 4.35
I would like to ask when is the update dependent

**Comment by morganchen12** [comment]
@nanshanyi this should already be available (see the [podspec here](https://github.com/CocoaPods/Specs/blob/master/Specs/b/c/2/FirebaseUI/7.0.0/FirebaseUI.podspec.json#L191)). You'll have to update your FirebaseUI version to 7.0.0.
