### ISSUE TITLE
Could not find module "FirebaseUI" using CocoaPods and Swift

### ISSUE THREAD

**Issue by cobyanderson** [firebase/FirebaseUI-iOS#69]
Using Swift

Even after installing using CocoaPods, I am unable to import "FirebaseUI" and thus cannot create an instance of "FirebaseLoginViewController."

I am getting this error as well:
```
[!] Unable to read the license file `/Users/cobyanderson/Documents/Taggle2/Pods/FirebaseUI/LICENSE` for the spec `FirebaseUI (0.4.0)`

[!] Unable to read the license file `/Users/cobyanderson/Documents/Taggle2/Pods/FirebaseUI/LICENSE` for the spec `FirebaseUI (0.4.0)`
```
Any chance these could be connected?

Attached is my podfile
[Podfile.txt](https://github.com/firebase/FirebaseUI-iOS/files/299250/Podfile.txt)

**Comment by iulukaya** [comment]
Please use FirebaseDatabaseUI and FirebaseAuthUI in the meantime

**Comment by mcdonamp** [comment]
Seems like you might be using the old docs, as `FirebaseLoginViewController` was a 0.3 thing, and we've replaced it with FirebaseAuthUI in 0.4.
