### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by AndriyGo** [firebase/FirebaseUI-iOS#692]
I have these entries in my Podfile related to Firebase:
```
pod 'Firebase/Analytics'
    pod 'Firebase/DynamicLinks'
    pod 'Firebase/Core'
    pod 'FirebaseUI/Auth'
    pod 'FirebaseUI/Facebook'
    pod 'FirebaseUI/Email'
    pod 'Firebase/Functions'
    pod 'Firebase/Firestore'
```

When I run `pod update` the output is (some of these are from other pods):
```
Using BoringSSL-GRPC (0.0.3)
Using Crashlytics (3.13.1)
Installing DGRunkeeperSwitch 1.1.6
Using FBSDKCoreKit (5.0.1)
Using FBSDKLoginKit (5.0.1)
Using Fabric (1.10.1)
Using Firebase (6.1.0)
Using FirebaseAnalytics (6.0.1)
Using FirebaseAnalyticsInterop (1.2.0)
Using FirebaseAuth (6.1.0)
Using FirebaseAuthInterop (1.0.0)
Using FirebaseCore (6.0.1)
Using FirebaseDynamicLinks (4.0.0)
Using FirebaseFirestore (1.3.1)
Using FirebaseFunctions (2.5.1)
Using FirebaseInstanceID (4.1.0)
Using FirebaseUI (7.0.0)
Using GTMSessionFetcher (1.2.2)
Using GoogleAppMeasurement (6.0.1)
Using GoogleUtilities (6.2.0)
Using Instructions (1.3.1)
Using Protobuf (3.8.0)
Installing SCLAlertView 0.8.1
Using SwiftConfettiView (0.1.0)
Using SwiftMessages (7.0.0)
Using SwiftyStarRatingView (1.0.4)
Using ZIPFoundation (0.9.9)
Using ZendeskSDK (2.3.1)
Using gRPC-C++ (0.0.8)
Using gRPC-Core (1.19.0)
Using leveldb-library (1.20)
Using nanopb (0.3.901)
```

When I try to build my app I get the following error in `FirebaseUI`:

<img width="1792" alt="Screenshot 2019-05-30 at 03 56 25" src="https://user-images.githubusercontent.com/7107815/58600868-f6da9d80-828e-11e9-95c1-c6caf370b4bf.png">

Does anyone know how to fix this? It used to work before...

**Comment by jonathanfoster** [comment]
@andirayo This issue was just resolved today, https://github.com/firebase/FirebaseUI-iOS/issues/684#issuecomment-497136073. To get the latest version, you'll have to clean the pod cache, delete the Pod dir, then do pod update.
```
pod cache clean --all
rm -rf Pods/
pod install
```

**Comment by morganchen12** [comment]
This is fixed in master as well now, unfortunately it's pushed as a new major release since I botched 7.0.0.
