### ISSUE TITLE
Extra margin on the last auth button

### ISSUE THREAD

**Issue by xuaninbox** [firebase/FirebaseUI-iOS#694]
https://github.com/firebase/FirebaseUI-iOS/blob/03511e614c40a91676335047d96a03d11265dfc4/Auth/FirebaseAuthUI/FUIAuthPickerViewController.m#L110

kSignInButtonVerticalMargin * (numberOfButtons) creates an extra margin makes the container harder to be centered.

**Comment by renkelvin** [comment]
@xuaninbox Can you offer more details? What's the expected behavior?

**Comment by xuaninbox** [comment]
with the current implementation, the buttonContainerView for a 3 button would be 

===ContainerView===
----
Button
----
VerticalMargin
----
Button
----
VerticalMargin
----
Button
----
VerticalMargin
===ContainerView===

There's an extra VerticalMargin after the last button. so the ContainerView is not 100% centered in the screen.

**Comment by renkelvin** [comment]
I got your point.
The buttons are not expected to be vertically centered and there has to be `VerticalMargin` between the last button and the "Terms of Service" text.
I'm closing the issue for now. Feel free to reopen if needed.
