### ISSUE TITLE
8.0.1 Facebook login broken

### ISSUE THREAD

**Issue by xuaninbox** [firebase/FirebaseUI-iOS#695]
https://github.com/firebase/FirebaseUI-iOS/blob/aa5a04f6c00f1acdc2f883b1979ef314b2f2fc84/FacebookAuth/FirebaseFacebookAuthUI/FUIFacebookAuth.m#L225

facebook SDK throws this error after the change

> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Please set FacebookAppID, FacebookDisplayName, and
> URL types > Url Schemes in `Supporting Files/Info.plist` according to https://developers.facebook.com/docs/ios/getting-started'

switch back to `NSBundle *bundle = [NSBundle mainBundle]; ` fixed the issue

**Comment by jonathanfoster** [comment]
A temporary workaround is to pin FirebaseUI to 7.0.0.
```
pod 'FirebaseUI', '~> 7.0.0'
```

**Comment by morganchen12** [comment]
The fix for this has been released in v8.0.2.
