### ISSUE TITLE
Support for "Sign In with Apple" in fall 2019 

### ISSUE THREAD

**Issue by ghowen** [firebase/FirebaseUI-iOS#698]
According to https://developer.apple.com/news/?id=06032019j, support for "Sign in with Apple" will be mandatory for all apps that support other third party logins:

> Sign In with Apple will be available for beta testing this summer. It will be required as an option for users in apps that support third-party sign-in when it is commercially available later this year.

If this remains true, it means that apps using FirebaseUI Auth with Google and/or Facebook will probably be rejected starting sometime in fall this year if "Sign in with Apple" is not a supported option.

**Comment by mylogon341** [comment]
Does anyone have an update on this?

**Comment by mylogon341** [comment]
Where other social sign ins are available, “sign in with Apple” will become mandatory to include in iOS 13 early next year

**Comment by morganchen12** [comment]
Upstream Firebase has all the necessary SDK changes in place. We're finishing up console support for Sign in with Apple.

**Comment by morganchen12** [comment]
Merged in #796. This will be released by EOD today.

**Comment by morganchen12** [comment]
This is now published in FirebaseUI 8.4.0.
