### ISSUE TITLE
Unable to build after 8.0.2

### ISSUE THREAD

**Issue by boardmain** [firebase/FirebaseUI-iOS#703]
after upgrading to 8.0.2 im unable to build

i have error in the facebook sdk

error is 'FBSDKRestrictiveDataFilterManager.h' file not found

thisi my pod file

platform :ios, '10.3'

target 'TESTAPP' do
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Phone'
  pod 'FirebaseUI/Facebook'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Email'
  pod 'GoogleSignIn'
  pod 'Apollo'
  pod 'SPPermission'
  pod 'SPAlert'
  pod 'SideMenuSwift'
  pod 'FontBlaster'
  pod 'SwifterSwift'
  pod 'Segmentio'
  # Pods for FoodTech

end

and this what installed

Using Apollo (0.10.1)
Using FBSDKCoreKit (5.0.2)
Using FBSDKLoginKit (5.0.2)
Using Firebase (6.2.0)
Using FirebaseAnalytics (6.0.1)
Using FirebaseAuth (6.1.1)
Using FirebaseAuthInterop (1.0.0)
Using FirebaseCore (6.0.2)
Using FirebaseInstanceID (4.1.1)
Using FirebaseUI (8.0.2)
Using FontBlaster (5.0.0)
Using GTMSessionFetcher (1.2.2)
Using GoogleAppMeasurement (6.0.1)
Using GoogleSignIn (4.4.0)
Using GoogleToolboxForMac (2.2.1)
Using GoogleUtilities (6.2.0)
Using SPAlert (1.0.4)
Using SPPermission (4.0.1)
Using Segmentio (3.3)
Using SideMenuSwift (2.0.0)
Using SwifterSwift (5.0.0)
Using nanopb (0.3.901)

**Comment by morganchen12** [comment]
I'm unable to reproduce this issue. Try comparing your build settings to the ones in the [sample app](https://github.com/firebase/FirebaseUI-iOS/tree/master/samples/swift).
