### ISSUE TITLE
Facebook login - update docs to include auth2 entry

### ISSUE THREAD

**Issue by Johnson145** [firebase/FirebaseUI-iOS#704]
### Describe the problem:
When using the Facebook login, I get the following log message:

`fbauth2 is missing from your Info.plist under LSApplicationQueriesSchemes and is required for iOS 9.0`

### Solution
Adding the missing entry to the Info.plist file as described [e.g. here](https://stackoverflow.com/a/31986544).

### Suggestion
While this key has been added to the sample app, it's not mentioned in the docs. So this step should get added to the docs.

### Related issues
Not sure, but this may be related to #666.

**Comment by morganchen12** [comment]
This part is mentioned in Facebook's getting started docs, which are linked to [here](https://github.com/firebase/FirebaseUI-iOS/blob/master/Auth/README.md).

IMO it's not worth duplicating their documentation, especially since the error message is informative and easy to resolve. Do you think we should duplicate this information anyway?

**Comment by Johnson145** [comment]
Thanks for your quick reply!

Linking is totally fine I'd say. I didn't see the link you're mentioning, because I was using the tutorial for the prebuild UI. So I suggest to add a similar link as you've already mentioned to the [official Firebase docs](https://firebase.google.com/docs/auth/ios/firebaseui#facebook). 

I don't know how the relation between this repo and the official docs looks like? Is this still the right place to discuss changes for the latter?

**Comment by morganchen12** [comment]
Yes, it is. The docs have been updated and changes will be reflected publicly shortly afterwards.

Thanks for filing this issue!
