### ISSUE TITLE
FirebaseUI/Auth with Email-Password

### ISSUE THREAD

**Issue by psopher** [firebase/FirebaseUI-iOS#71]
I'm hoping to use FirebaseUI/Auth with Facebook, Google, and email/password authentication options.

On the FirebaseUI/Auth landing page, it shows how to add Google and Facebook providers:

```
FIRGoogleAuthUI *googleAuthUI = [[FIRGoogleAuthUI alloc] initWithClientID:kGoogleClientID];
FIRFacebookAuthUI *facebookAuthUI = [[FIRFacebookAuthUI alloc] initWithAppID:kFacebookAppID];
authUI.providers = @[ googleAuthUI, facebookAuthUI];
```
How would I add email-password to the auth providers option and have it appear on `authViewController`?

**Comment by chaogoog** [comment]
Email-password is enabled as a sign-in option by default, it doesn't require any configuration :)

A "Sign in with email" option should appear on `authViewController`, unless `signInWithEmailHidden` is set to `YES`.

**Comment by psopher** [comment]
Awesome!

Just wondering, where can I find the properties of `<authViewController>`?

**Comment by chaogoog** [comment]
The `authViewController` is essentially a `UINavigationController` thats wraps a `FIRAuthPickerViewController`, there's not much you can do with the `UINavigationController` itself with the current API.

However, if you want to customize the UI of the first screen, you can provide an instance of a custom subclass of `FIRAuthPickerViewController` by implementing the `FIRAuthUI` delegate method `authPickerViewControllerForAuthUI:`. In your custom subclass, you can modify the default UI as you want.

**Comment by chaogoog** [comment]
Closing this issue now. Feel free to let us know if you have more questions :)

**Comment by xsoti** [comment]
In version 0.5.0 on uidemo there is no e-mail field, and setting signInWithEmailHidden to false doesn't help

**Comment by leeprobert** [comment]
I can confirm, if you don't set a provider you just get a blank view controller with a title of 'welcome'

**Comment by dbeulen** [comment]
For everyone having this problem on 5.0:

https://stackoverflow.com/a/54608189
