### ISSUE TITLE
Email-Password on AuthViewController Doesn't Query to Set a Password on First Use

### ISSUE THREAD

**Issue by psopher** [firebase/FirebaseUI-iOS#72]
I'm using `authViewController` for FirebaseUI/Auth. Here is what it looks like when I select the email-password option:

1)
![simulator screen shot jun 11 2016 4 01 00 pm](https://cloud.githubusercontent.com/assets/10428964/15987195/61e56e3a-2fee-11e6-8204-9c819e2968aa.png)

2)
![simulator screen shot jun 11 2016 4 01 06 pm](https://cloud.githubusercontent.com/assets/10428964/15987197/6ceb9cf0-2fee-11e6-920a-544b6ca9b30b.png)

3)
![simulator screen shot jun 11 2016 4 01 17 pm](https://cloud.githubusercontent.com/assets/10428964/15987202/7179d0de-2fee-11e6-9a34-80bbe46dbdf9.png)

4)
![simulator screen shot jun 11 2016 4 02 06 pm](https://cloud.githubusercontent.com/assets/10428964/15987203/75657518-2fee-11e6-931e-f335137b0140.png)

As you can see, there's no query to set a password, so it's impossible to actually authenticate with this method. Am I doing something wrong? How do I fix this?

Also, the flow is kind of strange. Why does it ask for your email on one page and then your email and password on the next?

**Addendum**
Email-password IS enabled in my Firebase Console.
The only code I use is to call `authViewController` because the email-password option appears automatically.

    self.authViewController = [authUI authViewController];

**Comment by psopher** [comment]
I just figured it out.. I was giving it an email for a previously authenticated FIRUser

**Comment by chaogoog** [comment]
The flow asks the user for the identifier first to determine what the next step should be. It not only helps differentiate sign-in and sign-up cases, it also avoids creating a duplicate account for users who have signed up using an identity provider.
