### ISSUE TITLE
I am getting issue on Firestore UI.

### ISSUE THREAD

**Issue by RuchiraMore** [firebase/FirebaseUI-iOS#721]
I am getting issue on Firestore UI. 
I am presenting Firestore UI. But not able to interacting while using "Google Sign In".

_Originally posted by @RuchiraMore in https://github.com/firebase/FirebaseUI-iOS/issues/482#issuecomment-507647036_

**Comment by morganchen12** [comment]
Can you share your code and any errors in console?
