### ISSUE TITLE
UISearchDisplayController is no longer supported when linking against this version of iOS. Please migrate your application to UISearchController.

### ISSUE THREAD

**Issue by valentcheung** [firebase/FirebaseUI-iOS#722]
* Swift 5
  * iOS version: iOS 13 Beta 3
  * Firebase SDK version: 6.3.0
  * FirebaseUI version: 8.0.2
  * CocoaPods Version: 1.7.3
  
#### Steps to reproduce:

  1. Phone number authentication
  2. Select country/region (FUICountryTableViewController.xib)
  
#### Observed Results:

The app crashes and posted a log message:

> *** Terminating app due to uncaught exception 'NSGenericException', reason: 'UISearchDisplayController is no longer supported when linking against this version of iOS. Please migrate your application to UISearchController.'

  
#### Expected Results:

Show country/region tableview
  
#### Relevant Code:

I am using the prebuilt UI.

**Comment by jkippen** [comment]
Same error and libraries. I use the UISearchController, not UISearchDisplayController - for me the app crashed on load.
