### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by valentcheung** [firebase/FirebaseUI-iOS#723]
* Swift 5
  * iOS 13 beta 3
  * Firebase SDK version: 6.3.0
  * FirebaseUI version: 8.0.2
  * CocoaPods Version: 1.7.3
 
#### Steps to reproduce:

  1. Authentication views of phone sign in and email-password sign in from the prebuilt UI (FirebaseUI)
  
#### Observed Results:

  * Color of the label texts (“Email”, “Password”) and background in sign-in/sign-up view do not change based on user’s dark mode setting.  
* The reason is those UI elements have color explicitly assigned. 
  
#### Expected Results:

  * It would be great if the prebuilt UI can adapt to the system-wide dark mode feature of the iOS 13. I attempted to change the colours. Since I am not quite familiar with ObjC so I could change only the password label into what you can see in the attached screenshot. The black “email” label and white background were already there in the prebuilt UI
![D1FFB1FE-C837-449A-9535-BD7689C04C1E](https://user-images.githubusercontent.com/36809245/60589320-d0e37400-9dcb-11e9-9e23-57f391bb02b0.png)

**Comment by cbess** [comment]
I definitely plan on working on this soon. If the Lord wills, sometime next week.

**Comment by KrisConrad** [comment]
@cbess The auth flow looks much better in dark mode. 

I did have a few issues though getting it to work. I'm using cocoa pods, and pointed the FirebaseUI pods to your branch. That branch requires the GoogleSignIn 5.0.0 pod (was previously on 4.40), that has a dependency of an "AppAuth" pod. AppAuth calls UIApplication in several locations without checking if it's actually running in the main app bundle and not an app extension. I'm checking auth state in a number of extension (share, chat, Siri intents) so at first my project wouldn't build. I had to wrap a few statements in a preprocessor macros I already has set up to check that the code was running in the main application.

**Comment by cbess** [comment]
@KrisConrad First thing, you definitely have one of the best avatars I've seen on GitHub. 
> Retro Zelda + cross shield, nice.

Related to your issues; I think I've seen those mentioned before and I thought they were resolved. Perhaps, submit a separate issue, since the code changes I made don't effect `UIApplication` calls.

Here are some references you may be familiar with that I think are related:
- https://github.com/firebase/firebase-ios-sdk/issues/69
- https://github.com/firebase/firebase-ios-sdk/issues/310
- https://stackoverflow.com/q/45427267/344591

**Comment by KrisConrad** [comment]
Thanks, I'm a huge fan of the Zelda Franchise. 

Those issues you linked were more about multithreading than App Extensions, but I can definitely seek out the proper repo and file an issue there, just thought you'd want to be aware of the problem one of the dependencies were causing.

Thanks again for the work you're putting into this.

**Comment by mylogon341** [comment]
I’m interested in how this is going. Has your Jesus graced you with enough time to finish this? XD
