### ISSUE TITLE
CocoaPods could not find compatible versions for pod "FirebaseStorage"

### ISSUE THREAD

**Issue by willbattel** [firebase/FirebaseUI-iOS#727]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 11.1
  * Firebase SDK version: 6.4.0
  * FirebaseUI version: 8.0.2
  * CocoaPods Version: 1.7.4
  
### Step 3: Describe the problem:

Trying to update from Firebase 6.3.0 to 6.4.0- encountering this error:
```
[!] CocoaPods could not find compatible versions for pod "FirebaseStorage":
  In Podfile:
    Firebase/Storage (~> 6.4.0) was resolved to 6.4.0, which depends on
      FirebaseStorage (~> 3.3.0)

    FirebaseUI/Storage (~> 8.0.2) was resolved to 8.0.2, which depends on
      FirebaseStorage (~> 3.2.0)
```

#### Steps to reproduce:

  1. Specify pod version 6.4.0 for Firebase/Storage, 8.0.2 for FirebaseUI/Storage
  2. `pod update`
  
#### Relevant Code:

My full Podfile

  ```
# Uncomment the next line to define a global platform for your project
platform :ios, '11.1'

target 'foobar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core', '~> 6.4.0'
  pod 'Firebase/AdMob', '~> 6.4.0'
  pod 'Firebase/Auth', '~> 6.4.0'
  pod 'Firebase/Firestore', '~> 6.4.0'
  pod 'Firebase/Functions', '~> 6.4.0'
  pod 'Firebase/Performance', '~> 6.4.0'
  pod 'Firebase/RemoteConfig', '~> 6.4.0'
  pod 'Firebase/Storage', '~> 6.4.0'
  pod 'FirebaseUI/Storage', '~> 8.0.2'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.13.3'
  
  pod 'Branch', '~> 0.27.1'

  target 'foobarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'foobarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
  ```

**Comment by willbattel** [comment]
Just waiting for the podspec to be updated. Cannot use Firebase 6.4.0 until FirebaseUI updates their Storage dependency to 6.3

https://github.com/CocoaPods/Specs/blob/master/Specs/b/c/2/FirebaseUI/8.0.2/FirebaseUI.podspec.json#L68

**Comment by morganchen12** [comment]
Unusual, this should be updated by now. Is this reproducible in a project without FirebaseUI?

**Comment by willbattel** [comment]
Firebase 6.4.0 incremented its FirebaseStorage requirement from 3.2 to 3.3. I can install no problem without FirebaseUI, but the podspec for FirebaseUI/Storage still requires 3.2- so the install fails. The FirebaseUI podfile doesn't specify this version requirement- only the podspec as I linked above.

I may be mistaken but I'm guessing FirebaseUI will need to publish a new patch version, i.e., 8.0.3, that increments this minor FirebaseStorage version in the podspec. I'm not a Cocoapods expert but I believe that the dependency versions are locked to each published podspec, so a new version would need to be published to update the dependency requirement.

**Comment by willbattel** [comment]
Hey @morganchen12 we're about to ship a project and we were going to update to 6.4.0 if possible. Is this something you think will be resolved in the next couple days, or should we just stick with 6.3.0? Thanks.

**Comment by morganchen12** [comment]
I'll have a fix pushed for this on Monday.

**Comment by morganchen12** [comment]
Release is out. Thanks for filing!
