### ISSUE TITLE
When importing just FirebaseUI.framework, FirebaseAuthUI not available 

### ISSUE THREAD

**Issue by pbonneville** [firebase/FirebaseUI-iOS#73]
When directly importing the FirebaseUI.framework into my project as an alternative to using Cocoapods, FirebaseAuthUI is not available when I try to import it via the configuration directions. I'm getting "No such module". 

This is a Swift project, so I thought I'd tweak the Firebase.h file to include the FirebaseAuthUI framework, but since there is no .h file in the FirebaseUI framework for FirebaseAuthUI, I'm at a loss as to how to use it.

**Comment by mcdonamp** [comment]
Where did you download this from? You'll want to download the framework from: https://dl.google.com/firebase/firebaseui/ios/0_4_0/FirebaseUIFrameworks.zip which should contain the four appropriate frameworks.

FirebaseUI.framework is 0.0-0.3, while FirebaseAuthUI is included in 0.4+

**Comment by pbonneville** [comment]
I downloaded it from https://github.com/firebase/FirebaseUI-iOS/releases per the documentation on https://github.com/firebase/FirebaseUI-iOS. I'll give what you linked to a whirl.

**Comment by mcdonamp** [comment]
Yep, the Zip I sent you is what you want. I'll update the releases with that Zip.

**Comment by pbonneville** [comment]
Using those provided frameworks takes care of the missing module issue but generates the following error with trying to build in the simulator or on device:

![screenshot 2016-06-15 15 04 54](https://cloud.githubusercontent.com/assets/1179637/16097365/b459ec1c-330a-11e6-8747-aba5fcd961ea.png)

This is after cleaning the build folder and clearing out derived data...

**Comment by mcdonamp** [comment]
You have to pull in a number of other frameworks both "internally" (`FirebaseAuth.framework`, `FirebaseDatabase.framework`) as well as several "external" frameworks (Facebook, GoogleSignIn, etc.). See https://firebase.google.com/docs/ios/setup#frameworks for more information.

This is why we recommend CocoaPods (as much as I understand how much people hate what it does to your project).

**Comment by pbonneville** [comment]
I already had all the other frameworks in place and had anon auth working. Playing with the UI was my next step. Turned out it was the -ObjC flag in Build Settings > Other Linker Flags that was tripping it up. It compiled after that but gave me an error: +[NSData gtm_dataByGzippingData:]... which Googling said you needed to add the -ObjC flag...but then I was back to getting the errors I screen grabbed above...

Cocoapods it shall be for now
