### ISSUE TITLE
FirebaseUI not displaying buttons - ReOpened

### ISSUE THREAD

**Issue by dbaij** [firebase/FirebaseUI-iOS#750]
Step 1: Are you in the right place?
Step 2: Describe your environment
Objective C or Swift: 5.0
iOS version: 12.2
Firebase SDK version: i dont know sorry
FirebaseUI version: i dont know sorry
CocoaPods Version: i dont know sorry
I Do have email enabled so that is not the problem.
<img width="957" alt="Screen Shot 2019-08-13 at 2 21 09 PM" src="https://user-images.githubusercontent.com/54078452/62966741-a4147a80-bdd5-11e9-8adf-7f0666f4112e.png">

Step 3: Describe the problem:
Hi recently I have used the firebase UI as a sign-in method for a test app. The buttons are not displaying for the page after you click a correct login button. But only the welcome displays as shown:
<img width="338" alt="Screen Shot 2019-08-12 at 5 51 15 PM" src="https://user-images.githubusercontent.com/54078452/62966381-ebe6d200-bdd4-11e9-82fb-5d011be853bb.png">

Steps to reproduce:
My code is for the login is the following:
```
import UIKit
import FirebaseAuth
import FirebaseUI

typealias FIRUser = FirebaseAuth.User

class LoginViewController: UIViewController {

@IBOutlet weak var loginButton: UIButton!


override func viewDidLoad() {
    super.viewDidLoad()

    // Do any additional setup after loading the view.
    
}

@IBAction func loginButtonPressed(_ Sender: UIButton) {
    // 1
    guard let authUI = FUIAuth.defaultAuthUI()
        else { return }
    
    // 2
    authUI.delegate = self
    
    // 3
    let authViewController = authUI.authViewController()
    present(authViewController, animated: true)
}



/*
// MARK: - Navigation

// In a storyboard-based application, you will often want to do a little preparation before navigation
override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    // Get the new view controller using segue.destination.
    // Pass the selected object to the new view controller.
}
*/
}

extension LoginViewController: FUIAuthDelegate {
func authUI(_ authUI: FUIAuth, didSignInWith authDataResult: AuthDataResult?, error: Error?) {
print("handle user signup / login")
}

}
```

Observed Results:
I feel like this has a simple answer and thank you for the help ahead of time!
I'm also in a different area zone away from the central server of my project. I did use a VPN and the problem remained so I do not think that is the problem.

**Comment by morganchen12** [comment]
You need to set the [providers](https://github.com/firebase/FirebaseUI-iOS/blob/master/Auth/FirebaseAuthUI/FUIAuth.h#L188), otherwise FirebaseAuthUI won't have any sign-in methods.
