### ISSUE TITLE
Non translucent navigation bar aren't positioned properly

### ISSUE THREAD

**Issue by SebastienFCT** [firebase/FirebaseUI-iOS#753]
### Step 1: Are you in the right place?

This is a bug directly related to the code of this repository

### Step 2: Describe your environment

  * Objective C or Swift: 5
  * iOS version: 12.2
  * Firebase SDK version: 6.6.0 (Firebase/Auth)
  * FirebaseUI version: 8.0.4 (FirebaseUIAuth)
  * CocoaPods Version: 1.5.2
  
### Step 3: Describe the problem:

The `pickerViewController` doesn't seem to be handling translucent navigation bar properly. It will push the scroll view down leaving a empty padding underneath the navigation bar. 

This results is poor padding outside of the safe area for devices with notch.

#### Steps to reproduce:

Set the properly `isTranslucent` of the picker's navigation controller ('s navigation bar) to `false`

See last section for code sample.
  
#### Observed Results:

* The scrollview embedded in the picker gets push down
  
#### Expected Results:

* It should properly support the "translucence"?
  
#### Relevant Code:

They are many ways to achieve this, here's 3 of them:

1. In your `AppDelegate`, call `UINavigationBar.appearance().isTranslucent = false` in the `viewDidFinishLaunchingWithOptions`
2. in your controller presenting your picker, you can access the root navigation controller as well:

```swift
let authUI = FUIAuth.defaultAuthUI()
authUI?.delegate = self

let providers: [FUIAuthProvider] = [
    FUIEmailAuth(),
    FUIGoogleAuth(),
    FUIFacebookAuth()
]

authUI?.providers = providers

if let controller = authUI?.authViewController() {
    controller.navigationBar.isTranslucent = true
    present(controller, animated: true)
}
```

3. You can also extends from the default picker and set the `isTranslucent` property from your `viewDidAppear` to actually see the difference:

```swift
import UIKit
import FirebaseUI

class LoginPickerVC: FUIAuthPickerViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        navigationController?.navigationBar.isTranslucent = false
    }
    
}
```

#### Work around:

* I suppose one could set the `navigationbar.backgroundColor` to match his/her default color **with** the translucence.
* Obviously (and it might help people facing the same issue), setting this particular navigation bar non translucent will fix the padding issue (you can achieve this through the last 2 code sample for example)

#### Illustration:

<img width="355" alt="Screen Shot 2019-08-17 at 9 42 49 PM" src="https://user-images.githubusercontent.com/2982335/63219628-afe89f80-c13b-11e9-846d-68f9b1a5c36c.png">

**Comment by morganchen12** [comment]
Closed in #754.
