### ISSUE TITLE
ld: library not found for -lFBSDKCoreKit

### ISSUE THREAD

**Issue by DaveKerr** [firebase/FirebaseUI-iOS#76]
**When I compile with XCode 7.3.1 I get the following error:**
```
ld: warning: directory not found for option '-L/Users/Dave/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphoneos/FBSDKCoreKit'
ld: warning: directory not found for option '-L/Users/Dave/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphoneos/FBSDKLoginKit'
ld: library not found for -lFBSDKCoreKit
```

**Using Cocoapods 1.0.1with this podfile**

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

target 'myapp' do

 pod 'Google-Mobile-Ads-SDK'
 pod 'Google/Analytics'
 pod 'Firebase'
 pod 'Firebase/Auth'
 pod 'FirebaseUI', '~> 0.4'

end
```

**Using a pod update:**
```
pod update
Update all pods
Re-creating CocoaPods due to major version update.
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing Bolts (1.7.0)
Installing FBSDKCoreKit (4.13.1)
Installing FBSDKLoginKit (4.13.1)
Installing Firebase (3.3.0)
Installing FirebaseAnalytics (3.2.1)
Installing FirebaseAuth (3.0.3)
Installing FirebaseDatabase (3.0.2)
Installing FirebaseInstanceID (1.0.7)
Installing FirebaseUI (0.4.0)
Installing Google (3.0.3)
Installing Google-Mobile-Ads-SDK (7.8.1)
Installing GoogleAnalytics (3.14.0)
Installing GoogleAppUtilities (1.1.1)
Installing GoogleAuthUtilities (2.0.1)
Installing GoogleInterchangeUtilities (1.2.1)
Installing GoogleNetworkingUtilities (1.2.1)
Installing GoogleParsingUtilities (1.1.1)
Installing GoogleSignIn (4.0.0)
Installing GoogleSymbolUtilities (1.1.1)
Installing GoogleUtilities (1.3.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 5 dependencies from the Podfile and 20
total pods installed.

[!] Unable to read the license file `/Users/Dave/Documents/KSS/myapp/Pods/FirebaseUI/LICENSE` for the spec `FirebaseUI (0.4.0)`

[!] Unable to read the license file `/Users/Dave/Documents/KSS/myapp/Pods/FirebaseUI/LICENSE` for the spec `FirebaseUI (0.4.0)`
```

**Comment by mcdonamp** [comment]
Strange--it looks like you're getting FBSDKCoreKit downloaded, but for some reason your project can't link the framework. Are you using Swift by chance?

**Comment by DaveKerr** [comment]
No - Objective-C.

**Comment by mcdonamp** [comment]
Things should definitely work in Objective-C. Are you sure you're opening the `.xcworkspace` after you run `pod install`? Maybe Facebook only supports iOS 8 and above because they went to dynamic frameworks in CocoaPods (pure wild speculation). If you target 8+ and use `use_frameworks!` in the `podfile` does it work?

**Comment by DaveKerr** [comment]
Thanks for the follow up.  I could not figure out / tinker with this problem so I created a whole new project, copied all my code and image assets to the new project, created new podfile and it is working.  So it appears as though it was some setting in the project that was creating the problem.  Unfortunately I don’t have the time to understand specifically what the problem is.  I need to move on at this point.

**Comment by mcdonamp** [comment]
I usually run `pod deintegrate`, clean, and re-build--but if some random `xcconfig` was broken then that's usually a good plan :)

Glad you got it working again!
