### ISSUE TITLE
Login via Facebook app can't be completed

### ISSUE THREAD

**Issue by slepimar** [firebase/FirebaseUI-iOS#760]
Describe your environment:

  * Swift: 5
  * iOS version: 12.4
  * Firebase SDK version: 6.7.0
  * FirebaseUI version: 8.0.4
  * CocoaPods Version: 1.7.2
  * FBSDKLoginKit: 5.4.1

Describe the problem:

I'm using Facebook login using the vie the FirebaseUI with FB provider. I configured facebook ap, enabled facebook login on firebase console and added url schemes (all checked many times). I'm also using the Google login and EmailLink. Facebook login is the only one that i can't get to work. I can sign in only with email/phone + password, but i can't sign in with facebook app. I don't know what else i can do. Could you please help me. Thank you

#### Steps to reproduce:

  1. click on firebase FUIFacebookAuth provider button - i'm now on page where i can chose from sign in from facebook app or via entering my credentials and password
  3. chose sign in via facebook app - i'm redirected to facebook app, where i'm asked if i want to continue(allow the sign in).
 4. clicked the continue and i'm redirected back to the page after the 1. step
 5. the sign in from facebook app is like never ending loop

**Comment by slepimar** [comment]
No errors printed to the console.

**Comment by joshqq** [comment]
Yes, I have the same experience as well. So I did a Analyze and showed a dozen of "memory errors". 

Some of the examples for FirebaseUI:
...app../Pods/FirebaseUI/FacebookAuth/FirebaseFacebookAuthUI/FUIFacebookAuth.m:193:35: nil passed to a callee that requires a non-null 1st parameter

..app.../Pods/FirebaseUI/Auth/FirebaseAuthUI/FUIPrivacyAndTermsOfServiceView.m:51:5: nil returned from a method that is expected to return a non-null value

hopefully this will shed some light to others...

**Comment by GGustavoLopez** [comment]
@slepimar I faced exactly the same issue, I was following the Firebase UI example when I realized that in AppDelegate.swift for handle open url, was returning false, what I did in order to resolve it, is update my AppDelegate's open url as follows. Let me know if that fixes your issue.

`func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any]) -> Bool {
        let sourceApplication = options[UIApplication.OpenURLOptionsKey.sourceApplication] as! String?
        let fbHandled = ApplicationDelegate.shared
        .application(app, open: url, options: options)
        
        return handleOpenUrl(url, sourceApplication: sourceApplication) || fbHandled
    }`

**Comment by loveuqian** [comment]
same issue here
only error with facebook

Error Domain=FIRAuthErrorDomain Code=17004 "Facebook Access token already expired." UserInfo={NSLocalizedDescription=Facebook Access token already expired., FIRAuthErrorUserInfoNameKey=ERROR_INVALID_CREDENTIAL}

**Comment by slepimar** [comment]
It was actually my fault handling FBSDK wrong(https://developers.facebook.com/docs/facebook-login/ios step 5). I handled the results from the native Facebook app wrong. This code added to AppDelegate fixed the issue.
`func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        return ApplicationDelegate.shared.application(app, open: url, options: options)
    }`
