### ISSUE TITLE
Cannot sign in with Email Link for users authenticated by both password and email link

### ISSUE THREAD

**Issue by shosokawa** [firebase/FirebaseUI-iOS#763]
### Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 12.4
  * Firebase SDK version: 6.7.0
  * FirebaseUI version: 8.0.4
  * CocoaPods Version: 1.7.5

### Describe the problem:
A user who has been authenticated by `Email` with both `password` and `emailLink` cannot use `emailLink` authentication even if it uses `FUIEmailAuth` initialized with `signInMethod: EmailLinkAuthSignInMethod`.

`fetchSignInMethodsForEmail` returns `["password", "emailLink"]`as `providers` for the user.
https://github.com/firebase/FirebaseUI-iOS/blob/8a6ad617c61e99a50a80585a7a2ba7b16bb35cab/EmailAuth/FirebaseEmailAuthUI/FUIEmailEntryViewController.m#L149-L151

It seems that if `providers` contains `"password"`, it never runs `[self sendSignInLinkToEmail:emailText];`. 
https://github.com/firebase/FirebaseUI-iOS/blob/8a6ad617c61e99a50a80585a7a2ba7b16bb35cab/EmailAuth/FirebaseEmailAuthUI/FUIEmailEntryViewController.m#L187-L189

#### Observed Results:
After a user inputs email address in the form, it always goto the form for password.
  
#### Expected Results:
I think that if `fetchSignInMethodsForEmail` returns both `["password", "emailLink"]` and `signInMethod` is indicated as `EmailLinkAuthSignInMethod`, it should use `emailLink`. 
Additionally I also think that it's nice to have a way to use `emailLink` authentication for a user who has been authenticated by email only with password.

#### Relevant Code:
- Our code to call SignIn by Email
  ```swift
        let authUI = FUIAuth.defaultAuthUI()!
        authUI.delegate = self
        let settings = ActionCodeSettings()
        settings.url = Constants.URLs.login
        settings.handleCodeInApp = true
        settings.setIOSBundleID(Constants.AppInfo.bundleIdentifier)
        authUI.providers = [
            FUIEmailAuth(
                authAuthUI: authUI,
                signInMethod: EmailLinkAuthSignInMethod,
                forceSameDevice: true,
                allowNewEmailAccounts: true,
                actionCodeSetting: settings
            )
        ]
        let provider = authUI.providers.first as! FUIEmailAuth
        provider.signIn(withPresenting: self, email: nil)
  ```

**Comment by morganchen12** [comment]
@renkelvin, is this intended behavior?

**Comment by renkelvin** [comment]
Yeah, it's intended. "password" sign in method is preferred to "emaillink" when it's available. We don't have plan to make it customizable at this time.
