### ISSUE TITLE
useAppLanguage() has no effect

### ISSUE THREAD

**Issue by lumo2707** [firebase/FirebaseUI-iOS#764]
### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 11.0
  * Firebase SDK version: 5.20.2
  * FirebaseUI version: 6.2.1
  * CocoaPods Version: 1.7.5
  
### Step 3: Describe the problem:

I'm trying to set the language of the FUIAuth.defaultAuthUI. For this I call the useAppLanguage() function. In the image you can see my language settings in the system settings.
![IMG_EEF5A965556F-1](https://user-images.githubusercontent.com/8993387/64061460-5b353200-cbdb-11e9-9531-b0dae876e9ce.jpeg)

#### Observed Results:

The language is always english.
  
#### Expected Results:

The language of the view elements should be the one of the device.
  
#### Relevant Code:

  ```   
self.authUI = FUIAuth.defaultAuthUI()
self.authUI.delegate = self
self.authUI.auth?.useAppLanguage()
authUI?.delegate = self
let providers: [FUIAuthProvider] = [
            FUIGoogleAuth(),
            FUIEmailAuth() ]
authUI?.providers = providers

  ```

**Comment by morganchen12** [comment]
This is most likely caused by FirebaseUI not being able to find the strings files in the framework bundle. Are you able to reproduce this issue with the apps in the [sample folder](https://github.com/firebase/FirebaseUI-iOS/tree/master/samples) of this repo?

**Comment by lumo2707** [comment]
With the sample application I have no issues. Could this problem be issued by an older version of FirebaseUI and Firebase? Currently i'm using 5.x for Firebase and FirebaseUI 6.2.1. I cannot update the dependencies because the RXFirebase resolves Firebase to ~>5.0.

I will try the sample application with the older version and update my answer.

**Comment by morganchen12** [comment]
Glad you were able to resolve this issue!

**Comment by Sosotess93** [comment]
Hi, sorry to reopen this matter. 
I do have the same issue actually. 
I'm using the latest version of FirebaseUI (FirebaseUI 9.0.0). 

Here is the code I use : 

```

        let authUI = FUIAuth.defaultAuthUI()
        authUI?.auth?.useAppLanguage()
        authUI?.auth?.languageCode = "fr"
        authUI?.delegate = self
        let providers: [FUIAuthProvider] = [
            FUIPhoneAuth(authUI:FUIAuth.defaultAuthUI()!)
        ]
        authUI?.providers = providers
        let phoneProvider = FUIAuth.defaultAuthUI()?.providers.first as! FUIPhoneAuth
        phoneProvider.signIn(withPresenting: self, phoneNumber: nil)
```

Firebase is still in english after that, my phone and region are configured in french.

**Comment by morganchen12** [comment]
Are you able to confirm that the localization strings are present in your app bundle?

**Comment by Sosotess93** [comment]
Yes, I can confirm you that the localization strings are present in the app bundle. 

<img width="491" alt="Screenshot 2020-11-21 at 23 13 04" src="https://user-images.githubusercontent.com/9814707/99888723-1ddd1a00-2c4f-11eb-8f91-5ba46770c03d.png">

The localisation are here in french as needed.

**Comment by morganchen12** [comment]
If FirebaseUI is able to find the localized strings at runtime, it should use the device's language without you having to set the language code explicitly. Are you able to reproduce this issue in the sample app in this repository?
