### ISSUE TITLE
ITMS-90809: Deprecated API Usage - FirebaseUI/Google

### ISSUE THREAD

**Issue by damienpraca** [firebase/FirebaseUI-iOS#771]
Hi,

The latest FirebaseUI/Google (8.0.4) is using  GoogleSignIn 4.4.0 (and not 5.0.0) and is not compliant anymore with the new Apple policies because of use of UIWebView API.

When trying to submit the app to Apple on AppConnect, they drop a no go warning message, preventing from being reviewed successfully :

`ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.`

Steps to reproduce :
```
$ pod install
Installing FirebaseUI 8.0.4
Installing GoogleSignIn (4.4.0)
Installing GoogleToolboxForMac (2.2.1)
```

but when forcing GoogleSignIn to 5.0.0 with `pod 'GoogleSignIn', '5.0.0'`
```
$ pod install
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "GoogleSignIn":
  In Podfile:
FirebaseUI/Google was resolved to 8.0.4, which depends on
      GoogleSignIn (~> 4.0)
GoogleSignIn (= 5.0.0)
```

then

```
$ grep -r "UIWeb" .
./Pods/GoogleSignIn/CHANGELOG.md:- Supports sign-in via UIWebView rather than app switching to a browser,
Binary file ./Pods/GoogleSignIn/Frameworks/GoogleSignIn.framework/GoogleSignIn matches
```

FirebaseUI/Google needs to be compatible with the latest release of GoogleSignIn 5.0.0 already available as a pod.

**Comment by damienpraca** [comment]
Have you got a chance to look at it, is the dependency bump worked or it needs more integration work?
Thanks

**Comment by angeria** [comment]
Also wondering about the state of this issue since the dependancy is not bumped to 5.0.0 yet.

**Comment by morganchen12** [comment]
Apologies for the delay, this has been released. Please update your FirebaseUI version and let me know if this is still an issue.

**Comment by sanchofox** [comment]
Installing FirebaseUI with CocoaPods, I still have GoogleSignIn version 4.4.0 instead of 5.0.0. Does anyone have the same issue?

**Comment by angeria** [comment]
I updated to FirebaseUI 8.1.0 and GoogleSignIn got updated to 5.0.0 as well. The grep match for UIWebView in GoogleSignIn has disappeared.

Make sure you use `pod update` and not `pod install` if you did that @sanchofox

**Comment by sanchofox** [comment]
Ok, thank you! Solved!

**Comment by damienpraca** [comment]
Thanks it is solved

**Comment by RanjeetStiga** [comment]
./Pods/GoogleSignIn/CHANGELOG.md:- Supports sign-in via UIWebView rather than app switching to a browser,  when grape UIWebView

Using GoogleSignIn 5.0.0

**Comment by Nikoloutsos** [comment]
I'm using:
`pod 'GoogleSignIn'`
I tried to use the following line
`pod 'GoogleSignIn', '~> 5.0.0'`
Terminal output:
`[!] CocoaPods could not find compatible versions for pod "GoogleSignIn":
  In Podfile:
    GoogleSignIn (~> 5.0.0)`

What should I do?

**Comment by morganchen12** [comment]
Run `pod repo update`.

**Comment by yesnoyes** [comment]
GoogleSignIn is still using AppAuth, which includes UIWebView. When would this be resolved?

**Comment by yesnoyes** [comment]
Appstore is keep giving warning after uploading App to Appstore -

Dear Developer,

We identified one or more issues with a recent delivery for your app, "XXXX. Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will no longer accept submissions of new apps that use UIWebView as of April 30, 2020 and app updates that use UIWebView as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

After you’ve corrected the issues, you can upload a new binary to App Store Connect.

**Comment by reysantana** [comment]
Versions higher than GoogleSignIn 4.4.0 produce errors when building, version 4.4.0 works fine without any error, but the problem is that it uses UIWebView, I would like UIWebView of 4.4.0 replaced with WKWebView.

**Comment by mayur43s** [comment]
It does not as I'm still seeing the user of webview and the app is getting rejected on App Store here's the terminal output with `pod update` 
```
Installing AppAuth (1.3.0)
Installing GTMAppAuth (1.0.0)
Installing GTMSessionFetcher 1.4.0 (source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing GoogleSignIn 5.0.2 (was 4.4.0 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
```
Now when I do `grep -r "UIWeb" .` It gives this output:
```
./Pods/AppAuth/Source/AppAuth.h:    for the auth request. `UIWebView` and `WKWebView` are explicitly *not*
./Pods/AppAuth/README.md:for the auth request. `UIWebView` and `WKWebView` are explicitly *not*
./Pods/GoogleSignIn/CHANGELOG.md:- Supports sign-in via UIWebView rather than app switching to a browser,```

**Comment by akinncar** [comment]
> Versions higher than GoogleSignIn 4.4.0 produce errors when building, version 4.4.0 works fine without any error, but the problem is that it uses UIWebView, I would like UIWebView of 4.4.0 replaced with WKWebView.

Same here, some update?

**Comment by morganchen12** [comment]
AppAuth references webview in a header comment only; you can either appeal your app rejection to Apple or you can remove the header comment manually and resubmit.

See this issue: https://github.com/openid/AppAuth-iOS/issues/449

**Comment by yeleleo** [comment]
5.0.2 is available, just update your Podfile to `pod 'GoogleSignIn', '5.0.2'`
and run `$ pod install`

Here is how to migrate from 4.x: https://developers.google.com/identity/sign-in/ios/quick-migration-guide

**Comment by itsmasabdi** [comment]
@kazunetakeda25 

> Versions higher than GoogleSignIn 4.4.0 produce errors when building, version 4.4.0 works fine without any error, but the problem is that it uses UIWebView, I would like UIWebView of 4.4.0 replaced with WKWebView.

I'm having the exact same issue, have even tried importing this repo and use 5.0.2 based on https://github.com/googlesamples/google-signin-unity/issues/122 but still no luck. 

Any help on this?
