### ISSUE TITLE
Versioning and login providers

### ISSUE THREAD

**Issue by borut-t** [firebase/FirebaseUI-iOS#784]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If your issue concerns the CocoaPods error, "...transitive dependencies that include static binaries", please take a look at any of the following issues and see if your problem is solved: #48, #47, #46, #34, #23.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Objective C or Swift: swift
  * iOS version: 13
  * Firebase SDK version: 5.20.1
  * FirebaseUI version: 6.2.1
  * CocoaPods Version: 7.5
  
#### Steps to reproduce:

1. I have always been confused by Firebase versioning and I still am. Looking at the release notes I can see there is a version 8.1.0 out there. Looking at the https://cocoapods.org and search for `FirebaseUI` I can see version 6.2.1. What in the hell is going on?
2. I've been used to the version 5.x and I didn't need to specify any login provider since email was a default. And that worked and still works today. When I've upgraded to 6.2.1 I needed to specify `FUIEmailAuth()` since we only support login with email. And when I run the app I got a new screen asking me first to select between one (1) provider - email in this case. And when I tapped it, I was finally able to get to the screen I wanted.

#### Observed Results:

I can see a list with only one provider instead.
  
#### Expected Results:

To see the only selected email provider without a list. What can we do here?

Also, dark mode still not supported. What's going on. WWDC was 3 months ago.

Also, documentation in general is really bad. Of is it missing or the example code is outdated.
  
#### Relevant Code:

```swift
let providers: [FUIAuthProvider] = [FUIEmailAuth()]
uiAuthenticationHelper?.providers = providers
```

**Comment by morganchen12** [comment]
1. Cocoapods search is a little weird, not sure what's going on there. You can see the latest version on the CocoaPods website is 8.1.0 [here](http://cocoapods.org/pods/FirebaseUI).
2. You can skip the sign in screen by calling [this method](https://github.com/firebase/FirebaseUI-iOS/blob/master/EmailAuth/FirebaseEmailAuthUI/FUIEmailAuth.h#L116) directly.
3. Dark mode support was merged just now and will be out in the next release. I'll look at updating the documentation soon.

**Comment by borut-t** [comment]
@morganchen12 thanks for answers. They were helpful. Although I still have some concerns. I'll respond to the original bullets:
1. I was able to upgrade to 8.10.0 now 👍 
2. I've tried and it works 👍 
3. I'll need to hold off with this update until the dark mode is officially supported. The main reason for updating this lib is because of dark mode support. 

Although your solution under 2. works fine I see you are using `default` presentation context which is different in iOS 13. That's fine, but I would like to disable pan gesture to dismiss view using `isModalInPresentation` flag. How can I do it with this method since I don't have any reference to the target view controller?

```swift
func presentLoginUI(from vc: UIViewController) {
  let emailAuth = FUIEmailAuth()
  let providers: [FUIAuthProvider] = [emailAuth]
  let authUi = FUIAuth.defaultAuthUI()
  authUi?.providers = providers
  authUi?.tosurl = URL(string: Constants.Legal.tosUrl)
  authUi?.delegate = self
  emailAuth.signIn(withPresenting: vc, email: nil)
}
```

Another thing is that I would like to change navigation bar style with mine. Previously I was able to do this:

```swift
guard let firebaseNc = FUIAuth.defaultAuthUI()?.authViewController(), let firebaseVc = firebaseNc.viewControllers.first else { return }
let myNc = MyNavigationController(rootViewController: firebaseVc)
myNc.isModalInPresentation = true
```

Any thougths?

**Comment by morganchen12** [comment]
@renkelvin can you answer these questions? Disabling the pan gesture may require a FirebaseUI patch.

**Comment by borut-t** [comment]
@morganchen12 what's the state with dark mode and pan gestures?

**Comment by morganchen12** [comment]
I plan on releasing the dark mode update this week. No progress on pan gesture yet.

**Comment by borut-t** [comment]
Ok, that's great for dark mode. However, it's not great for not implementing pan gesture handling. If you leave it as is since user will be stuck because we don't get a success/error callback. I think you should consider that too.

**Comment by borut-t** [comment]
@morganchen12 any progress update on dark mode and pan gesture handling?

**Comment by morganchen12** [comment]
Fix is up at #788. Sorry for the delay! I'll release the two features together.

**Comment by morganchen12** [comment]
8.2.0 has been released.

**Comment by artmatsak** [comment]
@morganchen12 Thank you for looking into this! However, the fix in #788 seems to only address `FUIAuthPickerViewController`. If I skip the sign-in screen by calling `phoneProvider.signIn(withPresenting: self, phoneNumber: nil)` directly, the modal is still dismissable with the pan gesture.

Also, a side question: Is there a way to make the modal fullscreen in iOS 13? The view controller isn't exposed so I can't set its `modalPresentationStyle` to `.fullScreen`.

**Comment by morganchen12** [comment]
@artmatsak You're right, see my comment here: https://github.com/firebase/FirebaseUI-iOS/issues/789#issuecomment-543349893

Let me know if #792 solves your issue.

**Comment by artmatsak** [comment]
I haven't tried it but it should work, thanks!
