### ISSUE TITLE
Property 'modalInPresentation' not found on object of type 'FUIAuthPickerViewController *' IOS 13

### ISSUE THREAD

**Issue by dbaij** [firebase/FirebaseUI-iOS#793]
Thanks for Help in Advance!

### Step 1: Are you in the right place?

Ye

### Step 2: Describe your environment

Objective C or Swift: Swift
iOS version: 12.4
Firebase SDK version: 6.9
FirebaseUI version: 8.2
CocoaPods Version: 1.8.4
  
### Step 3: Describe the problem:

  self.navigationItem.leftBarButtonItem = cancelBarButton;
  } else {
    if (@available(iOS 13, *)) {
      self.modalInPresentation = YES;
    }
  }  
#### Observed Results:

Property 'modalInPresentation' not found on object of type 'FUIAuthPickerViewController *'  
#### Expected Results:

My project to build  
#### Relevant Code:

} else {
    if (@available(iOS 13, *)) {
      self.modalInPresentation = YES;
    }
  }

**Comment by morganchen12** [comment]
For the time being you can work around this by using FirebaseUI 8.1.0. In the future, you'll need to upgrade to Xcode 11 to build FirebaseUI.
