### ISSUE TITLE
FUIAuthDelegate callback not called for Facebook login in iOS 13

### ISSUE THREAD

**Issue by alijaza** [firebase/FirebaseUI-iOS#794]
### Step 1: Are you in the right place?

yes

### Step 2: Describe your environment

  * Swift
  * iOS version: 13
  * Firebase SDK version: 6.3.1
  * FirebaseUI version: 8.2.0
  * CocoaPods Version: 1.6.2
  
### Step 3: Describe the problem:

Launching Facebook auth from root view controller (this seemed to be an issue with others). Facebook authenticates but callback is never triggered.

#### Steps to reproduce:

See sample ccode
  
#### Observed Results:

Callback not triggered  

#### Relevant Code:

  ```
class AuthViewController: UIViewController, FUIAuthDelegate {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.view.backgroundColor = .white
        let authUI = FUIAuth.defaultAuthUI()
        authUI?.delegate = self;
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        let vc = AuthHelper.shared.authUI.authViewController()
        vc.modalPresentationStyle = .overFullScreen
        self.present(vc, animated: true, completion: nil)
    }
    
    func authUI(_ authUI: FUIAuth, didSignInWith authDataResult: AuthDataResult?, error: Error?) {
        if (error != nil) {
            let vc = AuthHelper.shared.authUI.authViewController()
            vc.modalPresentationStyle = .overFullScreen
            self.present(vc, animated: true, completion: nil)
        } else {
            FlowControl.gotoMainApp(loggedIn: true)
        }
    }
    
    func authPickerViewController(forAuthUI authUI: FUIAuth) -> FUIAuthPickerViewController {
        return FUICustomAuthPickerViewController(nibName: "FUICustomAuthPickerViewController",
                                                 bundle: Bundle.main,
                                                 authUI: authUI)
    }
    
}
  ```

**Comment by alijaza** [comment]
You can create a sample project and just instantiate this VC as follows to reproduce:

`
guard let appDelegate = UIApplication.shared.delegate as? AppDelegate else { return }
appDelegate.window!.rootViewController = AuthViewController()
`

**Comment by alijaza** [comment]
Looks like the callback changed at some point. Was missing this:
    `func authUI(_ authUI: FUIAuth, didSignInWith user: User?, error: Error?) {...}`

**Comment by razamerchantwork** [comment]
Hi, 

I'm not opening a separate issue because I'm having same issue as the title explains.

I'm using FirebaseUI (8.4.0), iOS 13.3, FBSDKCoreKit (5.13.1), FBSDKLoginKit (5.13.1).

Issue I'm facing is that, when I press facebook login button it re-directs to facebook auth and then after pressing continue, facebook auth dismiss but nothing happens and Firebase AuthUI is stuck on loading.

Can anyone please help? 
Thanks in advance.
