### ISSUE TITLE
'GoogleSignIn/GoogleSignIn.h' file not found

### ISSUE THREAD

**Issue by jimbo51235** [firebase/FirebaseUI-iOS#801]
If I try to compile my Xcode project for the first time, I get the following error under iOS 13.0.

'GoogleSignIn/GoogleSignIn.h' file not found

Even if I install the GoogleSignIn pod, I get the same error.  I do find GoogleSignIn.h in the GoogleSignIn folder, though.

**Comment by morganchen12** [comment]
Make sure the GoogleSignIn framework is located in a directory specified under your project's Framework Search Paths. If you're using CocoaPods, this should happen automatically.

**Comment by jimbo51235** [comment]
Thanks.  I am using CocoaPods.  And it happens.

**Comment by morganchen12** [comment]
Make sure you're using the latest version of CocoaPods and opening the `.xcworkspace` file instead of the `.xcodeproj` file.
