### ISSUE TITLE
FUIAuthTableViewCell can't build with Xcode 10.2.1

### ISSUE THREAD

**Issue by Oklahomawhore** [firebase/FirebaseUI-iOS#806]
`if (@available(iOS 13.0, *)) {
    self.textField.textColor = [UIColor labelColor];
    self.label.textColor = [UIColor labelColor];
  }`

This code generates ARC semantic issue thus making builds under ios 13 SDK impossible

**Comment by paulb777** [comment]
This combined with the [AppAuth dependency issue](https://github.com/openid/AppAuth-iOS/issues/489) probably means the README should be updated to specify an Xcode 11 requirement.

**Comment by morganchen12** [comment]
Added Xcode version requirement in afc3d56dd807c3b1b3415b551ca800f9d609bdec.
