### ISSUE TITLE
create-docs.sh does not work in bash

### ISSUE THREAD

**Issue by apwelsh** [firebase/FirebaseUI-iOS#81]
The create-docs.sh script identifies itself as a bash script, however, running the script results with the following output:

```
Generating appledocs...
appledoc version: 2.2.1 (build 1334)

Caught: AppledocException: Path or file '/Users/apwelsh/src/FirebaseUI-iOS/FirebaseUI/**/*.h' doesn't exist!

````

If, instead I run it using zsh with `zsh create-docs.sh` then it can identify the source .h files, but it still fails to create the documentation.

Generating appledocs...
appledoc version: 2.2.1 (build 1334)

```
WARN | FIRGoogleAuthUI.h@44: Description for parameter 'clientID' missing for -[FIRGoogleAuthUI initWithClientID:]!
WARN | FIRGoogleAuthUI.h@44: 1 unknown parameter descriptions (clientId) found for -[FIRGoogleAuthUI initWithClientID:]
WARN | FIRPasswordSignUpViewController.h@33: Description for parameter 'nibNameOrNil' missing for -[FIRPasswordSignUpViewController initWithNibName:bundle:authUI:]!
WARN | FIRPasswordSignUpViewController.h@33: Description for parameter 'nibBundleOrNil' missing for -[FIRPasswordSignUpViewController initWithNibName:bundle:authUI:]!

```

I have had nothing but failures trying to get the most basic examples and docs generated.  Is the library really that broken, or am I seriously missing something?

**Comment by mcdonamp** [comment]
I do indeed use `zsh`, so I guess it doesn't surprise me too much that it works in `zsh` and not `bash`.

And yes--unfortunately it's pretty broken from a developer perspective. We incurred a lot of technical debt in the run up to I/O, and we haven't had time to fix things since then (combination of burnout and tremendous uptake/support volume).

**Comment by apwelsh** [comment]
Thanks. Since i have no documentation, dont know Objectice-C well enough to reverse engineer the requirements for implementing the library under Swfit, I will use the current API and build my sign-in page manually.  I was hoping to avoid that with this library.

Is there a certain issue I should follow to know when it is all ready for use again?
