### ISSUE TITLE
No such module 'FirebaseUI'

### ISSUE THREAD

**Issue by jtressle** [firebase/FirebaseUI-iOS#810]
I'm getting `No such module 'FirebaseUI'` on Xcode 11.3.  I'm using SwiftUI, and this should be working right?  

Here's my pod file:

```
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Analytics'
#pod 'GoogleSignIn'
pod 'FirebaseUI', '~> 5.0'  
```

Looks like Facebook has issues:

`No known class method for selector 'objectForJSONString:error:'`

for line:

NSDictionary *clientState = [FBSDKInternalUtility objectForJSONString:parameters[FBSDKLoginManagerLoggingClientStateKey] error:NULL];

Thanks

**Comment by jtressle** [comment]
For now, I went ahead and removed the Facebook login.  Everything compiles now.  Here's my updated pod:

```
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Analytics'
#pod 'GoogleSignIn'
pod 'FirebaseUI/Firestore', '~> 8.0'
pod 'FirebaseUI/Auth', '~> 8.0'
pod 'FirebaseUI/Google', '~> 8.0'
``` 

Thanks

**Comment by morganchen12** [comment]
Looks like in between you also changed your versions of FirebaseUI. Can you try re-adding facebook and seeing if the compilation issue reappears?

**Comment by jtressle** [comment]
@morganchen12 I ran a couple of tests.

(1) Adding pod 'FirebaseUI/Facebook' works.
(2) Using pod 'FirebaseUI', '~> 5.0' after a clean doesn't work.
(3) Using pod 'FirebaseUI' works.  

Below is the pod diff going from step (2) to (3) (i.e. removing the '~> 5.0' requirement.  I must have looked at older documentation.

```
Installing AppAuth (1.3.0)
Installing BoringSSL-GRPC 0.0.3 (was 0.0.2)
Installing FBSDKLoginKit 5.11.1 (was 4.44.1)
Installing Firebase 6.13.0 (was 5.20.2)
Installing FirebaseAnalytics 6.1.6 (was 5.8.1)
Installing FirebaseAuth 6.4.0 (was 5.4.2)
Installing FirebaseCore 6.4.0 (was 5.4.1)
Installing FirebaseCoreDiagnostics (1.1.2)
Installing FirebaseCoreDiagnosticsInterop (1.1.0)
Installing FirebaseDatabase 6.1.2 (was 5.1.1)
Installing FirebaseFirestore 1.8.1 (was 1.2.1)
Installing FirebaseInstanceID 4.2.7 (was 3.8.1)
Installing FirebaseStorage 3.4.2 (was 3.1.1)
Installing FirebaseUI 8.4.0 (was 5.2.2)
Installing GTMAppAuth (1.0.0)
Installing GTMSessionFetcher 1.3.0
Installing GoogleAppMeasurement 6.1.6 (was 5.8.1)
Installing GoogleDataTransport (3.2.0)
Installing GoogleDataTransportCCTSupport (1.2.2)
Installing GoogleSignIn 5.0.2 (was 4.4.0)
Installing GoogleUtilities 6.3.2 (was 5.8.0)
Installing SDWebImage 5.4.0 (was 4.4.7)
Installing abseil (0.20190808)
Installing gRPC-C++ 0.0.9 (was 0.0.6)
Installing gRPC-Core 1.21.0 (was 1.17.0)
Removing GoogleToolboxForMac
Removing Protobuf
Removing TwitterCore
Removing TwitterKit
```

Thanks for your help.

**Comment by morganchen12** [comment]
I'll update the docs this week.

**Comment by adriano-s** [comment]
Same issue, but with Twitter.

That works:
```
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'FirebaseUI/Google'
```
but with the added line
```
  pod 'FirebaseUI/Twitter'
```
I have the same `No such module 'FirebaseUI'` issue.

Observation: When i run pod update on the new podfile with the added Twitter pod, it downgrades a lot of firebase dependencies. That doesn't look good to me:
```
Installing Firebase 2.5.1 (was 6.14.0 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing Firebase 6.14.0 (source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing FirebaseUI 8.4.0
Installing FirebaseUI 0.3.2 (was 8.4.0)
```

**Comment by morganchen12** [comment]
@adriano-s TwitterKit has been deprecated, so Twitter auth uses `FirebaseUI/OAuth` now.

**Comment by morganchen12** [comment]
The docs have been updated, but I forgot to close this issue. Please let me know if it's still an issue and I'll reopen it.

**Comment by adriano-s** [comment]
Thank you for updating the docs. Here I can still find `pod 'FirebaseUI/Twitter'`
https://firebase.google.com/docs/auth/ios/firebaseui

**Comment by morganchen12** [comment]
Thanks for letting me know. The doc has been updated internally and will be published soon.
