### ISSUE TITLE
Email textfield is not enabled when `allowNewEmailAccounts` is set to `NO`

### ISSUE THREAD

**Issue by tikipatel** [firebase/FirebaseUI-iOS#814]
Welcome to FirebaseUI and thanks for submitting an issue!

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

Yes.

### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: iOS 13
  * Firebase SDK version: Unrelated
  * FirebaseUI version: 8.4.0
  * CocoaPods Version: N/A
  
### Step 3: Describe the problem:

When using `FUIEmailAuth` where `allowNewEmailAccounts` is set to `NO`, the user is unable to tap the email textfield to enter an email.

#### Steps to reproduce:

  1. Instantiate an instance of `FUIEmailAuth` with `allowNewEmailAccounts` as `NO`
  2. Instantiate an instance of `FUIAuth` and add the above as a provider
  3. Run the app and tap `Sign in with email`
  
#### Observed Results:

  * Unable to enter email address.
  
#### Expected Results:

  * Should be able to enter email address.
  
#### Relevant Code:

  ```
https://github.com/firebase/FirebaseUI-iOS/blob/master/EmailAuth/FirebaseEmailAuthUI/FUIPasswordSignInViewController.m#L262
  ```

I think that `cell.textField.enabled` should only be `NO` when the `_email` property of the `FUIPasswordSignInViewController` class is non-null.

For a better experience, the email textfield should always be enabled in case the user wants to use a different email to sign in.

**Comment by morganchen12** [comment]
The fix for this has been released.
