### ISSUE TITLE
Firebase Error Domain=FIRAuthErrorDomain Code=17995 in test target

### ISSUE THREAD

**Issue by saranyaj86** [firebase/FirebaseUI-iOS#818]
Environment:

  * Objective C or Swift: swift
  * iOS version: 10.14.6_
  * Firebase SDK version: Firebase 6.2.0, FirebaseAuth (6.1.2)
 * CocoaPods Version: 1.7.5
 
Problem:

I am trying to auth with username and password, it throws the following error.

▿ Optional<Error>
  - some : Error Domain=FIRAuthErrorDomain Code=17995 "An error occurred when accessing the keychain. The @c NSLocalizedFailureReasonErrorKey field in the @c NSError.userInfo dictionary will contain more information about the error encountered" UserInfo={FIRAuthErrorUserInfoNameKey=ERROR_KEYCHAIN_ERROR, NSLocalizedFailureReason=SecItemAdd (-34018), NSLocalizedDescription=An error occurred when accessing the keychain. The @c NSLocalizedFailureReasonErrorKey field in the @c NSError.userInfo dictionary will contain more information about the error encountered}

**Comment by morganchen12** [comment]
This error means you're missing the Keychain entitlement: https://www.osstatus.com/search/results?platform=all&framework=all&search=-34018

**Comment by saranyaj86** [comment]
How to enable keychain sharing in test target and resolve the above error? In my scenario , the host application is none and  writing unit tests for the static library.

**Comment by morganchen12** [comment]
You can create a dummy app that does nothing and use it as your test host. Link the static library into the host and write tests against the library API.

I'm not sure if there's a way to resolve the error without using a test host.

**Comment by riverbaymark** [comment]
I am getting this error too.  Keychain Sharing is enabled. At first I thought it was because I was utilizing sharing between multiple apps in a group but realized it fails to log me in at all on device or simulator with the same error mentioned above.  I have a similar version working from a few months ago though.

**Comment by riverbaymark** [comment]
Ok so I found the issue.  There is an odd glitch when using a simulator for a device in Xcode that already has an app using Firebase Auth and keychain.  I tried using a different simulator that was fresh and all worked fine.

**Comment by SergioB-dev** [comment]
`Signings & Capabilities > + Capability > Keychain Sharing`

Once enabled be sure to hit `+` to add your current app to the keychain.

**Comment by LuisUcla** [comment]
Indeed, it is a problem with the simulator in xcode, I had a mac and I changed it to iphone 14 and the error went away.

**Comment by gavinerasmus** [comment]
Mac and iOS have different entitlements - I can add Keychain sharing to the iOS xcode project but not the macOS xcode project. Literally click the + and double clicking Keychain Sharing and nothing is added...

**Comment by harmankang** [comment]
For anybody dealing with this issue in a keyboard app extension, double check that `Allow Full Access` is enabled for your keyboard on your device.
