### ISSUE TITLE
FireBase Phone Auth Not working on real device crashed when pop up 

### ISSUE THREAD

**Issue by Zeeshan90** [firebase/FirebaseUI-iOS#821]
reason: 'Could not instantiate class named _UITextLayoutView because no class named _UITextLayoutView was found; the class needs to be defined in source code or linked in from a library (ensure the class is part of the correct target)'

**Comment by morganchen12** [comment]
This is an Apple bug that you can fix by updating your version of Xcode to 11.2.1. See this StackOverflow post: https://stackoverflow.com/questions/58657087/after-upgrading-to-xcode-11-2-from-xcode-11-1-app-crashes-due-to-uitextlayoutv
