### ISSUE TITLE
FirebaseUI Apple Sign-in method iOS 12 compatibility

### ISSUE THREAD

**Issue by babkouew** [firebase/FirebaseUI-iOS#825]
The current sign-in with Apple method works only on iOS13 and we had many users reporting they couldn't find the App on the App Store. According to Apple, as of October 14, 2019, only 50% of users use iOS13. Is there any way to make the sign-in with Apple a viable option by making sure it is compatible with at least iOS12?

**Comment by morganchen12** [comment]
Looks like you've already closed this, but unfortunately Apple doesn't provide the Sign in with Apple capability on iOS 12 or lower.

**Comment by babkouew** [comment]
@morganchen12 Yes I figured out as much so I closed it but thanks for following up.
