### ISSUE TITLE
FirebaseAuthUI not creating new user from Facebook authentication - Swift

### ISSUE THREAD

**Issue by heydana** [firebase/FirebaseUI-iOS#83]
After setting up FirebaseAuthUI for Facebook - adding the redirect URIs to my Facebook app login details, facebook app ID to the Info.plist - I'm able to get my simple test app to go through all the steps to authenticate Facebook, but upon completion no new user is created in the authentication database. The app will show up under permissions in my Facebook account, but no new user is created in Firebase. 

Google authentication and email/password authentication work as expected and correctly create a new user.

This is the function I use for my simple sign-in button:

    @IBAction func signIn() {

        let authUI = FIRAuthUI.authUI()!
        let googleAuthUI = FIRGoogleAuthUI.init(clientID:FIRApp.defaultApp()!.options.clientID)
        let facebookAuthUI = FIRFacebookAuthUI.init(appID: NSBundle.mainBundle().infoDictionary?["FacebookAppID"] as! String)  
        authUI.signInProviders = [googleAuthUI!, facebookAuthUI!]       
        
        let authViewController = FIRAuthUI.authUI()!.authViewController()        
        self.presentViewController(authViewController, animated: true, completion: nil)

    }

(cross posted on: http://stackoverflow.com/questions/38317938/firebaseauthui-not-adding-new-facebook-user)

**Comment by mcdonamp** [comment]
Are you getting any errors in the process? Can you check `FIRAuth.auth()?.currentUser` and see if there's a signed in user?

**Comment by heydana** [comment]
So I added FIRAuth.auth()?.addAuthStateDidChangeListener and I got it to fire with Google and  email login, but not Facebook...

**Comment by chaogoog** [comment]
Just a quick check, have you enabled Facebook on Firebase console?

**Comment by heydana** [comment]
Yup it's enabled. 
<img width="439" alt="screen shot 2016-07-12 at 4 04 54 pm" src="https://cloud.githubusercontent.com/assets/6992884/16786531/67fe8ef4-484a-11e6-9fba-0afa0f9c609a.png">

**Comment by chaogoog** [comment]
Thanks! Can you please do the following to help debug the issue?

- Make a temporary variable of the `handleOpenURL` result and place a breakpoint there.

```
func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject) -> Bool {
    let handled = FIRAuthUI.authUI()!.handleOpenURL(url, sourceApplication: sourceApplication!)
    return handled
}
```

- Start and finish a Facebook sign-in flow and you should hit the breakpoint.

If `handled` is `false`, most likely there's something wrong with the Facebook setup. Check your plist file against the "Configure Xcode Project" section of [this doc](https://developers.facebook.com/docs/ios/getting-started), make sure there's a `CFBundleURLSchemes` value for Facebook in particular.

**Comment by heydana** [comment]
Put in the breakpoint and handled is true.

**Comment by chaogoog** [comment]
Hmm, are you getting any callback in `func authUI(authUI: FIRAuthUI!, didSignInWithUser user: FIRUser?, error: NSError?)`? Is the auth view controller dismissed after you sign in with Facebook?

**Comment by heydana** [comment]
Yes, the view controller is dismissed after signing in with Facebook and the app is shown as authorized in my facebook profile settings (for "Logged in using Facebook"). However, I'm not getting any callbacks for any of the sign-ins using the didSignInWithUser method. I do get a call with the FIRAuth.auth().addAuthStateDidChangeListener for Google and email/password (but not facebook).

**Comment by chaogoog** [comment]
Did you set the `delegate` of `FIRAuthUI` to the object that implements `didSignInUser`?

**Comment by heydana** [comment]
Oops, thanks. Ok with delegate assigned, I'm getting a callback for all three providers, but still no Facebook account creation.

**Comment by chaogoog** [comment]
Do you happen to use Facebook and Google accounts with the same email address? In this case, the two providers are linked to the same Firebase account.

**Comment by heydana** [comment]
Yes, however even without my Google account saved (I've tried deleting the account to have zero accounts at all in the database), the Facebook authentication still doesn't create a new user.

**Comment by heydana** [comment]
Also forgot to mention with didSignInUser, the user is nil when trying facebook login, but is assigned for Google/email.

**Comment by heydana** [comment]
Aha! Got the full error details - still not sure what the issue is as I've provided my app secret to Firebase?
FIRAuthErrorUserInfoDeserializedResponse - 
"Unsuccessful debug_token response from Facebook: {\"error\":{\"message\":\"(#100) You must provide an app access token or a user access token that is an owner or developer of the app\",\"type\":\"OAuthException\",\"code\":100,\"fbtrace_id\":\"ByZKant9ike\"}}"

-

**Comment by heydana** [comment]
Oh, I found the issue!

In my advanced settings within the facebook app, I had turned on "Is App Secret embedded in the client?"

Turning that off made it all work!
<img width="378" alt="screen shot 2016-07-13 at 5 19 50 pm" src="https://cloud.githubusercontent.com/assets/6992884/16824120/0edda83a-491e-11e6-9389-ce77b44056f4.png">

**Comment by ryanzulham** [comment]
@heydana Sory i cannot find is app secret embedded in the client?
where i can find?

**Comment by kalehv** [comment]
@ryanzulham facebook app portal -> Settings -> Advanced (top most section right side slider)
![screen shot 2017-02-08 at 10 46 33 pm](https://cloud.githubusercontent.com/assets/588703/22769767/8a299a3a-ee50-11e6-915c-6a3773395106.png)

**Comment by ObamaBinLaden1** [comment]
![image](https://user-images.githubusercontent.com/27396767/28475169-dc7c8656-6e68-11e7-832d-752a11afb1ce.png)

@kalehv this option is not there anymore. Any update please?

**Comment by kalehv** [comment]
@ObamaBinLaden1 I still see it, not sure what's different

**Comment by iballan** [comment]
@heydana I disabled "Is App Secret embedded in the client". Still getting the same error.

**Comment by dkdilipkumar** [comment]
Still not creating new user ?

**Comment by lelinhalins** [comment]
https://github.com/firebase/FirebaseUI-Android/issues/660

**Comment by songnhi1029** [comment]
you need check this:
<img width="1106" alt="screen shot 2018-01-10 at 11 09 31 am" src="https://user-images.githubusercontent.com/29114813/34755470-c4f15c30-f5f6-11e7-9de4-6ccca3308cac.png">

**Comment by Abhishek-NickelFox** [comment]
Hi, i also not getting that setting as mentioned above, also i have added appid and appsecret in firebase?

![screen shot 2018-05-18 at 6 14 31 pm](https://user-images.githubusercontent.com/27338504/40235362-a830a002-5ac7-11e8-98bb-16ec818b904e.png)

**Comment by tvjensen** [comment]
The solution for me was rechecking the app secret. Previously, I had copied and pasted the secured text (the dots) into Firebase, but what I was actually pasting into Firebase was the dot symbols and not actually the app secret. In order to correct this, I had to hit "Show" next to the app secret in the Facebook app portal and then copy the app secret in its unhidden form.

**Comment by prmichaelsen** [comment]
In my case, it was a mismatch of the secret I had pasted into Firebase and the actual secret. I am bumping this with that context. If you are encountering this, triple-check your app id and secrets.
