### ISSUE TITLE
Facebook Login stuck on loading iOS 13

### ISSUE THREAD

**Issue by razamerchantwork** [firebase/FirebaseUI-iOS#832]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If your issue concerns the CocoaPods error, "...transitive dependencies that include static binaries", please take a look at any of the following issues and see if your problem is solved: #48, #47, #46, #34, #23.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

Yes. I am using Firebase Auth UI, having Sign in with FB, Google, Apple.

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Objective C or Swift: SWIFT
  * iOS version: 13.3
  * FirebaseUI version: 8.4.0
  * CocoaPods Version: 1.8.3
  
### Step 3: Describe the problem:

Issue I'm facing is when I sign in with facebook. I press Sign In with Facebook, it shows me Facebook Auth Page, then I click Continue and Facebook Auth page dismiss. After that Firebase Auth UI is stuck showing a loader. 
And this callback is never called, 
func authUI(_ authUI: FUIAuth, didSignInWith authDataResult: AuthDataResult?, error: Error?)

#### Steps to reproduce:

  1. Tap Sign In with Facebook on AuthUI
  2. Tap "Continue" on Facebook Auth Page
  3. Facebook Auth Page dimisses, and a loader is shown.
  
#### Observed Results:
  * What happened?  This could be a description, log output, etc.
Firebase Auth UI is stuck on loading.
![Image from iOS (2)](https://user-images.githubusercontent.com/46725171/73026196-c9141b80-3e52-11ea-8029-77bd8588351b.png)
  
#### Expected Results:

  * What did you expect to happen?
Below callback must be called.
func authUI(_ authUI: FUIAuth, didSignInWith authDataResult: AuthDataResult?, error: Error?)

  
#### Relevant Code:

    /// Private method to show the Firebase auth sign up view
    private func showAuthPickerVC() {
        let auth = FUIAuth.defaultAuthUI()
        auth?.delegate = self
        var providers: [FUIAuthProvider] = []
        if #available(iOS 13.0, *) {
            providers = [FUIOAuth.appleAuthProvider(), FUIGoogleAuth(), FUIFacebookAuth()]
        } else {
           providers = [FUIGoogleAuth(), FUIFacebookAuth()]
        }
        auth?.providers = providers
        auth?.tosurl = Firebase.TermsOfService
        auth?.privacyPolicyURL = Firebase.TermsOfService
        
        if UIApplication.topViewController() is CPAuthPickerViewController == false {
            if let authVC = auth?.authViewController() {
                print(authVC.viewControllers)
                if let vc = authVC.viewControllers.first as? CPAuthPickerViewController {
                    vc.delegate = self
                }
                authVC.modalPresentationStyle = .fullScreen
                present(authVC, animated: true, completion: nil)
            }
        }
    }

**Comment by saalisumer** [comment]
I faced this issue while development. If you are trying FB login for the first time during dev, add your facebook account in the fb tester list for the app.
If you have logged in through FB ever before for this app, go to the Facebook apps in you facebook profile, and delete the app there and try login again.

**Comment by razamerchantwork** [comment]
@saalisumer  I have tried this as well, deleting app from account and re-login again from same account. Have tried new account as well.

**Comment by morganchen12** [comment]
To further troubleshoot this, are you experiencing the same error when logging in with just the Facebook SDK (no Firebase), or is it an error that only occurs with FirebaseUI?

**Comment by RaimundasSakalauskas** [comment]
There's similar issue that has workaround: https://github.com/firebase/FirebaseUI-iOS/issues/675

The bare minimum needed is to create and retain instance of `FUIEmailAuth` somewhere in your code. Even without including it in the provider list solves this issue.

**Comment by Ulquiorra222** [comment]
There is no callback because of the lack of
func application( _ app:UIApplication, open url:URL, options: [UIApplication.OpenURLOptionsKey :Any] = [:]) -> Bool{

        ApplicationDelegate.shared.application( app, open: url, sourceApplication: options[UIApplication.OpenURLOptionsKey.sourceApplication] as? String, annotation: options[UIApplication.OpenURLOptionsKey.annotation])

    }
Just add it to AppDelegate
