### ISSUE TITLE
Login Screen layout changed after updating to latest Xcode

### ISSUE THREAD

**Issue by Hamna21** [firebase/FirebaseUI-iOS#833]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If your issue concerns the CocoaPods error, "...transitive dependencies that include static binaries", please take a look at any of the following issues and see if your problem is solved: #48, #47, #46, #34, #23.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Objective C or Swift: 5.1
  * iOS version: 13.3
  * FirebaseUI version: 8.4.1
  * CocoaPods Version: 1.5.3
  
### Step 3: Describe the problem:
After I updated to Xcode 11, my login screens have a different layout now.
I want Login Screens to be presented as full screen. Currently they are displayed like this: 
![image](https://user-images.githubusercontent.com/20511422/73053345-4ec2b600-3ea9-11ea-842c-4dc69819423c.png)

What properties need to be set for this?

**Comment by morganchen12** [comment]
This is a new default behavior with iOS 13. Set the presentation style to `.fullScreen` to restore the old presentation style. See [here](https://stackoverflow.com/questions/56435510/presenting-modal-in-ios-13-fullscreen) for more details.
