### ISSUE TITLE
How do you clear cache for sd_setImage

### ISSUE THREAD

**Issue by justdan0227** [firebase/FirebaseUI-iOS#835]
How do we clear the cache.  I used sd_setImage and got the image from the server.  However if I delete the image on the server, the image in my app still remains?

**Comment by morganchen12** [comment]
See the [Remove methods on SDImageCache](https://github.com/SDWebImage/SDWebImage/blob/f5980e5fed2660c2b4bb1490174c724596b30d89/SDWebImage/Core/SDImageCache.h#L293).

**Comment by morganchen12** [comment]
Closing this since it seems to be resolved, let me know if you have any other questions.
