### ISSUE TITLE
Hello, I have submitted the application to apple and when they try to test the app the app crashed on the country textfield and when i test the app there is no crashing. What seems to be the issue ??

### ISSUE THREAD

**Issue by Zeeshan90** [firebase/FirebaseUI-iOS#836]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If your issue concerns the CocoaPods error, "...transitive dependencies that include static binaries", please take a look at any of the following issues and see if your problem is solved: #48, #47, #46, #34, #23.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Objective C or Swift: ____
  * iOS version: _____
  * Firebase SDK version: _____
  * FirebaseUI version: ____
  * CocoaPods Version: ____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by morganchen12** [comment]
Hey, looks like this issue doesn't really fit the format for the issue template. Consider asking the same question on a website like StackOverflow, or emailing Apple directly and asking them for more details on the environment that caused the crash. At the very least you should ask them for the crash's stack trace.

Chances are they're using a different language/localization combination that you're not running into.

**Comment by Ramnathtamiselvam** [comment]
@Zeeshan90  
Kindly update latest firebaseUI SDK to resolve this issue.     

pod 'FirebaseUI/Phone', '~> 8.1.0'

It's worked for me. Thanks
