### ISSUE TITLE
Use of undeclared type 'AuthDataResult'

### ISSUE THREAD

**Issue by joerivelli** [firebase/FirebaseUI-iOS#840]
* Swift:
  * iOS version: 13.2
  * FirebaseUI version: 8.4.2
  * CocoaPods Version: 1.9.0
  
I am getting this error when trying to use the delegate function:
func authUI(_ authUI: FUIAuth, didSignInWith authDataResult: AuthDataResult?, url: URL?, error: Error?)

**Comment by morganchen12** [comment]
You need to import the FirebaseAuth module.

**Comment by joerivelli** [comment]
When I try import FirebaseAuth I only get…. Pods_FirebaseAuth.

I wonder if it’s because I called my project FirebaseAuth and that is conflicting.

**Comment by morganchen12** [comment]
Yeah, I'm not sure what will happen if you name your project module the same thing as one of your dependency's modules but it can't possibly be good.

Also, are you setting `use_frameworks!` in your Podfile?

**Comment by joerivelli** [comment]
Yes I am.  I made a new project and it works fine, didn’t realize my project module was the same and when I did I figured that had to be the issue.

Thanks for your help.

Joe
