### ISSUE TITLE
FirebaseUI - Sign In with Apple Account Linking

### ISSUE THREAD

**Issue by johnswifttt** [firebase/FirebaseUI-iOS#848]
### Question

Does this repo (FirebaseUI) handle [implementing account linking with Sign In with Apple](https://firebase.google.com/docs/auth/ios/apple#reauthentication_and_account_linking). The documentation in Firebase states to handle `FIRAuthErrorUserInfoUpdatedCredentialKey` if an account already exists, but I don't see how that is handled in this repo. 

The reason I ask is, because since this repo is open-source, I want to learn how to do this. Could you please link to the part in this repo that handles this error `FIRAuthErrorUserInfoUpdatedCredentialKey` for Apple Sign In? It's a very small request and hopefully someone could help here. I tried looking but could not find it.

Sorry if this is not the correct place to post, but I noticed there was a lot of others with similar issue. Unfortunately, Firebase documentation does not explain it in detail.

**Comment by morganchen12** [comment]
Checking for the updated credential happens [here](https://github.com/firebase/FirebaseUI-iOS/blob/master/Auth/FirebaseAuthUI/FUIAuth.m#L239-L250). I'm not sure where the updated credential is used to complete the account linking. @renkelvin can you clarify?

**Comment by renkelvin** [comment]
It's used for autoupgrade. (1. sign in anonymously 2. upgrade with an Apple credential while it's already registered 3. sign in directly with the Apple credential)

**Comment by morganchen12** [comment]
Closing this since it seems to not be an issue anymore, let me know if that's not the case and I'll re-open.
