### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by yesnoyes** [firebase/FirebaseUI-iOS#860]
Dear Google Devs,
GoogleSignInSDK is using AppAuth, which is using deprecated UIWebView, therefore AppStore is keep giving warning when App is submitted to AppStore. Please update, when this issue would be resolved?

Warning message:
=====================================================================
Dear Developer,

We identified one or more issues with a recent delivery for your app, "XXXXX. Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will no longer accept submissions of new apps that use UIWebView as of April 30, 2020 and app updates that use UIWebView as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

After you’ve corrected the issues, you can upload a new binary to App Store Connect.

Best regards,

The App Store Team

**Comment by morganchen12** [comment]
What version of GoogleSignIn are you using?

**Comment by yesnoyes** [comment]
Hi, I am using latest version "Google Sign-In SDK 5.0.2"

**Comment by morganchen12** [comment]
UIWebView should not be present in the latest version of GoogleSignIn. Can you share your full `Podfile.lock`?

Also, you can check if your app bundle contains UIWebView symbols by running `nm "your_app_name" | grep UIWebView`.

**Comment by yesnoyes** [comment]
UIWebiew is mentioned inside the AppAuth in README.md file as a comment but Appstore is keep giving warning.
Here is the usage -
for the auth request. `UIWebView` and `WKWebView` are explicitly *not*

And here is my full Podfile.lock -

PODS:
  - Alamofire (4.9.1)
  - AppAuth (1.3.0):
    - AppAuth/Core (= 1.3.0)
    - AppAuth/ExternalUserAgent (= 1.3.0)
  - AppAuth/Core (1.3.0)
  - AppAuth/ExternalUserAgent (1.3.0)
  - ASN1Decoder (1.3.3)
  - CocoaLumberjack/Core (3.6.1)
  - CocoaLumberjack/Swift (3.6.1):
    - CocoaLumberjack/Core
  - Crashlytics (3.14.0):
    - Fabric (~> 1.10.2)
  - Fabric (1.10.2)
  - FBSDKCoreKit (6.5.2):
    - FBSDKCoreKit/Basics (= 6.5.2)
    - FBSDKCoreKit/Core (= 6.5.2)
  - FBSDKCoreKit/Basics (6.5.2)
  - FBSDKCoreKit/Core (6.5.2):
    - FBSDKCoreKit/Basics
  - FBSDKLoginKit (6.5.2):
    - FBSDKLoginKit/Login (= 6.5.2)
  - FBSDKLoginKit/Login (6.5.2):
    - FBSDKCoreKit (~> 6.5.2)
  - Firebase/Analytics (6.23.0):
    - Firebase/Core
  - Firebase/Core (6.23.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.4.2)
  - Firebase/CoreOnly (6.23.0):
    - FirebaseCore (= 6.6.7)
  - FirebaseAnalytics (6.4.2):
    - FirebaseCore (~> 6.6)
    - FirebaseInstallations (~> 1.2)
    - GoogleAppMeasurement (= 6.4.2)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (= 0.3.9011)
  - FirebaseCore (6.6.7):
    - FirebaseCoreDiagnostics (~> 1.2)
    - FirebaseCoreDiagnosticsInterop (~> 1.2)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
  - FirebaseCoreDiagnostics (1.2.4):
    - FirebaseCoreDiagnosticsInterop (~> 1.2)
    - GoogleDataTransportCCTSupport (~> 3.0)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
    - nanopb (~> 0.3.901)
  - FirebaseCoreDiagnosticsInterop (1.2.0)
  - FirebaseInstallations (1.2.0):
    - FirebaseCore (~> 6.6)
    - GoogleUtilities/Environment (~> 6.6)
    - GoogleUtilities/UserDefaults (~> 6.6)
    - PromisesObjC (~> 1.2)
  - FloatingPanel (1.7.1)
  - GoogleAppMeasurement (6.4.2):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (= 0.3.9011)
  - GoogleDataTransport (6.0.0)
  - GoogleDataTransportCCTSupport (3.0.0):
    - GoogleDataTransport (~> 6.0)
    - nanopb (~> 0.3.901)
  - GoogleSignIn (5.0.2):
    - AppAuth (~> 1.2)
    - GTMAppAuth (~> 1.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - GoogleUtilities/AppDelegateSwizzler (6.6.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.6.0):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (6.6.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.6.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (6.6.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.6.0)"
  - GoogleUtilities/Reachability (6.6.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.6.0):
    - GoogleUtilities/Logger
  - GTMAppAuth (1.0.0):
    - AppAuth/Core (~> 1.0)
    - GTMSessionFetcher (~> 1.1)
  - GTMSessionFetcher (1.4.0):
    - GTMSessionFetcher/Full (= 1.4.0)
  - GTMSessionFetcher/Core (1.4.0)
  - GTMSessionFetcher/Full (1.4.0):
    - GTMSessionFetcher/Core (= 1.4.0)
  - nanopb (0.3.9011):
    - nanopb/decode (= 0.3.9011)
    - nanopb/encode (= 0.3.9011)
  - nanopb/decode (0.3.9011)
  - nanopb/encode (0.3.9011)
  - NVActivityIndicatorView (4.8.0):
    - NVActivityIndicatorView/Presenter (= 4.8.0)
  - NVActivityIndicatorView/Presenter (4.8.0)
  - PromiseKit (6.13.1):
    - PromiseKit/CorePromise (= 6.13.1)
    - PromiseKit/Foundation (= 6.13.1)
    - PromiseKit/UIKit (= 6.13.1)
  - PromiseKit/CorePromise (6.13.1)
  - PromiseKit/Foundation (6.13.1):
    - PromiseKit/CorePromise
  - PromiseKit/UIKit (6.13.1):
    - PromiseKit/CorePromise
  - PromisesObjC (1.2.8)
  - ReachabilitySwift (4.3.1)
  - SDWebImage (5.7.3):
    - SDWebImage/Core (= 5.7.3)
  - SDWebImage/Core (5.7.3)
  - SSZipArchive (2.2.3)
  - SwiftyJSON (5.0.0)
  - SWXMLHash (5.0.1)
  - TextFieldEffects (1.6.0)
  - zxcvbn-ios (1.0.4)

DEPENDENCIES:
  - Alamofire
  - Alamofire (= 4.9.1)
  - ASN1Decoder
  - CocoaLumberjack/Swift
  - Crashlytics
  - Fabric
  - FBSDKCoreKit
  - FBSDKLoginKit
  - Firebase/Analytics
  - FloatingPanel (= 1.7.1)
  - GoogleSignIn
  - NVActivityIndicatorView
  - PromiseKit
  - ReachabilitySwift (= 4.3.1)
  - SDWebImage
  - SSZipArchive
  - SwiftyJSON
  - SWXMLHash
  - TextFieldEffects
  - zxcvbn-ios

SPEC REPOS:
  https://github.com/CocoaPods/Specs.git:
    - Alamofire
    - AppAuth
    - ASN1Decoder
    - CocoaLumberjack
    - Crashlytics
    - Fabric
    - FBSDKCoreKit
    - FBSDKLoginKit
    - Firebase
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseCoreDiagnosticsInterop
    - FirebaseInstallations
    - FloatingPanel
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleDataTransportCCTSupport
    - GoogleSignIn
    - GoogleUtilities
    - GTMAppAuth
    - GTMSessionFetcher
    - nanopb
    - NVActivityIndicatorView
    - PromiseKit
    - PromisesObjC
    - ReachabilitySwift
    - SDWebImage
    - SSZipArchive
    - SwiftyJSON
    - SWXMLHash
    - TextFieldEffects
    - zxcvbn-ios

SPEC CHECKSUMS:
  Alamofire: 85e8a02c69d6020a0d734f6054870d7ecb75cf18
  AppAuth: 73574f3013a1e65b9601a3ddc8b3158cce68c09d
  ASN1Decoder: c85bbe9d75370dab47503c13c4de213adf3a1442
  CocoaLumberjack: b17ae15142558d08bbacf69775fa10c4abbebcc9
  Crashlytics: 540b7e5f5da5a042647227a5e3ac51d85eed06df
  Fabric: 706c8b8098fff96c33c0db69cbf81f9c551d0d74
  FBSDKCoreKit: ada5c8a05188daefc9addb985c52b8a1b26da519
  FBSDKLoginKit: caa165495afa29a12324cb2307fe6e5b33783142
  Firebase: 585ae467b3edda6a5444e788fda6888f024d8d6f
  FirebaseAnalytics: 558f7a03d19de451093032c806f39d5f9dff096e
  FirebaseCore: a2788a0d5f6c1dff17b8f79b4a73654a8d4bfdbd
  FirebaseCoreDiagnostics: b59c024493a409f8aecba02c99928d0d8431d159
  FirebaseCoreDiagnosticsInterop: 296e2c5f5314500a850ad0b83e9e7c10b011a850
  FirebaseInstallations: 2119fb3e46b0a88bfdbf12562f855ee3252462fa
  FloatingPanel: 2f87246071476cf05d77ba3f50a373ca4b04549e
  GoogleAppMeasurement: 2253e99c1f22638cf234c059144660c338ad76c3
  GoogleDataTransport: 061fe7d9b476710e3cd8ea51e8e07d8b67c2b420
  GoogleDataTransportCCTSupport: 0f39025e8cf51f168711bd3fb773938d7e62ddb5
  GoogleSignIn: 7137d297ddc022a7e0aa4619c86d72c909fa7213
  GoogleUtilities: 39530bc0ad980530298e9c4af8549e991fd033b1
  GTMAppAuth: 4deac854479704f348309e7b66189e604cf5e01e
  GTMSessionFetcher: 6f5c8abbab8a9bce4bb3f057e317728ec6182b10
  nanopb: 18003b5e52dab79db540fe93fe9579f399bd1ccd
  NVActivityIndicatorView: d24b7ebcf80af5dcd994adb650e2b6c93379270f
  PromiseKit: 28fda91c973cc377875d8c0ea4f973013c05b6db
  PromisesObjC: c119f3cd559f50b7ae681fa59dc1acd19173b7e6
  ReachabilitySwift: 4032e2f59586e11e3b0ebe15b167abdd587a388b
  SDWebImage: 97351f6582ceca541ea294ba66a1fcb342a331c2
  SSZipArchive: 62d4947b08730e4cda640473b0066d209ff033c9
  SwiftyJSON: 36413e04c44ee145039d332b4f4e2d3e8d6c4db7
  SWXMLHash: 9cc0c2e4807926c74377724aa8722ee5707a0485
  TextFieldEffects: 529b8aff706fb40f82c41c780c0777941a893796
  zxcvbn-ios: fef98b7c80f1512ff0eec47ac1fa399fc00f7e3c

PODFILE CHECKSUM: e4ca3602eeb258dd00a2cdf32fb141719dcee2b3

COCOAPODS: 1.9.1

**Comment by morganchen12** [comment]
Looks like this is a false positive that the app store is flagging because a code comment in AppAuth mentions UIWebView. See https://github.com/openid/AppAuth-iOS/issues/449

You can probably fix this by manually deleting that comment and resubmitting.
