### ISSUE TITLE
FR: Support Mac Catalyst

### ISSUE THREAD

**Issue by platput** [firebase/FirebaseUI-iOS#863]
Hello,
I am trying to build my app for mac os as iPad apps can be run in mac now. The problem is there are many deprecation warnings related to FirebaseUI related to Mac Catalyst 13.0

Also, the phone verification doesn't work. As soon as I enter the phone number and press verify, it shows the browser and then returns to the app immediately without doing anything else. So I am not able to verify the phone number.

I tried updating the pods using pod update without any luck. Is there anything I am missing?

**Comment by morganchen12** [comment]
FirebaseUI does not currently support Catalyst apps.

**Comment by joeljfischer** [comment]
+1 on this request. With the huge focus on Catalyst and iOS apps running on Mac in iOS 14 / MacOS 11.0, this would be great to have.

**Comment by yuchenshi** [comment]
I've filed a feature request internally as b/160626909.

**Comment by joeljfischer** [comment]
Note, after signing the Firebase UI pod projects myself, I was able to get it to run (albeit with a number of deprecation warnings) on iOS 13 / macOS 10.15.

**Comment by CroperMR** [comment]
> Note, after signing the Firebase UI pod projects myself, I was able to get it to run (albeit with a number of deprecation warnings) on iOS 13 / macOS 10.15.

Please tell, how can I sign the Firebase UI pod projects myself? Where I need to fill my account info? Thanks!
