### ISSUE TITLE
“Use of '@import' when modules are disabled” Error for FirebaseUiAuth

### ISSUE THREAD

**Issue by audkar** [firebase/FirebaseUI-iOS#875]
### Step 1: Are you in the right place?

80% chance :thinking: 

### Step 2: Describe your environment

  * Objective C or Swift: Swift5
  * iOS version: 13.5
  * Firebase SDK version: 6.6
  * FirebaseUI version: 8.4.0
  * CocoaPods Version: 1.9.1
  
### Step 3: Describe the problem:

Using FirebasUI dependencies in kotlin-native with cocoapods support throws error during compilation. 
Not sure if valid fix, but if I replace module imports in FirebaseUI code then our project compiles successfully.
- `@import UIKit;` => `#import <UIKit/UIKit.h>`
- `@import Foundation` => `#import <Foundation/Foundation.h>`

**edit:** 

- setting `Enable modules (C and Object-c)` is `true` for project. 
- cacaopods Podfile contains `use_frameworks! :linkage => :static`

#### Steps to reproduce:

  1. Add `'FirebaseUI/Google` dependency to to kotlin-native project
  2. Execute `gradle podspec` cmd
  3. Execute `pod install`
  4. Build iOS project
  5. Observe error
  
#### Observed Results:

```
Use of '@import' when modules are disabled
``` 
error is thrown in 3 places: 
- [FirebaseAuthUI.h](https://github.com/firebase/FirebaseUI-iOS/blob/master/Auth/FirebaseAuthUI/FirebaseAuthUI.h#L17)
- [FUIAuthErrors.h](https://github.com/firebase/FirebaseUI-iOS/blob/master/Auth/FirebaseAuthUI/FUIAuthErrors.h#L17)
- [FirebaseGoogleAuthUI.h](https://github.com/firebase/FirebaseUI-iOS/blob/master/GoogleAuth/FirebaseGoogleAuthUI/FirebaseGoogleAuthUI.h#L17)
  
#### Expected Results:

Successful compilation

**Comment by schramm** [comment]
Hi. I am having the same issue building FirebaseUI for iOS, mixing c++ and ObjectiveC. No idea how to fix this. Any help?

**Comment by audkar** [comment]
@morganchen12 would you accept PR which replaces these imports?

**Comment by morganchen12** [comment]
Yes, PRs are very welcome.

**Comment by jinyuyoulong** [comment]
https://answers.unity.com/questions/1679641/use-of.html

need c++ flag setup

**Comment by top-master** [comment]
Using `-fmodules` and `-fcxx-modules` flags fixes this as long as the file extension is `.m`
(but not supported by `.mm` or rather `Objective-C++` yet).
