### ISSUE TITLE
Update Auth README to add Swift snippets

### ISSUE THREAD

**Issue by salqadri** [firebase/FirebaseUI-iOS#88]
1. Swift
  2. iOS Version 9:
  3. CocoaPods Version (FirebaseUI only officially supports CocoaPods <= 0.39, please make sure this repro's using 0.39 or below): 0.39.0 (can we please update the FirebaseUI official support to be with CocoaPods 1.0.0?)

### Explanation of your issue
Can we please get SWIFT instructions in your README so that we can more easily copy-paste the code snippets?
https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseUI/Auth/README.md

### Steps to reproduce
N/A

**Comment by morganchen12** [comment]
Fixed by #98.
