### ISSUE TITLE
SIWA on iPadOS : identityToken can be null

### ISSUE THREAD

**Issue by ttermeer-reboundcg** [firebase/FirebaseUI-iOS#880]
### Step 1: Are you in the right place?

The fault could be from FirebaseAuth

### Step 2: Describe your environment

  * Objective C or Swift: Objective-C
  * iOS version: iPadOS 13.5.1
  * Firebase SDK version: 6.14
  * FirebaseUI version: 8.4.2
  * CocoaPods Version: ____
  
### Step 3: Describe the problem:

When doing an Apple Sign-In from an iPad the identityToken returned by Apple can sometime be null without invoking `didCompleteWithError`.
This cause an exception to be raised by FirebaseAuth as the idToken is null.

I have not been able to find yet what cause the identityToken to be null in the first place but I believe that the raised exception from FirebaseAuth should not crash the application and instead provide an error message in FirebaseUI.

**Comment by ttermeer-reboundcg** [comment]
After further investigation, I believe the issue is from this line in FUIOAuth.m
`NSString *idToken = [NSString stringWithUTF8String:[appleIDCredential.identityToken bytes]];`

My knowledge on Objective-C is limited but I read that if the data is not NUL terminated, it will not be able to convert it with this method.

**Comment by yuchenshi** [comment]
I've filed b/160628284 internally for further investigation.

**Comment by morganchen12** [comment]
Fixed in #881.
