### ISSUE TITLE
FirebaseUI Facebook Auth Dependency Update

### ISSUE THREAD

**Issue by wimbledon** [firebase/FirebaseUI-iOS#885]
Please update [FirebaseUI.podspec](https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseUI.podspec) `FirebaseUI/Facebook` dependency from `'FBSDKLoginKit', '~> 5.0'` to `'FBSDKLoginKit', '~> 7.0'`.

`FBSDKLoginKit ~> 5.0` is causing  crash issues like https://stackoverflow.com/questions/62965382 and other SDKs depend on the latest version of [Facebook iOS SDK](https://github.com/facebook/facebook-ios-sdk/releases).

**Comment by wimbledon** [comment]
@morganchen12, any update on this issue?

**Comment by morganchen12** [comment]
I can update this today, but it will constitute a breaking change.

**Comment by morganchen12** [comment]
This is fixed in FirebaseUI 9.

**Comment by wimbledon** [comment]
Thank you, @morganchen12.
