### ISSUE TITLE
Change FUIDelayInSecondsBeforeShowingResendConfirmationCode from 15 seconds

### ISSUE THREAD

**Issue by barGenda** [firebase/FirebaseUI-iOS#895]
We are using FirebaseUI on our app for phone authentication and we want to change the value of 
FUIDelayInSecondsBeforeShowingResendConfirmationCode from 15 second to 45 or 60 seconds
It is possible to change this value, and if so, how can we change it?

**Comment by barGenda** [comment]
????

**Comment by morganchen12** [comment]
Hey, sorry for the slow response. It is not currently possible to change this value, but if you'd like you can send over a PR that enables customization of this value.

Note that shorter delays are more likely to be rate-limited.
