### ISSUE TITLE
Any plan for new release which contains the StorageUI fix code (after Mar 11th) ?

### ISSUE THREAD

**Issue by dreampiggy** [firebase/FirebaseUI-iOS#896]
### Step 1: Are you in the right place?

Yes. FirebaseUI current latest version https://github.com/firebase/FirebaseUI-iOS/releases/tag/v8.4.2, does not contains the fix code for StorageUI and PR #841 

### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: Any, iOS 13
  * Firebase SDK version: 6.31.1
  * FirebaseUI version: 8.4.2
  * CocoaPods Version: 1.9.4
  
#### Steps to reproduce:

  1. Use FirebaseUI-Storage `StorageImageLoader` to load a URL, which created via built-in API `URL(string:)`
  
#### Observed Results:

  * URL load failed.
  
#### Expected Results:

  * URL load success.
  
#### Relevant Code:

```swift
SDImageLoadersManager.shared.loaders = [FirebaseUI.StorageImageLoader.shared]
SDWebImageManager.defaultImageLoader = SDImageLoadersManager.shared
SDWebImageManager.shared.loadImage(with: URL(string: "gs://stickerland-smartfo/xxxxxx")!) { image, error, _, _ in
    print(image)
} 
```

**Comment by dreampiggy** [comment]
Pin again. Any schedule ? @morganchen12

**Comment by morganchen12** [comment]
Hey, sorry for the slow response. I can make a minor release this week or early next week.

**Comment by Dwite** [comment]
@morganchen12 that would be very helpful!

**Comment by morganchen12** [comment]
Released in today's minor update.
