### ISSUE TITLE
Apple App Store Rejects FirebaseUI "Sign in with Apple" Button

### ISSUE THREAD

**Issue by Casey10110** [firebase/FirebaseUI-iOS#904]
Similar to issue #845 (https://github.com/firebase/FirebaseUI-iOS/issues/845), Apple is rejecting my app because the background is white with a white button. Any idea on how to change this or why it is happening?
![Bildschirmfoto 2020-09-26 um 12 20 31 PM](https://user-images.githubusercontent.com/39539364/94348638-c75ab300-fff2-11ea-93d9-9e641034db70.jpeg)

**Comment by Casey10110** [comment]
I solved it, but this should probably be the default behavior. I have modified the file in FirebaseUI that describes the button to:

`
+ (FUIOAuth *)appleAuthProvider {
  UIImage *iconImage = [FUIAuthUtils imageNamed:@"ic_apple"
                            fromBundleNameOrNil:@"FirebaseOAuthUI"];
  UIColor *buttonColor = [UIColor blackColor];
  UIColor *buttonTextColor = [UIColor whiteColor];
  if (UITraitCollection.currentTraitCollection.userInterfaceStyle == UIUserInterfaceStyleLight) {
    iconImage = [iconImage imageWithTintColor:[UIColor whiteColor]];
    buttonColor = [UIColor blackColor];
    buttonTextColor = [UIColor whiteColor];
  }
  FUIOAuth *provider = [[FUIOAuth alloc] initWithAuthUI:[FUIAuth defaultAuthUI]
                                             providerID:@"apple.com"
                                        buttonLabelText:@"Sign in with Apple"
                                              shortName:@"Apple"
                                            buttonColor:buttonColor
                                              iconImage:iconImage
                                                 scopes:@[@"name", @"email"]
                                       customParameters:nil
                                           loginHintKey:nil];
  //provider.buttonAlignment = FUIButtonAlignmentCenter;
  provider.buttonTextColor = buttonTextColor;
  return provider;
}
`

**Comment by samhorlbeck** [comment]
Thanks for raising this issue. The team is looking into it; it may make sense to update the defaults to match what is expected. We're tracking this internally (b/169612501)

**Comment by rocketraman** [comment]
I have the opposite problem -- my app is showing a black apple sign-in button on a black background. It would be nice to have an easy way to configure this.

**Comment by rocketraman** [comment]
I see the current code does this:

```
  if (UITraitCollection.currentTraitCollection.userInterfaceStyle == UIUserInterfaceStyleDark) {
    iconImage = [iconImage imageWithTintColor:[UIColor blackColor]];
    buttonColor = [UIColor whiteColor];
    buttonTextColor = [UIColor blackColor];
  }
```

so if I am understanding this correctly, if I set `UITraitCollection.currentTraitCollection.userInterfaceStyle` to `UIUserInterfaceStyleDark`, then I should get the right button colors. Where do I do that?

**Comment by rocketraman** [comment]
Ok I see that the color is based on whether the system (or the app) is in dark mode or not, and can be overwridden via `Info.plist` in the application e.g.

```
        <key>UIUserInterfaceStyle</key>
        <string>Dark</string>
```

Works!

**Comment by landnbloc** [comment]
> <key>UIUserInterfaceStyle</key>
>         <string>Dark</string>

@rocketraman 
Yes it works! Thanks! Do you happen to know if this will work before iOS13? I'm trying to download iOS12.4 to test but xcode gives me a "There are no valid accounts registered with Xcode that have the ability to access this resource." error at the moment I am trying to resolve.

**Comment by rocketraman** [comment]
@landnbloc According to https://developer.apple.com/documentation/uikit/uiuserinterfacestyle, that value is supposed to be supported in 12+.

Note that XCode 12 shows that resource key as `Appearance` i.e. in Info properties,set `Appearance` = `dark` or `light`.

**Comment by morganchen12** [comment]
This should be fixed in the latest version of FirebaseUI. Please let me know if that's not the case.
