### ISSUE TITLE
Invalid Token” when trying to authenticate phone number using firebase in real device only

### ISSUE THREAD

**Issue by shanth923** [firebase/FirebaseUI-iOS#905]
whole process working fine in simulator(getting otp) but not working in real device

when verifyphonenumber method called
verification ID is getting "nil" when app runs in real device!

saying -> error

Optional(Error Domain=FIRAuthErrorDomain Code=17048 "Invalid token." UserInfo={NSLocalizedDescription=Invalid token., FIRAuthErrorUserInfoNameKey=INVALID_APP_CREDENTIAL}) unable to get verification: Optional("Invalid token.")

**Comment by morganchen12** [comment]
Hey @shanth923, please fill out the issue template. If you can provide a reproducible example, it will help a lot.
