### ISSUE TITLE
FIRAuthUI.authUI authentication workflow doesn't work on iOS 10

### ISSUE THREAD

**Issue by jeryRazakarison** [firebase/FirebaseUI-iOS#91]
1. Swift:
  2. iOS 10:
  4. Firebase 3.3.0, FirebaseUI 0.4.0

### Explanation of your issue
On iOS 10, the flow to authenticate with FIRAuthUI.authUI() is broken. After presenting authUI?.authViewController(), and clicking on Signin With Google, authViewController dismiss immediately, going in the delegate method **authUI(_ authUI: FIRAuthUI, didSignInWith user: FIRUser?, error: NSError?)**, with an error

> (Error Domain=FIRAuthUIErrorDomain Code=1 "(null)" UserInfo={NSUnderlyingError=0x79ff7420 {Error Domain=com.google.GIDSignIn Code=-2 "keychain error" UserInfo={NSLocalizedDescription=keychain error}}, FIRAuthUIErrorUserInfoProviderIDKey=google.com})

(without passing in the app delegate application:openUrl: method)

However, on iOS 9, the same code works.
### Steps to reproduce
  1. Configure a new project with Firebase, and add the pod FirebaseUI
  2. Add a button in the project created viewController with this IBAction:
```
    @IBAction func authenticate() {
		let authUI = FIRAuthUI.authUI()
		authUI?.delegate = self
		 let googleAuthUI = FIRGoogleAuthUI(clientID: "*******")
		authUI?.signInProviders = [googleAuthUI!]
		let authViewController = authUI?.authViewController()
		
		self.present(authViewController!, animated: true, completion: nil)
	}
```

  3. Conform to FIRAuthUIDelegate and add this delegate method
```
func authUI(_ authUI: FIRAuthUI, didSignInWith user: FIRUser?, error: NSError?) {
		if error != nil {
			print(error)
			return
		}
		if (user != nil) {
			
		}
	}
```
  4. Launch the app and test the workflow (on iOS 9 it works, on iOS 10, it breaks)

Sincerely

**Comment by chaogoog** [comment]
Thanks for the report. This appears to be a bug in iOS 10 beta 2 and beta 3. https://openradar.appspot.com/27422249

We will keep track of the issue internally and make sure everything works with the final release of iOS 10.
