### ISSUE TITLE
When the FirebaseUI will update the linked FBSDKLoginKit version to 9.0

### ISSUE THREAD

**Issue by fangyuxi** [firebase/FirebaseUI-iOS#931]
### Step 2: Describe your environment

  * Objective C or Swift: Objective C
  * iOS version: 14.2
  * Firebase SDK version:7.4.0
  * FirebaseUI version: 9.0.0
  
### Step 3: Describe the problem:

Now FirebaseUI Linked to FBSDKLoginKit version is 7.0
But the FBSDKLoginKit SDK 8.2.0 has been released for a long time

Due to the iOS 14 privacy policy, Facebook has made adjustments in their latest SDK (8.2.0). Now that we are using FirebaseUI, we cannot upgrade the Facebook SDK to the latest version.So When the FirebaseUI will update the linked FBSDKLoginKit version to 8.0 ?

- FirebaseUI/Facebook (9.0.0):
    - FBSDKLoginKit (~> 7.0)

**Comment by fangyuxi** [comment]
Any one help me ?

**Comment by morganchen12** [comment]
Hey @fangyuxi, I'll take a look this week.

**Comment by fangyuxi** [comment]
@morganchen12 OK, Thank you, I will continue to wait for this update, because we are advertising on Facebook to promote our App, but due to iOS14, we need to upgrade to the latest Facebook 8.2.0 SDK.

**Comment by fangyuxi** [comment]
Facebook SDK v9.0.0 has released

**Comment by fangyuxi** [comment]
#932

**Comment by fangyuxi** [comment]
Duplicate of #932

**Comment by fangyuxi** [comment]
@morganchen12  When we can upgrade to the new version, I see the new version has been released, but I can't found by "pod search". Thank you.

**Comment by morganchen12** [comment]
The fix has been published to CocoaPods.
