### ISSUE TITLE
Facebook requires developers to upgrade to v9.0

### ISSUE THREAD

**Issue by johnqh** [firebase/FirebaseUI-iOS#932]
* Objective C or Swift: Both
  * iOS version: iOS14
  * Firebase SDK version: 7.3
  * FirebaseUI version: 9.0
  * CocoaPods Version: 1.10.0
  
#### Steps to reproduce:

 Received email from Facebook:

  | Mandatory change to Facebook SDKs  Action required: You need to update the version of the Facebook SDK that you currently utilize for your application, XXXXX. As part of our release of v9.0 SDKs, we are requiring developers to upgrade to our newest version. This upgrade will give developers new security features, enhanced resilience, and increased performance.Your current SDK is deprecated and will no longer be supported by Facebook. We will continue to allow API calls from your SDK for a transition period of two years. Starting January 19, 2023 we will fail all calls from deprecated SDKs. We encourage you to upgrade to v9.0 as soon as possible to avoid disruption to your application and to access all the benefits of our newest SDK. | 
  
#### Observed Results:

 Updated to latest pods. Podfile.lock file shows FBSDKCoreKit and FBSDKLoginKit both have version 7.1.1
  
#### Expected Results:

 FBSDKCoreKit and FBSDKLoginKit should be version 9.0

**Comment by morganchen12** [comment]
This is fixed in the latest version of FirebaseUI.
