### ISSUE TITLE
FirebaseUI no longer installs properly through CocoaPods

### ISSUE THREAD

**Issue by frios** [firebase/FirebaseUI-iOS#938]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-iOS/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If your issue concerns the CocoaPods error, "...transitive dependencies that include static binaries", please take a look at any of the following issues and see if your problem is solved: #48, #47, #46, #34, #23.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 14.4
  * Firebase SDK version: _____
  * FirebaseUI version: 10.0.1
  * CocoaPods Version: 1.10.1
  
#### Steps to reproduce:

  1. run pod install on below podfile:

  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.

Analyzing dependencies
Downloading dependencies
Installing AppAuth (1.4.0)
Installing BoringSSL-GRPC (0.0.7)

[!] Error installing BoringSSL-GRPC
[!] /usr/bin/git clone https://github.com/google/boringssl.git /var/folders/mr/cytqx4857vb9fbt4tf_8c5sm0000gn/T/d20210129-19234-1rphs7q --template=

Cloning into '/var/folders/mr/cytqx4857vb9fbt4tf_8c5sm0000gn/T/d20210129-19234-1rphs7q'...
fatal: the remote end hung up unexpectedly
  
#### Expected Results:

  * What did you expect to happen?
  pods to be installed properly. This failure started when I updated to FirebaseUI 10.0.1
  
#### Relevant Code:

  ```
  # Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'mFood Vendor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mFood Vendor
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseStorage'
  pod 'FirebaseUI'
  pod 'FirebaseFirestore'
  pod 'FirebaseFirestoreSwift'

end
  ```

**Comment by morganchen12** [comment]
Looks like this is a git issue with BoringSSL, likely caused by GitHub downtime. Are you able to clone the BoringSSL repo manually via `git clone https://github.com/google/boringssl.git`?

**Comment by frios** [comment]
I am able to manually clone it. If I do that, how do I integrate it into CocoaPods as Cocoapods is attempting to download it? Excuse my naiveté.

**Comment by morganchen12** [comment]
```
fatal: the remote end hung up unexpectedly
```

This error message indicates the backend you're trying to clone from (in this case GitHub) stopped your clone unexpectedly. There's nothing you can do about this error when it occurs, though you may be able to find a root cause for the error by copying the clone command CocoaPods is running and manually executing it with the verbose flag.

**Comment by yusuftor** [comment]
I got a timeout error, the solution was to do `pod repo update`, give it a try!

**Comment by frios** [comment]
pod repo update did not work for me.

When I do a pod update, FirebaseUI gets updated to 10.0.1 and I get a build error
```
.../Pods/FirebaseUI/Auth/FirebaseAuthUI/FUIAuth.m:341:14: No visible @interface for 'FIRAuth' declares the selector 'useEmulatorWithHost:port:'
```

If I try to force using FirebaseUI 10.0.2, I get CocoaPods Error

```
[!] CocoaPods could not find compatible versions for pod "FirebaseCore":
  In Podfile:
    FirebaseCore

    FirebaseFirestoreSwift was resolved to 0.4.0, which depends on
      FirebaseFirestore (>= 1.6.1, ~> 1.6) was resolved to 1.15.0, which depends on
        FirebaseCore (~> 6.2)

    FirebaseUI (~> 10.0.2) was resolved to 10.0.2, which depends on
      FirebaseUI/Auth (= 10.0.2) was resolved to 10.0.2, which depends on
        Firebase/Auth (>= 7.2.0) was resolved to 7.2.0, which depends on
          Firebase/CoreOnly (= 7.2.0) was resolved to 7.2.0, which depends on
            FirebaseCore (= 7.2.0)

    FirebaseUI (~> 10.0.2) was resolved to 10.0.2, which depends on
      FirebaseUI/Auth (= 10.0.2) was resolved to 10.0.2, which depends on
        Firebase/Auth (>= 7.2.0) was resolved to 7.2.0, which depends on
          FirebaseAuth (~> 7.2.0) was resolved to 7.2.0, which depends on
            FirebaseCore (~> 7.0)
```

**Comment by morganchen12** [comment]
@frios, you have incompatible dependencies. You'll need to remove either FirebaseUI or FirebaseFirestoreSwift, as FirebaseFirestoreSwift has not yet been updated to Firebase 7+.

**Comment by frios** [comment]
Well that is unfortunate as I use both of those in my app. Any idea what the update timeline is for FirebaseFirestoreSwift?

**Comment by morganchen12** [comment]
Looks like it's [already been updated](https://github.com/CocoaPods/Specs/blob/master/Specs/4/3/f/FirebaseFirestoreSwift/7.5.0-beta/FirebaseFirestoreSwift.podspec.json), but was placed in beta when Firebase moved to a unified pod version. You'll need to explicitly specify the version of FirebaseFirestoreSwift, like so:

```ruby
pod 'FirebaseFirestoreSwift', '= 7.5.0-beta'
```

**Comment by frios** [comment]
That did the trick! Thanks so much for the help.
