### ISSUE TITLE
Remove static_framework flag?

### ISSUE THREAD

**Issue by pixelmatrix** [firebase/FirebaseUI-iOS#941]
Hi, I've read that in the past that this library's podspec had to use `spec.static_framework = true` since some Firebase dependencies were provided as static frameworks and a dynamic framework cannot depend on a static framework.

I'd really prefer to use this library as a dynamic framework if possible. It looks like as of last fall the Firebase team migrated to dynamic frameworks, so I'm wondering if this library would consider doing the same. I did a quick check of all the dependencies and they all appear to be dynamic now.

Here is the issue where it was discussed on Firebase's side: https://github.com/firebase/firebase-ios-sdk/issues/2022

**Comment by morganchen12** [comment]
`static_framework` has been removed from all components except Google auth, since GoogleSignIn is still distributed as a static binary. Slated for the next major release.

**Comment by pixelmatrix** [comment]
Ah, thanks. I didn't realize that Auth was still static. If/when Auth is updated are you considering updating this package as well?

**Comment by morganchen12** [comment]
To clarify, the base `FirebaseAuthUI` and all of its auth providers _except_ Google can now be built as dynamic frameworks. If GoogleSignIn adds dynamic library support we'll add it to this repository as well.

**Comment by morganchen12** [comment]
The fix for this has ben released.
