### ISSUE TITLE
All login button Customize

### ISSUE THREAD

**Issue by Rohit737-star** [firebase/FirebaseUI-iOS#943]
Hello sir,

can we create all login button in custom created viewController and can we call firebase method to login after click on custom button click. thanks

**Comment by morganchen12** [comment]
If you want to create a fully custom view controller and custom buttons, that's not too different from just implementing your own login flow entirely. Can you provide an example of what you're trying to do?

**Comment by Rohit737-star** [comment]
sir i need to put image logo in  firebase login screen at top side, i have added log image on top it is showing good in portrait mode  but in landscape orientation- log image and Firebase UI button is collapsing to each other can you give me idea how i can manage top logo image with firebase UI button in landscape mode. thanks

**Comment by morganchen12** [comment]
You should set your image view's content mode to `.scaleAspectFit` and then shrink the view when the phone rotates to prevent it from occluding the login button. You may be able to find more detailed tutorials online.

**Comment by Rohit737-star** [comment]
sir i think you are not getting my issue i am using .scaleAspectFit of imageView property, i have added Firebase button (Login With Email, Google Login, Facebook Login, Twitter login, Apple login, Phone number Login).

here are added 6 button that button added in bottom of screen via firebase default and after that i have taken imageVIew for set image logo on top of screen. so now  if single button size 50 then 6*50 = 300pt. (6 is total number of button)

if i have taken imageVIew for logo set on top of screen suppose imageView size 150 then

total container height = 300 + 150 = 450 or may be some padding space  80pt so total height will be  = 530

if it is in portrait mode then  height will be better and screen will look fine.
but if i will rotate screen then screen height will be less in this conditions all login button is scrolling bottom to top  but logo imageView not scrolling because this image view set on top padding by me not by firebase so that logo image and login button are overlapping.

 can we add all login button in Single UIView container.? please help sir

**Comment by morganchen12** [comment]
You'll need to add your image view to the scroll view containing all of the login buttons in order for it to scroll with the login buttons and avoid covering them. This is not particularly well-supported by FirebaseUI, but if you'd like to contribute this feature PRs are welcome!

**Comment by Rohit737-star** [comment]
sir how we can set all firebase button in my custom scroll view
because Firebase providing default button. how i can add this button in my
ScrollView this is big issue . other wise i can easily manage. please tell
me sir how i can manage image and all button in single viewContainr. thanks
