### ISSUE TITLE
FUIAuthBaseViewController_Internal.h not found

### ISSUE THREAD

**Issue by mamilov** [firebase/FirebaseUI-iOS#944]
After having seen that the swift package manager is now supported on the latest master commit, I wanted to give it a go. Unfortunately, the FUIAuthBaseViewController_Internal.h cannot be found during build (and clean build).

Following screenshot shows the error:
![image](https://user-images.githubusercontent.com/62982104/116366344-7c15b680-a806-11eb-9bc9-384db7ac5c0f.png)

**Comment by morganchen12** [comment]
Thanks for filing, the issue should now be fixed.
