### ISSUE TITLE
Facebook login error!!!

### ISSUE THREAD

**Issue by arno608rw** [firebase/FirebaseUI-iOS#947]
2021-05-10 11:13:49.746408+0700 XXXXXXXXXXXX [27552:167979] *** Terminating app due to uncaught exception 'InvalidOperationException', reason: 'App ID not found. Add a string value with your app ID for the key FacebookAppID to the Info.plist or call [FBSDKSettings setAppID:].'

![Screen Shot 2564-05-10 at 11 14 40](https://user-images.githubusercontent.com/3774145/117605152-47e4b300-b181-11eb-870b-46c14bbaecee.png)

**Comment by morganchen12** [comment]
You'll need to add your Facebook app ID to the app's Info.plist. Make sure this plist file is included in your app bundle.

This isn't an issue with the FirebaseUI SDK; you may be able to get more help on the Facebook SDK repository.

**Comment by shabbir21** [comment]
We are facing the same issue in our environment. It seems to be a bug in v9.3.0 of facebook-ios-sdk.
Link to issue: https://github.com/facebook/facebook-ios-sdk/issues/1745

@arno608rw @morganchen12

**Comment by AbishekHari** [comment]
I ran into the same issue. How did you all resolve this issue?
