### ISSUE TITLE
Package Resolution Failed 

### ISSUE THREAD

**Issue by SchwartzLizer** [firebase/FirebaseUI-iOS#948]
* Objective C or Swift: Swift
  * iOS version: 14.5
  * Firebase SDK version: 8.0.0
  * FirebaseUI version: Branch Master
  * CocoaPods Version: - (SPM)
  
#### Observed Results:

  * Package Resolution Failed
  
#### Expected Results:

  * Support Firebase SDK 8.0.0
  
#### Relevant Code:

![CleanShot 2021-05-12 at 15 47 45](https://user-images.githubusercontent.com/54163797/117946710-bf5d4280-b339-11eb-8a64-51f344db1930.png)

**Comment by weixifan** [comment]
Thanks for reporting this; I've filed an internal issue b/189040893 to track this.

**Comment by morganchen12** [comment]
This should be fixed on master now.
