### ISSUE TITLE
Add Google Auth to SPM

### ISSUE THREAD

**Issue by mamilov** [firebase/FirebaseUI-iOS#951]
* Objective C or Swift: Swift
  * iOS version: iOS 14.1
  * Firebase SDK version: 7.11.1
  * FirebaseUI version: master branch
  * CocoaPods Version: Swift Package Manager
  
### Step 3: Describe the problem:

When using with FirebaseUI with SPM, FUIGoogleAuth cannot be found in the project. Since I can find it in the spm packages, I assume that something is not exported right.

<img width="641" alt="Bildschirmfoto 2021-05-17 um 10 10 23" src="https://user-images.githubusercontent.com/62982104/118453993-22fbbd00-b6f8-11eb-9b82-ef69320640fd.png">

<img width="758" alt="Bildschirmfoto 2021-05-17 um 10 02 21" src="https://user-images.githubusercontent.com/62982104/118454004-2727da80-b6f8-11eb-9ab9-a2f987dfe72c.png">

#### Steps to reproduce:

  1. Add FirebaseUI with SPM
  2. Try to import and use FUIGoogleAuth
  
#### Observed Results:

  * Cannot find *FUIGoogleAuth' in scope
  
#### Expected Results:

  * Can find and use FUIGoogleAuth

**Comment by mamilov** [comment]
Can it be due to 'FirebaseGoogleAuthUI' missing in Package.swift?

<img width="444" alt="Bildschirmfoto 2021-05-17 um 14 53 19" src="https://user-images.githubusercontent.com/62982104/118492150-07a4a800-b720-11eb-8804-067d53f0df88.png">

**Comment by morganchen12** [comment]
Google Auth is not yet supported in SPM since one of the dependencies, GoogleSignIn, does not yet support SPM.

**Comment by weixifan** [comment]
Thank you for reporting this; I've filed an internal issue b/189044410 to track this.

**Comment by mamilov** [comment]
A new version of googlesignin with spm support has been released: https://github.com/google/GoogleSignIn-iOS

**Comment by mamilov** [comment]
Is there an ETA for an update regarding GoogleAuth support?

**Comment by morganchen12** [comment]
Sometime this week, hopefully, though given the changes in GoogleSignIn 6 it's likely going to require a major version update.

**Comment by morganchen12** [comment]
Re-opening since this hasn't been released yet.

**Comment by morganchen12** [comment]
The release containing the fix has been pushed as of last week.
