### ISSUE TITLE
Unable to get FirebaseUI-iOS 11.0.0 using CocoaPods.

### ISSUE THREAD

**Issue by koji-1009** [firebase/FirebaseUI-iOS#966]
### Step 1: Are you in the right place?

Yes

### Step 2: Describe your environment

  * Objective C or Swift: none
  * iOS version: none
  * Firebase SDK version: 8.0.0
  * FirebaseUI version: 11.0.0
  * CocoaPods Version: 10.0.2
  
#### Steps to reproduce:

  1. add `pod 'FirebaseUI', '~> 11.0'` to Podfile
  2. run `pod install`

or

  1. type `pod repo update`
  2. type `pod search firebaseui`
  
#### Observed Results:

I can't get FirebaseUI 11.0.0 using CocoaPods.

```txt
[!] CocoaPods could not find compatible versions for pod "FirebaseUI/Phone":
  In Podfile:
    flutter_auth_ui (from `.symlinks/plugins/flutter_auth_ui/ios`) was resolved to 2.0.1, which depends on
      FirebaseUI/Phone (~> 11.0)

None of your spec sources contain a spec satisfying the dependency: `FirebaseUI/Phone (~> 11.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

[project](https://github.com/koji-1009/flutter_auth_ui/blob/2.0.2+1/flutter_auth_ui/ios/flutter_auth_ui.podspec)

or 

```txt
-> FirebaseUI (10.0.2)
   UI binding libraries for Firebase.
   pod 'FirebaseUI', '~> 10.0.2'
   - Homepage: https://github.com/firebase/FirebaseUI-iOS
   - Source:   https://github.com/firebase/FirebaseUI-iOS.git
   - Versions: 10.0.2, 10.0.1, 9.0.0, 8.5.1, 8.4.2, 8.4.1, 8.4.0, 8.3.1, 8.2.0, 8.1.0, 8.0.4, 8.0.3, 8.0.2, 8.0.1, 7.0.0, 6.2.1, 6.1.1, 6.1.0, 6.0.1, 6.0.0, 5.2.2, 5.2.1, 5.2.0, 5.1.3, 5.1.2, 5.0.1,
   5.0.0, 4.5.5, 4.5.4, 4.5.3, 4.5.2, 4.5.1, 4.5.0, 4.4.0, 4.3.1, 4.3.0, 4.2.0, 4.1.1, 4.1.0, 4.0.0, 3.1.1, 3.1.0, 3.0.0, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.0.0, 0.7.0, 0.6.2, 0.6.1, 0.6.0, 0.5.6-rc3,
   0.5.6-rc2, 0.5.5, 0.5.4, 0.5.3, 0.5.2, 0.5.1, 0.5.0, 0.4.0, 0.3.2, 0.3.1, 0.3.0, 0.2.6, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.1.2 [trunk repo]
   - Subspecs:
     - FirebaseUI/Database (10.0.2)
     - FirebaseUI/Firestore (10.0.2)
     - FirebaseUI/Storage (10.0.2)
     - FirebaseUI/Auth (10.0.2)
     - FirebaseUI/Anonymous (10.0.2)
     - FirebaseUI/Email (10.0.2)
     - FirebaseUI/Facebook (10.0.2)
     - FirebaseUI/Google (10.0.2)
     - FirebaseUI/OAuth (10.0.2)
     - FirebaseUI/Phone (10.0.2)
```
  
#### Expected Results:

I want to download Firebase UI 11.0.0 using CocoaPods.
  
#### Relevant Code:

I couldn't find FirebaseUI 11.0.0 on the following two pages.
So, it looks like FirebaseUI 11.0.0 has not been uploaded to CocoaPods.

* https://cocoapods.org/pods/FirebaseUI
* https://github.com/CocoaPods/Specs/tree/master/Specs/b/c/2/FirebaseUI

Thanks!

**Comment by morganchen12** [comment]
Thanks @koji-1009, this should be fixed now.
