### ISSUE TITLE
Facebook Auth FBSDKCoreKit dependency update

### ISSUE THREAD

**Issue by wimbledon** [firebase/FirebaseUI-iOS#971]
Please make [Facebook Auth](https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseFacebookAuthUI.podspec) depend on the new FBSDKCoreKit_Basics instead of the old FBSDKCoreKit.
The reason is that FBAudienceNetwork 6.5.1 depends on FBSDKCoreKit_Basics [.](https://developers.facebook.com/docs/audience-network/setting-up/platform-setup/ios/changelog).
If FBSDKCoreKit_Basics and FBSDKCoreKit are installed side-by-side it causes duplicate symbols.

**Comment by morganchen12** [comment]
Fixed in https://github.com/firebase/FirebaseUI-iOS/pull/978.

**Comment by wimbledon** [comment]
Thank you, @morganchen12
