### ISSUE TITLE
Update FBSDKLoginKit Versions: 11.0.1

### ISSUE THREAD

**Issue by fangyuxi** [firebase/FirebaseUI-iOS#977]
Please update FBSDKLoginKit Versions: 11.0.1
Thank you.

**Comment by agiguere** [comment]
totally agree and the biggest deception is that GoogleSignIn version 5.0.2 has not been updated since 2019, big lack of commitments from Google

**Comment by fangyuxi** [comment]
@morganchen12 Please update FBSDKLoginKit dependency, can not compile successfully at present, We need to publish a new version to AppStore, Regret using this library.

**Comment by morganchen12** [comment]
Fixed in https://github.com/firebase/FirebaseUI-iOS/pull/978.

**Comment by fangyuxi** [comment]
> Fixed in #978.

Please update to Cocoapods.

**Comment by morganchen12** [comment]
FirebaseFacebookAuthUI has already been published. You should be able to install it with `pod update`.

**Comment by fangyuxi** [comment]
@morganchen12 
HI, can't find the latest version in Cocopods. Check out the URL.
https://github.com/CocoaPods/Specs/tree/master/Specs/b/c/2/FirebaseUI

**Comment by paulb777** [comment]
@fangyuxi See https://github.com/CocoaPods/Specs/blob/master/Specs/b/c/2/FirebaseUI/11.0.3/FirebaseUI.podspec.json#L79
