### ISSUE TITLE
FirebaseOAuthUI Pod Spec not updated

### ISSUE THREAD

**Issue by wimbledon** [firebase/FirebaseUI-iOS#980]
FirebaseOAuthUI is still at 11.0.3 and it should be updated to 11.1.3.

**Comment by wimbledon** [comment]
@morganchen12, you may have forgotten to update FirebaseOAuthUI.podspec?

**Comment by morganchen12** [comment]
Yep, I'll push it today. Thanks for catching this

**Comment by morganchen12** [comment]
Should be fixed now.
